### ISSUE TITLE
Bulding multiclass classification model

### ISSUE THREAD

**Issue by mgarort** [cornellius-gp/gpytorch#1003]
Hi, 

I'm opening this issue as a continuation of #1001. I understand now how `SoftmaxLikelihood` works (thanks a lot!) but I haven't been able to perform multiclass classification because I'm encountering the following error during a call to the marginal log likelihood:

```
Traceback (most recent call last):
  File "multiclass_classifier_for_issue.py", line 91, in <module>
    log_lik, kl_div, log_prior = mll(output, y_batch,combine_terms=False)
  File "/home/mgarort/housekeeping/virtualenv/ml2/lib/python3.6/site-packages/torch/tensor.py", line 421, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor
```

I think I'm using `SoftmaxLikelihood` correctly. I've created a short clean script that reproduces the error.
[multiclass_classifier_for_issue.zip](https://github.com/cornellius-gp/gpytorch/files/3993181/multiclass_classifier_for_issue.zip)

For convenience, I have created a Colab notebook where you can execute the code directly 
https://colab.research.google.com/drive/1Sg8kiqWajy6fyeu5G0sgZhR1Pqdkj8tS

Do you think you could take a look at it and let me know what the problem might be? In the hyperparameters section, you can set `mixing_weights` to be `True` or `False` depending on whether a mixing matrix is desired in the softmax likelihood or not. If `True`, the GP model's number of tasks is 100, and if `False`, it is the number of classes (10 in this case, for MNIST). In both cases I obtain the same error.

Thanks a lot in advance.

**Comment by gpleiss** [comment]
Thanks for the Colab notebook! It looks like you might have some code that's from an older version of the tutorial. The output of the `mll` by default is a scalar. If you pass the `combine_terms=False` to the mll object, then you can get the different components of the variational elbo - log_lik, kl_div, log_prior - on their own. (This is mostly useful for debugging purposes.)

To fix this, you should either pass the `combine_terms=False` argument to the mll - e.g.

```python
mll = VariationalELBO(likelihood, model, train_y.numel(), combine_terms=False)
# ...
for i in range(num_epochs):
    # ...
    log_lik, kl_div, log_prior = mll(output, y_batch)
    loss = -(log_lik - kl_div + log_prior)
```

or use the following lines in the training loop:

```python
mll = VariationalELBO(likelihood, model, train_y.numel())
# ...
for i in range(num_epochs):
    # ...
    loss = -mll(output, y_batch)
```

[The tutorial](https://gpytorch.readthedocs.io/en/latest/examples/06_PyTorch_NN_Integration_DKL/Deep_Kernel_Learning_DenseNet_CIFAR_Tutorial.html#Defining-Training-and-Testing-Code) has a correct training loop.

**Comment by mgarort** [comment]
Great, that worked!!

Thanks a lot :)

**Comment by gaoxiaoyao** [comment]
@mgarort 尊敬的先生，你好。我是一名高斯分类的初学者，想用光频谱混合(SM)内核对mnist数据集分类，我在运行你的程序时按要求修改，出现了如下错误：
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-cc679ee53dce> in <module>
    106         predictions = likelihood(model(test_x[i:i+n_gpu_can_take].cuda()))
    107         test_pred_labels = torch.cat((test_pred_labels,predictions.probs.max(dim=1)[1].float().cpu()))
--> 108 (test_pred_labels == test_y[:n_test]).float().mean()

RuntimeError: The size of tensor a (10) must match the size of tensor b (10000) at non-singleton dimension 1
请问是num_features设置问题还是num_class问题？谢谢你的指教

**Comment by KeAWang** [comment]
@gaoxiaoyao 
What you should do instead is
```
predictions = likelihood(model(test_x))
test_pred_labels = predictions.probs.mean(0).argmax(-1)
```

**Comment by gaoxiaoyao** [comment]
@KeAWang 非常感谢您的帮忙，我按照要求修改程序后，出现了如下错误：
# Evaluate accuracy
model.eval()
likelihood.eval()
n_test = 10000
n_gpu_can_take = 200
test_pred_labels = torch.Tensor([])
for i in range(0,n_test,n_gpu_can_take):
    with torch.no_grad(), gpytorch.settings.fast_pred_var():
        predictions = likelihood(model(test_x))
        test_pred_labels = predictions.probs.mean(0).argmax(-1)

RuntimeError: Expected object of backend CUDA but got backend CPU for sequence element 1 in sequence argument at position #1 'tensors'
请问应该怎样修改呀，谢谢您的指教

**Comment by gaoxiaoyao** [comment]
@KeAWang 非常感谢你的指教，我按照建议修改后出现下面的问题，想请教你怎么样修改，谢谢
# Evaluate accuracy
model.eval()
likelihood.eval()
n_test = 10000
n_gpu_can_take = 200
test_pred_labels = torch.Tensor([])
for i in range(0,n_test,n_gpu_can_take):
    with torch.no_grad(), gpytorch.settings.fast_pred_var():
        predictions = likelihood(model(test_x))
        test_pred_labels = predictions.probs.mean(0).argmax(-1)

RuntimeError: Expected object of backend CUDA but got backend CPU for sequence element 1 in sequence argument at position #1 'tensors'

**Comment by gaoxiaoyao** [comment]
你好，我还想请教一下如果想要确认mnist模型准确性，最后还应该添加哪些输出？谢谢

**Comment by KeAWang** [comment]
You have to ensure that your model and your data are on the same device. It looks like your model is on the GPU but test_x is on the CPU. You need a `test_x.cuda()` call before prediction.

To evaluate the performance of your model on MNIST, you can just evaluate the accuracy on the test set.

**Comment by gaoxiaoyao** [comment]
@KeAWang 谢谢你的指教，明白了

**Comment by gaoxiaoyao** [comment]
@KeAWang 你好，我在mnist模型下方添加了准确性能评估程序：
test_output = model(test_x)  
pred_y = torch.max(test_output, 1)[1].data.squeeze()
accuracy = sum(pred_y == test_y) / test_y.size(0) 
print('Test Acc: %.3f'%accuracy)
将test在cuda上运行后，依旧cuda与cpu的问题，并且精度无法显示，可以分析一下问题的原因么，谢谢。为方便起见，我将压缩程序放在下面。
[multiclass_classifier_for_issue.zip](https://github.com/cornellius-gp/gpytorch/files/4796342/multiclass_classifier_for_issue.zip)
