### ISSUE TITLE
[Bug] Can't reproduce GPyTorch Regression Tutorial

### ISSUE THREAD

**Issue by ThiagoLira** [cornellius-gp/gpytorch#1013]
# 🐛 Bug

The training loop on the example yields an error.

## To reproduce

Just copy the code from https://gpytorch.readthedocs.io/en/latest/examples/01_Exact_GPs/Simple_GP_Regression.html

** Stack trace/error message **

/usr/local/lib/python3.7/site-packages/gpytorch/utils/pivoted_cholesky.py in woodbury_factor(low_rank_mat, shift)
    100     shifted_mat = shifted_mat + torch.eye(k, dtype=shifted_mat.dtype, device=shifted_mat.device)
    101 
--> 102     R = torch.potrs(low_rank_mat, torch.cholesky(shifted_mat, upper=True))
    103     return R
    104 

**AttributeError: module 'torch' has no attribute 'potrs'**

## Expected Behavior

Model trains without further errors.

## System information

**Please complete the following information:**
- GPyTorch Version 1.0.0 
- PyTorch Version  1.3.1  
- Computer OS  MacOS Catalina

**Comment by jacobrgardner** [comment]
Hi @ThiagoLira -- you are running on an old (from the look of the stack trace, very old) version of GPyTorch (which admittedly would probably work if you had a comparably old version of torch).

Could you make sure that your install procedure actually installed 1.0.0? The line referenced in your stack trace does not even exist in the codebase anymore :-).

**Comment by ThiagoLira** [comment]
Oh, sorry... I should have suspected when print(gpytorch.__version__) didn't work haha

pip definitely thinks that this is version 1.0.0. 
I'm using a fresh python3.7 env via virtualenv

``` 
(deepfact) Thiagos-MacBook-Pro ~ $ pip install gpytorch
Collecting gpytorch
  Downloading https://files.pythonhosted.org/packages/e2/d9/796c53bffa43aa099bb7bbdbb7bf50e294ec9033e0b2a9df714fc6991b88/gpytorch-1.0.0.tar.gz (232kB)
     |████████████████████████████████| 235kB 5.8MB/s 
Building wheels for collected packages: gpytorch
  Building wheel for gpytorch (setup.py) ... done
  Created wheel for gpytorch: filename=gpytorch-1.0.0-py2.py3-none-any.whl size=390233 sha256=fe004a5aeee378f3d688e82db7bb042a72671c9b97d8cf70563a7cd23561d039
  Stored in directory: /Users/thiagolira/Library/Caches/pip/wheels/cb/cd/72/b8c3f9a71d0df1e07d8d2b3d3e47155825eae45e13a8e58d2a
Successfully built gpytorch
Installing collected packages: gpytorch
Successfully installed gpytorch-1.0.0
```

If I use 

```
pip install --upgrade git+https://github.com/cornellius-gp/gpytorch.git
```

It then installs gpytorch 0.3.6.

**Comment by gpleiss** [comment]
Can you call `print(gpytorch.__version__)` to confirm you're using 1.0?

**Comment by ThiagoLira** [comment]
The problem vanishes when I run the script outside of jupyter lab. It must be using the wrong kernel although I'm pretty sure I've set it up correctly. You never know with python 

![image](https://user-images.githubusercontent.com/11686042/72103831-cec51980-3308-11ea-868c-34f8a63f6788.png)

I'm closing the issue since this is my messy envs fault. Sorry for bothering you!
