### ISSUE TITLE
Bug with GridInterpolationKernel and Variables with 'requires_grad=True'

### ISSUE THREAD

**Issue by samuelstanton** [cornellius-gp/gpytorch#102]
Currently trying to evaluate a GP using GridInterpolationKernel on test points stored as torch.nn.Parameter. 

Line 89 in utils/interpolation.py results in an assertion error from 
`assert not ctx.needs_input_grad[2]` in torch/autograd/_functions/tensor.py

You can produce this error by putting 
`x = Variable(torch.Tensor(1, 2).uniform_(), requires_grad=True)`
`model(x)`
at the end of the kissgp_kronecker_product_regression.ipython notebook in examples.

This issue does not occur when using RBFKernel or SpectralMixtureKernel
I reproduced this issue after doing a fresh pull and install of gpytorch, traceback attached.

[traceback.txt](https://github.com/cornellius-gp/gpytorch/files/1905058/traceback.txt)

**Comment by gpleiss** [comment]
Which version of PyTorch are you using?

**Comment by gpleiss** [comment]
Sorry for the slow reply. I'll investigate today.

**Comment by jacobrgardner** [comment]
@samuelstanton @gpleiss Fixed by 8b50f2f48069652f90bc32baccb6f29ca14bfb44
