### ISSUE TITLE
Saving gpytorch models as ONNX

### ISSUE THREAD

**Issue by driesvr** [cornellius-gp/gpytorch#1022]
Hi GPytorch team,

First off, thanks for creating a great piece of software! I was wondering if there's a way to save the models as ONNX files at this point, or if this would be in the plans for the future?

Cheers,

Dries

**Comment by gpleiss** [comment]
Hi @driesvr - I don't think we have ONNX support at the moment. It's definitely something we have on our minds, but not sure exactly when it'd be added.

**Comment by jacobrgardner** [comment]
I believe it may be possible currently by first saving a model as torch script and then saving as ONNX. Let me (1) put up an example notebook saving am exact GP and a variational GP to torch script, and then see if it works.

**Comment by jacobrgardner** [comment]
Closed via #1026 -- just follow the example notebooks for converting to torchscript but instead of calling torch.jit.trace call the ONNX save on the model (which will trace it).

**Comment by Liyongchao321** [comment]
Hi, 

I followed your example "TorchScript_Exact_Models" and tried to export it to ONNX format as below:

with torch.no_grad(), gpytorch.settings.fast_pred_var(), gpytorch.settings.trace_mode():
    model.eval()
    test_x = torch.linspace(0, 1, 51)
    pred = model(test_x)  # Do precomputation
    wrapper = MeanVarModelWrapper(model)
    pred_wrapper = wrapper(test_x)
    torch.onnx.export(wrapper, test_x, 'gpytorch_model.onnx', verbose=True, example_outputs=pred_wrapper) 

However, I got  KeyError: 'diag' .  Could you please help me with it? 
My torch version is 1.4.0.

Thanks,
Yongchao

**Comment by jacobrgardner** [comment]
@Liyongchao321 This one may actually be on PyTorch. Could you open a separate issue for tracking?

**Comment by supersjgk** [comment]
Hi @driesvr @Liyongchao321 were you able to successfully convert gpytorch model to ONNX?
