### ISSUE TITLE
Hard-coded tensor types in LogNormalCDF

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#106]
The tensors initialized in LogNormalCDF are cpu float32 tensors, which causes test a failure when running the GPU test: https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/functions/log_normal_cdf.py#L51 (the adding of r_i fails). 

This will probably also cause issues when running anything involving LogNormalCDF under a float64 or other data type

**Comment by gpleiss** [comment]
Taking care of this now!
