### ISSUE TITLE
[Docs] Regression with DeepGP

### ISSUE THREAD

**Issue by vincent2303** [cornellius-gp/gpytorch#1067]
Hi,

I'm trying to use the deep GP example from the documentation to do a simple regression on a step function. I succeeded to use deepgp module [https://github.com/SheffieldML/PyDeepGP] to do so and I would like to reproduce the results with gpytorch. I tried many times with different parameters but I couldn't get a good result with 90 training points. Is there a simple regression example with deepGp from gpytorch ?

<img width="964" alt="Capture d’écran 2020-03-03 à 15 02 15" src="https://user-images.githubusercontent.com/37476143/75782984-0deb7600-5d60-11ea-967c-46f4a679d16f.png">
<img width="962" alt="Capture d’écran 2020-03-03 à 15 02 23" src="https://user-images.githubusercontent.com/37476143/75783005-16dc4780-5d60-11ea-8877-e742b06d8d33.png">

Thank you.

**Comment by gpleiss** [comment]
Can you post a jupyter notebook with your code? This will help us debug the problem.

**Comment by vincent2303** [comment]
Sure, here is the jupyter notebook.

[question.ipynb.zip](https://github.com/cornellius-gp/gpytorch/files/4284335/question.ipynb.zip)

(if you don't have deepgp installed, you can skip the first parts and just run the second part and the first two cells)

**Comment by gpleiss** [comment]
When I run your code, my gpytorch prediction looks like

<img width="376" alt="Screen Shot 2020-03-03 at 7 29 22 PM" src="https://user-images.githubusercontent.com/824157/75832881-6123ef80-5d85-11ea-9bc1-d1fb67a511c8.png">

**Comment by gpleiss** [comment]
I think your problem is that - in your code - you're plotting predictive variances rather than the predictive mean:

```python
fig = go.Figure(data=[
    go.Scatter(x=X_obs[:, 0], y=Y_obs[:, 0], mode='markers', marker_color='red', name='Observations'),
    go.Scatter(x=X_axis[:, 0], y=predictive_variances.mean(0), mode='lines', line_color='blue', name='deep gp predictions'),
    go.Scatter(x=X_axis[:, 0], y=y_step_function, mode='lines', line_color='green', name='step function', opacity=.5)
])
```

**Comment by vincent2303** [comment]
Ha my bad, it was a stupid mistake, I was plotting the variance...
Thank you very much for the answer and sorry...

**Comment by gpleiss** [comment]
All good! :)
