### ISSUE TITLE
[Feature Request] Request for help about default params and additive kernels 

### ISSUE THREAD

**Issue by cauchy7203** [cornellius-gp/gpytorch#1069]
1. How to change the default parameters？

（1）The default parameters  `variance`  and 'lengthscale' in linear kernel and RBF kernel always seems to be 0.6931.  
For example
```python
covar_module = gpytorch.kernels.LinearKernel() 
print(covar_module.variance)
```
The result is always:
`tensor([[0.6931]], grad_fn=<SoftplusBackward>)`

**Why should it be like this? And how to set it to be 1 or other values? Please help! SOS!**

2. **I can not understand how the additive kernels are combined.**

First I use the very simple example:
```python

x1 = torch.randn(3, 2)+1
covar_module =  LinearKernel(active_dims=1) + RBFKernel(active_dims=2)
additive_kernel_matrix = covar_module(x1)
tensor_covar_matrix = lazy_covar_matrix.evaluate() 
print(tensor_covar_matrix )
```
Result is:
```python
tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.6931, 1.3863],
        [0.0000, 1.3863, 2.7726]], grad_fn=<MmBackward>)
```
Then I tried to use the seperated kernels and add them together:

```python
x11 = torch.reshape(x1[:,0],[3,1])  # the first column
x12 = torch.reshape(x1[:,1],[3,1])  # the second column

lin_par = covar_module.kernels[0]
rbf_par = covar_module.kernels[1]

cm_lin = lin_par(x1)
lin_val = cm_lin.evaluate()

cm_rbf = rbf_par(x1)
rbf_val = cm_rbf.evaluate()

#print the Gram matrix by linear kernel
print(lin_val )
#print the Gram matrix by RBF kernel
print(rbf_val)
#print the sum of these two kernels
print(lin_val + rbf_val)
```

Results:

``` python

tensor([[0.0383, 0.2133, 0.1348],
        [0.2133, 1.1871, 0.7502],
        [0.1348, 0.7502, 0.4741]], grad_fn=<MmBackward>)
tensor([[1.0000, 0.4176, 0.3444],
        [0.4176, 1.0000, 0.0209],
        [0.3444, 0.0209, 1.0000]], grad_fn=<RBFCovarianceBackward>)
tensor([[1.0383, 0.6308, 0.4792],
        [0.6308, 2.1871, 0.7711],
        [0.4792, 0.7711, 1.4741]], grad_fn=<AddBackward0>)
```

Please see that the Gram matrices generated by the additive of linear and RBF kernels is not equal to the manual sum of these two kernels in the same module `covar_module`. 

**So, how is the additvekernel defined, and why it is not the summation of two kernels (using two dimensions)?**

**Comment by jacobrgardner** [comment]
For your first question, see our example notebook https://github.com/cornellius-gp/gpytorch/blob/master/examples/00_Basic_Usage/Hyperparameters.ipynb

Your second question appears to duplicate the other issue you raised in #1070 so I'll answer over there.

**Comment by cauchy7203** [comment]
Hi, Jacob.

Thanks very much for your response, I didn't expect such a fast response!!
I feel sorry to duplicate the questions.

1. The problem is fixed. Finally I recognized it was my own fault. The main reason was that I didn't clear the temp variables these the variables were mixtured.

2. The version I used for the last time was 0.3.0. This is caused by using the `conda install`. And I found it would keep the lastest version using `pip install`, and now it is 1.0.1

3. But I still have another question:

I want to use the kernels with kernel parameters set by myself.

e.g. when I use the linear kernel 
𝐾(𝑥,𝑦)=𝜈 𝑥𝑇 𝑦
I want to set 𝜈.  But it seems always to be 𝜈 = 0.6931. 

Check the following:
``` python
import torch
import gpytorch
from gpytorch.kernels import *

x1 = torch.rand(3,2)

temp_l = LinearKernel(variace =1)
temp_l_lazytensor = temp_l(x1)
temp_l_value = temp_l_lazytensor.evaluate()

print('Kernel Matrix produced by LinearKernel Module:\n',temp_l_value,'\n')
print('Kernel Matrix produced by dot product:\n',x1.mm(x1.T),'\n')
print('Ratio between these kernels:\n',temp_l_value/x1.mm(x1.T),'\n')
```
Results:

```
Kernel Matrix produced by LinearKernel Module:
 tensor([[0.6522, 0.2305, 0.3965],
        [0.2305, 0.0966, 0.2051],
        [0.3965, 0.2051, 0.5202]], grad_fn=<MmBackward>) 

Kernel Matrix produced by dot product:
 tensor([[0.9409, 0.3325, 0.5720],
        [0.3325, 0.1393, 0.2959],
        [0.5720, 0.2959, 0.7504]]) 

Ratio between these kernels:
 tensor([[0.6931, 0.6931, 0.6931],
        [0.6931, 0.6931, 0.6931],
        [0.6931, 0.6931, 0.6931]], grad_fn=<DivBackward0>) 
```

Could you please tell me why it is like this or how to set a default value of these kernel parameters by myself? (Maybe just give me some tips or a paper list related to this problem)

Thank you very much again for your response and the brilliant work!
