### ISSUE TITLE
[Bug] Bug on Additive kernels

### ISSUE THREAD

**Issue by cauchy7203** [cornellius-gp/gpytorch#1070]
I carefully checked the using of additive kernel, finding it is really a bug.

Source code:
``` python

import math
import torch
import gpytorch
from matplotlib import pyplot as plt
from gpytorch.kernels import *

covar_module =  LinearKernel(active_dims=torch.tensor([0])) + RBFKernel(active_dims=torch.tensor([1]))
x1 = torch.randn(3, 2) # randomly generate a 3 x 2 matrix

additive_kernel_matrix = covar_module(x1)
tensor_covar_matrix = lazy_covar_matrix.evaluate() 

print(tensor_covar_matrix)
```

**See the results after 5 runs:**

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.6931, 1.3863],
        [0.0000, 1.3863, 2.7726]], grad_fn=<MmBackward>)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.6931, 1.3863],
        [0.0000, 1.3863, 2.7726]], grad_fn=<MmBackward>)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.6931, 1.3863],
        [0.0000, 1.3863, 2.7726]], grad_fn=<MmBackward>)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.6931, 1.3863],
        [0.0000, 1.3863, 2.7726]], grad_fn=<MmBackward>)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.6931, 1.3863],
        [0.0000, 1.3863, 2.7726]], grad_fn=<MmBackward>)

Notice that the matrix  `x1` used here is randomly generated, but the results are always the same. 

There must be something wrong in this module.

**Comment by jacobrgardner** [comment]
@cauchy7203 I can't reproduce this on master:
```python
import math
import torch
import gpytorch
from matplotlib import pyplot as plt
from gpytorch.kernels import *

covar_module =  LinearKernel(active_dims=torch.tensor([0])) + RBFKernel(active_dims=torch.tensor([1]))
x1 = torch.randn(3, 2) # randomly generate a 3 x 2 matrix

additive_kernel_matrix = covar_module(x1)
tensor_covar_matrix = additive_kernel_matrix.evaluate() 

print(tensor_covar_matrix)
```
Results in e.g.:
```
tensor([[1.0072, 0.1899, 0.0646],
        [0.1899, 1.0004, 0.9142],
        [0.0646, 0.9142, 1.0379]], grad_fn=<AddBackward0>)

tensor([[1.0159, 0.2324, 0.7225],
        [0.2324, 2.0800, 2.9964],
        [0.7225, 2.9964, 5.9296]], grad_fn=<AddBackward0>)
```

Please note that in your previous example where you had this bug, you were passing active_dims as 1 and 2, rather than 0 and 1 and seeing the code run which is not expected (e.g., we now check that dims are in range).

What version of GPyTorch are you running on? Can you do:
```python
>>> print(gpytorch.__version__)
```
