### ISSUE TITLE
[Docs][Help] Scalability of SKIP/KISS-GP models

### ISSUE THREAD

**Issue by Giodiro** [cornellius-gp/gpytorch#1079]
Hi,

I was trying to follow the [example notebook for SKIP](https://github.com/cornellius-gp/gpytorch/blob/master/examples/02_Scalable_Exact_GPs/Scalable_Kernel_Interpolation_for_Products_CUDA.ipynb) with a larger dataset (approximately **500k points with 90 features**), and encountering memory errors on a large machine and without using the GPU. 
The stacktrace during training is the following:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<timed eval> in <module>

<ipython-input-43-f645465add06> in train()
     18             output = model(Xtr)
     19             # Calc loss and backprop derivatives
---> 20             loss = -mll(output, Ytr)
     21             loss.backward()
     22         print('Iter %d/%d - Loss: %.3f' % (i + 1, training_iterations, loss.item()))

~/anaconda3/envs/torch/lib/python3.7/site-packages/gpytorch/module.py in __call__(self, *inputs, **kwargs)
     22 
     23     def __call__(self, *inputs, **kwargs):
---> 24         outputs = self.forward(*inputs, **kwargs)
     25         if isinstance(outputs, list):
     26             return [_validate_module_outputs(output) for output in outputs]

~/anaconda3/envs/torch/lib/python3.7/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py in forward(self, function_dist, target, *params)
     49         # Get the log prob of the marginal distribution
     50         output = self.likelihood(function_dist, *params)
---> 51         res = output.log_prob(target)
     52 
     53         # Add additional terms (SGPR / learned inducing points, heteroskedastic likelihood models)

~/anaconda3/envs/torch/lib/python3.7/site-packages/gpytorch/distributions/multivariate_normal.py in log_prob(self, value)
    118 
    119         mean, covar = self.loc, self.lazy_covariance_matrix
--> 120         diff = value - mean
    121 
    122         # Repeat the covar to match the batch shape of diff

RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 860126404900 bytes. Error code 12 (Cannot allocate memory)
```

I tried reducing the values of the `grid_size` parameter in the `GridInterpolationKernel` (down to 10 grid points), as well as the size of the Lanczos approximation (parameter `max_root_decomposition_size`) down to 2 iterations.

Is there any other parameter that I could adjust, or is the limitation intrinsic of the model? It was my understanding that SKIP scaled linearly with the number of dimensions, and that choosing a small enough grid size would be enough to reduce memory usage.
Would it be possible to use mini-batching to reduce memory footprint?

Thanks for your efforts in developing this library,
Giacomo

**Comment by jacobrgardner** [comment]
It's hard to be sure without seeing the exact set-up, but as we mention in the paper the increased space complexity is definitely one of the limitations of SKIP. At datasets of that size, I'm not extremely surprised to see it exhaust GPU memory, at least on just a consumer GPU. We generally observed that SKIP ran out of GPU memory even scaling linearly long before it became slow.

You're basically going to use (num Lanczos iterations x n x d) memory, which is like 500k x 10k in this case, plus some additional memory. This is because we run the Lanczos iterations in parallel.

**Comment by Giodiro** [comment]
Makes sense, thanks. Sorry the off-topic issue.
