### ISSUE TITLE
[Bug] run time error when converting variational models to TorchScript

### ISSUE THREAD

**Issue by sjiang2018** [cornellius-gp/gpytorch#1088]
# 🐛 Bug

traced_model saving issue
## To reproduce

** Code snippet to reproduce **
```python
# Your code goes here
class MeanVarModelWrapper(nn.Module):
    def __init__(self, gp):
        super().__init__()
        self.gp = gp

    def forward(self, x):
        output_dist = self.gp(x)
        return output_dist.mean, output_dist.variance


def save_gp(model, test_x):
    wrapped_model = MeanVarModelWrapper(model)
    with torch.no_grad():
        fake_input = test_x
        pred = wrapped_model(fake_input)  # Compute caches
        traced_model = torch.jit.trace(wrapped_model, fake_input, check_trace=False)
        logging.info("saving model")
    traced_model.save('/tmp/traced_gp_example.pt')

# Please make sure it does not require any external dependencies (other than PyTorch!)
# (We much prefer small snippets rather than links to existing libraries!)
```

** Stack trace/error message **
```
  File "./gp_regression/gpytorch_train_example.py", line 127, in <module>
    save_gp(gp_model, test_x)
  File "./gp_regression/gpytorch_train_example.py", line 107, in save_gp
    traced_model.save('/tmp/traced_gp_example.pt')
  File "/home/sjiang/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 1626, in save
    return self._c.save(*args, **kwargs)
RuntimeError: 
Could not export Python function call 'MaternCovariance'. Remove calls to Python functions before export. Did you forget add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:

// Paste the bad output here!
```

## System information

**Please complete the following information:**
- 
- 
- 

## Additional context
I am following the instruction listed here
https://github.com/cornellius-gp/gpytorch/blob/ff1881b5fe92147f5e34e4141c0d5255e2650fdc/examples/08_Advanced_Usage/TorchScript_Variational_Models.ipynb
except:
self.covar_module = MaternKernel()

**Comment by jacobrgardner** [comment]
Oops -- add `gpytorch.settings.trace_mode()` to your context list in addition to `torch.no_grad()`. So:

```python
with gpytorch.settings.trace_mode(), torch.no_grad():
```

I'll update this in the example notebook.

**Comment by sjiang2018** [comment]
I tried that also, but there is error saying "gpytorch.settings has no attribute "trace_mode" ".

**Comment by jacobrgardner** [comment]
model tracing isn't on an officialy release yet. You need to run on master for now.

Here's the setting:
https://github.com/cornellius-gp/gpytorch/blob/5cfd9cfddc046bc09537762df5cb298b0f3feb09/gpytorch/settings.py#L512

**Comment by sjiang2018** [comment]
Yes. I did try to run on master. But somehow, I still get the same error. I am using 
-e git+git://github.com/cornellius-gp/gpytorch.git@master#egg=gpytorch
in my yaml file

**Comment by sjiang2018** [comment]
Thank you for your reply. It works now.

**Comment by jacobrgardner** [comment]
Glad to hear it!
