### ISSUE TITLE
Improving the score of Exact GP regression model

### ISSUE THREAD

**Issue by manjunaths** [cornellius-gp/gpytorch#1092]
Hello,

Newbie here, sorry if this is not the right forum to ask the questions. I have been trying to run Exact GP regression gpytorch built from the latest master on Kaggle House Prices dataset. I get an ok score on the dataset (0.138), but I was wondering, if you had any tricks that would reduce the score on the dataset ? I have removed the data pre-processing stage and directly load the pre-processed code.

The dataset and the notebook is also attached.
[GithubIssue.zip](https://github.com/cornellius-gp/gpytorch/files/4407074/GithubIssue.zip)

I had some really very basic questions, when I use the GridInterpolationKernel, what would I put in active_dims ? This dataset is of size (samples=1460, features=354). I tried putting a feature_extractor network, but the score is really bad, like 0.44 was the best I got. 

What does ard_num_dims do ? Is there anywhere where these concepts are documented in more detail than the API ?

```
#!pip install seaborn
%set_env CUDA_VISIBLE_DEVICES=1
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import random
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import torch
import gpytorch

from sklearn import preprocessing
%matplotlib inline

from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import WhiteKernel, Matern
from sklearn.metrics import mean_squared_log_error, mean_squared_error
from math import sqrt

#pd.options.display.max_rows = 4000
pd.options.display.max_seq_items = 2000

train_x = torch.load('train_x.pt')
train_y = torch.load('train_y.pt')
test_x = torch.load('test_x.pt')
test_y = torch.load('test_y.pt')

# We will use the simplest form of GP model, exact inference
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()

        self.covar_module = gpytorch.kernels.AdditiveKernel(
            gpytorch.kernels.ScaleKernel(gpytorch.kernels.MaternKernel(nu=2.5)),
            gpytorch.kernels.ScaleKernel(gpytorch.kernels.MaternKernel(nu=1.5)),
            gpytorch.kernels.ScaleKernel(gpytorch.kernels.MaternKernel(nu=0.5))
        )
#         self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())
#         self.covar_module = gpytorch.kernels.ProductKernel(gpytorch.kernels.RBFKernel(), 
#                                                          gpytorch.kernels.MaternKernel(nu=2.5))
#         grid_size = gpytorch.utils.grid.choose_grid_size(train_x,1.0)
#         self.covar_module = gpytorch.kernels.GridKernel(gpytorch.kernels.MaternKernel(nu=2.5), 
#                                                        grid=range(grid_size))
        
#         self.covar_module = gpytorch.kernels.ScaleKernel(
#             gpytorch.kernels.GridInterpolationKernel(
#                 gpytorch.kernels.RBFKernel(), grid_size=grid_size, num_dims=354))
#         self.covar_module = gpytorch.kernels.SpectralMixtureKernel(num_mixtures=64, ard_num_dims=354)
#         self.covar_module.initialize_from_data_empspect(train_x, train_y)        
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

# initialize likelihood and model
likelihood = gpytorch.likelihoods.GaussianLikelihood(noise_constraint=gpytorch.constraints.GreaterThan(1e-6))
model = ExactGPModel(train_x, train_y, likelihood).cuda()

# Find optimal model hyperparameters
model.train()
likelihood.train()

# Use the adam optimizer
optimizer = torch.optim.Adam([
    {'params': model.parameters()},  # Includes GaussianLikelihood parameters
], lr=0.9)

# "Loss" for GPs - the marginal log likelihood
mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

for i in range(training_iter):
    # Zero gradients from previous iteration
    optimizer.zero_grad()
    # Output from model
    output = model(train_x.cuda())
    # Calc loss and backprop gradients
    loss = -mll(output, train_y.cuda())
    loss.backward()
    #print('Iter %d/%d - Loss: %.3f   lengthscale: %.3f   noise: %.3f' % (
    print('Iter %d/%d - Loss: %.3f   noise: %.3f' % (
        i + 1, training_iter, loss.item(),
        #model.covar_module.base_kernel.lengthscale.item(),
        model.likelihood.noise.item()
    ))
    if loss.item() < 0.004:
        break
    optimizer.step()      

model.eval()
likelihood.eval()

with torch.no_grad(), gpytorch.settings.fast_pred_var():
    observed_pred = likelihood(model(test_x.cuda()))
    
predicted_val = np.expm1(observed_pred.mean.cpu().numpy())

acc = sqrt(mean_squared_log_error(predicted_val, test_y))

```

Thank you.

**Comment by jacobrgardner** [comment]
In general, basic stationary kernels like RBF and Matern often don't work amazingly well on 354 dimensional problems. You may need something like a very small feature extractor or even just running PCA to reduce the dimensionality.

In general, the answer to this question kind of boils down to the fundamentals of how to do data science, and there are lots of great resources for debugging machine learning models.  Try measuring whether you are overfitting or underfitting, and go from there.

To your questions that are actually specific to GPyTorch:
1. ard_num_dims specifies that we should learn a separate lengthscale for each input dimension. See the general kernel docs **[here](https://gpytorch.readthedocs.io/en/latest/kernels.html#kernel)**.

**Comment by ginward** [comment]
> In general, basic stationary kernels like RBF and Matern often don't work amazingly well on 354 dimensional problems. You may need something like a very small feature extractor or even just running PCA to reduce the dimensionality.
> 
> In general, the answer to this question kind of boils down to the fundamentals of how to do data science, and there are lots of great resources for debugging machine learning models. Try measuring whether you are overfitting or underfitting, and go from there.
> 
> To your questions that are actually specific to GPyTorch:
> 
> 1. ard_num_dims specifies that we should learn a separate lengthscale for each input dimension. See the general kernel docs **[here](https://gpytorch.readthedocs.io/en/latest/kernels.html#kernel)**.

If 354 dimensional problems are an issue for GPs, I was wondering usually how many features do people use for GPs?

**Comment by gpleiss** [comment]
> If 354 dimensional problems are an issue for GPs, I was wondering usually how many features do people use for GPs?

It's not that GPs are bad at 354 dimensions - it's just that the RBF and Matern kernels are not well suited to these high dimensional problems. [Deep kernel learning](https://docs.gpytorch.ai/en/latest/examples/06_PyTorch_NN_Integration_DKL/index.html) can help to learn kernels that are better for high-dimensional problems.

Closing this issue for now - open a [Discussion topic](https://github.com/cornellius-gp/gpytorch/discussions) if there are more questions.
