### ISSUE TITLE
Default max cholesky size is not 128 [Docs]

### ISSUE THREAD

**Issue by wjmaddox** [cornellius-gp/gpytorch#1093]
# 📚 Documentation/Examples

** Is documentation wrong? **
max cholesky size is not 128 as [referenced](https://github.com/cornellius-gp/gpytorch/blob/9f0fa216909d7ae49d713c0a6e83e4c9f0b3d4af/gpytorch/settings.py#L379), it's 800 according to [here](https://github.com/cornellius-gp/gpytorch/blob/9f0fa216909d7ae49d713c0a6e83e4c9f0b3d4af/gpytorch/settings.py#L382)

** Think you know how to fix the docs? ** 
Should be a one line fix.

- Link to [GPyTorch documentation](https://gpytorch.readthedocs.io)
- Link to [GPyTorch examples](https://github.com/cornellius-gp/gpytorch/tree/master/examples)

**Comment by jacobrgardner** [comment]
Yeah the docstring is wrong
