### ISSUE TITLE
[question]Can anyone please explain the relationship between 'raw_parameter' and 'parameter' ?

### ISSUE THREAD

**Issue by GilgameshD** [cornellius-gp/gpytorch#1099]
Can anyone please explain the relationship between 'raw_parameter' and 'parameter' inside the models? 
I ask this question because I need to reset the model parameters during the training, like the lengthscale or likelihood.noise_covar. But I don't know which one I should modify. 
It seems the 'raw_xxx' is the non-constrained version of 'xxx'. Is there any explanation about them?

**Comment by jacobrgardner** [comment]
Hi -- please see our tutorial on hyperparameter usage here: https://github.com/cornellius-gp/gpytorch/blob/master/examples/00_Basic_Usage/Hyperparameters.ipynb

It explains the difference between raw and actual parameters, and how to set them.

**Comment by GilgameshD** [comment]
Thanks!
