### ISSUE TITLE
Question about computing probabilities from a GPR

### ISSUE THREAD

**Issue by Galto2000** [cornellius-gp/gpytorch#1115]
Howdy folks,

I have a general question in regards to computing probabilities from a  GPR, or more in particular, the probability of the GPR attaining certain outputs `Y` over a certain input region `X`. 

For instance, consider a single-task 3D GPR predicting the temperature in a volume `H x W x D` where `X` is a `Nx3` input, for each `N` being a point in 3D space, and `Y` is a `Nx1` single task output, being the predicted temperature for each point.

How should I go about obtaining the probability that the temperature in a certain sub-volume `dH x dW x dD` is within a certain temperature range, in GPyTyorch?

Thanks in advance

Galto

**Comment by jacobrgardner** [comment]
I'm not sure I totally understand the question, but if you want to compute for some dense set of points x_1,...,x_t in the sub volume the probability that all temperatures are all between a and b you can make a joint prediction at that set of points and then use multivariate normal CDFs to do the calculation. Is that roughly what you are asking? If you need to integrate the multivariate normal CDF against complex regions (for example, you want different temperature ranges for the points), then you'll need to use other strategies. https://arxiv.org/pdf/1111.6832.pdf for example uses expectation propagation to compute Gaussian probabilities over certain types of regions.

**Comment by Galto2000** [comment]
Hi @jacobrgardner 

Thanks for your reply.

> "compute for some dense set of points x_1,...,x_t in the sub volume the probability that all temperatures are all between a and b"

Yes, I am interested in the joint probability of the temperature at every point` x_1, ..., x_t` being between a and b

If I understand you correctly, you are suggesting that I compute the CFD from the multivariate Gaussian distribution that is returned as the prediction in GpyTorch - i.e the CFD of the posterior distribution of the latent function.

Since a sample from the posterior is just one particular joint assignment of temperatures over the points ` x_1, ..., x_N`, this suggests that I have to integrate the posterior over each dimension from a to b ?

So for a sub-volume of N points I'll have N nested definite integrals?

Please bear with me as I am still trying to wrap my head around this, your help is greatly appreciated!

**Comment by jacobrgardner** [comment]
Yes, that's right. With that being said, we have extremely good numerical algorithms for computing multivariate normal CDF values. You want something like MVNCDF(b; gp_mu, gp_covar) - MVNCDF(a; gp_mu, gp_covar). If t is not extremely large, this should be very feasible.

**Comment by Galto2000** [comment]
Is there a MVNCDF-like function declared in GPyTorch, or Pytorch that would be directly applicable to a  `MultivariateNormal` object?

**Comment by Balandat** [comment]
Not that I am aware. There is the pretty much undocumented `scipy.stats.mvn.mvnun` that you can use for that.

**Comment by Balandat** [comment]
Fortran to the rescue once again!

**Comment by Galto2000** [comment]
Are there any convenient functions that would convert a GPyTorch `MultivariateNormal` object to a `scipy.stats.mvn` object?

I think I know the answer already, but I had to ask :)

**Comment by Balandat** [comment]
well `scipy.stats.mv` is a module here, and the `mvnun` function expects you to pass in bounds, a mean vector and a covariance matrix as numpy arrays. You can get those from the gpytorch tensors with `.detach().numpy()`

**Comment by Galto2000** [comment]
Thanks for pointing that out, much appreciated

**Comment by Galto2000** [comment]
I am wondering why the covariance matrix that I am getting from the posterior is not positive semidefinite.

When I am wrapping the posterior into a `scipy.stats.multivariate_normal` as follows:

```
mvn_posterior = multivariate_normal(latent_prediction.mean.detach().numpy(), latent_prediction.covariance_matrix.detach().numpy())
```

I get an exception 

`ValueError: the input matrix must be positive semidefinite`

(it computes the eigenvalues and it turns out I have at least one negative one)

**Comment by Balandat** [comment]
How negative? If it's tiny that can just be numerical accuracy if your matrix is almost singular / singular. Note that if you have repeated points then your posterior will be singular no matter what.

**Comment by Galto2000** [comment]
The smallest eigenvalue (`np.min(s)` in the code snippet below)  has a value of -1.0122036067733123e-06

In `scipy/stats/_multivariate.py`, line 158 it does the following
```

        eps = _eigvalsh_to_eps(s, cond, rcond)
        if np.min(s) < -eps:
            raise ValueError('the input matrix must be positive semidefinite')
```
`s` is the array of eigenvalues of the covariance matrix
`eps` has the value 8.551187880113014e-11, so it trips the exception

**Comment by Galto2000** [comment]
Thanks for the suggestions
