### ISSUE TITLE
[Docs] How do you build the documentation on Windows?

### ISSUE THREAD

**Issue by ndalchau** [cornellius-gp/gpytorch#1118]
How do you build the documentation? I can't find this documented anywhere. Also, I'm on windows, if that makes a difference.

**Comment by jacobrgardner** [comment]
If you're wanting to build the docs from scratch, you'll need the requirements listed in `setup.py`:
https://github.com/cornellius-gp/gpytorch/blob/5ea8483114813655c792321b334a1f8e15788d74/setup.py#L61

Then just cd in to `docs` and do `make html`.

For most people just wanting to view the docs, they are hosted here: https://gpytorch.readthedocs.io/en/latest/

**Comment by ndalchau** [comment]
Thanks for clarifying. I've been using Windows Subsystem for Linux (WSL), which facilitates `make`, usually without problem. I fell into trouble with sphinx version 3.0.1, as I did `pip install -r requirements.txt` from within the docs folder. Your post says the requirements are sphinx<3.0.0, but I still get errors with 2.4.4:

```
Running Sphinx v2.4.4

Exception occurred:
  File "/home/ndalchau/.local/lib/python3.6/site-packages/sphinx/builders/html/__init__.py", line 1234, in setup
    app.connect('config-inited', convert_html_css_files, priority=800)
TypeError: connect() got an unexpected keyword argument 'priority'
The full traceback has been saved in /tmp/sphinx-err-o0_v3kuv.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2
```
Any ideas?

**Comment by ndalchau** [comment]
Well, it turns out that I got tripped up by pip not uninstalling sphinx-3.0.1 when I installed sphinx-2.4.4. I have no idea why! It should not do this unless you specify `-I`.

Oh well, it builds now!
