### ISSUE TITLE
[Docs] Clarification about Approximate GP with ExactGP class

### ISSUE THREAD

**Issue by jejjohnson** [cornellius-gp/gpytorch#1123]
I just wanted to get some clarity on something within the documentation. In particular, I'm trying to understand what the **GPyTorch syntax** means for "Approximate GP". I saw two examples within the documentation.

1. **ApproximateGP** - which features a scalable kernel with inducing points but inherits the model from the `ExactGP` class - [Docs Example](https://gpytorch.readthedocs.io/en/latest/examples/02_Scalable_Exact_GPs/SGPR_Regression_CUDA.html#Defining-the-SGPR-Model)
2. **ApproximateGP** - which has its own `ApproximateGP` class which has a lot of other components like variational strategies and variational likelihoods - [Docs Example](https://gpytorch.readthedocs.io/en/latest/examples/02_Scalable_Exact_GPs/SGPR_Regression_CUDA.html#Defining-the-SGPR-Model)

I know theoretically they are different algorithms but I'm not sure I understand how GPyTorch handles the differences. I notice that the only difference between the **Exact** and  **ApproximateGP** with the `ExactGP` class is that you add a kernel matrix with inducing points as the [document](https://gpytorch.readthedocs.io/en/latest/examples/02_Scalable_Exact_GPs/index.html#how-gpytorch-scales-exact-gps) states. So they're almost essentially the same model but obviously the kernel is different.

However, the **Approximate GP** with a `ApproximateGP` class is one that has extra components like variational parameters, distributions and strategies. So in the [docs](https://gpytorch.readthedocs.io/en/latest/examples/04_Variational_and_Approximate_GPs/index.html#variational-and-approximate-gps) this simply means that it's approximate in the how it's doing the training and how it does the model. And I'm assuming you're still using BBMM techniques correct?

Am I on the right track? I think I'm just getting confused with the terminology. This is for my own understanding as I was trying to explain to someone some differences between some of the GPyTorch GPs and I realized I didn't really understand. 

**Side Note**: Is an GP under the `ExactGP` class kind of similar to the [slide 12](https://nips.cc/media/Slides/nips/2018/220e(05-15-30)-05-16-55-12683-GPyTorch:_Black.pdf) where you show how this is essentially the same mode but with different kernels?

**Comment by KeAWang** [comment]
When we say Exact GPs, we are typically referring to Gaussian process models without inducing points and without variational approximations. For example, an Exact GP with a RBF kernel is exact in the sense that it's the textbook definition of a Gaussian process with a RBF kernel and predictions are computed exactly (possibly with Krylov subspace methods instead of Cholesky).

Everything else is considered to be an Approximate GP, including predictions that are computed exactly with an inducing point approximate kernel like SGPR since the inducing point kernel is an approximation of the true kernel.

**Comment by jejjohnson** [comment]
I see so it's more or less just like the literature then. The fact that you can create a Sparse GP (the Titsias method) by simply inheriting an `ExactGP` is just a product of the model design and there is no change in the meaning. OK, I think I get it now. 

Thank you!
