### ISSUE TITLE
WhiteNoiseKernel can not be found

### ISSUE THREAD

**Issue by littletigerhao** [cornellius-gp/gpytorch#1128]
Hello,

I am going to use the white noise kernel, as shown in your doc 
self.covar_module = ScaleKernel(RBFKernel() + WhiteNoiseKernel())
but I am not able to improt the WhitNoiseKernel. I have looked into the kernels, while, no 'WhiteNoiseKernel' was found. I wonder that how can I implement it? or it has been included in somewhere?

https://gpytorch.readthedocs.io/en/latest/examples/01_Exact_GPs/Simple_GP_Regression.html

thanks for your kindly reply.

**Comment by gpleiss** [comment]
Sorry for the slow reply @littletigerhao !

The WhiteNoiseKernel is deprecated now I think. We should update the docs.
If you want to include fixed noise, check out the FixedNoiseGaussianLikelihood (an example of using it is here: https://github.com/cornellius-gp/gpytorch/blob/master/test/examples/test_white_noise_regression.py#L60)

**Comment by littletigerhao** [comment]
Okay. Got it. Thank you!

**Comment by littletigerhao** [comment]
> Sorry for the slow reply @littletigerhao !
> 
> The WhiteNoiseKernel is deprecated now I think. We should update the docs.
> If you want to include fixed noise, check out the FixedNoiseGaussianLikelihood (an example of using it is here: https://github.com/cornellius-gp/gpytorch/blob/master/test/examples/test_white_noise_regression.py#L60)

Thanks for your reply. Let me try this!

**Comment by aegonwolf** [comment]
> Sorry for the slow reply @littletigerhao !
> 
> The WhiteNoiseKernel is deprecated now I think. We should update the docs. If you want to include fixed noise, check out the FixedNoiseGaussianLikelihood (an example of using it is here: https://github.com/cornellius-gp/gpytorch/blob/master/test/examples/test_white_noise_regression.py#L60)

@gpleiss apologies for the late question on this issue. I played around with this also looking for a white noise kernel and wondered if I got it right. The noise I add is equal to the Variance I would have for a white noise kernel or how would I choose my noise to mimic a white noise?

**Comment by gpleiss** [comment]
@aegonwolf You can add the white noise to the FixedNoiseGaussianLikelihood. https://docs.gpytorch.ai/en/stable/likelihoods.html#fixednoisegaussianlikelihood
