### ISSUE TITLE
[Docs] Attribute has still old name in documentation

### ISSUE THREAD

**Issue by marecabo** [cornellius-gp/gpytorch#1130]
# 📚 Documentation/Examples

The attribute `lov_var` got renamed to `raw_var` in https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/kernels/index_kernel.py#L40 and does not exist anymore.

**Comment by gpleiss** [comment]
Thanks for the catch! Mind throwing up a quick PR for this?

**Comment by gpleiss** [comment]
Whoops I didn't mean to close this (I got trigger happy)
