### ISSUE TITLE
Fix lengthscale but optimize outputscale 

### ISSUE THREAD

**Issue by hchenids** [cornellius-gp/gpytorch#1131]
Is it possible to fix lengthscale but optimize other hyperparameters?

I found a similar question in #689 and I tried
optimizer = torch.optim.Adam([
    {'params': model.likelihood.parameters()},
    {'params': list(set(model.covar_module.parameters()) - {model.covar_module.base_kernel.lengthscale})}
], lr=0.1) but the lengthscale was still being optimized. Is there a solution to this? Thank you!

**Comment by jacobrgardner** [comment]
Add `model.covar_module.base_kernel.raw_lengthscale.requires_grad_(False)` before your training loop
