### ISSUE TITLE
Iteratively improve an overall GP regression quality by adding training points where are necessary

### ISSUE THREAD

**Issue by takafusui** [cornellius-gp/gpytorch#1137]
Dear all,

I have a black-box function to be interpolated by the Gaussian process regression. Suppose that I have [n, d] training inputs and [n, ] output, and can arbitrarily add training inputs-output.
My question is that how can I efficiently locate the input space to improve the overall GP regression quality? My naive idea is to iteratively add sample points where are necessary until fulfilling the quality of GP regression.
I believe the background idea is similar to the Bayesian optimization, but my objective is to maximize the overall approximation quality, not to find the maximum (or minimum) of the target black-box function.
Does anybody kindly give me some instructions or literature to know how I should proceed?

Thank you in advance.

**Comment by Balandat** [comment]
This is sometimes referred to as an "Active Learning" problem, and sometimes as "Experimental Design" or "Design of Experiments".

 You wan to choose the points that you evaluate next based on how you believe they will reduce a global measure of uncertainty. A simple way to do this is to minimize posterior variance integrated over your domain (interestingly, for a standard GP and if you don't re-fit you hyperparameters, that is actually independent of the observed function values). 

We implement a [`qNegativeIntegratedPosteriorVariance`](https://github.com/pytorch/botorch/blob/master/botorch/acquisition/active_learning.py#L38-L48) acquisition function for this in BoTorch. The docstring of that function has references that should be helpful.

**Comment by takafusui** [comment]
Dear @Balandat, thank you very much for your inputs. They are very helpful to me. I will start with Seo et al. (2000) you suggested as well as the `qNegativeIntegratedPosteriorVariance` class.

By the way, do you have a hands-on tutorial on how to use the `qNegativeIntegratedPosteriorVariance` class or some related tutorials to learn the usage of the class?

**Comment by Balandat** [comment]
Yeah so the `fantasize` method is something we define on BoTorch's `Model` API: https://github.com/pytorch/botorch/blob/master/botorch/models/model.py#L95

For your use case, it's probably enough to subclass your model from both `gpytorch.models.ExactGP` and `botorch.models.gpytorch.GPyTorchModel`. That mixin will add the botorch functionalities but retain all the GPyTorch ones.

We don't have a tutorial for this, but we probably should :)

**Comment by takafusui** [comment]
Dear @Balandat, thank you for your comments. I want to clarify two things:
1. As you suggested, my model class `ExactGPModel` becomes a subclass of two-parent classes.
```python
class ExactGPModel(gpytorch.models.ExactGP,
                       botorch.models.gpytorch.GPyTorchModel):
        num_outputs = 1
        def __init__(self, train_x, train_y, likelihood):
            super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
            self.mean_module = gpytorch.means.ConstantMean()
            self.covar_module = gpytorch.kernels.ScaleKernel(
                gpytorch.kernels.RBFKernel())
            # Apply batch normalization
            self.bn = torch.nn.BatchNorm1d(num_features=2)

        def forward(self, x):
            # Normalize train_x
            x = self.bn(x)
            mean_x = self.mean_module(x)
            covar_x = self.covar_module(x)
            return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
```
but still I have to argue that `num_ouputs = 1`, otherwise I got
```python
AttributeError: 'ExactGPModel' object has no attribute 'num_outputs'
```
Is it the expected behavior?

2. In the definition of the above class, I introduce the `torch.nn.BatchNorm1d()` layer. Then I construct the `qNegIntegratedPosteriorVariance` instance and optimize the acquisition function.
```python
# Batch integrated negative posterior variance for active learning
qNIPV = qNegIntegratedPosteriorVariance(model=gp, mc_points=test_X)

qNIPV, _ = optimize_acqf(
    acq_function=qNIPV,
    bounds=torch.tensor([[kbeg, abeg], [kend, aend]]),
    q=5,  # Number of candidates
    num_restarts=15,
    raw_samples=256,
    options={}
)
```
But I got the following error:
```python
Traceback (most recent call last):
  File "main_GHH_2x2.py", line 126, in <module>
    options={}
  File "/home/takafumi/.pyenv/versions/anaconda3-5.3.1/envs/dice/lib/python3.7/site-packages/botorch/optim/optimize.py", line 150, in optimize_acqf
    options=options,
  File "/home/takafumi/.pyenv/versions/anaconda3-5.3.1/envs/dice/lib/python3.7/site-packages/botorch/optim/initializers.py", line 104, in gen_batch_initial_conditions
    X_rnd[start_idx:end_idx].to(device=device)
  File "/home/takafumi/.pyenv/versions/anaconda3-5.3.1/envs/dice/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/takafumi/.pyenv/versions/anaconda3-5.3.1/envs/dice/lib/python3.7/site-packages/botorch/utils/transforms.py", line 200, in decorated
    return method(cls, X)
  File "/home/takafumi/.pyenv/versions/anaconda3-5.3.1/envs/dice/lib/python3.7/site-packages/botorch/utils/transforms.py", line 171, in decorated
    return method(cls, X)
  File "/home/takafumi/.pyenv/versions/anaconda3-5.3.1/envs/dice/lib/python3.7/site-packages/botorch/acquisition/active_learning.py", line 94, in forward
    X=X, sampler=self.sampler, observation_noise=True
  File "/home/takafumi/.pyenv/versions/anaconda3-5.3.1/envs/dice/lib/python3.7/site-packages/botorch/models/model.py", line 124, in fantasize
    post_X = self.posterior(X, observation_noise=observation_noise)
  File "/home/takafumi/.pyenv/versions/anaconda3-5.3.1/envs/dice/lib/python3.7/site-packages/botorch/models/gpytorch.py", line 126, in posterior
    mvn = self(X)
  File "/home/takafumi/.pyenv/versions/anaconda3-5.3.1/envs/dice/lib/python3.7/site-packages/gpytorch/models/exact_gp.py", line 314, in __call__
    full_output = super(ExactGP, self).__call__(*full_inputs, **kwargs)
  File "/home/takafumi/.pyenv/versions/anaconda3-5.3.1/envs/dice/lib/python3.7/site-packages/gpytorch/module.py", line 28, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/takafumi/Dropbox/Research/PostDoc/UZH/ML/GPstudy/py/GHHpreferences/TrainGPmodel.py", line 43, in forward
    x = self.bn(x)
  File "/home/takafumi/.pyenv/versions/anaconda3-5.3.1/envs/dice/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/takafumi/.pyenv/versions/anaconda3-5.3.1/envs/dice/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 106, in forward
    exponential_average_factor, self.eps)
  File "/home/takafumi/.pyenv/versions/anaconda3-5.3.1/envs/dice/lib/python3.7/site-packages/torch/nn/functional.py", line 1923, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 25 elements not 2
```
Interestingly, when I remove the batch normalization layer from the `ExactGPModel` class, `optimize_acqf` returns the candidate points.
How can I avoid this error?

**Comment by Balandat** [comment]
1. Yes. You'll need to tell the model how many outputs there are (better to use `_num_outputs` as the class attribute, this is automatically being made into a `num_outputs` via an internal property). The issue is that on the gpytorch end there is some ambiguity about the meaning of the dimensions, since single-outcome models will work on inputs of both `n x 1` and `n` dimension. In BoTorch we are very explicit about the dimensions to avoid ambiguity, so you'll need to tell the model how many outputs there are. 

2. This appears to be is an issue with `BatchNorm1d` operating on batched tensors. The acquisition function in botorch always receives a `batch_shape x q x d` dim tensor, where `batch_shape` is at least one-dimensional (can have arbitrary batch dimensions). So looking at the docs, [`BatchNorm1d`](https://pytorch.org/docs/stable/nn.html#batchnorm1d) ends up trying to normalize the wrong dimension. You'll have to make your own batch normalization (we also have an [`InputTransform`](https://github.com/pytorch/botorch/blob/master/botorch/models/transforms/input.py#L19) abstraction in botorch, but we haven't fully hooked that up yet), or you could hack around the existing one by doing some permuting of indices.

**Comment by takafusui** [comment]
Dear @Balandat, thank you very much for your comments. I would like to close this issue tentatively, and if I come up with something nice about the normalization issue, I would like to reopen it. Thank you again!

**Comment by Balandat** [comment]
Sounds good. If you have other botorch-related follow-ups, please open the issue over at https://github.com/pytorch/botorch/issues
