### ISSUE TITLE
Can I marginalize inputs using Gpytorch?

### ISSUE THREAD

**Issue by lk1983823** [cornellius-gp/gpytorch#1150]
Suppose I have input with two dimensions and ouput with one dimension. After using a gaussian process model to fit the data, can I marginalize one dimension of the input using Gpytorch?

Thanks.

**Comment by KeAWang** [comment]
Marginalizing the input dimensions doesn't make sense in the context of Gaussian processes. It's the outputs values that are assumed to be probabilistically distributed, not the inputs.

**Comment by gpleiss** [comment]
If you know the data distribution of dimension_1, you could densely sample in that dimension, and then average the results. That should approximate the marginal distribution over one dimension reasonably well.

**Comment by lk1983823** [comment]
Thanks, that is a monte-carlo method.
