### ISSUE TITLE
[Bug] Large MLLs on multitask models, even with z-scored data

### ISSUE THREAD

**Issue by gpleiss** [cornellius-gp/gpytorch#1155]
It seems like we've had several issues (e.g. #1129) where multitask models are returning very large MLL values (e.g. in the 1000s) even though the data is z-scored.

cc/ @Balandat @jacobrgardner

**Comment by gpleiss** [comment]
also #1159

**Comment by gpleiss** [comment]
also #1033

**Comment by Hamcastle** [comment]
Bumping this

**Comment by jacobrgardner** [comment]
Looking in to this now

**Comment by xanderladd** [comment]
I am currently experiencing this issue as well-- just wanted to bring this up to see if there has been any progress with this or if I should start looking into it. Thanks in advance!

**Comment by gpleiss** [comment]
Thanks for bumping this @xanderladd - haven't investigated too much, so please feel free to dig into it! We appreciate the help
