### ISSUE TITLE
Ignored prior mean for inducing points in VariationalStrategy

### ISSUE THREAD

**Issue by maciejkorzepa** [cornellius-gp/gpytorch#1156]
Hi, it seems that in `VariationalStrategy` the mean for inducing points is ignored. I guess due to whitening `self.prior_distribution.mean` is a zero vector, but the actual mean is not included anywhere else than in this if clause:
https://github.com/cornellius-gp/gpytorch/blob/bbf5abeafdb2581d11b615561a19cfeaa695e3ec/gpytorch/variational/variational_strategy.py#L135
which is never entered as `updated_strategy` is set to `True` from the start. 

Is it a bug? If yes, is writing another strategy with overloaded `prior_distribution` property that sets the mean to the actual prior mean and keep the variance unchanged (identity) a correct quick fix?

Best,
Maciej

**Comment by gpleiss** [comment]
The prior mean is added in this line: https://github.com/cornellius-gp/gpytorch/blob/bbf5abeafdb2581d11b615561a19cfeaa695e3ec/gpytorch/variational/variational_strategy.py#L111

In the whitened parameter space, the prior distribution of the inducing points (`p(u)`) is a standard normal `N(0, 1)`. The whitened variational parameters (`q(u) = N(m, S)`) encapsulate this coordinate shift:

m = K^{-1/2} ( m' - prior_mean )
S = K^{-1/2} S' K^{-1/2}

where m' and S' are the unwhitened parameters. For more information, see appendix E of this paper: https://arxiv.org/pdf/1910.07123.pdf

**Comment by maciejkorzepa** [comment]
Thanks for quick reply, Goeff. Isn't the prior mean in the whitened space a zero vector only if the prior mean in unwhitened space is also a zero vector? When I look at the code (below) I can see that the whitened prior mean (in the comment) is defined as K_ZZ^{-1/2} \mu_Z which is a zero vector only if the unwhitened prior mean \mu_Z is a zero vector.
```python
# Compute the mean of q(f)
# k_XZ K_ZZ^{-1/2} (m - K_ZZ^{-1/2} \mu_Z) + \mu_X
predictive_mean = (
      torch.matmul(
                interp_term.transpose(-1, -2), (inducing_values - self.prior_distribution.mean).unsqueeze(-1)
            ).squeeze(-1)
            + test_mean
        )        
```

**Comment by gpleiss** [comment]
There's a slight typo in the comment there. The whitening transformation is always:

f = K^{-1/2} ( f' - prior_mean )

where f' is the un-whitened GP. So the whitened prior will have mean zero and covariance I.

**Comment by maciejkorzepa** [comment]
Then I don't get one thing. If let's say I take some points from my training set and set them as (non-learnable) inducing points (whose unwhitened prior distribution is `N(\mu_Z, K_ZZ)` and `\mu_Z` is a non zero mean), and then I train the model on a dataset, let's assume, without these inducing points, then I can't see where `\mu_Z` comes in in the predictive posterior. In fact, I tried setting `\mu_Z` to some arbitrary value (even infinity) and I always get the same result. So either the predictive posterior is independent of the (unwhitened) prior mean of the inducing points or I'm misunderstanding something here.

**Comment by gpleiss** [comment]
>  If let's say I take some points from my training set and set them as (non-learnable) inducing points (whose unwhitened prior distribution is N(\mu_Z, K_ZZ) and \mu_Z is a non zero mean), and then I train the model on a dataset, let's assume, without these inducing points, then I can't see where \mu_Z comes in in the predictive posterior.

I'm not sure exactly what your setup is here. Do you have a code example showing this?

If you lock down the inducing points to be some training points, then the corresponding inducing values need to be set to their whitened equivalents. In other words, the `inducing_mean` for these points should be `u' = K_ZZ^{-1/2} ( y_Z - \mu_Z)`.

When you then make predictions with these points, the posterior mean will be:

`k_X^T K_ZZ^{-1/2} u + \mu_x` (the whitened posterior mean, from VariationalStrategy)
`= k_X^T K_ZZ^{-1} ( y_Z - \mu_Z) + \mu_x` (the unwhitened posterior mean)

So the math does work out :)

**Comment by maciejkorzepa** [comment]
Thanks for writing this down. The math definitely works out there. This part:
`u' = K_ZZ^{-1/2} ( y_Z - \mu_Z)` is never computed explicitly though right? As I understand `y_Z` is unwhitened posterior mean, but as we don't learn `y_Z` but directly the whitened `u` we don't need to know `\mu_Z` - is my understanding correct?

**Comment by gpleiss** [comment]
Yes - though the prior mean function comes into play when computing `\mu_x`.

**Comment by maciejkorzepa** [comment]
Everything is perfectly clear now, thanks!
