### ISSUE TITLE
How to slice and compute the marginal log likelihood (MLL) 

### ISSUE THREAD

**Issue by Apollo201** [cornellius-gp/gpytorch#1161]
Hi, everyone

I would like to compute the marginal log-likelihood (MLL) of part of the data. My basic idea is:

```python
x = data.feature
x_deep_feature = deepmodel(x)
```

then apply GP layer
```python
likelihood = gpytorch.likelihoods.SoftmaxLikelihood(num_features, num_classes=n_classes)
mll = gpytorch.mlls.VariationalELBO(likelihood, model.gp_layer, num_data=len(part_data)))
res = GP(x_deep_feature)
loss = -mll(res[part_data_index], y[part_data_index])
```
Then there will  an exception in gpytorch/lazy/lazy_tensor.py line831, in diag:
```python
 RuntimeError: Diag works on square matrices (or batches)
```
How could I solve the problem, thanks a lot

**Comment by jacobrgardner** [comment]
I think I might be confused by how your problem differs from the basic variational inference setup, which supports mini batches / sub sampling already? If this were the case, our variational inference examples (e.g., our SVGP example) already demonstrates training where the MLL is evaluated on mini batches of data.

**Comment by Apollo201** [comment]
Thanks for your reply. 

It is not batch training but transductive semi-supervised learning, where I need access to the whole dataset including labeled and unlabeled data. But compute and update parameters on labeled data. 

the steps can also be written as:
```python
results = GP([x_labeled_feature; x_unlabeled_feature)
```
then
```python
loss = -mll(results[labeled_index], y[labeled_index])
```

Then there will an exception in gpytorch/lazy/lazy_tensor.py line831, in diag:
```python
 RuntimeError: Diag works on square matrices (or batches)
```

**Comment by gpleiss** [comment]
I think you should be indexing the input to the GP, not the output:

```python
likelihood = gpytorch.likelihoods.SoftmaxLikelihood(num_features, num_classes=n_classes)
mll = gpytorch.mlls.VariationalELBO(likelihood, model.gp_layer, num_data=len(part_data)))
res = GP(x_deep_feature[part_data_index])
loss = -mll(res, y[part_data_index])
```

Let us know if this works.

**Comment by gpleiss** [comment]
Ahhh.. I think part of the issue here is that `res` here is a multitask multivariate normal. The existing `__getitem__` implementation for MVNs doesn't work in the multitask case.

@Balandat - since we've been talking about different representations of MMVN shapes, I think that a simple fix for right now is to throw a `NotImplementedError` for `MMVN.__getitem__`?

**Comment by Apollo201** [comment]
> ```python
> [part_data_index]
> ```

yeah, indexing the input to the GP works fine. But I am not sure if another part of the unlabeled data will be used, which is quite important for semi-supervised learning.

**Comment by Balandat** [comment]
@gpleiss I think that should work, yes. 

The MTMVN overhaul in https://github.com/cornellius-gp/gpytorch/pull/1083 will need a little work, but I think it's worth it- so if anyone wants to help out with that ....
