### ISSUE TITLE
[Docs] How to deal with N*M input and K*1 output VGPR training?

### ISSUE THREAD

**Issue by sjiang2018** [cornellius-gp/gpytorch#1165]
# 📚 Documentation/Examples
Hello there,

My training data has input dimension is N * 50 * 9  and output is N * 3 * 1, where N is the batch size or data set size. 
How to implement a Variation GP regression. 

I am using this example https://gpytorch.readthedocs.io/en/latest/examples/04_Variational_and_Approximate_GPs/SVGP_Multitask_GP_Regression.html
But this example assumes the input dimension is N * 9 and output is N * 3.

If I feed the multi-dimension input data (50 * 9) to original model, there will raise an error here
return self.constant.expand(_mul_broadcast_shape(input.shape[:-1], self.constant.shape)), 
in _mul_broadcast_shape func.

Thanks

**Comment by gpleiss** [comment]
I'm not quite understanding the exact setup of your problem. Is `N` the number of data points?
What do the different feature dimensions correspond to? My guess if you need to flatten your inputs so that they are `N * 450` and flatten your outputs to be `N * 3`.

**Comment by sjiang2018** [comment]
Thank you for the reply. N is the number of data points. But the input shape is 50 * 9. Every 50 input data (with 9 dimensions) can get 1 output data (with 3 dimensions). The 50 input data could be continuous in time domain, say from time t=1 sec to t=50 sec. And the output happens every 50 sec. So the training data would looks like N pair of data (x,y), where the dimension of x is 50*9 and the dimension of y is 1*3.

**Comment by gpleiss** [comment]
Yeah - then flatten the input dimension to be 450 and the output dimension to be 3. You can always re-shape in inputs/outputs afterwards.

**Comment by sjiang2018** [comment]
I see. Thank you.
