### ISSUE TITLE
Additional algorithms - for comparisons

### ISSUE THREAD

**Issue by andrewcz** [cornellius-gp/gpytorch#117]
Hi all,
Love the package! Looks super cool blush!
Was wondering if the below algorithms could be added-

https://gist.github.com/vdutor/0c720e1399e6bf7eae5c2bf32cdfb47d

https://github.com/ZilongTan/sigp

Many thanks,
Best,
Andrew

**Comment by gpleiss** [comment]
Thanks for those pointers @andrewcz ! The autoregressive model could probably be built with existing components. SIGP might require a bit more thinking.

We are open to PRs if you want to try your hand at implementing one of these models :grin:
