### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by jmaronas** [cornellius-gp/gpytorch#1181]
# 🚀 Feature Request

 White Noise Kernel  

## Motivation

Why was the white noise kernel removed? I am not sure if there is any feature in the kernels available that I can use for this purpose 

## Pitch

Copy and paste the old class in early gpytorch version

**Comment by jacobrgardner** [comment]
That feature is now accomplished through a `FixedNoiseGaussianLikelihood`.

**Comment by jmaronas** [comment]
How about using a kernel with white noise on a Deep Gaussian Process?
