### ISSUE TITLE
problem about the replacement of kernel 

### ISSUE THREAD

**Issue by gaoxiaoyao** [cornellius-gp/gpytorch#1189]
Hello, I want to replace the standard kernel with the spectral kernel when I do the Gaussian classification problem about mnist, but the following error appears after the replacement. 
I replace the procedure"self.covar_module = gpytorch.kernels.ScaleKernel(
            gpytorch.kernels.RBFKernel() )" with the procedure "self.covar_module =gpytorch.kernels.SpectralMixtureKernel(num_mixtures=4)",but it appears that
AttributeError: 'SpectralMixtureKernel' object has no attribute 'base_kernel'
I want to know how to modify it?Thanks a lot.

**Comment by gaoxiaoyao** [comment]
What I mean is that whether the kernel replacement will have any effect on the running of the program,thank you.

**Comment by gpleiss** [comment]
You should replace it with `self.covar_module = gpytorch.kernels.ScaleKernel(
gpytorch.kernels.SpectralMixtureKernel(num_mixtures=4) )`. That will fix the issue.

**Comment by gaoxiaoyao** [comment]
Hello, I made the following mistakes according to your suggestion. May I ask how to correct them，thank you.
self.covar_module = gpytorch.kernels.ScaleKernel( gpytorch.kernels.SpectralMixtureKernel(num_mixtures=4) )
AttributeError: 'SpectralMixtureKernel' object has no attribute 'raw_lengthscale'

**Comment by gpleiss** [comment]
My guess is that somewhere in your code you're trying to print out the lengthscale. Delete that line.

**Comment by gaoxiaoyao** [comment]
Hi, I have deleted  that line of the lengthscale, but the following problem appears in the program. May I ask whether the optical spectrum kernel only supports the input of one-dimensional data? Thank you.
RuntimeError: The SpectralMixtureKernel expected the input to have 1 dimensionality (based on the ard_num_dims argument). Got 784.
I put the program below. Thank you very much for your help
[multiclass_classifier_for_issue.txt](https://github.com/cornellius-gp/gpytorch/files/4808019/multiclass_classifier_for_issue.txt)

**Comment by KeAWang** [comment]
Yes the number of dimensions is specified by `ard_num_dims`. Right now it is set to 784 because you are training on MNIST. If you want to train on 1D data, just change it to 1.

**Comment by gaoxiaoyao** [comment]
@KeAWang  thank you,if I'm going to train the MNIST data set, can the dimensions be modified, not the one-dimensional data.

**Comment by KeAWang** [comment]
I'm not sure what you mean. If you want to train on MNIST then you need `ard_num_dims` to be 784

**Comment by gaoxiaoyao** [comment]
Where should I modify ard_num_dims?I can't find it in site-packages.Thank you

**Comment by KeAWang** [comment]
https://docs.gpytorch.ai/en/latest/_modules/gpytorch/kernels/spectral_mixture_kernel.html#SpectralMixtureKernel
