### ISSUE TITLE
RBF Kernel Change Breaks Testing Code

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#119]
The change to RBFKernel in 84fccd898c45c08279fb5c109e6e234f3a47588a may break something about our prediction code. 

I am not totally sure what the problem is yet, but I isolated this as the problem with `git bisect` and have a reasonable test case where results are significantly worse with the commit in compared to after a revert commit. 

It seems like the stability issues we encountered when making this change in the past don't come up in the unit tests, but do on some real datasets.

I can try to push my test case to a branch as well, although it relies on a UCI dataset.

@Balandat @gpleiss

**Comment by Balandat** [comment]
I am not sure what the problem would be other than maybe some issue with how the bounds on the lengthscales are being handled. Did you adjust the bounds appropriately given the new definition? 

Can you post your test case?

**Comment by gpleiss** [comment]
I think this has been fixed by bdaa640 . Dividing the lengthscale by 2 before the sum operation seems to be more numerically stable.

**Comment by gpleiss** [comment]
Oh whoops just realized that commit wasn't actually pushed to master. I'll make a real PR out of it
