### ISSUE TITLE
DiagLazyVariable Sampling

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#120]
https://github.com/cornellius-gp/gpytorch/blob/d29e08ebba7f998b7eda1a0f4d670e87363b7e07/gpytorch/lazy/diag_lazy_variable.py#L72

This should probably be
```python
samples = self._diag.unsqueeze(-1).sqrt() * base_samples 
```

? Just making sure I'm not missing something, since I've never used `PsdSumLazyVariable`, which is where I assume this actually gets used.

**Comment by gpleiss** [comment]
Whoops you're totally right. I'll fix this now.

**Comment by gpleiss** [comment]
Fixed by f3d794b
