### ISSUE TITLE
Logit transform and fixed noise gaussian likelihood

### ISSUE THREAD

**Issue by iprada** [cornellius-gp/gpytorch#1205]
Dear gpytorch developers,

This a probably basic question rather than a documentation/examples question. I removed the template in order to acomodate my question better. I hope it is fine

 I have an issue using logit transformed data and a fixed noise gaussian likelihood:

**My setting**

I have a set of training observations `train_x` and `train_y` , and I have known noise for the `train_y`.  I know the observation noise associated to to the training inputs, and the noise is a bit heterocedastic. Thus, I am using a FixedNoiseGaussianLikelihood with a vector  `my_noise` specifing the input noise. I simply implement this as follows:

```
likelihood = gpytorch.likelihoods.FixedNoiseGaussianLikelihood(noise=my_noise)
model = ExactGPMode(train_x,train_y,likelihood)
```

The rest of the model is pretty much the same as the Spectral mixture kernel notebook

**The problem**

My `train_y` data lies in the interval (0,0.5], in and has a lot of probability density close to 0 and 0.5. In order to account for this, I logit transform `train_y` before to feeding it to the gpytorch engine. However, due to the non-linear transformation of the logit, I cannot directly pass the noise vector as:
'
$logit(y+noise) != logit(y) + logit(noise)$

Is there a way to deal with this inside the gpytorch engine?

Having said that, thanks a lot for this great library. Makes implementing gaussian processes very easy to people!

Best,

Inigo

**Comment by KeAWang** [comment]
It seems that you are doing regression in logit space, i.e. using x to predict logit(y+noise) instead of y+noise. The likelihood of the data in logit space would no longer be a Gaussian likelihood since it is no longer additive Gaussian noise. Thus you would have to write your own non-Gaussian likelihood.

Alternatively a hack you could try would be to change your modeling assumption and assuming that noise in logit space is additive, which may or may not be appropriate in your case.

**Comment by jacobrgardner** [comment]
I believe we have an implementation of a Beta likelihood on a branch, which could be useful for you since that would be one possible way to model outputs on a defined range.

Let me see if I can put that together in to a PR.

**Comment by iprada** [comment]
Hi,

Thanks a lot to both of you for your help.

@jacobrgardner it will be great to have the implementation of the beta likelihood. Let me know if you need anything. I will be glad to help

**Comment by iprada** [comment]
Hi @jacobrgardner thanks a lot for the Pull request

I was thinking more on this. If I switch to the beta likelihood I guess that I should change my marginal log likelihood module? I guess that I can no longer use the ExactMarginalLogLikelihood, right?

Best,

Iñigo

**Comment by jacobrgardner** [comment]
Yeah, your likelihood is no longer Gaussian so you'll need to use approximate inference like VI.
