### ISSUE TITLE
train inputs not a tensor

### ISSUE THREAD

**Issue by gaoxiaoyao** [cornellius-gp/gpytorch#1206]
hi,I modified the example at https://gpytorch.readthedocs.io/en/latest/examples/01_Exact_GPs/Simple_GP_Regression.html#Introduction to train and test on my own data.The train_x and train_y were shown in the XLSX table. However, it was suggested that train_x was non-tensor input when gaussian process was used for training. How should I modify it,thank you for your help.

Procedure is as follows:
import xlrd
ExcelFile=xlrd.open_workbook(r'C:\Users\user\Desk

[]([CO2data.xlsx](https://github.com/cornellius-gp/gpytorch/files/4897004/CO2data.xlsx))

top\CO2data.xlsx')
sheet1_name=ExcelFile.sheet_names()[0]
print(sheet1_name)
sheet1=ExcelFile.sheet_by_name('xtrain')
print(sheet1.name,sheet1.nrows,sheet1.ncols)
rows1=sheet1.row_values(2)
cols1=sheet1.col_values(0)
rows2=sheet2.row_values(2)
cols2=sheet2.col_values(0)

import math
import torch
import gpytorch
from matplotlib import pyplot as plt
train_x = cols1
train_y = cols2
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
likelihood = gpytorch.likelihoods.GaussianLikelihood()
model = ExactGPModel(train_x, train_y, likelihood)

RuntimeError: Train inputs must be a tensor, or a list/tuple of tensors
The attachment is as follows:[CO2data.zip](https://github.com/cornellius-gp/gpytorch/files/4897013/CO2data.zip)

**Comment by KeAWang** [comment]
You need to turn the data in your Excel file into a pytorch Tensor. 
For example, if you have a numpy array or a list of numbers `x`, you can just do `x = torch.as_tensor(x)`.

For more info, please see online tutorials on how to use PyTorch.
