### ISSUE TITLE
Quantifying the uncertainty of the GP posterior

### ISSUE THREAD

**Issue by cisprague** [cornellius-gp/gpytorch#1212]
Hey! I'm using a stochastic variational GP `model` to model a surface — mapping 2D points `x` to scalar elevations`z`, which are all Gaussians (besides the point, I guess).

After I train `model`, I want to compute a scalar that quantifies the "uncertainty" of its belief of the 3D surface it intends to model.
I found that I could do `model(x).entropy()`, but I'm not exactly sure how that is computed. Could you clarify that?

I want to compute [Rényi's entropy ](https://www.sciencedirect.com/science/article/pii/S0020025509005428), which I supposed I'll need to use `model(x).covariance_matrix` for, if I can't use `model.entropy()`.

Some documentation on how to quantify the uncertainty of a GP model would be nice.

Thanks!

**Comment by jacobrgardner** [comment]
`model(x).entropy()` will have computed the differential entropy, e.g. `0.5 * logdet(model(x).covariance_matrix)`.

**Comment by cisprague** [comment]
Is there a standard way to compute the uncertainty of a GP over a certain area?

For instance, in my case, described in the original post, the box bounds of the input points `x` are defined by `low` and `high`, both with shape `(2,)`. Would it make sense to use randomly sampled query points from within those bounds to compute the uncertainty of the belief in that area, like shown below?

```python
# GP model: maps (n x 2) -> (n, )
model = SVGP(...)

# bounds of inputs
low = [-10, -10]
high = [10, 10]

# number of trials and samples
trials = 20
n = 1000

# randomly sample the posterior multiple times
entropy = 0
for _ in range(trials):

    # (n x 2) random sample
    x = np.vstack([
        np.random.uniform(
            low=low[i], 
            high=high[i], 
            size=n
        ) for i in range(2)
    ]).transpose()
    x = torch.from_numpy(x).float().cuda()

    # sample posterior
    with torch.no_grad():
        entropy += float(model(x).entropy().cpu().numpy())

#  average entropy
entropy /= trials
```

Also, what would be the difference if I used `likelihood(model(x)).entropy()` instead?

Cheers!
