### ISSUE TITLE
[Question] Do I need to load a saved model with the exactly same inducing points in training?

### ISSUE THREAD

**Issue by sjiang2018** [cornellius-gp/gpytorch#1216]
Say I am am loading a model from previous training result. When I init the model,should I input the same inducing points as those used in that training process to get the correct result? Or I can use any inducing points as long as the dimensions are same?

For example:
state_dict = torch.load('model_state.pth')
model = ApproximateGPModel(inducing_points)
model.load_state_dict(state_dict)

where ApproximateGPModel is defined as 
class ApproximateGPModel(gpytorch.models.ApproximateGP):
    def __init__(self, inducing_points):

**Comment by jacobrgardner** [comment]
As long as the dimensions are the same, you're all good. The act of loading the model will overwrite whatever's put in the inducing points anyways.
