### ISSUE TITLE
loading saved model in example [Docs]

### ISSUE THREAD

**Issue by irum** [cornellius-gp/gpytorch#1221]
I am following the [example](https://docs.gpytorch.ai/en/v1.1.1/examples/06_PyTorch_NN_Integration_DKL/Deep_Kernel_Learning_DenseNet_CIFAR_Tutorial.html) to save the model and likelihood but In documentation it is not clear where to load the model again after saving it . 
I have restored the model as follows:

          model = DKLModel(feature_extractor, num_dim=num_features)
         likelihood = gpytorch.likelihoods.SoftmaxLikelihood(num_features=model.num_dim, num_classes=num_classes)
         if os.path.isfile(gp_ckpt_path):
               print("training from gp model")
               m_state_dict = torch.load(gp_ckpt_path)
               model.load_state_dict(m_state_dict)
But I am getting the following error:

RuntimeError: Error(s) in loading state_dict for DKLModel:
	Missing key(s) in state_dict: "feature_extractor.conv1.weight", "feature_extractor.bn1.weight", "feature_extractor.bn1.bias", "feature_extractor.bn1.running_mean", "feature_extractor.bn1.running_var", "feature_extractor.layer1.0.conv1.weight", "feature_extractor.layer1.0.bn1.weight", "feature_extractor.layer1.0.bn1.bias", "feature_extractor.layer1.0.bn1.running_mean", "feature_extractor.layer1.0.bn1.running_var", "feature_extractor.layer1.0.conv2.weight", "feature_extractor.layer1.0.bn2.weight", "feature_extractor.layer1.0.bn2.bias", "feature_extractor.layer1.0.bn2.running_mean", "feature_extractor.layer1.0.bn2.running_var", "feature_extractor.layer1.0.conv3.weight", "feature_extractor.layer1.0.bn3.weight", "feature_extractor.layer1.0.bn3.bias", "feature_extractor.layer1.0.bn3.running_mean", "feature_extractor.layer1.0.bn3.running_var", "feature_extractor.layer1.0.downsample.0.weight", "feature_extractor.layer1.0.downsample.1.weight", "feature_extractor.layer1.0.downsample.1.bias", "feature_extractor.layer1.0.downsample.1.running_mean", "feature_extractor.layer1.0.downsample.1.running_var", "feature_extractor.layer1.1.conv1.weight", "feature_extractor.layer1.1.bn1.weight", "feature_extractor.layer1.1.bn1.bias", "feature_extractor.layer1.1.bn1.running_mean", "feature_extractor.layer1.1.bn1.running_var", "feature_extractor.layer1.1.conv2.weight", "feature_extractor.layer1.1.bn2.weight", "feature_extractor.layer1.1.bn2.bias", "feature_extractor.layer1.1.bn2.running_mean", "feature_extractor.layer1.1.bn2.running_var", "feature_extractor.layer1.1.conv3.weight", "feature_extractor.layer1.1.bn3.weight", "feature_extractor.layer1.1.bn3.bias", "feature_extractor.layer1.1.bn3.running_mean", "feature_extractor.layer1.1.bn3.running_var", "feature_extractor.layer1.2.conv1.weight", "feature_extractor.layer1.2.bn1.weight", "feature_extractor.layer1.2.bn1.bias", "feature_extractor.layer1.2.bn1.running_mean", "feature_extractor.layer1.2.bn1.running_var", "feature_extractor.layer1.2.conv2.weight", "feature_extractor.layer1.2.bn2.weight", "feature_extractor.layer1.2.bn2.bias", "feature_extractor.layer1.2.bn2.running_mean", "feature_extractor.layer1.2.bn2.running_var", "feature_extractor.layer1.2.conv3.weight", "feature_extractor.layer1.2.bn3.weight", "feature_extractor.layer1.2.bn3.bias", "feature_extractor.layer1.2.bn3.running_mean", "feature_extractor.layer1.2.bn3.running_var", "feature_extractor.layer2.0.conv1.weight", "feature_extractor.layer2.0.bn1.weight", "feature_extractor.layer2.0.bn1.bias", "feature_extractor.layer2.0.bn1.running_mean", "feature_extractor.layer2.0.bn1.running_var", "feature_extractor.layer2.0.conv2.weight", "feature_extractor.layer2.0.bn2.weight", "feature_extractor.layer2.0.bn2.bias", "feature_extractor.layer2.0.bn2.running_mean", "feature_extractor.layer2.0.bn2.running_var", "feature_extractor.layer2.0.conv3.weight", "feature_extractor.layer2.0.bn3.weight", "feature_extractor.layer2.0.bn3.bias", "feature_extractor.layer2.0.bn3.running_mean", "feature_extractor.layer2.0.bn3.running_var", "feature_extractor.layer2.0.downsample.0.weight", "feature_extractor.layer2.0.downsample.1.weight", "feature_extractor.layer2.0.downsample.1.bias", "feature_extractor.layer2.0.downsample.1.running_mean", "feature_extractor.layer2.0.downsample.1.running_var", "feature_extractor.layer2.1.conv1.weight", "feature_extractor.layer2.1.bn1.weight", "feature_extractor.layer2.1.bn1.bias", "feature_extractor.layer2.1.bn1.running_mean", "feature_extractor.layer2.1.bn1.running_var", "feature_extractor.layer2.1.conv2.weight", "feature_extractor.layer2.1.bn2.weight", "feature_extractor.layer2.1.bn2.bias", "feature_extractor.layer2.1.bn2.running_mean", "feature_extractor.layer2.1.bn2.running_var", "feature_extractor.layer2.1.conv3.weight", "feature_extractor.layer2.1.bn3.weight", "feature_extractor.layer2.1.bn3.bias", "feature_extractor.layer2.1.bn3.running_mean", "feature_extractor.layer2.1.bn3.running_var", "feature_extractor.layer2.2.conv1.weight", "feature_extractor.layer2.2.bn1.weight", "feature_extractor.layer2.2.bn1.bias", "feature_extractor.layer2.2.bn1.running_mean", "feature_extractor.layer2.2.bn1.running_var", "feature_extractor.layer2.2.conv2.weight", "feature_extractor.layer2.2.bn2.weight", "feature_extractor.layer2.2.bn2.bias", "feature_extractor.layer2.2.bn2.running_mean", "feature_extractor.layer2.2.bn2.running_var", "feature_extractor.layer2.2.conv3.weight", "feature_extractor.layer2.2.bn3.weight", "feature_extractor.layer2.2.bn3.bias", "feature_extractor.layer2.2.bn3.running_mean", "feature_extractor.layer2.2.bn3.running_var", "feature_extractor.layer2.3.conv1.weight", "feature_extractor.layer2.3.bn1.weight", "feature_extractor.layer2.3.bn1.bias", "feature_extractor.layer2.3.bn1.running_mean", "feature_extractor.layer2.3.bn1.running_var", "feature_extractor.layer2.3.conv2.weight", "feature_extractor.layer2.3.bn2.weight", "feature_extractor.layer2.3.bn2.bias", "feature_extractor.layer2.3.bn2.running_mean", "feature_extractor.layer2.3.bn2.running_var", "feature_extractor.layer2.3.conv3.weight", "feature_extractor.layer2.3.bn3.weight", "feature_extractor.layer2.3.bn3.bias", "feature_extractor.layer2.3.bn3.running_mean", "feature_extractor.layer2.3.bn3.running_var", "feature_extractor.layer3.0.conv1.weight", "feature_extractor.layer3.0.bn1.weight", "feature_extractor.layer3.0.bn1.bias", "feature_extractor.layer3.0.bn1.running_mean", "feature_extractor.layer3.0.bn1.running_var", "feature_extractor.layer3.0.conv2.weight", "feature_extractor.layer3.0.bn2.weight", "feature_extractor.layer3.0.bn2.bias", "feature_extractor.layer3.0.bn2.running_mean", "feature_extractor.layer3.0.bn2.running_var", "feature_extractor.layer3.0.conv3.weight", "feature_extractor.layer3.0.bn3.weight", "feature_extractor.layer3.0.bn3.bias", "feature_extractor.layer3.0.bn3.running_mean", "feature_extractor.layer3.0.bn3.running_var", "feature_extractor.layer3.0.downsample.0.weight", "feature_extractor.layer3.0.downsample.1.weight", "feature_extractor.layer3.0.downsample.1.bias", "feature_extractor.layer3.0.downsample.1.running_mean", "feature_extractor.layer3.0.downsample.1.running_var", "feature_extractor.layer3.1.conv1.weight", "feature_extractor.layer3.1.bn1.weight", "feature_extractor.layer3.1.bn1.bias", "feature_extractor.layer3.1.bn1.running_mean", "feature_extractor.layer3.1.bn1.running_var", "feature_extractor.layer3.1.conv2.weight", "feature_extractor.layer3.1.bn2.weight", "feature_extractor.layer3.1.bn2.bias", "feature_extractor.layer3.1.bn2.running_mean", "feature_extractor.layer3.1.bn2.running_var", "feature_extractor.layer3.1.conv3.weight", "feature_extractor.layer3.1.bn3.weight", "feature_extractor.layer3.1.bn3.bias", "feature_extractor.layer3.1.bn3.running_mean", "feature_extractor.layer3.1.bn3.running_var", "feature_extractor.layer3.2.conv1.weight", "feature_extractor.layer3.2.bn1.weight", "feature_extractor.layer3.2.bn1.bias", "feature_extractor.layer3.2.bn1.running_mean", "feature_extractor.layer3.2.bn1.running_var", "feature_extractor.layer3.2.conv2.weight", "feature_extractor.layer3.2.bn2.weight", "feature_extractor.layer3.2.bn2.bias", "feature_extractor.layer3.2.bn2.running_mean", "feature_extractor.layer3.2.bn2.running_var", "feature_extractor.layer3.2.conv3.weight", "feature_extractor.layer3.2.bn3.weight", "feature_extractor.layer3.2.bn3.bias", "feature_extractor.layer3.2.bn3.running_mean", "feature_extractor.layer3.2.bn3.running_var", "feature_extractor.layer3.3.conv1.weight", "feature_extractor.layer3.3.bn1.weight", "feature_extractor.layer3.3.bn1.bias", "feature_extractor.layer3.3.bn1.running_mean", "feature_extractor.layer3.3.bn1.running_var", "feature_extractor.layer3.3.conv2.weight", "feature_extractor.layer3.3.bn2.weight", "feature_extractor.layer3.3.bn2.bias", "feature_extractor.layer3.3.bn2.running_mean", "feature_extractor.layer3.3.bn2.running_var", "feature_extractor.layer3.3.conv3.weight", "feature_extractor.layer3.3.bn3.weight", "feature_extractor.layer3.3.bn3.bias", "feature_extractor.layer3.3.bn3.running_mean", "feature_extractor.layer3.3.bn3.running_var", "feature_extractor.layer3.4.conv1.weight", "feature_extractor.layer3.4.bn1.weight", "feature_extractor.layer3.4.bn1.bias", "feature_extractor.layer3.4.bn1.running_mean", "feature_extractor.layer3.4.bn1.running_var", "feature_extractor.layer3.4.conv2.weight", "feature_extractor.layer3.4.bn2.weight", "feature_extractor.layer3.4.bn2.bias", "feature_extractor.layer3.4.bn2.running_mean", "feature_extractor.layer3.4.bn2.running_var", "feature_extractor.layer3.4.conv3.weight", "feature_extractor.layer3.4.bn3.weight", "feature_extractor.layer3.4.bn3.bias", "feature_extractor.layer3.4.bn3.running_mean", "feature_extractor.layer3.4.bn3.running_var", "feature_extractor.layer3.5.conv1.weight", "feature_extractor.layer3.5.bn1.weight", "feature_extractor.layer3.5.bn1.bias", "feature_extractor.layer3.5.bn1.running_mean", "feature_extractor.layer3.5.bn1.running_var", "feature_extractor.layer3.5.conv2.weight", "feature_extractor.layer3.5.bn2.weight", "feature_extractor.layer3.5.bn2.bias", "feature_extractor.layer3.5.bn2.running_mean", "feature_extractor.layer3.5.bn2.running_var", "feature_extractor.layer3.5.conv3.weight", "feature_extractor.layer3.5.bn3.weight", "feature_extractor.layer3.5.bn3.bias", "feature_extractor.layer3.5.bn3.running_mean", "feature_extractor.layer3.5.bn3.running_var", "feature_extractor.layer4.0.conv1.weight", "feature_extractor.layer4.0.bn1.weight", "feature_extractor.layer4.0.bn1.bias", "feature_extractor.layer4.0.bn1.running_mean", "feature_extractor.layer4.0.bn1.running_var", "feature_extractor.layer4.0.conv2.weight", "feature_extractor.layer4.0.bn2.weight", "feature_extractor.layer4.0.bn2.bias", "feature_extractor.layer4.0.bn2.running_mean", "feature_extractor.layer4.0.bn2.running_var", "feature_extractor.layer4.0.conv3.weight", "feature_extractor.layer4.0.bn3.weight", "feature_extractor.layer4.0.bn3.bias", "feature_extractor.layer4.0.bn3.running_mean", "feature_extractor.layer4.0.bn3.running_var", "feature_extractor.layer4.0.downsample.0.weight", "feature_extractor.layer4.0.downsample.1.weight", "feature_extractor.layer4.0.downsample.1.bias", "feature_extractor.layer4.0.downsample.1.running_mean", "feature_extractor.layer4.0.downsample.1.running_var", "feature_extractor.layer4.1.conv1.weight", "feature_extractor.layer4.1.bn1.weight", "feature_extractor.layer4.1.bn1.bias", "feature_extractor.layer4.1.bn1.running_mean", "feature_extractor.layer4.1.bn1.running_var", "feature_extractor.layer4.1.conv2.weight", "feature_extractor.layer4.1.bn2.weight", "feature_extractor.layer4.1.bn2.bias", "feature_extractor.layer4.1.bn2.running_mean", "feature_extractor.layer4.1.bn2.running_var", "feature_extractor.layer4.1.conv3.weight", "feature_extractor.layer4.1.bn3.weight", "feature_extractor.layer4.1.bn3.bias", "feature_extractor.layer4.1.bn3.running_mean", "feature_extractor.layer4.1.bn3.running_var", "feature_extractor.layer4.2.conv1.weight", "feature_extractor.layer4.2.bn1.weight", "feature_extractor.layer4.2.bn1.bias", "feature_extractor.layer4.2.bn1.running_mean", "feature_extractor.layer4.2.bn1.running_var", "feature_extractor.layer4.2.conv2.weight", "feature_extractor.layer4.2.bn2.weight", "feature_extractor.layer4.2.bn2.bias", "feature_extractor.layer4.2.bn2.running_mean", "feature_extractor.layer4.2.bn2.running_var", "feature_extractor.layer4.2.conv3.weight", "feature_extractor.layer4.2.bn3.weight", "feature_extractor.layer4.2.bn3.bias", "feature_extractor.layer4.2.bn3.running_mean", "feature_extractor.layer4.2.bn3.running_var", "feature_extractor.fc.0.weight", "feature_extractor.fc.0.bias", "feature_extractor.fc.3.weight", "feature_extractor.fc.3.bias", "gp_layer.variational_strategy.base_variational_strategy.inducing_points", "gp_layer.variational_strategy.base_variational_strategy.variational_params_initialized", "gp_layer.variational_strategy.base_variational_strategy.grid", "gp_layer.variational_strategy.base_variational_strategy._variational_distribution.variational_mean", "gp_layer.variational_strategy.base_variational_strategy._variational_distribution.chol_variational_covar", "gp_layer.covar_module.raw_outputscale", "gp_layer.covar_module.base_kernel.raw_lengthscale", "gp_layer.covar_module.base_kernel.lengthscale_prior.a", "gp_layer.covar_module.base_kernel.lengthscale_prior.b", "gp_layer.covar_module.base_kernel.lengthscale_prior.sigma", "gp_layer.covar_module.base_kernel.lengthscale_prior.tails.loc", "gp_layer.covar_module.base_kernel.lengthscale_prior.tails.scale", "gp_layer.mean_module.constant". 
	Unexpected key(s) in state_dict: "model", "likelihood".

**Comment by jacobrgardner** [comment]
That example saves a dict with the state dicts for the model and the likelihood.

You need to do `model.load_state_dict(m_state_dict["model"])` and `likelihood.load_state_dict(m_state_dict["likelihood"])`.
