### ISSUE TITLE
Kernel with gradients + double precision

### ISSUE THREAD

**Issue by esgarijo** [cornellius-gp/gpytorch#1225]
I have been trying to use the kernel with gradients as in the example but providing features and inputs from my own source, which were originally in numpy format.

Torch's from_numpy produces tensors of type double tensor (dtype torch.float64) while default in torch seems to be float32 or single. I think this is the source of the error messages I get, such as: 
"RuntimeError: expected dtype Double but got dtype Float"
This error message is raised by a _matmul method of a lazy tensor, I guess it is trying to multiply a double tensor coming somehow from my data to something that is defined inside that class, which is then of the default type in torch.
 
Using double precision works beautifully without the gradients (Thanks!, it is a great package), but I wished I could use the gradients too, with double precision. I was wondering if someone could provide an example on how to use double precision or if it is something that is not supported yet and could be fixed.

**Comment by gpleiss** [comment]
Hi @esgarijo - would you be able to provide a small code example? Everything should work in double precision, assuming that your model/data are both in double mode

```python
# create data and gp_model

train_x = train_x.double()
train_y = train_y.double()
gp_model = gp_model.double()

# training loop
```

**Comment by esgarijo** [comment]
Thank you! that was it! I am new to this.
Thank you very much!
