### ISSUE TITLE
[Question] 2D heatmap for GP, (Latitude and longitude)

### ISSUE THREAD

**Issue by sebastianduque1323** [cornellius-gp/gpytorch#1228]
Hello, I hope you are doing well. I would like to know the correct way to plot a 2D GP in which X is comprised of latitude and longitude.

Thanks a lot!.

**Comment by gpleiss** [comment]
There isn't really a "correct" way. One option is to make two contour plots: one for the GP mean and one for the GP variance.

**Comment by dhruvbalwada** [comment]
You could also draw conditioned samples from posterior, and plot a few different example posteriors. The nice thing about these would be that you would be able to see the roughness level in the predicted field.
