### ISSUE TITLE
[Feature Request] Wrapper for kernels that handles integer-valued variables

### ISSUE THREAD

**Issue by jrojsel** [cornellius-gp/gpytorch#1239]
# 🚀 Feature Request

In order to perform BO with categorical and integer-valued variables, I would like a wrapper or something for kernels which transforms the the covariance matrix according to 

<a href="https://www.codecogs.com/eqnedit.php?latex=k(x_i,x_j)\rightarrow&space;k(T(x_i),T(x_j))" target="_blank"><img src="https://latex.codecogs.com/gif.latex?k(x_i,x_j)\rightarrow&space;k(T(x_i),T(x_j))" title="k(x_i,x_j)\rightarrow k(T(x_i),T(x_j))" /></a>

as proposed in [Dealing with categorical and integer-valued variables in Bayesian Optimization with Gaussian processes](https://www.sciencedirect.com/science/article/pii/S0925231219315619) 

Quote from the paper:

> T(x) is a transformation in which all input variables of f (·) that are not real are modified as follows: 
• The input variables that correspond to an integer-valued variable are simply rounded to the closest integer value. 
• The input variables that correspond to the same categorical variable are assigned 0 value, unless they take the largest value among its corresponding group of extra variables. If they take the largest value, they are set equal to 1.

## Motivation

Hopefully, this would enhance efficiency of categorical/mixed-integer-BO with e.g. BoTorch.

## Pitch

Clear enough from above text

**Describe the solution you'd like**

Create a wrapper for kernels which performs the transformation given a specification of which dimensions that are integer-valued

**Describe alternatives you've considered**
-

**Are you willing to open a pull request?** (We LOVE contributions!!!)
I don't feel at ease messing around with the inner workings of the (lazy) covariance matrices, so I'm hoping for someone else to investigate this... :)

**Comment by jacobrgardner** [comment]
Why would this require modifications to the package specifically? You can already modify input data in the `forward` method of a GP arbitrary ways:

```python
def forward(self, x):
    # Literally any arbitrary transformation of x. Preferably a differentiable one if you plan on needing derivatives w.r.t. x.
    t_x = self.transform(x)
    covar_x = self.covar_module(t_x)
    mean_x = self.mean_module(t_x)
    return MultivariateNormal(mean_x, covar_x)
```

**Comment by jrojsel** [comment]
Ok, you're right, thanks!

I'll probably use something like the [x -> x - sin(2•pi•x)/2•pi approach](https://stackoverflow.com/questions/46596636/differentiable-round-function-in-tensorflow/50434452) to keep the transformation differentiable if anyone is interested:

![image](https://user-images.githubusercontent.com/55212242/89552383-5b3aaa80-d80c-11ea-9dfe-e4c661206070.png)

But what about variational (inducing point) models? Is there any way of transforming the inducing points after (or prior to) every optimization step to assert that the dimensions of the inducing points corresponding to integer-valued input variables are transformed to integers as well? I would like to experiment with such an approach if it is possible.
