### ISSUE TITLE
How to set the seed for GP initialization?

### ISSUE THREAD

**Issue by cisprague** [cornellius-gp/gpytorch#1249]
Hi! I want to make sure the initialisation of my GP is reproducible. Is there a way to set the seed *only* for the GP?
I suppose I could just do `torch.manual_seed(0)`, but I believe that would affect the initialisation of other torch objects within my programme.

**Comment by jacobrgardner** [comment]
@cisprague The "best" way in my opinion to accomplish setting a seed temporarily would be to wrap the relevant code in a `torch.random.fork_rng` context. Inside this context, you can set manual seeds etc, and when you exit the context everything will be set back to the random state things were before you entered the context.
