### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by dialuser** [cornellius-gp/gpytorch#1254]
# 🐛 Bug

Tensor object has no attribute 'ndim'
## To reproduce
Run the multioutput example, from https://docs.gpytorch.ai/en/latest/examples/03_Multitask_Exact_GPs/Multitask_GP_Regression.html

** Code snippet to reproduce **
```python
# Your code goes here
# Please make sure it does not require any external dependencies (other than PyTorch!)
# (We much prefer small snippets rather than links to existing libraries!)
```

** Stack trace/error message **
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/autograd/function.py", line 77, in apply
    return self._forward_cls.backward(self, *args)
  File "/opt/anaconda3/lib/python3.7/site-packages/gpytorch/functions/_matmul.py", line 46, in backward
    arg_grads = ctx.representation_tree(*matrix_args)._quad_form_derivative(grad_output_matrix, rhs)
  File "/opt/anaconda3/lib/python3.7/site-packages/gpytorch/lazy/block_lazy_tensor.py", line 114, in _quad_form_derivative
    if left_vecs.ndim == 1:
AttributeError: 'Tensor' object has no attribute 'ndim'

// Paste the bad output here!
```

## Expected Behavior

<!-- A clear and concise description of what you expected to happen. -->

## System information

**Please complete the following information:**
- <!-- GPyTorch Version (run `print(gpytorch.__version__)` -->
- <!-- PyTorch Version (run `print(torch.__version__)` -->
- <!-- Computer OS -->

## Additional context
Add any other context about the problem here.

**Comment by KeAWang** [comment]
Are you using an old version of pytorch? See https://github.com/huggingface/transformers/issues/5593 for example

**Comment by dialuser** [comment]
Yes. I'm using pytorch 1.1. I'm in the process of updating. Thanks.
