### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by dialuser** [cornellius-gp/gpytorch#1256]
# 📚 Documentation/Examples
Hi, 
I have a problem where the output samples are 2D images of sizes N*N. Different images represents outputs of a PDE solver from different times. There's strong spatial correlation among the grid cells.
I have looked into MultitaskGPModel and GridGPRegressionModel.
The former maybe used if I treat the grid cells as different tasks, the latter seems to be similar. But I wonder if this is the best way to cast the problem using gpytorch. I'm mainly concerned with scalability (N^2). Any advice? Thanks ahead.

** Is there documentation missing? **

** Is documentation wrong? **

** Is there a feature that needs some example code? **

** Think you know how to fix the docs? ** (If so, we'd love a pull request from you!)

- Link to [GPyTorch documentation](https://gpytorch.readthedocs.io)
- Link to [GPyTorch examples](https://github.com/cornellius-gp/gpytorch/tree/master/examples)

**Comment by jacobrgardner** [comment]
You might try the variational multitask models, which scale reasonably well with the number of output GPs: https://github.com/cornellius-gp/gpytorch/blob/master/examples/04_Variational_and_Approximate_GPs/SVGP_Multitask_GP_Regression.ipynb

**Comment by Balandat** [comment]
@wjmaddox has implemented the HOGP model from http://proceedings.mlr.press/v89/zhe19a.html that works quite well in these settings. Should be able to diff put this up as a PR once it's cleaned up and tested some more.

**Comment by dialuser** [comment]
@Balandat, I'm looking forward to using HOGP.  Thanks.

**Comment by Balandat** [comment]
It might be a little bit until this is all polished, in particular the current version does not support efficiently computing predictive variances, but we should get there.

**Comment by wjmaddox** [comment]
Just bumping this thread now that the implementation is in botorch [here](https://github.com/pytorch/botorch/blob/master/botorch/models/higher_order_gp.py). Let us know how it works for your use case.
