### ISSUE TITLE
conda-forge release date for gpytorch 1.1.2 (or higher)?

### ISSUE THREAD

**Issue by mihai-spire** [cornellius-gp/gpytorch#1257]
Hi,
I'm wondering if you have already set a release date for `gpytorch` 1.1.2 (or higher) through `conda-forge`? I'm very keen to try the new [deep sigma point process API](https://docs.gpytorch.ai/en/latest/examples/05_Deep_Gaussian_Processes/Deep_Sigma_Point_Processes.html). I know that  code is already in `master` - our operational environment, however, requires the use of pre-built `conda` packages. Thanks!

**Comment by jacobrgardner** [comment]
We are planning to release GPyTorch 1.2 fairly soon. I think one to two more features need to go in, one of which has a PR up (#1207).
