### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by dialuser** [cornellius-gp/gpytorch#1259]
# 📚 Documentation/Examples
Hi, 
In my problem, the outputs are constrained to [0,1]. I wonder if there's a way to impose this nonnegativity in gpytorch. Currently, the outputs I got expand to <0. Thank you very much.

** Is there documentation missing? **

** Is documentation wrong? **

** Is there a feature that needs some example code? **

** Think you know how to fix the docs? ** (If so, we'd love a pull request from you!)

- Link to [GPyTorch documentation](https://gpytorch.readthedocs.io)
- Link to [GPyTorch examples](https://github.com/cornellius-gp/gpytorch/tree/master/examples)

**Comment by jacobrgardner** [comment]
Do variational inference with a BetaLikelihood: https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/likelihoods/beta_likelihood.py

**Comment by dialuser** [comment]
Hi, @jacobrgardner, thanks for the hint. I'm dealing with a multitask case here, so does the Bernoulli likelihood work for the multitask case?

**Comment by gpleiss** [comment]
@dialuser - can you define your problem setup a bit more? That will help us determine if you're using the right likelihood.
