### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by dialuser** [cornellius-gp/gpytorch#1261]
# 📚 Documentation/Examples
Hello, I'm trying to implement a Variational Multioutput model by following the example at [https://docs.gpytorch.ai/en/v1.1.1/examples/04_Variational_and_Approximate_GPs/SVGP_Multitask_GP_Regression.html](url)

In my case, the number of tasks is defined by nTasks. The input dimension is n x d and the output dimension is n x nTasks. 
The motivation was mentioned in my question from yesterday--the outputs need to be constrained to [0,1] range. I was advised to use BetaLikelihood.

My question is what the shape of induce points should be for the multi-output case. Is it nTasks x nLatentSpace x d ?
The example documentation is not very clear.  Also, is there a multitask version of Betalikelihood somewhere. Thank you in advance from a newbie.

```
	class MultitaskVarGPModel(gpytorch.models.ApproximateGP):
	    def __init__(self, inducing_points):
		nTasks = N*N
		variational_distribution = gpytorch.variational.CholeskyVariationalDistribution(
		    inducing_points.size(-2), batch_shape=torch.Size([nTasks])
		)
		variational_strategy = gpytorch.variational.MultitaskVariationalStrategy(
		    gpytorch.variational.VariationalStrategy(
			self, inducing_points, variational_distribution, learn_inducing_locations=True
		    ), num_tasks=nTasks
		)
		super().__init__(variational_strategy)
		self.mean_module = gpytorch.means.ConstantMean(batch_shape=torch.Size([nTasks]))
		self.covar_module = gpytorch.kernels.ScaleKernel(
		    gpytorch.kernels.RBFKernel(batch_shape=torch.Size([nTasks])),
		    batch_shape=torch.Size([nTasks])
		)

	    def forward(self, x):
		# The forward function should be written as if we were dealing with each output
		# dimension in batch
		mean_x = self.mean_module(x)
		covar_x = self.covar_module(x)
		return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)


```

** Is there documentation missing? **

** Is documentation wrong? **

** Is there a feature that needs some example code? **

** Think you know how to fix the docs? ** (If so, we'd love a pull request from you!)

- Link to [GPyTorch documentation](https://gpytorch.readthedocs.io)
- Link to [GPyTorch examples](https://github.com/cornellius-gp/gpytorch/tree/master/examples)

**Comment by gpleiss** [comment]
> Is it nTasks x nLatentSpace x d ?

Yes

> Is there a multitask version of Betalikelihood somewhere?

It should possibly work right out of the box with multitask models - if not give us a code example and a stack trace.

**Comment by dialuser** [comment]
Hi, all multitask likelihoods have this num_tasks parameter, right? I'm not clear when you said it should work out of the box. Anyway, I'd like to replace MultitaskGaussianLikelihood with Beta in the following,

`        likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(num_tasks=train_y.shape[1])        `

Thanks.

**Comment by gpleiss** [comment]
> Hi, all multitask likelihoods have this num_tasks parameter, right?

This is only because the Gaussian likelihood has a parameter that's dependent on the number of tasks. This is not the case with Beta likelihoods, so it doesn't require a `num_tasks` argument.

What happens when you replace that line with

```python
likelihood = gpytorch.likelihoods.BetaLikelihood()
```

**Comment by ZhiliangWu** [comment]
Hi @gpleiss, I am also reading this multitask SVGP tutorial and would like to ask what does it mean by `batch dimension` in [Variational Strategies for Multi-Output Functions](https://docs.gpytorch.ai/en/v1.2.0/variational.html#variational-strategies-for-multi-output-functions), as both `task_dim` in `IndependentMultitaskVariationalStrategy` and `latent_dim` in `LMCVariationalStrategy` referred it. Does it refer to the dimension of the batch GP we defined in e.g., `CholeskyVariationalDistribution` through the `batch_shape` or something else? Where did we set this during building the multi-task SVGP? The default suggested value of `-1` seems a bit abstract to me. Thanks for your reply in advance.

**Comment by gpleiss** [comment]
@ZhiliangWu `LMCVariationalStrategy` and `IndependentMultitaskVariationalStrategy` both convert a batch of GPs into a multitask GP. For example, the `IndependentMultitaskVariationalStrategy` converts the output of `d` Gaussian processes into a `n x d` MultitaskMultivariateNormal.

Both `IndependentMultitaskVariationalStrategy` and `LMCVariationalStrategy` must operate on a **batch** of Gaussian processes, since multiple GPs are needed for multiple output dimensions. (See [section 4.2 of this paper for more information](https://arxiv.org/pdf/1106.6251.pdf)).

However, it's possible that you might want to have a batch of `c` multi-output GPs, each with `d` dimensions. In this case, the `IndependentMultitaskVariationalStrategy` would have a batch shape of `[c, d]`, where `d` would correspond to the multiple outputs, and `c` would correspond to the actual batch of multi-output GPs. In this case, the `task_dim` argument specifies that the `d` dimension corresponds to the GP outputs.

**Comment by ZhiliangWu** [comment]
Hi @gpleiss, thanks for the detailed explanation and pointers. Just to help my understanding:

> the `IndependentMultitaskVariationalStrategy` converts the output of `d` Gaussian processes into a `n x d` MultitaskMultivariateNormal.

In this case, does it mean each task is actually a linear combination of the `d` GP processes? In the case of  `n=d=2`, it is NOT the same as implementing two separated GPs, each for a different output as the following slide (from the author you pointed to at [GPSS2017](http://gpss.cc/gpss17/slides/multipleOutputGPs.pdf))

![image](https://user-images.githubusercontent.com/18686697/95090545-b06c3d00-0725-11eb-88dc-1f70e5e701a6.png)

But rather use batch GPs as "features" for the prediction tasks?

> it's possible that you might want to have a batch of `c` multi-output GPs, each with `d` dimensions. 

In such a case, we set `batch_shape=torch.Size([c, d])` in e.g., `gpytorch.variational.CholeskyVariationalDistribution`? I cannot imagine the cases where we might need such a setup. Could you also kindly give some pointers or examples?

**Comment by ZhiliangWu** [comment]
Hi @gpleiss, I still got stuck on this. 😭 

> However, it's possible that you might want to have a batch of c multi-output GPs, each with d dimensions.

Does it refer to a setup of outputs lying in some grid structure? So actually we have a output of shape `c x d` but split it into a matrix form using `[c, d]`?

**Comment by gpleiss** [comment]
@ZhiliangWu - I am reading back through this issue, and I am having trouble understanding what your setup and model are. Can you describe exactly what you are trying to model, and the expected input/output dimensions of your model?

**Comment by ZhiliangWu** [comment]
Hi, @gpleiss. It would be great if you would take a look at the questions above.

**Comment by gpleiss** [comment]
> I am trying to model a vector of values using multi-output/multi-task GP. The dimensions are e.g., 4 for bounding boxes predictions. The inputs are e.g., 10 dimensional feature vectors for each sample. As far as I understood, the task can be done by using GPyTorch with IndependentMultitaskVariationalStrategy or LMCVariationalStrategy.
> 
> In IndependentMultitaskVariationalStrategy the dependency of the outputs are not considered, so we have a separate GP corresponding for each output. The batch_shape=torch.Size([4]) is used for CholeskyVariationalDistribution(). (A question here would be, is it basically the same as training a separate GP model for each output? In the example, it would be 4 separate GPs for 4 output values. )
> 
> Meanwhile, LMCVariationalStrategy considers the possible dependencies between outputs. If we have batch_shape=torch.Size([3]) inCholeskyVariationalDistribution(), it means each output would modeled by all of these three latent functions from corresponding GPs.
> 
> In both previous cases, we set task_dim=-1 as in the default setting.

Your understanding is correct. If you want 4 outputs, then use `IndependentMultitaskVariationalStrategy` or `LMCVariationalStrategy` as you have described.

> However, from your previous answers, you claimed that one can actually set the batch_shape=(c, d), where c is the number of involved GPs and d is the number of actual outputs.

Just ignore this. What I'm saying is that you can train `c` independent vector-valued GP models, each with `d` output dimensions. It sounds like, from the way you describe the issue, you understand how to use `IndependentMultitaskVariationalStrategy` and `LMCVariationalStrategy` for your purposes.

This thread is quite long and difficult for me to follow/context-switch to, so I am going to close it for now. If you still have questions, please open up a new discussion.
