### ISSUE TITLE
[Bug] Typo in doc - Matern Kernel

### ISSUE THREAD

**Issue by dhruvbalwada** [cornellius-gp/gpytorch#1266]
# 🐛 Bug

Should the documentation here https://docs.gpytorch.ai/en/v1.1.1/kernels.html#maternkernel have $ \Theta^{-2}$ in the definition of `d` like the other kernels (example RBF)?

**Comment by KeAWang** [comment]
That does seem like a typo

**Comment by dhruvbalwada** [comment]
Is d defined a different way then? Maybe it should be $d=\sqrt( (x_1 - x_2)^T (x_1-x_2))$ when $\theta=1$. Otherwise the units don't seem to add up. 
Also, I think that equation you are pointing to seems to suggest that when I take that x1_ and (x2_) and put it in the formula for d in the doc, then there would be a lengthscale^2 in the denominator.

**Comment by KeAWang** [comment]
`d` should be the distance after rescaling, so $d = \sqrt((x_1-x_2)^\top \Theta^{-2} (x_1 - x_2))$
