### ISSUE TITLE
 How to condition stochastic variational GPs on new observations?

### ISSUE THREAD

**Issue by cisprague** [cornellius-gp/gpytorch#1269]
After having optimised the hyperparameters of an `ApproximateGP`, how can I condition it on new observations without having to optimise the hyperparameters again? I think this would be like `ExactGP.get_fantasy_model`.

Thank you!

**Comment by gpleiss** [comment]
For variational GPs you will have to optimize the variational parameters to take the new data into account. Variational GPs require optimization since there is no closed form version of the posterior.

**Comment by cisprague** [comment]
Thanks for the quick reply!
