### ISSUE TITLE
Tuning the mean function with the log marginal likelihood 

### ISSUE THREAD

**Issue by guol1nag** [cornellius-gp/gpytorch#1279]
# 🐛 Bug

The associative hyper-parameters in kernels are tunable by maximising the log marginal likelihood. However, can I know why the mean function (mean_module.constant) is also tunable after maximising the log marginal likelihood? 

I have a noiseless setting so the log marginal likelihood is as follows:

$$log p(f | X) = -(1/2) f^T K^{-1} f - (1/2) log |K| - (n/2) log (2 \pi)$$

From the equation, I can not really see which part containing the mean functions. However from my code, the mean_module.constant changes after training, i.e. maximising the log marginal likelihood.

## To reproduce

** Code snippet to reproduce **
```python
class environment:
    def __init__(self):
        self.x = torch.linspace(0,1.4,7)
        self.X_test = torch.linspace(-0.1,1.5,500)
    
    def function(self,x):
        return torch.sin((10*x)) + torch.exp(x)/2 + torch.sin((30*x))

    def transition(self,x):
        if type(x) is not torch.Tensor:
            x = torch.tensor(x)
        return self.function(x)
    
    def plot(self):
        fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(8, 5))
        ax.plot(self.X_test,self.function(self.X_test))
        ax.set_title("the true function")
        ax.legend()
        plt.show()

env = environment()
X_train1 = (env.x).double()
X_test1 = (env.X_test).double()
y_train1 = env.transition(env.x).double()

# format data 
X_train_ei1 = X_train1.unsqueeze(1)
y_train_ei1 = y_train1.unsqueeze(1)

def model_init(x,y,state_dict=None):
    # zeros-noise settings
    likelihood = gpytorch.likelihoods.GaussianLikelihood()
    likelihood.noise = 1e-4
    likelihood.noise_covar.raw_noise.requires_grad_(False)

    model = botorch.models.SingleTaskGP(x, y, likelihood)

    mll = gpytorch.mlls.ExactMarginalLogLikelihood(model.likelihood, model)
    if state_dict is not None:
        model.load_state_dict(state_dict)
    return mll, model


def ADAM(mll,model, x,y):
    y  = y.squeeze(-1)
    model.train()
    model.likelihood.train()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.1)
    for _ in range(256):
        optimizer.zero_grad()
        output = model(x)
        loss = -mll(output, y)
        loss.backward()
        optimizer.step()
    print("Iter %d - Loss: %.3f" % (256, loss.item()))


mll1, model1 = model_init(X_train_ei1, y_train_ei1)
mll2, model2 = model_init(X_train_ei1, y_train_ei1)
ADAM(mll2,model2, X_train_ei1, y_train_ei1)

print(model1.state_dict()["mean_module.constant"])
print(model2.state_dict()["mean_module.constant"])



```

** Stack trace/error message **
```
tensor([0.], dtype=torch.float64)
tensor([1.4094], dtype=torch.float64)
```

## Expected Behavior

The training should not change mean_module.constant.
## System information

**Please complete the following information:**
-  GPytorch Version: 1.2.0
-  Torch Version: 1.6.0+cu101
-  Running on Google Colab
 
## Additional context
The mean of training sample (y_train_ei1) is 1.4187, and it is still different from the trained mean_module, 1.4094.

**Comment by KeAWang** [comment]
The equation you listed is derived by assuming a zero mean latent `f`. A non-zero mean prior on `f` will give you an equation for the marginal likelihood that involves the mean function. See https://stats.stackexchange.com/questions/280105/log-marginal-likelihood-for-gaussian-process for example
