### ISSUE TITLE
FC layer replacement with GP

### ISSUE THREAD

**Issue by deepkshikha** [cornellius-gp/gpytorch#1280]
How we can use it to implement Gaussian in our Architecture??? like I have a classification model is there a way to use this to replace FC layer in the model with Gaussian process???

**Comment by gpleiss** [comment]
> How we can use it to implement Gaussian in our Architecture???

By architecture do you mean neural network?

> like I have a classification model is there a way to use this to replace FC layer in the model with Gaussian process???

Maybe check out the [deep kernel learning example](https://docs.gpytorch.ai/en/v1.2.0/examples/06_PyTorch_NN_Integration_DKL/Deep_Kernel_Learning_DenseNet_CIFAR_Tutorial.html)
