### ISSUE TITLE
float16 support in gpytorch 1.2?

### ISSUE THREAD

**Issue by mihai-spire** [cornellius-gp/gpytorch#1284]
Does `gpytorch` have specialized support for `float16` variables (half-precision floats)?

I'm doing large-scale exact GP regression with `float32`s and have run into GPU memory limitations. I suspect using half-precision inputs won't have a major impact on numerical accuracy for my particular use case; switching to `fp16` may allow me to increase the size of my training data set. Not sure about the level of fp16 support in the `gpytorch` kernels etc.

**Comment by KeAWang** [comment]
See https://github.com/cornellius-gp/gpytorch/issues/969
