### ISSUE TITLE
[Question] Multi-output SVGP with irregular inputs?

### ISSUE THREAD

**Issue by jrojsel** [cornellius-gp/gpytorch#1285]
Is there a way of training a multi-output variational GP model with irregular inputs, as in the  [Hadamard Multitask GP Regression](https://docs.gpytorch.ai/en/v1.2.0/examples/03_Multitask_Exact_GPs/Hadamard_Multitask_GP_Regression.html) example notebook?

Thanks,
Jimmy

**Comment by gpleiss** [comment]
Hmmm good question. At the moment there isn't - though it shouldn't be hard to make one. What I would recommend for the time being is using the [multi-output variational GP](https://docs.gpytorch.ai/en/v1.2.0/examples/04_Variational_and_Approximate_GPs/SVGP_Multitask_GP_Regression.html), and just selecting the appropriate output dimension for each input.

It shouldn't be too hard to make something like this, but it'd probably require a bit of thought regarding the API design.
