### ISSUE TITLE
Natural Gradient Descent with Pyro Integration

### ISSUE THREAD

**Issue by smsharma** [cornellius-gp/gpytorch#1287]
Hello, I'm trying to use the recently-implemented natural gradient descent to do inference with additional latent variables and non-Gaussian likelihoods through the Pyro integration---essentially, combine the [NGD](https://docs.gpytorch.ai/en/v1.2.0/examples/04_Variational_and_Approximate_GPs/Natural_Gradient_Descent.html) and [low-level Pyro integration](https://docs.gpytorch.ai/en/v1.2.0/examples/07_Pyro_Integration/Pyro_GPyTorch_Low_Level.html) examples notebooks.

My model is very similar to the [low-level Pyro example notebook](https://docs.gpytorch.ai/en/v1.2.0/examples/07_Pyro_Integration/Pyro_GPyTorch_Low_Level.html) model (but with a Poisson rather than Exponential latent function), and the optimization block is a modification of the examples from the [NGD notebook](https://docs.gpytorch.ai/en/v1.2.0/examples/04_Variational_and_Approximate_GPs/Natural_Gradient_Descent.html) as follows:

``` py
pyro.clear_param_store()

num_iter = 3000
num_particles = 32

# Instantiate model
model = PVGPRegressionModel(name_prefix="test", num_inducing=20)

# Define optimizers separately for the variational and hyper-parameters
variational_ngd_optimizer = gpytorch.optim.NGD(model.variational_parameters(), num_data=train_y.size(0), lr=0.1)
hyperparameter_optimizer = torch.optim.Adam(model.hyperparameters(), lr=0.01)

elbo = pyro.infer.Trace_ELBO(num_particles=num_particles, vectorize_particles=True, retain_graph=True)

model.train()

# Training loop 

iterator = tqdm.notebook.tqdm(range(num_iter))

for i in iterator:
    
    model.zero_grad()
    
    variational_ngd_optimizer.zero_grad()
    hyperparameter_optimizer.zero_grad()
    
    loss = elbo.differentiable_loss(model.model, model.guide, train_x, train_y)
    loss.backward()
    
    variational_ngd_optimizer.step()
    hyperparameter_optimizer.step()
    
    iterator.set_postfix(loss=loss, lengthscale=model.covar_module.base_kernel.lengthscale.item())
```

The error, associated with the line `loss = elbo.differentiable_loss(model.model, model.guide, train_x, train_y)
`, is

```
RuntimeError: Non-negative-definite natural covariance. You probably updated it using an optimizer other than gpytorch.optim.NGD (such as Adam). This is not supported.
                Trace Shapes:           
                 Param Sites:           
                Sample Sites:           
num_particles_vectorized dist       |   
                        value    32 |   
                      .u dist 32  1 | 20
                        value 32  1 | 20
```

A notebook with the full example is [here](https://nbviewer.jupyter.org/gist/smsharma/5836cb7556df6ac99cc64a776ea8717d). 

I was wondering if I need to be more careful about the parameters fed into the respective optimizers in this case, or if maybe NGD with this kind of model specification is not currently supported. Thank you!

**Comment by martinjankowiak** [comment]
@smsharma  have you tried using smaller learning rates, in particular for `variational_ngd_optimizer`? for non-conjugate likelihoods a large learning rate can be problematic

**Comment by smsharma** [comment]
@martinjankowiak thanks very much for the very quick response. Indeed setting the learning rate for `variational_ngd_optimizer` in this case to 1e-5 avoided the error, with faster optimization than using a universal Adam opt. Thank you for adding this very nice feature!
