### ISSUE TITLE
User-defined Mean Function

### ISSUE THREAD

**Issue by LL8848** [cornellius-gp/gpytorch#1289]
Hi,

Is there a quick way to use a customized explicit mean function? Something like gpytorch.means.constant_mean but takes a function as the input?  For example, say, I want to use a mean function of m(x) = x**2, how do I implement it in GPyTorch?

Do I have to write a new class inheriting the class Mean?  It seems that the class should have a method `forward`, but I don't quite understand what kind of data type that `forward` returns.  Any answers/comments are greatly appreciated.

Cheers,
Lingnan

**Comment by gpleiss** [comment]
A custom mean is pretty simple to write. See [the linear mean](https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/means/linear_mean.py) for an example.

A mean function should reduce a `(batch) x n x d`-dimensional input into a `(batch) x n` dimensional output. For your example - let's assume you want to return `m(x) = ||x||**2` (since x could have multiple dimensions). It should look like:

```python
class QuadraticMean(Mean):
    def __init__(self):
        pass

    def forward(self, x):
        return x.norm(dim=-1).pow(2)

**Comment by LL8848** [comment]
Thanks a lot for the feedback!
Does the calculation within the `forward` function have to be torch-supported (i.e. vectorized operations)?  Can I brutally 
compute each element of the output vector like this:

```python
from gpytorch.means.mean import Mean

class myMean(Mean):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        m = torch.empty((x.shape[0],1))
        for i,row in enumerate(x[:]):
            m[i] = row[1] ** 2 + row[3]  # The formulae may be much more complicated than this one
        return m
```

I actually tried this code and it didn't work.  The issue seems to do with the backprop.  If only the tensor operations are allowed, is there any way to work around this?  
PS: I only do non-batch GP.

**Comment by jacobrgardner** [comment]
This isn't working for you because you're modifying m in place. Do something like:
```python
m = []
for i, row in enumerate(x[:]):
    m.append(some_calculation)

m = torch.cat(m)
```
and you won't get errors, although it'll be really slow.

**Comment by LL8848** [comment]
Got it!  It's working now.  Really appreciated. 

btw, I used `m = torch.stack(m)` instead because the calculation for each element of `m` will produce zero-dimensional tensor with which `torch.cat()` doesn't work (otherwise will raise the error "zero-dimensional tensor (at position 0) cannot be concatenated").

It's indeed slow, but fortunately I'm working with some small datasets

**Comment by jacobrgardner** [comment]
I'll assume this is closed for now -- reopen or open a new issue if something else comes up.
