### ISSUE TITLE
[Docs][Question] Example on how to adapt Multitask GP Regression to multi dimentional inputs.

### ISSUE THREAD

**Issue by 4aHxKzD** [cornellius-gp/gpytorch#1291]
How can one adapt the example on:

- [GPyTorch Multitask_GP_Regression](https://docs.gpytorch.ai/en/v1.1.1/examples/03_Multitask_Exact_GPs/Multitask_GP_Regression.html)

which I can reproduce here for convenience:

```Python
train_x = torch.linspace(0, 1, 100)

train_y = torch.stack([
    torch.sin(train_x * (2 * math.pi)) + torch.randn(train_x.size()) * 0.2,
    torch.cos(train_x * (2 * math.pi)) + torch.randn(train_x.size()) * 0.2,
], -1)
```

to the case of 2 dimensional inputs, for example?

More specifically, I would like for the sine and cosine to have 2 inputs instead of 1.

for example, like this:

``` Python
x = np.arange(-5, 5, 0.1)

y = np.arange(-5, 5, 0.1)

xx, yy = np.meshgrid(x, y)

z1 = np.sin(xx**2 + yy**2) / (xx**2 + yy**2)
z2 = np.cos(xx**2 + yy**2) / (xx**2 + yy**2)
```

**Comment by jacobrgardner** [comment]
@4aHxKzD This should be as straightforward as having a `num_data x num_dimensions` training data matrix `X` and a `num_data x num_tasks` training label matrix `y`. Is there specific code where that isn't working?

**Comment by 4aHxKzD** [comment]
I'm trying to run the code from that example but with

``` Python
>>> train_x.shape
torch.Size([100, 2])
```

and

``` Python
>>> train_y.shape
torch.Size([100, 2])
```
and i'm getting 

``` Python
RuntimeError: Expected object of scalar type Float but got scalar type Double for argument #3 'mat2' in call to _th_addmm_out
```

**Comment by 4aHxKzD** [comment]
This is how I generated my fake data

``` Python
x = np.linspace(-5,5,10)
y = np.linspace(-5,5,10)
xmesh, ymesh = np.meshgrid(x, y)

xx = xmesh.reshape(-1,1)
yy = ymesh.reshape(-1,1)

xy = np.hstack((xx, yy))

z1 = np.sin(xmesh**2 + ymesh**2) / (xmesh**2 + ymesh**2)
z2 = -1 / (xmesh**2 + ymesh**2 + 1)

zz = np.hstack(( z1.reshape(-1,1), z2.reshape(-1,1)))

train_x = torch.from_numpy(xy);
train_y = torch.from_numpy(zz);
```

**Comment by jacobrgardner** [comment]
This isn't a dimensionality issue. Numpy's default dtype is double while torch's is float.

You either need to do `train_x = train_x.float()` and `train_y = train_y.float()` or `model = model.double()`.

**Comment by 4aHxKzD** [comment]
I checked the type of the elements inside the numpy arrays before asking, and it gave me floats. Weird

**Comment by jacobrgardner** [comment]
Numpy calls double "float64"

**Comment by 4aHxKzD** [comment]
I did not know about that. Thanks again!
