### ISSUE TITLE
Time for bugfix release?

### ISSUE THREAD

**Issue by y0ast** [cornellius-gp/gpytorch#1320]
I just hit a combination of:
https://github.com/cornellius-gp/gpytorch/commit/5bff5be87be033f2d3a95423557b5af3dbf1746b
https://github.com/cornellius-gp/gpytorch/commit/903ae8bac6f35b250a0a3f58302935510d336f57

and it was very painful to debug.

Would it be possible to make a 1.2.1 bugfix release?

I am running the nightly now, so it's fixed for me, but I don't wish anyone else the same bug chase experience. :)

Thanks for your work! I thoroughly enjoy GPyTorch.

**Comment by gpleiss** [comment]
Can do! I'm going to try to squeeze in one or two more bug fixes today - then I'll cut a release later today/early tomorrow.

**Comment by gpleiss** [comment]
Released.
