### ISSUE TITLE
[Question] Is it possible to output 3*sigma using confidence_region?

### ISSUE THREAD

**Issue by sjiang2018** [cornellius-gp/gpytorch#1321]
Hello there!

[confidence region](https://docs.gpytorch.ai/en/v1.2.1/_modules/gpytorch/distributions/multivariate_normal.html?highlight=confidence_region#)
default return 2 standard deviations.

Is there any way to output 3 standard deviation?

Thanks!

**Comment by gpleiss** [comment]
You can write your own method pretty easily:
```python
def confidence_region(mvn):
    return mvn.mean - mvn.stddev * 3, mvn.mean + mvn.stddev * 3
```

**Comment by sjiang2018** [comment]
Thanks!
