### ISSUE TITLE
Don't Use Stochastic Trace Estimation for KroneckerProductAddedDiagLT logdets

### ISSUE THREAD

**Issue by wjmaddox** [cornellius-gp/gpytorch#1331]
Quit using stochastic trace estimation to estimate backwards passes through `KroneckerProductAddedDiagLazyTensor` log determinants. This change will remove the logdet backwards setup call in https://github.com/cornellius-gp/gpytorch/blob/8f9b44fc57dbb0a13b568946f07a37e9332f92c4/gpytorch/lazy/kronecker_product_added_diag_lazy_tensor.py#L32 in order to improve memory efficiency and instead use pytorch's native backwards pass through symeig instead.

```
import torch

from gpytorch.lazy import KroneckerProductLazyTensor, KroneckerProductAddedDiagLazyTensor
from gpytorch.kernels import MaternKernel

xlist = [torch.randn(x, 1).cuda() for x in [100, 200, 210, 5]]
kernel_list = [MaternKernel().cuda()] * 4

eval_kernel = KroneckerProductLazyTensor(*[k(x) for k, x in zip(kernel_list, xlist)])

eval_kernel_with_noise = eval_kernel.add_jitter(0.1)

# is extremely memory intensive and OOMs on many GPUs.
solve, ld = eval_kernel_with_noise.inv_quad_logdet(torch.randn(100 * 200 * 210 * 5).cuda(), logdet=True)
```

This OOMs because internally we use 10 samples for the trace estimation part of the log determinant rather than backpropagating through the output of symeig (which would mean multiplication with slightly smaller matrices).

Stack tracing in the `matmul` here gives this output
```
> /..../gpytorch/gpytorch/lazy/kronecker_product_lazy_tensor.py(192)_matmul()
    190             rhs = rhs.unsqueeze(-1)
    191 
--> 192         res = _matmul(self.lazy_tensors, self.shape, rhs.contiguous())
    193 
    194         if is_vec:

ipdb> rhs.shape
torch.Size([21000000, 11])
```

I know that stability with backpropagation through the eigenvalues is going to be an issue for some kernels (especially RBF), but we could maybe implement something to fall back onto if the backwards pass nans out or something to resolve that issue?
Looking at the math further, I could alternatively implement something non-stochastic for the backwards pass given that the derivative is pretty clear --- this approach could also allow for varying types of diagonalization in the solves (e.g. one component is large enough that we would use Lanczos on while we use symeig on the others).

**Comment by gpleiss** [comment]
I think if we're going to compute the logdet with an eigendecomposition, it might make since to also compute the inv_quad term with the eigendecomposition as well? @jacobrgardner what do you think?

I like the idea of falling back on stochastic trace estimation/CG if symeig fails. That should hopefully account for numerical instabilities.

**Comment by wjmaddox** [comment]
Yeah, so `KroneckerProductAddedDiagLazyTensor` solves are already done with eigendecompositions, but the implementation in `KroneckerProductLazyTensor` uses a standard inv_matmul (which is probably more scalable if one of the components is really large). Ideally, I'd like to add support for both lazy tensors to have partial eigen-decompositions coming out from Lanczos but I'm not entirely sure how to do that yet.

So, maybe the way to implement the inv_quad with eigendecompositions is to use the eigendecomposition for the root decomposition if it's already been computed (so we don't have to run cholesky to get out another root decomposition). That probably will require playing with the lazy tensor backend I think?

**Comment by gpleiss** [comment]
Yeah - the root decomposition approach seems reasonable.
