### ISSUE TITLE
[Problem] Estimation period parameter of the PeriodicKernel

### ISSUE THREAD

**Issue by joacorapela** [cornellius-gp/gpytorch#1335]
I struggled to make GPyTorch learn the period parameter of the periodic kernel, as I show below. Then I realized that the kernel covariance matrix of the periodic kernel is singular at countably infinite values of the period parameter. These singularities densely cover with local maxima the optimization landscape of the period parameter (i.e., the value of the marginal log likelihood as a function of the period parameter -- bottom panel of the figure below). Therefore, for any initial value of the period parameter the numerical optimization will converge to a close-by local maxima. I would greatly appreciate any feedback about the correctness of these arguments and any workaround.

I simulated a Gaussian Process with a periodic kernel with period parameter equal to 5.0. I used an ExactGPModel to estimate this parameter but could not do it. The code for this simulation and estimation appears at http://www.gatsby.ucl.ac.uk/~rapela/gpytorch/problemPeriodParam/doTestPeriodicKernel.py

The top panel of the figure below plots the condition number of the periodic kernel covariance matrix as a function of its period parameter value. It shows multiple singularities. The bottom panel plots the marginal log likelihood as a function of the same parameter. Ideally the largest value should be at the generative period (5.0), but it is not, and the optimization landscape is filled by local maxima. The code to generate this plot can be found at http://www.gatsby.ucl.ac.uk/~rapela/gpytorch/problemPeriodParam/doPlotMLL.py

![condNumberAndLowerBound](https://user-images.githubusercontent.com/27322752/98483038-4ac81080-21fd-11eb-957e-e264bb29b7a9.png)

My explanation for the reason for this problem appears at http://www.gatsby.ucl.ac.uk/~rapela/gpytorch/problemPeriodParam/explanation.pdf

Thanks.

**Comment by jacobrgardner** [comment]
My hunch is that the issue doesn't have much to do with the kernel matrix being singular. The thing is, we don't need to invert `K` directly ever, we invert it after adding likelihood noise which by default is lower bounded by 1e-4 in GPyTorch. Even if `K` is singular due to duplicate data points (or, equivalently with a periodic kernel, data points separated by exactly a period), `K + sI` is positive definite.

I think the period length can often just be somewhat difficult to estimate starting from a single restart. Do you still have the same problem if you start the initial period length closer to the true one?

**Comment by joacorapela** [comment]
Thanks for your feedback Jacob!                                                                                                           

Your hunch was completely right. The problem was unrelated to the ill-conditioning of the kernel covariance matrix, but happened because I was using too few points to calculate the marginal log likelihood (I was afraid that including too many points would increase the ill conditioning of the matrix and make the problem even worse). But after your response I increased this number of points and, as expected, the kernel covariance matrix became more poorly conditioned. However, despite this, the marginal log likelihood showed a clear peak at the generative period parameter 5.0.

For the records, the figure below shows the simulated data in the top panel, the kernel covariance matrix condition number as a function of the period parameter in the middle panel, and the marginal log likelihood as a function of the period parameter in the bottom panel. The code to generate this figure appears at http://www.gatsby.ucl.ac.uk/~rapela/gpytorch/problemPeriodParam/doPlotMLL2.py

![condNumberAndLowerBound88736753](https://user-images.githubusercontent.com/27322752/98701423-2bea8b00-2371-11eb-9b6b-814588580925.png)

Thanks again!
