### ISSUE TITLE
Keops for Index Kernel

### ISSUE THREAD

**Issue by xanderladd** [cornellius-gp/gpytorch#1348]
I am currently using Keops for the hadamard multitask example and it works great, thanks! Now, I am interested in making a keops wrapper for index kernel, but I am wondering if that is even possible? It seems like it might not be because index kernel involves some explicit evaluation and custom lazy tensor operations that keops doesn't support, but I am hoping I could get a second opinion before I jump into it. The motivation is that if I could do the MVM that is done on index kernel and rbf kernel in keops, the program would be even faster. 

Thank you in advance for advising.

**Comment by jacobrgardner** [comment]
@xanderladd You could possibly do this, but I'm not sure that you should want to. Calling an IndexKernel already returns a fairly efficient lazy tensor representation that can be combined with the KeOpsLazyTensors returned by KeOps kernels, as would be done in the hadamard multitask notebook, for example.

Is there a specific reason you also want to use KeOps for IndexKernel?

**Comment by xanderladd** [comment]
The motivation for doing this is that if index kernel was wrapped by keops, instead of doing using the lazy tensor .mul method to multiply index and covariance kernels, one could use the keops math operators. To my understanding this result in further acceleration and scalability.

 For example, using two GPUs, it takes about 15 minutes to train Hadamard example at 100k training points using keops and only about 90 seconds to do the exact GP version (same # of iterations). But it seems that maybe this change would not reconcile this difference? I want to make sure it would before I start working on it.

**Comment by jacobrgardner** [comment]
@xanderladd that's actually a fairly reasonable reason to want to do this. I imagine you probably would get at least some speed up if KeOps can handle hadamard products times a vector.

To be honest, I'm not entirely sure whether KeOps supports the indexing you need here. The easiest thing to do might be to just try it, and see where it fails.

**Comment by xanderladd** [comment]
@jacobrgardner ok, glad to see that theoretically there is a possible speed up here. So far I can tell that keops supports this indexing for vectors, unclear what will happen if I try matrices... but now I will try it out and see what happends. Since this was just a question I'll close this and reopen if anything notable happens.
