### ISSUE TITLE
Exact GPs should compute test and train kernel matrices separately at test time

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#135]
Persuant to the discussion in #113, Exact GPs should compute the various covariance matrices needed for the predictive distribution separately. This could save a lot of time and space for applications like BayesOpt, and also make the white noise kernel implementation a little easier since we wouldn't have to pad the diagonal with `t` zeros.

@gpleiss and I talked, and I think a great solution is to only create matrices as they are needed. Basically `exact_gp.py` would create some object like a `LazyKernelEvaluationVariable`, whose `__getitem__` and `diag` methods would explicitly call the kernel.  E.g., `my_lazy_evaled_kernel[:n_train, :n_train]` would actually call the kernel on `k(x_train, x_train)`.

In addition to space and time savings, with this kind of construct, something like the code as written by @Balandat in #113 for the white noise kernel would work.

**Comment by Balandat** [comment]
This would be awesome. And it would make it straightforward to cache `k(x_train, x_train)` for eval mode.

**Comment by jacobrgardner** [comment]
I am going to work on this unless someone would prefer that #134 gets handled first. I have no preference on an order for these two, but this issue seems more directly problematic for using exact GPs for BayesOpt.

**Comment by Balandat** [comment]
makes total sense, I think this is higher pri as it will make #113 much easier
