### ISSUE TITLE
[Docs] Training Multiple Models Problem

### ISSUE THREAD

**Issue by eitanlees** [cornellius-gp/gpytorch#1358]
I have been working with the example: [Cox Processes (w/ Pyro/GPyTorch Low-Level Interface)](https://docs.gpytorch.ai/en/latest/examples/07_Pyro_Integration/Cox_Process_Example.html)

The example works well, but I ran into trouble when trying to train multiple Cox models. 

The simplest way to reproduce my issue is to copy the entire notebook and paste it again at the bottom. The first model runs as expected but the second model fails to train. 

### First Model
![Screen Shot 2020-11-23 at 11 29 10 AM](https://user-images.githubusercontent.com/2041969/99988923-0ea9b980-2d80-11eb-946e-d996eae5b9e8.png)
### Second Model
![Screen Shot 2020-11-23 at 11 29 20 AM](https://user-images.githubusercontent.com/2041969/99988929-0f425000-2d80-11eb-8bf9-13b104150ec9.png)

I am unsure why the same code ran twice in a single notebook would lead to different results.

Any advice would help. 

Thanks!

**Comment by jacobrgardner** [comment]
I think this has to do chiefly with how pyro stores model parameters. If you haven't changed the model prefix name in your second model, pyro will use the same parameter store for the second model as for the first. Basically, it keeps a global record of parameters.

**Comment by eitanlees** [comment]
Ah! That fixed everything. Thanks for your help!
