### ISSUE TITLE
[Bug] priors are lost after deepcopy (and ExactGP.get_fantasy_model) 

### ISSUE THREAD

**Issue by sdaulton** [cornellius-gp/gpytorch#1360]
# 🐛 Bug

GPyTorch modules register priors using a (name, prior, closure, setting_closure) tuple. The closure and setting_closure are callables that reference the instance (self) as a global variable. When a module is deepcopied. Those closure methods are copied over, but still reference the original instance (not the new copy). Therefore the closure returns the parameters attached to the old module, not the new copy. This makes the loss term from the priors constant in the MLL evaluation.

## To reproduce
[test_deepcopy.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/5585605/test_deepcopy.ipynb.txt)

## Expected Behavior

Ideally, the prior distributions would work as expected on fantasy models.

**Comment by sdaulton** [comment]
FYI @Balandat @danielrjiang

**Comment by Balandat** [comment]
Hmm yeah that's not good. One possible way to fix this would be to override `__deepcopy__` to make those closures point to the newly created object. But it's not clear if there is a way to do this programmatically. 

These closures may not be a great design patten after all (I introduced this to be flexible and allow things like putting priors over derived functions of parameters as done here https://github.com/cornellius-gp/gpytorch/blob/d931d0c6a9b7caf66cbcec2c49d6f532cc516f44/gpytorch/likelihoods/multitask_gaussian_likelihood.py#L248 

It also is a challenge when trying to serialize things. 

Any suggestions for a better solution here? One thing we could do is require the closures to take the instance as an argument (and thereby not making them closures anymore).

**Comment by Balandat** [comment]
also FYI @bletham, @qingfeng10, @jpchen

**Comment by Balandat** [comment]
Fixed the referencing issue in #1361. This doesn't address the serializability concerns, but one thing at at time...
