### ISSUE TITLE
[Docs] Clustered Multitask GP

### ISSUE THREAD

**Issue by kseverso** [cornellius-gp/gpytorch#1375]
I'm trying to implement the clustered multitask GP described here: https://docs.gpytorch.ai/en/v1.2.1/examples/07_Pyro_Integration/Clustered_Multitask_GP_Regression.html

I'm using a toy dataset based off of the example used in the multitask GP tutorial then I go through the following steps:

    model = ClusterMultitaskGPModel(train_x, train_y, num_functions=2)

    num_particles = 1
    num_iter = 1000`

    def train(lr=0.01):
        optimizer = pyro.optim.Adam({"lr": 0.1})
        elbo = pyro.infer.Trace_ELBO(num_particles=num_particles, vectorize_particles=True, retain_graph=True)
        svi = pyro.infer.SVI(model.model, model.guide, optimizer, elbo)
        model.train()

       iterator = tqdm.notebook.tqdm(range(num_iter))
       for i in iterator:
           model.zero_grad()
           loss = svi.step(train_x, train_y)
           iterator.set_postfix(loss=loss)

    %time train()

    # Set into eval mode
    model.eval()

    # Make predictions
    with torch.no_grad(),  gpytorch.settings.fast_pred_var():
        test_x = torch.linspace(0, 1, 51)
        predictions = model.likelihood(model(test_x))
        mean = predictions.mean

The documentation notes how we need to add functionality to sample when the likelihood is used in predictive mode, however I get the following error when I attempt to make predictions: 
`ModuleAttributeError: 'ClusterGaussianLikelihood' object has no attribute '_cluster_dist'`
which traces back to the forward function in the likelihood. I don't understand enough Pyro yet to de-bug, can someone help me understand? Thanks!

**Comment by jacobrgardner** [comment]
@kseverso I'm pretty sure that the pyro sample calls involving `_cluster_dist` calls in the likelihood definition in that notebook should just be something like:
```python
        pyro.sample(
            self.name_prefix + ".cluster_logits",  # self.name_prefix is added by PyroGP
            pyro.distributions.OneHotCategorical(logits=self.variational_cluster_logits).to_event(1)
        )
```
Try swapping that in and see if it works? We can put up a PR to fix that

**Comment by zhidilin** [comment]
> ```python
>         pyro.sample(
>             self.name_prefix + ".cluster_logits",  # self.name_prefix is added by PyroGP
>             pyro.distributions.OneHotCategorical(logits=self.variational_cluster_logits).to_event(1)
>         )
> ```
> 
> Try swapping that in and see if it works? We can put up a PR to fix that

I faced the same problem, it didn't work by swapping the above codes. So can anyone help figure out why this is the case? Thanks.
