### ISSUE TITLE
Get posterior covariance matrix between two sets of points

### ISSUE THREAD

**Issue by henrymoss** [cornellius-gp/gpytorch#1391]
# 🚀 Feature Request

Hi 

I have been trying to calculate the posterior covariance between two sets of points X1 and X2 for some Bayesian Optimisation applications.

For example, suppose that X1 is a set of n points and X2 is a set of m points. I want to return the posterior covariance evaluated between X1 and X2, i.e a n*m matrix.

Is this possible with gpytorch? I have struggled to work out how to do this. 

Thanks Henry

**Comment by gpleiss** [comment]
Right now the best way to do this is to compute

```python
# X1 <- n x d
# X2 <- m x d
with gpytorch.settings.fast_pred_var():
    out = model((torch.cat[X1, X2], dim=-2))
    cross_covar = out.lazy_covariance_matrix[:n, n:]
```

The covariance terms are lazily evaluated, so this is a fairly efficient operation. Under the hood, it doesn't compute any additional posterior covariance terms.

**Comment by henrymoss** [comment]
Thanks so much!

Henry
