### ISSUE TITLE
Minimal Documentation

### ISSUE THREAD

**Issue by AjayTalati** [cornellius-gp/gpytorch#14]
Hi,

thanks for releasing this repository - it's really cool :+1: 

I was just wondering if you would be providing any minimal documentation? The examples are really nice, some extra comments though we be very helpful, especially for folks new to GPs. 

Maybe easier for you, perhaps references to tutorials/other learning materials/video lectures? I'm guessing a lot of newbies, will be drawn to this repo :) 

Thanks.

**Comment by gpleiss** [comment]
Documentation is definitely in the works! We're trying to finish up some features/interface changes first, and then we'll add documentation and release an alpha.

As a GP-newbie myself, this library is definitely designed for those with little GP knowledge (as well as GP experts like @jrg365).

We're shooting for a mid-September alpha, by the way.

**Comment by AjayTalati** [comment]
Sounds great :)

Just in case folks are looking for resources to help them here's some good links,

[GPflow](https://gpflow.readthedocs.io/en/latest/tutorialsAndExamples.html) - similar to this repo, but in TF
[GPy](http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/index.ipynb) - a nice place to start if you want to get a feel for GPs without too much technical stuff

**Comment by gpleiss** [comment]
I'm going to close this issue for now. Each of the example notebooks is now much more well documented, and we have a README guide to help guide model building.

We hope to have bigger documentation in the future, which will outline more about the internals. For now, this repo should be more usable though.
