### ISSUE TITLE
[Question] How to use different kernels for every feature or every subset of features

### ISSUE THREAD

**Issue by mohammad-saber** [cornellius-gp/gpytorch#1401]
Hi,

Assume that I have 3 features in the dataset (feature_A, feature_B, feature_C). Each feature may have 1 or more columns. 

Is it possible to use a different kernel for every feature? For example:

kernel_A for feature_A ---> A1 * RBF() 

kernel_B for feature_B ---> A2 * RBF() 

kernel_C for feature_C ---> A3 * Matern(nu=1.5) 

A1, A2, A3 are hyper-parameters.

To calculate K(X1, X2):
kernel_A is used only for feature_A in X1 and X2
kernel_B is used only for feature_B in X1 and X2
kernel_C is used only for feature_C in X1 and X2

Then, final output will be: 
kernel_A + kernel_B + kernel_C

Reason:
In the dataset, some features have binary values, and I would like to use a different kernel for those features. 
Also, some other features have different physical meanings. So, I would to try the idea of using different kernels for different features. 

I am new to Gaussian Processes.I really appreciate it, if you could guide me.

**Comment by gpleiss** [comment]
See the `active_dims` attribute ([documentation here](https://docs.gpytorch.ai/en/stable/kernels.html#kernel)). Assuming `feature_A/B/C` correspond to dimensions `0/1/2`, then:

```python
kernel_a = RBFKernel(active_dims=[0])
kernel_b = RBFKernel(active_dims=[1])
kernel_c = MaternKernel(nu=1.5, active_dims=[2])
self.covar_module = kernel_a + kernel_b + kernel_c
```

If all sub-kernels are the same type of kernel (e.g. RBF), then you can use `AdditiveStructureKernel` for increased parallelism:

```python
self.covar_module = AdditiveStructureKernel(RBFKernel(ard_num_dims=3), num_dims=3)
```

(this is equivalent to `kernel_a + kernel_b + kernel_c`, if each of the kernels are RBF kernels).

Hope this helps!

**Comment by mohammad-saber** [comment]
Thank you. 

How can I multiply each Kernel by a constant value? For example:

ConstantKernel() * RBFKernel()

I checked the list of kernels. I couldn't find "ConstantKernel()". It seems that GPyTorch considers the constant kernel by default. Is my understanding correct?

**Comment by gpleiss** [comment]
`ScaleKernel(kernel_a)` will add a learnable constant multiple. If you have a fixed constant, then do:
covar = kernel_a(input) * fixed_constant.

**Comment by mohammad-saber** [comment]
Is it possible to add a learnable constant as addition (like below)?

ConstantKernel() + kernel_a + kernel_b + kernel_c

**Comment by gpleiss** [comment]
Sorry for the slow reply @mohammad-saber . That is possible, but you'd probably have to write your own `ConstantKernel`. That should be pretty straightforward - see [this tutorial](https://docs.gpytorch.ai/en/latest/examples/00_Basic_Usage/Implementing_a_custom_Kernel.html) for details.

I'm going to close this issue for now - but if you would like to discuss this more please open up a [Discussion](https://github.com/cornellius-gp/gpytorch/discussions).

**Comment by aegonwolf** [comment]
> `ScaleKernel(kernel_a)` will add a learnable constant multiple. If you have a fixed constant, then do: covar = kernel_a(input) * fixed_constant.

@gpleiss Sorry, I am probably not understanding this right. When I try to do this, I get float is not a subclass of module. Do have to wrap the constant in something?
