### ISSUE TITLE
[Question] Not independent tasks with different input lenghts

### ISSUE THREAD

**Issue by desch142** [cornellius-gp/gpytorch#1403]
Hi everyone,
I am currently working on a project, where I have e.g 8 vital parameters (_tasks_), which are not independant from each other. Each vital paramter (_task_) consists of a the numerical value for the measurement (y_i) and the corresponding time/hours passed for the measurement (x_i). My problem is, that I now have multiple _x_i_ and _y_i_ with different lengths, since the measurements were taken irregulary for each specific vital parameter (_task_).
I would like to use a MultitaskGP for this problem and obtain an 8xn tensor _T_, where n corresponds to length(_x_pred_). So _T_ should then have "regular" sampled values for the specific vital parameters. 

Is there a possibility to use multiple _(x,y) pairs_ with different lengths for a MultitaskGPModel ?

Sadly I could not find such a case in the documentation :/ 

Thank you in advance

**Comment by Balandat** [comment]
You should be able to do this with the Hadamard-style MTGP in https://github.com/cornellius-gp/gpytorch/blob/master/examples/03_Multitask_Exact_GPs/Hadamard_Multitask_GP_Regression.ipynb

**Comment by desch142** [comment]
Thank you very much for this quick and very very helpful answer! 

Is there a way to obtain the data in the MultivariateNormal(loc: torch.Size([...])) object directly or to have it as a torch.tensor ?

Happy Holidays and stay healthy!

**Comment by Balandat** [comment]
yeah so `observed_pred_y1.mean` will give you the mean and `observed_pred_y1.covariance_matrix` will give you the (dense) covariance matrix of the posterior distribution, both as torch tensors.

**Comment by desch142** [comment]
Thanks!
