### ISSUE TITLE
Computing mean cache for training set using loaded model parameters

### ISSUE THREAD

**Issue by m-julian** [cornellius-gp/gpytorch#1406]
Hello,

I am trying to load in a model file with optimized parameters and write out K<sub>XX</sub><sup>-1</sup>**y**, to a separate file.
However, I am not sure if I am calculating K<sub>XX</sub><sup>-1</sup>**y** (alpha) correctly, below is a snippet of my script (some of the code is from the mean_cache method) https://github.com/cornellius-gp/gpytorch/blob/4dec144de87ae4b6900f4afffcd6f276455b6786/gpytorch/models/exact_prediction_strategies.py#L277-L284

``` 
# .... training and valdiation part

self.likelihood = gpytorch.likelihoods.GaussianLikelihood()
# prior mode, no training data
self.model = ExactGPModel(train_x=None, train_y=None, likelihood=self.likelihood)

state_dict = torch.load("model_file.pth")
self.model.load_state_dict(state_dict)
self.model = self.model.cuda()
self.likelihood = self.likelihood.cuda()

self.model.eval()
self.likelihood.eval()

mvn = self.likelihood(self.model(self.train_x), self.train_x)
train_mean, train_train_covar = mvn.loc, mvn.lazy_covariance_matrix
train_labels_offset = (self.train_y - train_mean).squeeze(-1)
alpha = train_train_covar.evaluate_kernel().inv_matmul(train_labels_offset).squeeze(-1)
alpha = alpha.cpu().detach().numpy().reshape(-1,1)

# write out values ....
```

Is this approach for evaluating alpha after loading in model parameters correct, and is there an easier way of obtaining the cache directly?

**Comment by gpleiss** [comment]
The easiest way of evaluating `alpha` is making a prediction with the model, and then calling `alpha = self.model.prediction_strategy.mean_cache`.

**Comment by m-julian** [comment]
Ah that makes it much simpler, thank you very much for the quick response!
