### ISSUE TITLE
Travis CI doesn't actually run Python 2.7 tests

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#142]
See https://travis-ci.org/cornellius-gp/gpytorch/jobs/382926170 for an example (0 tests ran).

The Python 3 tests still work fine, but this explains why the Python 2 tests have never failed in recent memory even when the Python 3 tests do :-).

Considering a couple of us develop on Python 3, this could theoretically mean we have some undetected backward compatibility issues. I doubt it, though.

**Comment by Balandat** [comment]
Interesting. Wonder why that is...

Anyone has an idea when pytorch is going to cut py2 support? numpy/scipy/pandas are doing it for new releases starting the end of this year...

**Comment by jacobrgardner** [comment]
My opinion on this is we should maintain 2.7 compatibility until PyTorch drops it, and then we can as well.
