### ISSUE TITLE
[Docs] Access linear kernel parameter

### ISSUE THREAD

**Issue by Dan15993** [cornellius-gp/gpytorch#1425]
Hello, I am Daniele and I am new to GitHub. I am trying to use GPyTorch for an industrial project and, after quite a bit of struggling, I decided to ask for some help here.

I am trying to customize the simple linear regression example found in the documentation. Instead of an RBF kernel I have used a linear kernel:
```
class MyGP(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(MyGP, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ZeroMean()
        self.covar_module = gpytorch.kernels.LinearKernel(ard_num_dims=input_dim, has_lengthscale=True)
```
In my mind this code should produce the kernel defined as K(x_i,x_j) = x_i^\top \Sigma x_j where the matrix \Sigma represents the lengthscale. Following the example of the documentation, I was able to produce predictions.

The problem I have is that for my application I need the matrix \Sigma (which should have size input_dim times input_dim) for some subsequent computations. According to my understanding of the documentation, the matrix \Sigma should be in `model.covar_module.lengthscale`, but I get `None` as result.

I am aware that this might be a very dumb question but, is there a way to access that matrix? Thanks a lot in advance for your help!

**Comment by dme65** [comment]
If you look at the docs you can see that the linear kernel as it is implemented doesn't have a lengthscale parameter which is why you get `None`: https://docs.gpytorch.ai/en/stable/kernels.html#linearkernel.

**Comment by Dan15993** [comment]
Dear dme65, thank you very much for your answer. I did suspect that but then it comes the question: is there no way to implement that simple dot-product kernel, i.e. K(x,y) = x^\top \Theta y? 

Thanks for your assistance, it is deeply appreciated!

**Comment by gpleiss** [comment]
In your model, you could include a parameter that represents `\Theta`:

```python
class GPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        # ....
        self.covar_module = gpytorch.kernels.LinearKernel()
        self.register_parameter("theta_factor", torch.nn.Parameter(torch.randn(d, d)) # theta_factor.T @ theta_factor = theta
    
   def forward(self, input):
        scaled_input = self.theta_factor @ input
        covar = self.covar_module(scaled_input)
        # ...
```

**Comment by Dan15993** [comment]
Dear gpleiss, thank you very much for your answer, and forgive my ignorance: I am a rookie in Pytorch as well. 

If I understood correctly in this way the hyperparameters of my kernel K(x,y) = x^\top \Theta y will be the square root of \Theta right? 

Thank you very much!
