### ISSUE TITLE
[Docs] inducing_points and learn_inducing_points

### ISSUE THREAD

**Issue by ginward** [cornellius-gp/gpytorch#1427]
Hi all, hope you are staying well and safe! 

I just have a quick question regarding the documentation on `gpytorch.variational.VariationalStrategy`. 

I am just not sure why, if `learn_inducing_points` is by default `True`, one still needs to supply `inducing_points`.  From my (likely wrong) understanding, by setting `learn_inducing_points = True`, the model should learn the inducing points by itself, right? If that is the case, why would I still need to supply specific inducing point location (`inducing_points`) to it? 

Thanks!

- Link to [GPyTorch documentation](https://docs.gpytorch.ai/en/v1.1.1/variational.html)

**Comment by gpleiss** [comment]
This makes it possible to use custom initialization procedures for the inducing points.

**Comment by ginward** [comment]
I see. So the GP will actually learn the inducing points later?

**Comment by gpleiss** [comment]
Yes - that is correct.
