### ISSUE TITLE
[Docs] performance of the SM kernel with unevenly spaced observations

### ISSUE THREAD

**Issue by iprada** [cornellius-gp/gpytorch#1435]
# 📚 Documentation/Examples

**Is there documentation missing?**

The fast-fourier transform assumes that the observations (i.e. train_x) are evenly spaced. Do the initialization routines of the SM kernel takes this into account?

My guess after scanning through the code is that "initialize_from_data" should handle the above issue, while the "initialize_from_data_empspect" should not be used when the data is not evenly spaced.

**Is documentation wrong?**
No, it is okay, as long as this is clarified

**Is there a feature that needs some example code?**

No

**Think you know how to fix the docs?** (If so, we'd love a pull request from you!)

f the above is an issue for the "initialize_from_data_empspect" routine, I'll be happy to update the docs myself.

On the other hand, one could use Lomb-Scargle periodograms (https://iopscience.iop.org/article/10.3847/1538-4365/aab766/pdf) to initialize from the empirical spectrum, on cases were observations are unevenly spaced. 

Best,

Iñigo

**Comment by gpleiss** [comment]
> My guess after scanning through the code is that "initialize_from_data" should handle the above issue, while the "initialize_from_data_empspect" should not be used when the data is not evenly spaced.

Yes - that is the intended use case. If you have suggestions for how to note this in the documentation, please put up a PR!

**Comment by iprada** [comment]
Great. Thanks for the clarification!

 I have added two sentences to the documentation on the PR #1439. I hope it helps
