### ISSUE TITLE
[Docs] Mistake in the Simple_GP_Regression.ipynb notebook about GaussianLikelihood

### ISSUE THREAD

**Issue by alantan-SQ40** [cornellius-gp/gpytorch#1441]
https://github.com/cornellius-gp/gpytorch/blob/master/examples/01_Exact_GPs/Simple_GP_Regression.ipynb
In the notebook in the link above it says that: 

The likelihood
The simplest likelihood for regression is the gpytorch.likelihoods.GaussianLikelihood. This assumes a heteroskedastsic noise model (i.e. all inputs have the same observational noise).

However, in the documentation:
https://docs.gpytorch.ai/en/stable/likelihoods.html#gaussianlikelihood

it says that GaussianLikelihood is: The standard likelihood for regression. Assumes a standard homoskedastic noise model.

Which is correct?

**Comment by Balandat** [comment]
it should be heteroskedastsic -> homoskedastic in the notebook

**Comment by gpleiss** [comment]
This appears to be fixed on the master branch.
