### ISSUE TITLE
[Docs] Prediction with or without noise

### ISSUE THREAD

**Issue by torabin** [cornellius-gp/gpytorch#1455]
Hi there, was wondering whether GPytorch uses the noise term in the prediction or not? I mean when applying model(test_x) in https://docs.gpytorch.ai/en/v1.1.1/examples/01_Exact_GPs/Simple_GP_Regression.html, is the nugget effect (noise on the diagonal) incorporated or not. Sorry I could not figure that out from the documentation. Thanks

**Comment by Balandat** [comment]
No. To get the prediction including the noise term, you will need to do `likelihood(model(test_x))`
