### ISSUE TITLE
[Feature Request] should psd_safe_cholesky always respect cholesky jitter settings? 

### ISSUE THREAD

**Issue by mshvartsman** [cornellius-gp/gpytorch#1457]
# 🚀 Feature Request

`psd_safe_cholesky` takes max jitter as an argument. Looking across the codebase, sometimes `gpytorch.settings.cholesky_jitter.value()` is passed in and sometimes it's not. Is there a pattern I'm missing? If not, should it default to the global setting if nothing is passed rather than defaulting to a hardcoded 1e-6 or 1e-8 depending on the input dtype? 

## Motivation

In our active learning setting, we occasionally run into crashes where the default jitter isn't big enough. I've set the global jitter value to be higher to avoid them, so I was surprised to see that it's still crashing with the smaller jitter. 

## Pitch

Defaulting to the global setting value is the behavior I would expect. An alternative is for users to change the `psd_safe_cholesky` calls directly but they're almost always buried pretty deep elsewhere in gpytorch (or in my case, botorch) rather than my client code so there's no easy path there. 

Willing to PR this. This would be a breaking behavior change though, and I'm not sure of other downstream effects on other client code.

**Comment by Balandat** [comment]
Sounds reasonable to me. I don't really see a reason for this not to take the values set in the global settings..

**Comment by gpleiss** [comment]
@mshvartsman a PR would be great!
