### ISSUE TITLE
[Docs]MaternKernel formula

### ISSUE THREAD

**Issue by hayato-n** [cornellius-gp/gpytorch#1458]
The documentation for the [Matern Kernel](https://docs.gpytorch.ai/en/stable/kernels.html#maternkernel) says that the Matern kernel is

<img src=
"https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Bequation%2A%7D%0A+++k_%7B%5Ctext%7BMatern%7D%7D%28%5Cmathbf%7Bx_1%7D%2C+%5Cmathbf%7Bx_2%7D%29+%3D+%5Cfrac%7B2%5E%7B1+-+%5Cnu%7D%7D%7B%5CGamma%28%5Cnu%29%7D%0A+++%5Cleft%28+%5Csqrt%7B2+%5Cnu%7D+d+%5Cright%29+K_%5Cnu+%5Cleft%28+%5Csqrt%7B2+%5Cnu%7D+d+%5Cright%29%0A%5Cend%7Bequation%2A%7D%0A" 
alt="\begin{equation*}
   k_{\text{Matern}}(\mathbf{x_1}, \mathbf{x_2}) = \frac{2^{1 - \nu}}{\Gamma(\nu)}
   \left( \sqrt{2 \nu} d \right) K_\nu \left( \sqrt{2 \nu} d \right)
\end{equation*}
">

but I suspect that the usual Matern kernel (such as described [here](https://en.wikipedia.org/wiki/Matérn_covariance_function)) is 

<img src=
"https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Bequation%2A%7D%0A+++k_%7B%5Ctext%7BMatern%7D%7D%28%5Cmathbf%7Bx_1%7D%2C+%5Cmathbf%7Bx_2%7D%29+%3D+%5Cfrac%7B2%5E%7B1+-+%5Cnu%7D%7D%7B%5CGamma%28%5Cnu%29%7D%0A+++%5Cleft%28+%5Csqrt%7B2+%5Cnu%7D+d+%5Cright%29%5E%5Cnu+K_%5Cnu+%5Cleft%28+%5Csqrt%7B2+%5Cnu%7D+d+%5Cright%29%0A%5Cend%7Bequation%2A%7D%0A" 
alt="\begin{equation*}
   k_{\text{Matern}}(\mathbf{x_1}, \mathbf{x_2}) = \frac{2^{1 - \nu}}{\Gamma(\nu)}
   \left( \sqrt{2 \nu} d \right)^\nu K_\nu \left( \sqrt{2 \nu} d \right)
\end{equation*}
">

Is it mistake of documentation, or the implementation of GPyTorch is different from others?

**Comment by gpleiss** [comment]
Mistake in documentation. If you could put up a PR fixing this, that'd be great.

**Comment by hayato-n** [comment]
Thanks. Should I fix the docstrings in https://github.com/hayato-n/gpytorch/blob/master/gpytorch/kernels/matern_kernel.py ?

**Comment by gpleiss** [comment]
@hayato-n I was making some other bug fixes, so I just pushed a change. Docs are fixed now.

**Comment by hayato-n** [comment]
@gpleiss I got it. Thank you!
