### ISSUE TITLE
[Feature Request] Is there any reason why LessThan constraint does not take initial_value as argument?

### ISSUE THREAD

**Issue by pabloprf** [cornellius-gp/gpytorch#1463]
# 🚀 Feature Request

`constraints.constraints.GreaterThan()` does take `initial_value` as argument. However, the sister function `LessThan()` does not take it, even though they share the parent `Interval` class. Is there any reason why `LessThan` should not have such capability? 

## Motivation

I wanted to add a maximum value for the noise in my GP model, but without the `initial_value` constraint my optimizer failed at fitting the hyperparameters. Adding `initial_value` solved my issue, so I figured it may be good to have it in the code.

**Comment by Balandat** [comment]
Hmm no I think this must have been an oversight. Happy to review a PR if you want to put it up, should be as simple ass adding that arg and passing it to the superclass constructor.

**Comment by gpleiss** [comment]
Closed by #1464
