### ISSUE TITLE
Typo in examples/03_Multitask_Exact_GPs/Multitask_GP_Regression.ipynb

### ISSUE THREAD

**Issue by 4aHxKzD** [cornellius-gp/gpytorch#1472]
I think that there is a typo in [Line 87 of Multitask_GP_Regression.ipynb](https://github.com/cornellius-gp/gpytorch/blob/17899474f8442407a78945fc5e69052d5a04bb40/examples/03_Multitask_Exact_GPs/Multitask_GP_Regression.ipynb#L87) as this model does not use a `IndexKernel` but a `MultitaskKernel` instead. This might have been copied from the Hadamard notebook.

As an offtopic, could you also add another point to the list that explains the differences between this model and the `ExactGP` with a little explanation of what the rank of the `MultitaskKernel` does? Or add the explanation to point 2

> 2. Rather than just using a RBFKernel, we're using that in conjunction with a MultitaskKernel. This gives us the covariance function described in the introduction. "Explain why we need to specify the rank here".

**Comment by gpleiss** [comment]
Thanks for catching this typo! Any chance you could put up a PR to fix it?

> As an offtopic, could you also add another point to the list that explains the differences between this model and the ExactGP with a little explanation of what the rank of the MultitaskKernel does?

The rank controls the complexity of the model. A rank-2 kernel corresponds to a model where all output dimensions are controlled by two independent latent processes. See [this paper, chapter 4](https://arxiv.org/pdf/1106.6251.pdf) for more details.

**Comment by 4aHxKzD** [comment]
> Thanks for catching this typo! Any chance you could put up a PR to fix it?

Sure, I'll do it.

**Comment by 4aHxKzD** [comment]
> > Thanks for catching this typo! Any chance you could put up a PR to fix it?
> 
> Sure, I'll do it.

**Comment by gpleiss** [comment]
Closed by #1475
