### ISSUE TITLE
How are additive kernels represented

### ISSUE THREAD

**Issue by dhruvbalwada** [cornellius-gp/gpytorch#1478]
I am trying to learn how to add and multiply different kernels together, and am doing this a bit arbitrarily at this point. 
The thing I find confusing is, how is the internal representations of combined kernels being made? 

In the screenshot below you can see that things like `kernels.0.kernels.0` are being set. I would have have thought that if I added three kernels then I might get 'kernels.0`, 'kernels.1`, 'kernels.2` etc.  

Am I doing something wrong? or is there some documentation on how the parameters get represented? I am asking because I want to initialize the different parameters, and it is quite confusing to figure out which kernel is getting inherited inside what.

![Screen Shot 2021-02-11 at 11 05 19 PM](https://user-images.githubusercontent.com/18236610/107739424-b23ea200-6cbd-11eb-996a-77c1e523fe9f.png)

**Comment by gpleiss** [comment]
That's a good point. I'll put up a quick PR to make this read better.
In the future, it's better to post actual code rather than screenshots so we can reproduce the examples easier.

**Comment by watNoel** [comment]
I had  a similar issue, particularly initializing an and retrieving the parameter values (not raw values) for additive kernels.
Is there a convenient way of doing this for additive/product kernels?

The convenience method shown in the tutorial:

# Convenient way of getting true outputscale
print(f'Actual outputscale: {model.covar_module.outputscale}')
# Convenient way of setting true outputscale
model.covar_module.outputscale = 2.
print(f'Actual outputscale after setting: {model.covar_module.outputscale}')

Does not seem to work when the parameters names include things like  ".0." or ".1." as in the example posted above.

**Comment by gpleiss** [comment]
Additive kernels don't have an output scale. If you are wrapping your additive kernel with a ScaleKernel, then this code that you posted should work.

**Comment by watNoel** [comment]
Well, I managed to work around the issue as shown in the supplied notebook, however the method is strange and i just felt there is likely some simpler way of doing this that I'm just missing. 

---
'''
%ipynb 
def Parameter_value_extractor(model):
'''

---

**Comment by watNoel** [comment]
Well, I managed to solve part of  the issue in the following rather convoluted way:
-------

import math
import torch
import gpytorch
from matplotlib import pyplot as plt
import numpy as np
train_x = torch.linspace(0, 5, 300)

 `Let's take some simple function as response`
train_y = 10*torch.sin(train_x * (2 * math.pi*0.2 )) + torch.randn(train_x.size()) * math.sqrt(0.04) + 2*torch.sin(train_x*2*math.pi* 3) 

class ExactGPModelAnyKernel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood,kernel):
        super(ExactGPModelAnyKernel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module=kernel
    def forward(self,x):
        mean_x=self.mean_module(x)
        covar_x= self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
    
    
likelihood = gpytorch.likelihoods.GaussianLikelihood()

`I realized one can initialize values of hyperparameters before actually creating the additive kernel`
kernel = gpytorch.kernels.ScaleKernel(gpytorch.kernels.PeriodicKernel().initialize(period_length=3)+
                                      gpytorch.kernels.PeriodicKernel().initialize(period_length=1)
                                     ).initialize(outputscale=10)

model = ExactGPModelAnyKernel(train_x, train_y, likelihood,kernel)

`Cumbersome way of retrieving the true values of model hyperparameters, is there a better way?`

for param_name, param in model.named_parameters():
        print(f'Parameter name: {param_name:42} \n value = {param.item()}')
        if model.constraint_for_parameter_name(param_name) is not None:
            constraint=model.constraint_for_parameter_name(param_name)
            print(f"True Value is : {constraint.transform(param.data)} \n  ")

----------
### The output below this highlights the strange names of the parameters but gets the correct true values 
Parameter name: likelihood.noise_covar.raw_noise           
 value = 0.0
True Value is : tensor([0.6932]) 
  
Parameter name: mean_module.constant                       
 value = 0.0
Parameter name: covar_module.raw_outputscale               
 value = 9.999954223632812
True Value is : 10.0 
  
Parameter name: covar_module.base_kernel.kernels.0.raw_lengthscale 
 value = 0.0
True Value is : tensor([[0.6931]]) 
  
Parameter name: covar_module.base_kernel.kernels.0.raw_period_length 
 value = 2.9489307403564453
True Value is : tensor([[3.]]) 
  
Parameter name: covar_module.base_kernel.kernels.1.raw_lengthscale 
 value = 0.0
True Value is : tensor([[0.6931]]) 
  
Parameter name: covar_module.base_kernel.kernels.1.raw_period_length 
 value = 0.5413248538970947
True Value is : tensor([[1.]])

-----
### Now,  If I want to set a new value to any of these hyperparameters, how would I do this? 
The analogy to the "convenient method" would be, for the period length of the 0th kernel as an example:

 `model.covar_module.base_kernel.kernels.0.period_length= `somevalue`

Which is invalid syntax.

I guess I can create some loop in a similar fashion as I've done above but just thought there might be simpler way I'm just missing
