### ISSUE TITLE
[Bug] Unexpected behavior -- initial value for constraint sets raw value, not transformed value

### ISSUE THREAD

**Issue by syncrostone** [cornellius-gp/gpytorch#1481]
# 🐛 Bug

Setting the initial value of a parameter constraint sets the raw parameter to that value, not the transformed parameter. I expect the transformed parameter to be set as that is what I and I expect other users would want to set as the initial value. 

If setting the raw parameter is the expected / desired behavior, then that should be clarified in the docs.

## To reproduce

** Code snippet to reproduce **
```python
import torch
import gpytorch
initial_value = torch.tensor(1.)
kernel = gpytorch.kernels.RBFKernel(lengthscale_constraint=gpytorch.constraints.Positive(initial_value=initial_value))
print("kernel lengthscale: %f \nkernel raw_lengthscale: %f"% (kernel.lengthscale, kernel.raw_lengthscale))
```

** Stack trace/error message **
```
kernel lengthscale: 1.313262 
kernel raw_lengthscale: 1.000000
```

## Expected Behavior

I expect the following output
```
kernel lengthscale: 1.00000
kernel raw_lengthscale: 0.541325
```

because I expect the above code snippet to be equivalent to 
```python
import torch
import gpytorch
initial_value = torch.tensor(1.)
kernel = gpytorch.kernels.RBFKernel()
kernel.lengthscale= initial_value
print("kernel lengthscale: %f \nkernel raw_lengthscale: %f"% (kernel.lengthscale, kernel.raw_lengthscale))
```

## System information

**Please complete the following information:**
- GPyTorch Version 1.3.1
- PyTorch Version 1.7.1+cu101

**Comment by gpleiss** [comment]
Will be closed by #1482 . Thanks @syncrostone !
