### ISSUE TITLE
SpectralMixtureKernel overwrites Module initialize() function

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#149]
SpectralMixtureKernel has an `.initialize()` function that overrides the function fo the same name of the superclass `Module`, but these functions have different purposes. This is confusing and has created hard to debug issues for me working on the Priors. 

Since this function is used nowhere in the code, I suggest simply renaming this to `initialize_training_data`.

**Comment by jacobrgardner** [comment]
The spectral mixture kernel uses initialization procedures for the hyperparams that are based on the training data. It is kind of a special case.

We could rename the method to something like `initialize_from_data`.

Another option might be to make the kernel require training data in __init__ and perform those initializations by default. The SM kernel is extremely sensitive to hyperparameter initialization and things can go very awry with bad init, so we might just make it the default behavior.

Either way, it doesn't have to stay in a method called `initialize`.

**Comment by Balandat** [comment]
Ok I will rename it to `initialize_from_data` for now to avoid the issues mentioned above. We can figure out whether we want to make this the default behavior down the road. Maybe you can open an issue for that so we can keep this one contained?

**Comment by Balandat** [comment]
Resolved by #150
