### ISSUE TITLE
[Question] how to build a customer MultiOutput kernels ?

### ISSUE THREAD

**Issue by linkzhao** [cornellius-gp/gpytorch#1498]
hi, i am new guy. in my project, I want to usea customer MultiOutput kernels,  I tried, but failed. my kernel form refer to the attachment. can you help me code it by gpytorch when you are free? thank you very much!

<img width="331" alt="kernel" src="https://user-images.githubusercontent.com/20676356/108508253-81322300-72f6-11eb-9308-b10ed135dd0a.PNG">

**Comment by gpleiss** [comment]
Hi @linkzhao - please open up a [discussion](https://github.com/cornellius-gp/gpytorch/discussions) rather than an issue for this topic.
