### ISSUE TITLE
[Bug] num_gauss_hermite quadrature value setter isn't working

### ISSUE THREAD

**Issue by wjmaddox** [cornellius-gp/gpytorch#1509]
# 🐛 Bug

Trying to set `num_gauss_hermite_quadrature(int)` isn't affecting the number of locations in the quadrature.

I think it's with how the default is set in the initialization because using `num_likelhood_samples(int)` works fine so it's not just the setter method.

## To reproduce

** Code snippet to reproduce **
```python
from gpytorch.utils.quadrature import GaussHermiteQuadrature1D
from gpytorch.settings import num_gauss_hermite_locs

with num_gauss_hermite_locs(25):
    quadrature = GaussHermiteQuadrature1D()
    print(num_gauss_hermite_locs._global_value) # 25
    print(num_gauss_hermite_locs.value()) # 25
    print(quadrature.num_locs) # 20
```

** Stack trace/error message **
see above

## Expected Behavior

`quadrature.num_locs` should be 20

## System information

**Please complete the following information:**
- gpytorch master
- torch 1.7.0

**Comment by gpleiss** [comment]
Closed by #1513
