### ISSUE TITLE
Parallel GPU training

### ISSUE THREAD

**Issue by stanbiryukov** [cornellius-gp/gpytorch#151]
Hi there,
Has anyone been able to train a GP model utilizing multiple GPUs via torch.nn.DataParallel?

**Comment by jacobrgardner** [comment]
It's not something we've specifically designed the package to support currently, but multi GPU support is definitely something worth considering. The most obvious place multi GPU support would be useful are the matrix multiplications we do in CG. This might not be super difficult to implement for exact GPs, but I expect it may require a significant amount of effort for the sparse GP methods.

**Comment by stanbiryukov** [comment]
Great - I've been attempting to implement multi-gpu training for an exact GP classification model.  I think for larger models where exact GP is desired this will be a useful enhancement.  Will loop back in if I make progress.

**Comment by eytan** [comment]
@stanbiryukov, any updates on this?

**Comment by stanbiryukov** [comment]
@eytan No updates yet - haven’t been able to spend more time with parallelism.  For my particular problem I simply used a sparser dataset.

**Comment by stanbiryukov** [comment]
Good point, using KISSGP on all training data instead of exact GP on sparser data improved my out of sample RMSE.  Thanks @andrewgordonwilson

**Comment by jacobrgardner** [comment]
@stanbiryukov #450 adds support for multiple GPUs!
