### ISSUE TITLE
Use of VariationalStrategy wrappers in Deep multitask GPs [Docs]

### ISSUE THREAD

**Issue by jdavid04** [cornellius-gp/gpytorch#1510]
Hi,

I've been trying to build a Deep, variational, multitask GP following the documentation examples, both from the variational multitask GP, and the multitask DeepGP. I eventually got it to work following the multitask DeepGP example very closely. I initially failed to get working code when incorporating the variational multitask GP example's comments about requiring a multitask wrapper around the variational strategy object (LMCVariationalStrategy and IndependentMultitaskVariationalStrategy). So my questions are:

1) Why would these wrappers not be required in the multitask DeepGP case?
2) How are the final outputs treated if nothing is specified. I assume independently? If so, why would an IndependentMultitask object also cause issues? 

It seemed possible upon inspection that the dimension manipulations in the DeepGP layer might be handling the multitask case differently from ApproximateGP, which could explain these issues. But I'm not sure exactly what is going on there.

Any insight would be appreciated. Thanks

**Comment by gpleiss** [comment]
> Why would these wrappers not be required in the multitask DeepGP case?

This is handled by the DeepGPLayer wrapper class. Most DeepGP layers are multi-output by nature.

> How are the final outputs treated if nothing is specified. I assume independently? If so, why would an IndependentMultitask object also cause issues?

Independent. Currently, this is the only option.
