### ISSUE TITLE
[Question] Multiple mean predictions when defining custom likelihood

### ISSUE THREAD

**Issue by roussel-ryan** [cornellius-gp/gpytorch#1514]
# 📚 Documentation/Examples

Hello, I'm trying to follow the example for using Non-Gaussian Likelihoods here https://docs.gpytorch.ai/en/latest/examples/04_Variational_and_Approximate_GPs/Non_Gaussian_Likelihoods.html 
and I tried to adapt the Laplace likelihood file 
https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/likelihoods/laplace_likelihood.py 
to define a custom LogNormal likelihood.

The model trains fine with a simple dataset, however when I go to do the prediction at a set of test points, it returns a set of 10 means and 10 variances at each test point. I'm not sure why it is doing this and could use some help/explanation as to why this is happening (trying to comb through the documentation did not reveal any answers).

I attached a simple example script of what I'm trying to do
[custom_likelihood.zip](https://github.com/cornellius-gp/gpytorch/files/6052663/custom_likelihood.zip)

Thanks!

**Comment by roussel-ryan** [comment]
Thank you for your response! That is what I thought was happening but I wasn't sure. Is there a place I can specify the number of samples returned in this manner?

**Comment by gpleiss** [comment]
Yes. Use the context manager `with gpytorch.settings.num_likelihood_samples(<value>):` context manager.

**Comment by roussel-ryan** [comment]
Perfect, thank you for your help!
