### ISSUE TITLE
[Docs] White noise kernel (for DeepGP layers)

### ISSUE THREAD

**Issue by EvanBaker57** [cornellius-gp/gpytorch#1522]
# 📚 Documentation/Examples

Hi,

Is it possible to create an additive white nosie kernel? Something like the "White" kernel in gpflow. I know there used to be a WhiteNoiseKernel in gpytorch before, but I think that depended on something called "DiagLazyVariable", which no longer exists, and it was mainly for fixed (known) variances.

The reason I'd like a white noise kernel is to add a cosntant noise term to the diagonal to be learnt. I know that for single layer GPs, this is all wrapped up in the likelihood; but for deepGPs it currently isn't possible for each layer to also have a noise term(?) and the easiest way would be to modify the kernels? (basically, how does one implement y = f1 (f2 + noise) + noise1?)

Any advice (whether that be how to make this custom kernel, or some other way to make noisy deepGP layers, or be told that this is a silly idea) would be appreciated.

Thanks,
Evan

**Comment by wjmaddox** [comment]
A basic way would be to add a new parameter in the initialization and then add it to the output of the covariance matrix in the forwards pass of the layer. For example, copying over from the deep GP tutorial, you would have something like:

```python

class ToyDeepGPHiddenLayer(DeepGPLayer):
    def __init__(self, input_dims, output_dims, num_inducing=128, mean_type='constant'):
        if output_dims is None:
            inducing_points = torch.randn(num_inducing, input_dims)
            batch_shape = torch.Size([])
        else:
            inducing_points = torch.randn(output_dims, num_inducing, input_dims)
            batch_shape = torch.Size([output_dims])

        variational_distribution = CholeskyVariationalDistribution(
            num_inducing_points=num_inducing,
            batch_shape=batch_shape
        )

        variational_strategy = VariationalStrategy(
            self,
            inducing_points,
            variational_distribution,
            learn_inducing_locations=True
        )

        super(ToyDeepGPHiddenLayer, self).__init__(variational_strategy, input_dims, output_dims)

        if mean_type == 'constant':
            self.mean_module = ConstantMean(batch_shape=batch_shape)
        else:
            self.mean_module = LinearMean(input_dims)
        self.covar_module = ScaleKernel(
            RBFKernel(batch_shape=batch_shape, ard_num_dims=input_dims),
            batch_shape=batch_shape, ard_num_dims=None
        )
        self.noise_term = torch.nn.Parameter(torch.zeros(batch_shape, 1), requires_grad=True)

    def forward(self, x):
        mean_x = self.mean_module(x)
        # add a constant term to the covariance and ensure that the noise term is positive
        covar_x = self.covar_module(x).add_jitter(self.noise_term.exp())
        return MultivariateNormal(mean_x, covar_x)

    def __call__(self, x, *other_inputs, **kwargs):
        """
        Overriding __call__ isn't strictly necessary, but it lets us add concatenation based skip connections
        easily. For example, hidden_layer2(hidden_layer1_outputs, inputs) will pass the concatenation of the first
        hidden layer's outputs and the input data to hidden_layer2.
        """
        if len(other_inputs):
            if isinstance(x, gpytorch.distributions.MultitaskMultivariateNormal):
                x = x.rsample()

            processed_inputs = [
                inp.unsqueeze(0).expand(self.num_samples, *inp.shape)
                for inp in other_inputs
            ]

            x = torch.cat([x] + processed_inputs, dim=-1)

        return super().__call__(x, are_samples=bool(len(other_inputs)))
```

**Comment by EvanBaker57** [comment]
thanks,
I didn't know about the add_jitter command

WIth the above I get the following error:

```python
Traceback (most recent call last):

  File "<ipython-input-76-b790acf972c3>", line 1, in <module>
    model = DeepGP()

  File "<ipython-input-72-71ad38465900>", line 4, in __init__
    hidden_layer1 = ToyDeepGPHiddenLayer(

  File "<ipython-input-75-bd731ddd0395>", line 32, in __init__
    self.noise_term = torch.nn.Parameter(torch.zeros(batch_shape, 1), requires_grad=True)

TypeError: zeros() received an invalid combination of arguments - got (torch.Size, int), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 ```
 
 What would the correct inputs to that line

**Comment by wjmaddox** [comment]
Oops, should have been `torch.zeros(*batch_shape, 1)` I believe

**Comment by EvanBaker57** [comment]
That does then run, but the noise_term parameters don't optimise or change at all; they just stay as 0 (or whatever their original value is set to). Any ideas?

**Comment by wjmaddox** [comment]
Good catch, I should have tested out the solution in the deep gps code. switching the `add_jitter` to `add_diag` results in the noise terms having gradients and moving in your synthetic example:

The initialization in the deep GPs code now looks like this: 
```python
        self.raw_noise = torch.nn.Parameter(0.1 * torch.ones(*batch_shape, 1), requires_grad=True)
        self.register_constraint("raw_noise", gpytorch.constraints.Positive())

    @property
    def noise(self):
        return self.raw_noise_constraint.transform(self.raw_noise)
    
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x).add_diag(self.noise)

        return MultivariateNormal(mean_x, covar_x)
```

**Comment by EvanBaker57** [comment]
Thanks,
That does indeed run now.

However, I don't think it does what it should do (but this might be a bug, rather than documentation?).
If I turn off the likelihood variance (because the newly added noise term should be doing the same job in that last layer), the variability does not seem to be captured at all.

See below for prediction results (after 10,00 epochs rather than 200):

And I used the following code to set the likelihood variance to (near) zero
```python
model.likelihood.noise_covar.register_constraint("raw_noise", gpytorch.constraints.Positive())
model.likelihood.noise_covar.raw_noise.requires_grad_(False)
model.likelihood.noise_covar.noise = 0.000001
```

![1000](https://user-images.githubusercontent.com/66376590/110469843-0a58a080-80d2-11eb-8161-67000d381673.png)


Is it likely that the noise terms aren't being estimated properly, or that the predictions aren't using them? or something more serious?

**Comment by wjmaddox** [comment]
You're right that the model is probably unidentifiable if you include both the diagonal noise in the final deep gp layer and in the likelihood. There's also going to be a small distinction in the performance of both terms separately due to how the likelihood estimates the data log probability. 

The likelihood function is estimating the log probability by integrating over the approximate posterior, e.g. `E_{q(f)}(-log p(y | f))` so that setting `q(f) = N(\mu, \Sigma + \sigma^2 I)` and assuming `p(y | f) = N(y | f, \epsilon)` is likely going to result in different gradients than using `q(f) = N(\mu, \Sigma + \epsilon I)` and learning the likelihood noise `p(y | f) = N(y | f, \sigma^2)` for fixed `\epsilon` and learnable `\sigma^2`.

All of this goes to say that clamping the final layer's noise term to be small and learning the likelihood noise estimates both the mean and the variability in a sensible fashion:
```python
model.last_layer.raw_noise.detach_()
# hacky way to set raw noise b/c i didnt implement a setter
model.last_layer.raw_noise.data.mul_(0.).add_(-5.)
# should be 0.0067
print(model.last_layer.noise)
```

Running the rest of the script gets me something that looks like this:
![image](https://user-images.githubusercontent.com/13008542/110641869-7a256480-8180-11eb-87f9-e73affb7ff1b.png)

**Comment by EvanBaker57** [comment]
Hmm,

Even fixing the last layer noiser term, and letting the likelihood noise term be learnt; this then does suggest that the noise terms in the deepGP layers aren't being learnt properly (or that they aren;t being used properly in predictions)

For example, for a different example, using the DeepGP code from GPy (http://inverseprobability.com/talks/notes/deep-gps.html), I get the following predictions:

![GPy DeepGP](https://user-images.githubusercontent.com/66376590/110667427-250a4280-81c2-11eb-8981-8741f2ced13b.png)


But using the GPytorch code I get the following, which doesnt look right:

![GPytorch](https://user-images.githubusercontent.com/66376590/110667488-36534f00-81c2-11eb-9344-990bedb1edea.png)

The inference algorithms are different, but the underlying models are (I think) the same. Including these noise terms in the latent layers should allow the changing noise to be picked up, but its not here. You can see this with the previous example as well, where the smaller variance near x = 0 is not captured (although that could have been chalked up to limited data, I now don't think it is).

**Comment by wjmaddox** [comment]
Like in my previous comment, there is a subtle distinction in my understanding between fixing the likelihood noise and fixing the last layer noise. In the second setting, I'm not really sure if either is going to be able to model that type of heteroscedastic noise because both are fundamentally homoscedastic noise models. 

From your reference, I'm not sure if you're really comparing the same models, and I'd suggest a) double checking that they are the same speicification and b) after that, try plugging in the model parameters (with variational distributions) into gpytorch from the working GPy model.

**Comment by EvanBaker57** [comment]
Sorry for the slow reply.

They aren't quite the same models, and so the exact parameters cant be plugged in (for example, GPys deepGP doesnt seem to have variational distributions for the last layer), but they are still both DeepGPs with the same number of layers, so I would have thought that some kind of simialrity would exist (its jsut a difference in inference isn't it?)

Also, I thought that heteroscedascitiy could arise because the final model would be something like y = f( g(x) + e1) + e2, where e1 and e2 are homoscedastic noise terms, and because e1 is being transformed by f the resulting nosie would be heteroscedastic?


Either way, I've managed to get good performance by using the PredictiveLogLikelihood rather than the VariationalELBO. Is this coupling allowed along with the DeepApproximateMLL module with deepGPs?

**Comment by wjmaddox** [comment]
Re your first comment: it wasn't clear to me if the GPy deep GP was residual, whereas this one definitely is. That was my original concern (don't know why a residual deep GP would be harder to train on this data, but seems like a big confounding factor).

Second comment: yes, but optimization to produce heteroscedasticity could be quite tricky.

I think it should be fine to use PredictiveLogLikelihood, especially as it's designed to pull out more heteroscedasticity in the response.

**Comment by georgedeath** [comment]
Just for completeness: even without adding a new white noise term for each layer I was able to recreate all of the heteroscedasticity found in Neil Lawrence's examples (marathon, step function, motorcycle helmet) using the PredictiveLogLikelihood -- the VariationalELBO really led to poor results. Good shout @EvanBaker57 .

**Comment by jacobrgardner** [comment]
Also for completeness: For deep GPs, the direct analog of using PredictiveLogLikelihood would be the deep sigma point process, which we have an example notebook for. That'll use DeepPredictiveLogLikelihood.

**Comment by georgedeath** [comment]
> 
> 
> Also for completeness: For deep GPs, the direct analog of using PredictiveLogLikelihood would be the deep sigma point process, which we have an example notebook for. That'll use DeepPredictiveLogLikelihood.

Thanks, Jacob. I'll give that a whirl.
