### ISSUE TITLE
question about example "Simple_GP_Regression"(question)

### ISSUE THREAD

**Issue by open2333** [cornellius-gp/gpytorch#1535]
Hi there, I am running the example "Simple_GP_Regression", I am using points without noise and I got this result 
![image](https://user-images.githubusercontent.com/43056772/111603716-9758d380-880f-11eb-843c-9d325bd3fb19.png)

May I ask how can I get the result that the confidence(variance) is zero at training points(observed data ) like the picture 
![image](https://user-images.githubusercontent.com/43056772/111603950-cd965300-880f-11eb-9dbc-d36a0be44418.png)

Many thanks to whoever can help me with this, Thank a loooooot!

**Comment by gpleiss** [comment]
Hi @open2333 - can you open a [discussion topic](https://github.com/cornellius-gp/gpytorch/discussions) on this issue? We like to reserve issues for bugs and feature requests.
