### ISSUE TITLE
[Docs] about LMCVariationalStrategy

### ISSUE THREAD

**Issue by sjiang2018** [cornellius-gp/gpytorch#1547]
If there is a multi-dimension output [y1, y2, y3, y4, y5]; only y4 and y5 are correlated. Is there a way to specify the correlated output dimensions in  LMCVariationalStrategy, instead of setting num_latents as 4. 

- Link to [GPyTorch documentation](https://gpytorch.readthedocs.io)
- Link to [GPyTorch examples](https://github.com/cornellius-gp/gpytorch/tree/master/examples)

**Comment by gpleiss** [comment]
Hi @sjiang2018 - would you mind asking your question as a [discussion topic](https://github.com/cornellius-gp/gpytorch/discussions)? We're trying to reserve issues for bugs and feature requests.
