### ISSUE TITLE
Add docstrings for automatic documentation generation

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#156]
Something that has been on the list for a while has been to add docstrings so we can host a Read the Docs. 

I've started doing this on the `documentation` branch, using the Google style docstrings (http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html), starting with `lazy_variable.py`, and will make my way through the package a bit at a time. It would be great if we could start adding brief docstrings as we create new files. 

Once we have slightly better coverage, I'll actually take a stab at setting up the documentation generation, as well as writing up more general documentation stuff about how to use the package, etc. The example notebooks are nice, but it'll be great to have something properly written as well. My goal is to have a reasonable version of this up by mid July or so.

**Comment by gpleiss** [comment]
It's started! http://gpytorch.readthedocs.io
