### ISSUE TITLE
Inverse of a non-symmetric matrix

### ISSUE THREAD

**Issue by tawe141** [cornellius-gp/gpytorch#1597]
Is there a way to do an inverse of a non-symmetric LazyTensor? It looks like all the tools available assume a symmetric matrix, even `LazyTensor.svd()`, which uses `symeig` under the hood. Would I need to `evaluate()` the kernel and use PyTorch's tools instead?

**Comment by Balandat** [comment]
Yeah currently Lazy tensors are pretty much all symmetric psd (except for `TriangularLazyTensor`s). We had some abstract plans to support more general ones in https://github.com/cornellius-gp/linear_operator but never got to it.

**Comment by tawe141** [comment]
Very well, thanks!
