### ISSUE TITLE
[Bug] Wrong formulation of the PeriodicKernel

### ISSUE THREAD

**Issue by glemaitre** [cornellius-gp/gpytorch#1615]
# 🐛 Bug

The current formulation of the periodic kernel is the following:

<img src="https://render.githubusercontent.com/render/math?math=k(\mathbf{x^1, x^2}) = \exp ( \frac{-2 \sin^2(\frac{\pi}{p} \sum_i | x^{1}_{i} - x^{2}_{i} |)}{l^2} )">

However, the original formula proposed [Mackay, 1998](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.81.1927&rep=rep1&type=pdf) (Eq. 47) is the following:

<img src="https://render.githubusercontent.com/render/math?math=k(\mathbf{x^1, x^2}) = \exp ( \frac{-0.5  \sum_i \sin^2(\frac{\pi}{p} | x^{1}_{i} - x^{2}_{i} |)}{l^2} )">

The constant is not -2 or -0.5 is not really important (it will have an impact on the derivative only). However, the original formulation is taking the the sum of the sine squared of the difference. Currently, the formulation is the sine squared of the sum of the difference. Note that the confusion could come from the fact that in the literature, the kernel is used for 1D signal and thus there is no sum, thus both formulations are equivalent.

In addition, looking at the implementation, it seems that the distance computed between the samples is norm-2 distance and not the norm-1 distance.

The current formulation make it that the kernel is not PSD. In addition, there is still another bug with a missing square over the length scale as reported in https://github.com/cornellius-gp/gpytorch/issues/1020.

Note: I found this issue because I am currently working on a similar issues in scikit-learn:
https://github.com/scikit-learn/scikit-learn/issues/19343
https://github.com/scikit-learn/scikit-learn/pull/20070

## To reproduce

** Code snippet to reproduce **
```python
import numpy as np
import torch
from gpytorch.kernels import PeriodicKernel

r = np.linspace(0, 1, num=4)
train_x, train_y = np.meshgrid(r, r)
X = np.stack((train_x.flatten(), train_y.flatten()), axis=-1)

periodicity, length_scale=1.5, 0.5
kernel_pytorch = PeriodicKernel(
    period=periodicity, length_scale=length_scale
)
K_pytorch = kernel_pytorch(torch.from_numpy(X))

np.linalg.eigh(K_pytorch.numpy())[0]
```

** Stack trace/error message **
```
array([-1.27815495, -1.21435487, -1.21435487, -0.93566031, -0.75456704,
       -0.24301193, -0.24301193,  0.47435512,  0.72370254,  1.58773803,
        1.58773803,  2.42356711,  2.67356606,  2.67356606,  3.10565507,
        6.63322787])
```

There is some negative eigenvalues.

## Expected Behavior

We are investigating the issue in scikit-learn and already implemented a naive approach: https://github.com/scikit-learn/scikit-learn/pull/20070 for tracking the bug. With the code of the PR, there is no negative eigenvalues:

```python
from sklearn.gaussian_process.kernels import ExpSineSquared

kernel_sklearn = ExpSineSquared(
    periodicity=periodicity, length_scale=length_scale,
)
K_sklearn = kernel_sklearn(X)
np.linalg.eigh(K_sklearn)[0]
```

```
array([0.88422032, 0.92031869, 0.92031869, 0.95789078, 0.95961332,
       0.95961332, 0.99716727, 0.99716727, 0.99878962, 0.99878962,
       1.03787671, 1.03787671, 1.0414347 , 1.08219069, 1.08219069,
       1.12454163])
```

On the process, we also worked with the implementation of tensorflow-probability that follow the equation of the paper, and we have consistent results:

```python
from tensorflow_probability import math

kernel_tfp = math.psd_kernels.ExpSinSquared(
   period=periodicity, length_scale=length_scale
)
K_tfp = kernel_tfp.matrix(X, X)
np.linalg.eigh(K_tfp.numpy())[0]
``` 

```
array([0.8842203 , 0.92031866, 0.92031866, 0.95789075, 0.9596133 ,
       0.9596133 , 0.9971673 , 0.9971673 , 0.9987896 , 0.9987896 ,
       1.0378767 , 1.0378767 , 1.0414346 , 1.0821906 , 1.0821906 ,
       1.1245416 ], dtype=float32)
```

## System information

**Please complete the following information:**
- GPyTorch version: `1.4.1`
- PyTorch version: `1.8.1+cpu`
- Linux 5.8.0-50-generic #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tawe141** [comment]
Good catch! I made PR #1593 to fix this already. Could you look it over and make sure it matches what you'd expect? It's somewhat different from Mackay's kernel to ensure backwards compatibility, but maybe it's worth changing it to match exactly how it's written by Mackay to match other libraries like tf-probability or sklearn. @gpleiss any thoughts?
