### ISSUE TITLE
[Feature Request] Review skorch integration

### ISSUE THREAD

**Issue by BenjaminBossan** [cornellius-gp/gpytorch#1654]
# 🚀 Feature Request

This is less a feature request and more an RFC: I implemented a [skorch integration](https://github.com/skorch-dev/skorch/pull/782) for GPyTorch and would like to hear your opinions on it.

## Motivation

skorch is a higher level framework for PyTorch that provides an sklearn interface. By integrating with GPyTorch, the user could focus on implementing the kernel function etc. while leaving the "tedious" work like training loop, callbacks etc. to skorch. This might help to lower the entry barrier to GPs.

Might solve #279

## Request for help

If you have time, I would be really happy if you could take a look at the [skorch PR](https://github.com/skorch-dev/skorch/pull/782) or at least at the examples in the [notebook](https://github.com/skorch-dev/skorch/blob/feature/gaussian-processes-via-gpytorch/notebooks/Gaussian_Processes.ipynb) and tell me if there are any egregious errors. I only started looking into GPs recently and can't say I understood everything. Therefore, the help of a GP and GPyTorch expert would be highly welcome.

If there is no time for that, it would still help a lot if you could clarify these questions that I have:

1. Do the gyptorch criteria always takes likelihood and module as input arguments?
2. Do gpytorch losses always need to be maximized, i.e. we should minimize the negative objective function?
3. Does sampling work even if we use batching (i.e. for non-exact solutions)?
4. I could never get multiclass classification to provide reasonable results? Is there a self-contained example to replicate?

**Comment by jacobrgardner** [comment]
@BenjaminBossan This looks awesome! I'd be happy to take a closer look at the PR and can give some feedback there. In the meantime:

1. More or less? Approximate MLLs (e.g. used for variational inference) additionally have an argument for how much total training data there is. The reason for this involves the need to multiply the expected log likelihood by `N/B` (N is the number of total data points, B is the minibatch size) to get an unbiased estimate.
2. Yeah I'd imagine that will always be true. It's certainly true so far. We're either maximizing the marginal log likelihood or maximizing the ELBO (and therefore minimizing the negative objective function).
3. Kind of. Out of the box, you'll get perfectly fine samples for a batch, but getting a sample for a large set of data isn't as simple as looping over batches sampling from each independently. Doing that basically assumes independence between samples that are in different batches. Recent work (like, 2020) has some ways to get around this that we haven't implemented yet. In other words, sampling works as long as you pass the points you want samples at through the approximate model all in one go currently.
4. We can put together an example of this.

**Comment by BenjaminBossan** [comment]
> I'd be happy to take a closer look at the PR and can give some feedback there.

That would be awesome. I think the [notebook](https://github.com/skorch-dev/skorch/blob/feature/gaussian-processes-via-gpytorch/notebooks/Gaussian_Processes.ipynb) would be a good start. As I said, I'm not a GP expert, so please also feel free to correct any wrong statements that I make there, as I would expect this notebook to be the entry point for many curious users.

>     1. Approximate MLLs (e.g. used for variational inference) additionally have an argument for how much total training data there is

That is fine, since skorch always allows to pass additional parameters. But I hard-coded `likelihood` and `model` as criterion parameters (using keyword args, not positional) and wanted to ensure that there were not (plans for) any criteria that don't take those as arguments.

>     2. Yeah I'd imagine that will always be true. It's certainly true so far.

Great, then I'll leave the hard-coded minus in.

>     3. sampling works as long as you pass the points you want samples at through the approximate model all in one go currently.

Okay, got it.

>     4. We can put together an example of this.

That would be great. I did include an estimator for multiclass classification, but since it never learned (always produced `nan`s), I commented the code out for now.

**Comment by BenjaminBossan** [comment]
Hey, did you have time to look at the PR yet? Don't hesitate to ask me any question if something is unclear. Also, if there are any cool GPyTorch features that you think we should support, please tell me.

Btw., I had to exclude PyTorch v1.7.1, but 1.5.1 and 1.6.0 worked.

**Comment by BenjaminBossan** [comment]
@jacobrgardner Hey, I really don't want to pester you, but just in case you forgot, here is a reminder :)

We would like to make a skorch release soon and would probably merge that PR beforehand. It would be an experimental feature with possible breaking changes in the future, thus we can still fix grave mistakes later. But it would still be nice to have one of the experts make sure there aren't any egregious errors, especially since I can imagine that this feature could be attractive to users with little to no experience with GPs.

**Comment by jacobrgardner** [comment]
@BenjaminBossan Yeah, totally fair — let me set aside an hour to look at this tomorrow on my calendar to make sure I get to it.
