### ISSUE TITLE
[Docs]What exactly is num_inducing_points in _VariationalDistribution?

### ISSUE THREAD

**Issue by czkg** [cornellius-gp/gpytorch#1665]
In most of your examples such as "Variational GPs w/ Multiple Outputs", you have

`inducing_points = torch.rand(num_latents, 16, 1)`
`variational_distribution = gpytorch.variational.CholeskyVariationalDistribution(
            inducing_points.size(-2), batch_shape=torch.Size([num_latents])
)`

The num_inducing_points == 16, which is the number of inducing points.

However, inside the source code 'lmc_variational_strategy.py', you give another example

`inducing_points = torch.randn(32, 2)`
`variational_distribution = gpytorch.variational.MeanFieldVariationalDistribution(
             inducing_points.size(-1), batch_shape=torch.Size([3]),
)`

The num_inducing_points == 2, which is the event shape. I am totally missed, could you please explain what's the difference?

**Comment by gpleiss** [comment]
That is a typo. It should be `inducing_points.size(-2)` in both cases.

**Comment by czkg** [comment]
> That is a typo. It should be `inducing_points.size(-2)` in both cases.

Thanks!
