### ISSUE TITLE
[Docs] FixedNoiseGaussianLikelihood plus missing data?

### ISSUE THREAD

**Issue by jhennawi** [cornellius-gp/gpytorch#1676]
Dear Gpytorch Developers, 

Thanks for the great software. I'm trying to follow the GPLVM example here: 

https://docs.gpytorch.ai/en/stable/examples/045_GPLVM/Gaussian_Process_Latent_Variable_Models_with_Stochastic_Variational_Inference.html

but would like to adapt to: 

1) Fixed Gaussian noise, i.e. I have a heterskedastic error matrix var_Y which is the variance of Y, 
2) The possibility of missing data in Y, which is to say I would like to set some of values of Y to nans, or equivalently
the values in var_Y to a very large number. 

I'm trying to do this with SGD as in the example linked above, but cannot figure out the calling sequence, i.e. how do I instantiate the likelihood, and pass in the noise for each batch in the SGD loop. 

Many Thanks!

**Comment by gpleiss** [comment]
Hi @jhennawi - can you?
1. Open up a [discussion topic](https://github.com/cornellius-gp/gpytorch/discussions) instead of an issue?
2. Include a code example of what you've tried so far?
