### ISSUE TITLE
Require grad on non-floating point tensors breaks on pytorch master

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#169]
On current pytorch master, gpytorch master breaks b/c of requiring grad from non-floating point tensors, e.g. here: https://github.com/cornellius-gp/gpytorch/blame/9902384d6543c14fa8bf29c3981631aef02da6ad/test/lazy/test_interpolated_lazy_variable.py#L98

Test failure in e.g. in test_inv_matmul (test.lazy.test_interpolated_lazy_variable.TestInterpolatedLazyVariable)

```
RuntimeError: Only Tensors of floating point dtype can require gradients
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/pytorch/gpytorch/test_gpytorch#binary,link-tree/test/lazy/test_interpolated_lazy_variable.py", line 98, in test_inv_matmul
    left_interp_indices = Variable(torch.LongTensor([[2, 3], [3, 4], [4, 5]]), requires_grad=True)
```

**Comment by jacobrgardner** [comment]
I'll set up a conda environment with pytorch master and debug this and the other issue. 

At a glance, that just shouldn't be `required_grad=True` I think -- we only need gradients with respect to the interpolation values.

**Comment by Balandat** [comment]
Yeah that was my thinking - I mean what does the gradient w.r.t. the index mean? Probably don't even have continuity much less differentiability....
