### ISSUE TITLE
Trying to sample from the LKJCovariancePrior

### ISSUE THREAD

**Issue by vr308** [cornellius-gp/gpytorch#1690]
Trying to declare and LKJ prior and sample from it however it doesn't like the event_shape of the sd_prior:

```
import torch
from gpytorch.priors import LKJCovariancePrior, GammaPrior

sd_prior = GammaPrior(torch.tensor([1.0]),torch.tensor([1.0]), validate_args=True)
cov_prior = LKJCovariancePrior(n=10, eta=1, sd_prior=sd_prior)
```
```
Traceback (most recent call last):

  File "<ipython-input-40-1ca20a6657f1>", line 5, in <module>
    cov_prior = LKJCovariancePrior(n=10, eta=1, sd_prior=sd_prior)

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/gpytorch/priors/lkj_prior.py", line 111, in __init__
    raise ValueError("sd_prior must have event_shape 1 or n")

ValueError: sd_prior must have event_shape 1 or n

```
event_shape is not a settable attribute and by default it is empty torch.Size([]) for a prior over scalar - is this a bug?

Thanks.

**Comment by wjmaddox** [comment]
Hi, I was dealing with this the other day, and don't think it's actually a bug in gpytorch but rather a bug in `torch.distributions.ExponentialFamily` (or some strange feature), as there's no way to set event shape in those distributions.

This works though
```python
sd_prior = GammaPrior(torch.tensor([1.0]),torch.tensor([1.0]), validate_args=True)
sd_prior._event_shape = torch.Size((1,))
cov_prior = LKJCovariancePrior(n=10, eta=torch.ones(1), sd_prior=sd_prior)
```

**Comment by vr308** [comment]
thanks, but, how do we get the sampling to work?

`cov_prior.sample()
`

throws a notImplemented error.

**Comment by gpleiss** [comment]
We need to write a `sample()` implementation for the LKJPrior. Open to a PR! ;)

**Comment by wjmaddox** [comment]
I can try to setup a PR soon, finally managed to track down some code for sampling from the LKJ priors: 

- Python (numpy): https://github.com/pymc-devs/pymc3/blob/7e464e59bcb0adb28df94f379b3e8d4af12bd4d1/pymc3/distributions/multivariate.py#L1107 
- R (this is much more readable): https://github.com/rmcelreath/rethinking/blob/2acf2fd7b01718cf66a8352c52d001886c7d3c4c/R/distributions.r#L214

**Comment by wjmaddox** [comment]
As a heads up, LKJ sampling is now in Pytorch core (https://pytorch.org/docs/1.8.1/distributions.html#lkjcholesky). Moving #1737 over to that sampling method.
