### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by mkishinev** [cornellius-gp/gpytorch#1693]
# 🐛 Bug

The Spectral Mixture kernel as used in the tutorial https://docs.gpytorch.ai/en/latest/examples/01_Exact_GPs/Spectral_Mixture_GP_Regression.html 
has non-deterministic behavior (i.e. run-to-run variations).

If the notebook runs twice from scratch (i.e. restart the kernel and run all) we see 
* first run:
  Iter 1/100 - Loss: 1.272
  ...
  Iter 100/100 - Loss: -2.424

* second run:
  Iter 1/100 - Loss: 1.274
  ...
  Iter 100/100 - Loss: -1.203

Similar on other examples with this kernel. The Matern kernel does not have run-to-run variations.

## Expected Behavior

Deterministic behavior (as an option) e.g. by propagating a fixed random seed as an input parameter to initialize functions that are responsible for the non-determinism.

## System information

**Please complete the following information:**
-  gpytorch version:  1.4.2
-  torch version:  1.9.0+cpu
-  Windows 10

**Comment by gpleiss** [comment]
This is expected behavior. Note that the example has the following line:

```Python
self.covar_module.initialize_from_data(train_x, train_y)
```

This initialization function is stochastic (similar to neural network initialization). Fix the seed if you want reproducible results.

**Comment by mkishinev** [comment]
Thanks Geoff!
—mike
