### ISSUE TITLE
[Question] How to get product of inverse kernel matrix and training targets? "K^(-1) y"

### ISSUE THREAD

**Issue by bensrabe** [cornellius-gp/gpytorch#1703]
Hello. (This is my first time on Github, so please excuse any improper actions.)

My question is how to simply get the matrix-vector product of the inverse kernel matrix K^(-1) and the training target values y: namely the vector K^(-1) y.

Since this is the crucial computational burden of GPs, this must be stored somewhere along the training/evaluation process when setting up a model (e.g. ExactGP with SKIP kernel approximation).

In the docs we always evaluate the posterior mean, m(x) = k(x,X) K^(-1) y, at test inputs x = test_x. Instead, I only need K^(-1) y.
(Here, X denotes the training points and K = K(X,X) the kernel matrix. k(x,X) is the cross-kernel for test value x.)

I'd very very much appreciate if someone could help me. I'm quite desperate. Thanks in advance!

**Comment by wjmaddox** [comment]
Indeed, this is stored in an object called the `prediction_strategy` that is only produced after a posterior is called.

For an exact GP this can be accessed from:
```python
# setup code from a basic gpytorch tutorial
import torch
import math
import gpytorch

# Training data is 100 points in [0,1] inclusive regularly spaced
train_x = torch.linspace(0, 1, 100)
# True function is sin(2*pi*x) with Gaussian noise
train_y = torch.sin(train_x * (2 * math.pi)) + torch.randn(train_x.size()) * math.sqrt(0.04)

# We will use the simplest form of GP model, exact inference
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

# initialize likelihood and model
likelihood = gpytorch.likelihoods.GaussianLikelihood()
model = ExactGPModel(train_x, train_y, likelihood)

# generate a posterior
test_x = torch.linspace(0, 2, 10)
model.eval()
model(test_x)

# the predictive cache is (K + \sigma^2 I)^{-1} y and is of shape 100
model.prediction_strategy.mean_cache.shape
```

**Comment by bensrabe** [comment]
Thank you so much for your response, Wesley. This is exactly what I was looking for!
