### ISSUE TITLE
Should SGPR use diagonal correction for posterior prediction?

### ISSUE THREAD

**Issue by AustinT** [cornellius-gp/gpytorch#1715]
The inducing point kernel has the following lines that correct the diagonal when performing posterior predictions, so that the variances are always equal to the true variances even if the covariances are approximate.

https://github.com/cornellius-gp/gpytorch/blob/3e9bdb203f59a5f16cb8a48c89232078ac8ee52d/gpytorch/kernels/inducing_point_kernel.py#L64-L66

I see the motivation for this and recognize that this correction was featured in section 2 of Titsias et al 2009. However, the following observations have made me doubt that it should be there:

- Neither GPy or gpflow use this in their SGPR implementation. By default, with the same kernel/same inducing points, the posterior means/variance of gpytorch and GPy/gpflow **do not match**, but if I remove this diagonal correction then the outputs **match exactly** (at least in some quick tests I did on random data with a linear kernel)
- Looking through the actual derivation by Titsias et al in section 3, it seems like the version of SGPR proposed in that paper doesn't actually use the diagonal correction (I could be wrong about this though)
- Empirically on my data the test RMSE is consistently slightly better (~10%) _without_ the diagonal correction with N >> M (**Edit**: this actually seems to depend on M, for small M performance is consistently better without the correction, but for large M it is sometimes better with the correction. There also seem to be more numerical errors when the correction is _not_ used. I know gpflow uses some tricks make their non-corrected SGPR more stable.)

I see that this was added in #257 without much discussion. Could you double check that this should actually be there? If it is, would you consider implementing an option to turn it off for people who want their model to be consistent with other GP libraries? I could open a PR for this as it seems like it would essentially just be adding a kwarg to the constructor.

**Comment by gpleiss** [comment]
Hmm seems reasonable that the diagonal correction should be an optional feature. We could add a new context manager `with gpytorch.settings.diagonal_correction(True)`. @AustinT would you be able to put up a PR for this feature? If not I can get to it sometime soon.

**Comment by jacobrgardner** [comment]
Closed via #1717
