### ISSUE TITLE
Implementing Gibbs Kernel

### ISSUE THREAD

**Issue by atharvahans1** [cornellius-gp/gpytorch#1716]
I was going through the available kernels in GpyTorch and couldn’t find the Gibbs covariance function given as:
![Screen Shot 2021-08-02 at 7 58 19 AM](https://user-images.githubusercontent.com/56398096/127859064-0fd0ad38-9f5c-4d11-aca5-6903c86885dd.png)
Would it be possible to have this kernel implemented in GPyTorch?

**Comment by gpleiss** [comment]
Yes - we would accept a PR for this kernel function. See [these docs](https://docs.gpytorch.ai/en/stable/examples/00_Basic_Usage/Implementing_a_custom_Kernel.html) about implementing a custom kernel.

**Comment by atharvahans1** [comment]
@gpleiss I have created the kernel function. Are there any tests to test my code?

**Comment by jacobrgardner** [comment]
@atharvahans1 We have a series of base kernel test cases that you can extend here: https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/test/base_kernel_test_case.py

If after implementing the two abstract methods your kernel passes those tests, it's an indication that most model types in GPyTorch will work with your kernel.

**Comment by iwishiwasaneagle** [comment]
> @atharvahans1 did you finish this ?

bump

**Comment by Jordy-VL** [comment]
bump²

**Comment by charliebudd** [comment]
This is a duplicate of https://github.com/cornellius-gp/gpytorch/issues/671

**Comment by gpleiss** [comment]
Closed because it is a duplicate.
