### ISSUE TITLE
Trace term

### ISSUE THREAD

**Issue by ZohrehAdabi** [cornellius-gp/gpytorch#1719]
Hi,
In the [[ SVGP ]](https://docs.gpytorch.ai/en/stable/examples/02_Scalable_Exact_GPs/SGPR_Regression_CUDA.html) documentation you have used Inducing point kernel. Like the paper "**Variational Learning of Inducing Variables in Sparse Gaussian Processes, 2009, Titsias**", I want to add trace term [1/sigma^2 Tr(K - Q)] to marginal likelihood. However, I do not know how to do this if this term has not been implemented yet. Specially I want to implement the Trace term effectively like other features in gpytorch. Could anyone help me? I really appreciate any help you can provide.

**Comment by wjmaddox** [comment]
That's implemented already [here](https://github.com/cornellius-gp/gpytorch/blob/3e9bdb203f59a5f16cb8a48c89232078ac8ee52d/gpytorch/kernels/inducing_point_kernel.py#L95).

**Comment by ZohrehAdabi** [comment]
> 
> 
> That's implemented already [here](https://github.com/cornellius-gp/gpytorch/blob/3e9bdb203f59a5f16cb8a48c89232078ac8ee52d/gpytorch/kernels/inducing_point_kernel.py#L95).

Oh yes, really an effective implementation. Thank you for your quick response.
