### ISSUE TITLE
Don't know how to simply set the prior mean in GP

### ISSUE THREAD

**Issue by SyngnathZ** [cornellius-gp/gpytorch#1723]
## My code

```python
class ExactGPModel(models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.mean_module.register_prior("mean_prior", gpytorch.priors.NormalPrior(1.0, 1), "constant")
        self.mean_module.train(False)
        RBF = gpytorch.kernels.RBFKernel()
        RBF.initialize(lengthscale=xyz_range * 0.04)
        self.covar_module = RBF

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return distr.MultivariateNormal(mean_x, covar_x)

     ......

    likelihood = gpytorch.likelihoods.GaussianLikelihood()
    model = ExactGPModel(train_X, train_y, likelihood)

    # Get into evaluation (predictive posterior) mode
    model.eval()
    likelihood.eval()

    test_X_torch = torch.Tensor(test_X)
    f_preds = model(test_X_torch)
    mu = f_preds.mean

    mu_num = mu.detach().numpy()
```

And the **model.mean_module.mean_prior.mean = tensor(1.)**
But I cannot get a reasonable output cause the prior mean is not taking effect.

```
mu_num: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0., 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0., 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0., 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. .......]
```
My training set train_X is a **3D coordinate** (x,y,z) , train_Y is 0 (which means it is on the object at that 3D coordinate), and when y=1 it means it is not on the object, so I need the a priori mean to be all 1 (Because all the points are not on the object at the beginning, and I will gradually put the 3D coordinates on the object to train this Gaussian process).

So when I put in some training set with y=0, mu_num should be **between 0 and 1**, and there should be a lot of 1, but it can't be all 0, which can only mean that the a priori mean value is not set successfully.

## Additional context
The procedure I want to implement is the same as the function shown below (setting the m), by setting the a priori mean value to achieve the function I described above.
```python
    def predict(self, X):
        if not self.is_fit:
            print("GPR Model not fit yet.")
            return

        X = np.asarray(X)
        Kff = self.kernel(self.train_X, self.train_X)  # (N, N)
        Kyy = self.kernel(X, X)  # (k, k)
        Kfy = self.kernel(self.train_X, X)  # (N, k)
        Kff_inv = np.linalg.inv(Kff + 1e-8 * np.eye(len(self.train_X)))  # (N, N)

        m = 1 # set the prior mean
        mu = m + Kfy.T.dot(Kff_inv).dot(self.train_y - m)
        cov = Kyy - Kfy.T.dot(Kff_inv).dot(Kfy)
        return mu, cov
```
So how should I modify my code to implement the above process? Thanks!

**Comment by wjmaddox** [comment]
It's not the cleanest approach but you can manually set the constant data as:

```python
model.mean_module.constant.data = torch.ones(1)
model.mean_module.constant
# returns 
# Parameter containing:
# tensor([1.], requires_grad=True)
```

**Comment by SyngnathZ** [comment]
> It's not the cleanest approach but you can manually set the constant data as:
> 
> ```python
> model.mean_module.constant.data = torch.ones(1)
> model.mean_module.constant
> # returns 
> # Parameter containing:
> # tensor([1.], requires_grad=True)
> ```

It worked, thanks a lot!
