### ISSUE TITLE
Why is `ScaleToBounds` scaling to an interval multiplied by 0.95?

### ISSUE THREAD

**Issue by andreimargeloiu** [cornellius-gp/gpytorch#1749]
### Discussed in https://github.com/cornellius-gp/gpytorch/discussions/1740

<div type='discussions-op-text'>

<sup>Originally posted by **andreimargeloiu** August 30, 2021</sup>
Looking at the [source code](https://docs.gpytorch.ai/en/stable/_modules/gpytorch/utils/grid.html#ScaleToBounds) for ScaleToBounds, I noticed that it scales to an interval multiplied by 0.95. For example `ScaleToBounds(1, 2)` will output numbers between 0.95 and 1.9. 

What's the rationale behind the decision to multiply by 0.95?</div>

**Comment by gpleiss** [comment]
Just catching up on this - is there an issue associated with this, or did #1740 resolve your questions?

**Comment by andreimargeloiu** [comment]
All working, I was just curious. Thank you for helping out!
