### ISSUE TITLE
Possible extra derivative calculations at test time

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#175]
See the discussion in #174. When calling backward to get the derivative of the mean function with respect to a test input, we enter the backward pass of `InvMatmul`. There doesn't seem to be an obvious reason we should be doing this, since none of the linear solves involved in the predictive __mean__ depend on the test point. 

This suggests we might also he computing derivatives with respect to model hyperparameters, which would be wasted computation.

@Balandat

**Comment by jacobrgardner** [comment]
This might be solvable with a few judicious detach calls if we are in eval mode?

**Comment by gpleiss** [comment]
I think the cache's should be detached. This would probably solve the issue.
