### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ianhill60** [cornellius-gp/gpytorch#1764]
# 🚀 Feature Request

I'd like to request batch-training support for the MultitaskGPModel to enable training large models with limited RAM. 

I attempted to integrate a DataLoader to train a MultitaskGPModel. Unfortunately, I received the RuntimeError: You must train on the training inputs! 

The model described in: https://towardsdatascience.com/batched-multi-dimensional-gaussian-process-regression-with-gpytorch-3a6425185109 accomplishes batching with a multitask GPR model, however it sacrifices inter-task correlations as each task corresponds to a separate GP. 

Please let me know if I missed an alternative avenue to accomplish batched multitask GPR modeling with CUDA support. 

Thanks, 

Ian

**Comment by gpleiss** [comment]
I believe this is a duplicate of #1763
