### ISSUE TITLE
PR for Custom Mean ?

### ISSUE THREAD

**Issue by irinaespejo** [cornellius-gp/gpytorch#1772]
Hi team :wave: 

I am using GPyTorch for a complex analysis involving experimental high energy physics data and I arrived to the conclusion I need a fairly simple class `class CustomMean(Mean)` that takes as input a vector and assigns it to the Mean of the GP before initialization.

Here I explain what we want to do in detail and you may have better suggestions:
- We have a "cheap" to evaluate function called "truth-level" and en expensive function called "reco-level". Both are black boxes but for now I use toy data. They are similar functions but not the same, just highly correlated.
Because it is easy to evaluate the cheap function, we have "plenty" of data. Like in the plot below :arrow_down: 
![output](https://user-images.githubusercontent.com/13988100/135526273-acf74764-3411-4397-becc-19ebd961664e.png)

- But, our goal is to estimate properties of the expensive (reco-level) function! We use the cheap (truth-level) function to do a warm start. This way we get a sense of the shape of the expensive value before performing Active Learning and we have to run the expensive black box. See the plot below :arrow_down: 

![output2](https://user-images.githubusercontent.com/13988100/135552841-4927b8ed-8ee6-4e40-b6bb-e35befcd5247.png)

Therefore we would need a Custom Mean function. Would you be interested in a PR? Any advice? It is a problem that a priori looks like a Multifidelity problem but _not quite_ since we have two different functions and not different fidelity observations for the same function.

Thank you so much for your work, it's an excellent package I use on a daily basis! :star:

**Comment by jacobrgardner** [comment]
> It is a problem that a priori looks like a Multifidelity problem but not quite since we have two different functions and not different fidelity observations for the same function.

To me, it still looks like a pretty good candidate for some of the same tools people use for multifidelity modelling. In the multifidelity setting, different fidelity levels are allowed to have _bias_ compared to the true function of interest, not simply additional _variance_, and it seems like the bias is what's going on here. 

I also think giving something just like a [multitask GP](https://github.com/cornellius-gp/gpytorch/blob/master/examples/03_Multitask_Exact_GPs/Hadamard_Multitask_GP_Regression.ipynb) could be worth a shot -- it's basically exactly designed to model multiple functions that are just assumed to be very correlated. The Hadamard multitask model I linked to in particular doesn't require that you observe every all functions at all inputs. As a result, it can support more observations of the cheap function than of the expensive function.

**Comment by jacobrgardner** [comment]
Sorry, to also actually answer your original question -- I'm not 100% sure what exactly you want to submit a PR for. In principle, an `ExactGP` (or an `ApproximateGP`) can return really whatever you want as a mean for x in `forward`:

```python
    def forward(self, x):
        n = x.size(-2)
        mean_x = literally_any_vector_of_size_n
        ...
```
Part of the reason we only support a very small set of means out of the box in GPyTorch currently is because (1) prior means tend to be more problem dependent, and (2) prior means are a lot less restricted than kernels are, they can pretty much be anything, where as kernels always have to return positive definite matrices.

**Comment by Balandat** [comment]
I agree, a multitask model would be the first thing I'd try here.

**Comment by irinaespejo** [comment]
Thanks for the quick answer and advice!
