### ISSUE TITLE
[Bug]In the tutorials of SVDKL, an error occurred when I run 'from densenet import DenseNet'

### ISSUE THREAD

**Issue by wyxwyx46941930** [cornellius-gp/gpytorch#1780]
In the tutorials of SVDKL, an error A occurred when I run "from densenet import DenseNet". The information of error A is "No module names densenet". When I tried to use "pip install densenet" to deal with this question, another error B occurred. The information of error B is "Could not find a version that satisfies the requirement tensorflow==2.0.0-alpha0 (from densenet) (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0)ERROR: No matching distribution found for tensorflow==2.0.0-alpha0 (from densenet)
". But I have installed tensorflow==2.4.0 and the densenet in this tutorial should be in pytorch format.

**Comment by gpleiss** [comment]
`from densenet import DenseNet` is a relative import to open this file: https://github.com/cornellius-gp/gpytorch/blob/master/examples/06_PyTorch_NN_Integration_DKL/densenet.py.

You should run that example tutorial from the examples/06_PyTorch_NN_Integration_DKL/ folder, or update your `PYTHONPATH` environment variable to include that folder.

**Comment by wyxwyx46941930** [comment]
> `from densenet import DenseNet` is a relative import to open this file: https://github.com/cornellius-gp/gpytorch/blob/master/examples/06_PyTorch_NN_Integration_DKL/densenet.py.
> 
> You should run that example tutorial from the examples/06_PyTorch_NN_Integration_DKL/ folder, or update your `PYTHONPATH` environment variable to include that folder.

Thank you. I know.
