### ISSUE TITLE
Load trained ExactGP

### ISSUE THREAD

**Issue by tomcattiger1230** [cornellius-gp/gpytorch#1787]
# 🐛 Bug

Hi, I would like to know how to load the trained ExactGP model without loading train_x and train_y. 

I save the trained model as a '.pth' file. Then I would like to use another script to load the trained model. I've tried to load directly only the pth file and let train_x and train_y as None. However, the results are not identical with/without train_x and train_y. Is there any possible way to load the pretrained model without train_x/y? Thanks

I've checked the state_dict, for both approaches the output of state_dict are same

The following code shows how I check the predicted results.

model1 = ExactGPModel(None, None, likelihood)
model1.load_state_dict(model_dict)

model2 = ExactGPModel(train_x, train_y, likelihood)
model2.load_state_dict(model_dict)

model3 = ExactGPModel(None, None, likelihood)
model3.set_train_data(train_x, train_y, strict=False)
model3.load_state_dict(model_dict)

with torch.no_grad(), gpytorch.settings.fast_pred_var():
    x_ = torch.from_numpy(np.array([0.3, 0.1])).float().to(device)
    result1 = model1(x_.view(1, -1))
    result2 = model2(x_.view(1, -1))
    result3 = model3(x_.view(1, -1))

result1  --> tensor([0.0631])
result2 --> tensor([0.1254])
result3 --> tensor([0.1254])

**Comment by irinaespejo** [comment]
Hello,

I would be interested in caching the posterior with our having to load heavy training data. 
This wasn't possible when the issue was closed. Is by any chance possible now or relatively easy to hack?

Thank you! :)

**Comment by gpleiss** [comment]
At the moment, there's not a good way to do this/hack this in the dataset :/

**Comment by pengzhi1998** [comment]
@gpleiss Hi Prof. Pleiss, sorry to bother you. I found a problem that the loaded model has a worse testing performance than the evaluations during training. [Here](https://github.com/cornellius-gp/gpytorch/issues/2394#issue-1843964648) is the link to the detailed issue. May I have your help on that? Thank you so much for your precious time!
