### ISSUE TITLE
[Bug] Segfault on Spectral mixture GP regression test (MacOS)

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#1810]
# 🐛 Bug

Running the `test/examples/test_spectral_mixture_gp_regression.py` reliably produces a segfault on my Mac, even when installing into a virgin conda env. This happens on master but also on commits a few months old (I haven't run tests locally in a while though, so not sure when this broke).

I don't see this issue on Linux. 

## To reproduce

** Code snippet to reproduce **
```python
conda create -n gptt python=3.8
conda activate gptt
conda install -c pytorch pytorch
conda install scipy scikit-learn

cd gpytorch
pip install -e .

(gptt) balandat@balandat-mbp gpytorch % pytest test/examples/test_spectral_mixture_gp_regression.py
==================================================================================================================== test session starts =====================================================================================================================
platform darwin -- Python 3.8.12, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/balandat/Code/gpytorch
collected 2 items

test/examples/test_spectral_mixture_gp_regression.py Fatal Python error: Segmentation fault

Thread 0x000000011e4aee00 (most recent call first):
  File "/Usezsh: segmentation fault  pytest test/examples/test_spectral_mixture_gp_regression.py

```

Here is the conda env:
```
# packages in environment at /Users/balandat/miniconda3/envs/gptt:
#
# Name                    Version                   Build  Channel
attrs                     21.2.0             pyhd3eb1b0_0
blas                      1.0                         mkl
ca-certificates           2021.10.26           hecd8cb5_2
certifi                   2021.10.8        py38hecd8cb5_0
gpytorch                  1.5.1                     dev_0    <develop>
iniconfig                 1.1.1              pyhd3eb1b0_0
intel-openmp              2021.4.0          hecd8cb5_3538
joblib                    1.1.0              pyhd3eb1b0_0
libcxx                    12.0.0               h2f01273_0
libffi                    3.3                  hb1e8313_2
libgfortran               3.0.1                h93005f0_2
libuv                     1.40.0               haf1e3a3_0
llvm-openmp               12.0.0               h0dcd299_1
mkl                       2021.4.0           hecd8cb5_637
mkl-service               2.4.0            py38h9ed2024_0
mkl_fft                   1.3.1            py38h4ab4a9b_0
mkl_random                1.2.2            py38hb2f4e1b_0
more-itertools            8.10.0             pyhd3eb1b0_0
ncurses                   6.3                  hca72f7f_1
numpy                     1.21.2           py38h4b4dc7a_0
numpy-base                1.21.2           py38he0bd621_0
openssl                   1.1.1l               h9ed2024_0
packaging                 21.0               pyhd3eb1b0_0
pip                       21.2.4           py38hecd8cb5_0
pluggy                    0.13.1           py38hecd8cb5_0
py                        1.10.0             pyhd3eb1b0_0
pyparsing                 3.0.4              pyhd3eb1b0_0
pytest                    6.2.4            py38hecd8cb5_2
python                    3.8.12               h88f2d9e_0
pytorch                   1.10.0                  py3.8_0    pytorch
readline                  8.1                  h9ed2024_0
scikit-learn              1.0.1            py38hae1ba45_0
scipy                     1.7.1            py38h88652d9_2
setuptools                58.0.4           py38hecd8cb5_0
six                       1.16.0             pyhd3eb1b0_0
sqlite                    3.36.0               hce871da_0
threadpoolctl             2.2.0              pyh0d69192_0
tk                        8.6.11               h7bc2e8c_0
toml                      0.10.2             pyhd3eb1b0_0
typing_extensions         3.10.0.2           pyh06a4308_0
wheel                     0.37.0             pyhd3eb1b0_1
xz                        5.2.5                h1de35cc_0
zlib                      1.2.11               h1de35cc_3
```

## System information

**Please complete the following information:**
- master
- 1.10
- MacOS 11.6.1

**Comment by Balandat** [comment]
@wjmaddox suggested this could be related to https://github.com/scikit-learn/scikit-learn/issues/21302.

**Comment by gpleiss** [comment]
I can confirm this issue (which only happens with scikit-learn >= 1.0). Maybe we should lock the dependency on scikit-learn to 0.24?

**Comment by wjmaddox** [comment]
It looks from that issue (but haven't confirmed yet), that importing scikit-learn after torch causes the issue. So, one easy fix may be to just import the GaussianMixture model before torch in the file.

**Comment by gpleiss** [comment]
I tried switching the order of the imports in the spectral mixture file, and this doesn't seem to help. I also tried importing it at the top of the gpytorch/__init__.py file and this doesn't seem to help.

**Comment by Balandat** [comment]
It also seems a bit brittle to rely on the import order to avoid segfaults, esp since we use I sort… Probably fine to pin scikit-learn for now.

**Comment by wjmaddox** [comment]
Yeah, let's just remember to visit this 3-6 months down the road and check scikit-learn again since the fix seems to be in their nightly.

**Comment by Balandat** [comment]
Hmm I still get that segfault even after downgrading to scikit-learn 0.24.2.

**Comment by Balandat** [comment]
I did some more digging, this is really weird. The segfault happens in this line: https://github.com/cornellius-gp/gpytorch/blob/master/test/examples/test_spectral_mixture_gp_regression.py#L69, and we can trace it down to this: https://github.com/cornellius-gp/gpytorch/blob/master/test/examples/test_spectral_mixture_gp_regression.py#L51 (i.e. it only happens when `emspec=False`). 

Now the weird thing is that this fails when calling https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/kernels/spectral_mixture_kernel.py#L218, regardless what this functions implements (I replaced this with a simple `pass` after commenting out the logic)? This makes me wonder whether this is actually a python issue.

In all of this sklearn doesn't seem to be involved (even imported) at all, so that's probably a red herring.

**Comment by pipme** [comment]
I also encountered segmentation fault on Mac M1 (rosetta) when reaching here https://github.com/cornellius-gp/gpytorch/blob/ade5db8df1f8e4acbc64ec1dd8809e58506827f1/gpytorch/kernels/spectral_mixture_kernel.py#L205-L207 but it was fixed after pip reinstalling scikit-learn. My current version is `scikit-learn==1.0.1`.

**Comment by eringrant** [comment]
I also get a segfault on MacOS during `import gpytorch`. Neither `scikit-learn>=1.0.1` `scikit-learn<=0.24` me. Here is a minimal conda environment that gives me the issue: 

```
channels:
  - default
  - conda-forge

dependencies:
  - python>=3.10
  - numpy>=1.22.3
  - scipy>=1.8.0
  - pip>=22.0.4
  - pip:
    - gpytorch>=1.6.0
```

What's strange is that `python -q -X faulthandler -c "import gpytorch"` gives me a different line for the occurrence of the segfault on each run.

Was there ever a cause determined for this? Thanks!

**Comment by Balandat** [comment]
No, as of now this is still a mystery to me.

**Comment by Balandat** [comment]
Actually, just played around with this some more, looks like installing a new scikit-learn version (1.1.1 in my case) via `pip install -U scikit-learn` resolved the issue for me.

**Comment by flying-sheep** [comment]
> What's strange is that `python -q -X faulthandler -c "import gpytorch"` gives me a different line for the occurrence of the segfault on each run.

Not strange at all, segfaults are undefined behavior, so anything could happen. In practice, they’ll result in an invalid read/write somewhere down the line which is catchable by the OS (the segfault you see) but there’s no guarantee that or when or where that happens.
