### ISSUE TITLE
`LazyEvaluatedKernelTensor.add_jitter` evaluates the kernel

### ISSUE THREAD

**Issue by pierocor** [cornellius-gp/gpytorch#1826]
The `add_jitter` method of the `LazyEvaluatedKernelTensor` class explicitly evaluates the kernel: https://github.com/cornellius-gp/gpytorch/blob/c58dc3a77c7be7ee4434484e359a0bbc1c2d27f6/gpytorch/lazy/lazy_evaluated_kernel_tensor.py#L237

Is there a particular reason for doing so? Adding the jitter in a lazy way as implemented by the parent class `LazyTensor` ([here](https://github.com/cornellius-gp/gpytorch/blob/c58dc3a77c7be7ee4434484e359a0bbc1c2d27f6/gpytorch/lazy/lazy_tensor.py#L730)) would drastically decrease the memory consumption.

**Comment by gpleiss** [comment]
Hmm good question. I'll investigate later this week.
