### ISSUE TITLE
[Type of train_inputs vs train_targets] in e.g. ExactGP

### ISSUE THREAD

**Issue by mhqo** [cornellius-gp/gpytorch#1830]
According to the docstring and documentation (https://docs.gpytorch.ai/en/stable/_modules/gpytorch/models/exact_gp.html#ExactGP)

The attribute train_inputs of ExactGP is supposed to be a ```torch.Tensor train_inputs: (size n x d)```, at least this is what is passed. Yet, it is actually saved as a tuple:
```
...
    def __init__(self, train_inputs, train_targets, likelihood):
        if train_inputs is not None and torch.is_tensor(train_inputs):
            train_inputs = (train_inputs,)
...
```
Is there a reason for this? I find the behaviour quite unintuitive since model.train_targets is actually a torch.Tensor, while model.train_inputs  requires a [0].

**Comment by gpleiss** [comment]
> Is there a reason for this? I find the behaviour quite unintuitive since model.train_targets is actually a torch.Tensor, while model.train_inputs requires a [0]

Yes. For multitask models, you have two `train_input` tensors: one for the set of features (`X \in \reals^{N x D}`), and one for the set of task indices (`I \in Z^N`).
