### ISSUE TITLE
Reference for IndexKernel

### ISSUE THREAD

**Issue by mvsoom** [cornellius-gp/gpytorch#1833]
Could I get a reference for `gpytorch.kernels.IndexKernel`? I didn't find anywhere. Thanks.

**Comment by wjmaddox** [comment]
I don't think there's a real reference to it but the sorts of low rank plus diagonal parameterizations have been used a lot in the literature. For example, see Section 3.1 of [Bonilla et al, '09](https://papers.nips.cc/paper/2007/file/66368270ffd51418ec58bd793f2d9b1b-Paper.pdf) where they use low rank plus constant diagonal (their PPCA style parameterizations) and low rank plus diagonal ("pivoted cholesky" style parameterizations).

**Comment by gpleiss** [comment]
In general, `gpytorch.kernels.IndexKernel` is a kernel that acts on a finite-dimensional input space (e.g. the task indices {1, ..., num_tasks}). The space of valid kernels on this finite-dimensional input space is the set of all `num_tasks x num_tasks` positive semidefinite matrices.

**Comment by mvsoom** [comment]
OK, thank you!
