### ISSUE TITLE
[Question] Impact of x scale on results

### ISSUE THREAD

**Issue by LMolr** [cornellius-gp/gpytorch#1841]
Hello, I am trying to fit some observations with the simplest model from the tutorials:

```python
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

# Training data (omitted for brevity).
#train_y = ...
#train_x = ...

likelihood = gpytorch.likelihoods.GaussianLikelihood()
model = ExactGPModel(train_x, train_y, likelihood)

# Training code (omitted for brevity).
# Optimizer: Adam, lr=0.1
# Loss: ExactMarginalLogLikelihood
```

After training, I am evaluating the model by feeding a linspace with 100 points with this pattern:

```python
with torch.no_grad(), gpytorch.settings.fast_pred_var():
    test_x = torch.linspace(0, train_x[-1], 100, dtype=torch.double)
    observed_pred = likelihood(model(test_x))
```

However, **I am experiencing very different results depending on how I choose to scale the _x_ dimension**.

### X in [0..1]

![fig](https://user-images.githubusercontent.com/428521/143897698-8460f32a-4efb-45b4-9f5c-f05316e70ebe.png)

### X in [0..100]

![fig](https://user-images.githubusercontent.com/428521/143897973-11b7f9e7-92eb-4504-ae03-bf0b4a402888.png)

### X in [0..1000]

![fig](https://user-images.githubusercontent.com/428521/143898197-ffcb67aa-9481-4450-8ca2-62c7696a29cd.png)

I am confused: I did expect a result invariant w.r.t. the scale chosen for X dimension.
Is this behaviour consistent with the theory of Gaussian Processes?

Thanks in advance for any help!

**Comment by wjmaddox** [comment]
Yeah, this is due to numerical instability and the initial value of the kernel hyperparameters, which basically assume x in [0., 1.] (or at least x \sim N(0., 1.)). 

In general, you probably want your x to be on the [0., 1.] range for best results. But, you could alternatively set your initial lengthscale to be ten times (ish) larger on initialization via `kernel.base_kernel.lengthscale = 10.` (for example).

**Comment by LMolr** [comment]
Hello Wesley, thanks for the answer.
If I indeed set an appropriate initial lengthscale, I get a convergence.

I've also noticed that the mean line of the fitted model does not pass exactly through the points from the training set. Is there a way to set an hard constraint over the model to achieve that? I'd need a model with perfect fit on the observed data.

Thank you again.

**Comment by wjmaddox** [comment]
To try to induce the model to more closely fit the data, one suggestion would be to set the likelihood noise to be small on initialization (or even to fix it). For example, `model.likelihood.noise = 1e-3 * torch.ones(1)`

**Comment by Balandat** [comment]
@LMolr are you observations indeed noiseless? As Wesley said you can crank down the likelihood noise `sigma` and not estimate it as part of the fitting. In the limit `sigma -> 0` you will get the model mean pass through the observations, but a zero value may lead to numerical issues b/c of ill conditioned linear solves.

**Comment by LMolr** [comment]
Yes, my observations are exact values.

To contextualize, I am training a Machine Learning model for time-series forecasting, where the training output time-series is sampled at very sparse intervals.
To overcome this, I am experimenting with the idea using a Gaussian Process as an alternative to raw interpolation.

The idea is to use the sigma information from the fitted GP model as a measure of the prediction error of the Time Series model.
This is why I need a very low sigma for the direct observed points.

Anyways, I'll try to experiment with adjustments of the likelihood noise.. thank you again!
