### ISSUE TITLE
ModuleNotFoundError: No module named 'gpytorch.priors'

### ISSUE THREAD

**Issue by polarlightman** [cornellius-gp/gpytorch#185]
Hi, I am new here. I notice there are some changes yesterday of your example files. And I follow the new file of 'simple gp regression' , but I got an error:'**ModuleNotFoundError: No module named 'gpytorch.priors**'' when I do '**from gpytorch.priors import SmoothedBoxPrior**'. I even reinstall the gpytorch but still get the same error. 
(Sorry if I asked a stupid question, it's my first time to use pytorch and even github)

**Comment by jacobrgardner** [comment]
Hi!

The most likely explanation seems to me that you pulled the repo and examples after installing GPyTorch. Yesterday's patch involved some fairly large changes. Try reinstalling.

**Comment by jacobrgardner** [comment]
Actually, also try pulling again before you reinstall. I just added the priors import to the init file. The unit tests and examples work for me without this, but maybe there's an issue in some older versions of python?

**Comment by polarlightman** [comment]
@jacobrgardner Thank you:) . I reinstall gpytorch and it works now!
