### ISSUE TITLE
[Bug] remove your test folder from pkg

### ISSUE THREAD

**Issue by ngam** [cornellius-gp/gpytorch#1854]
# 🐛 Bug

## To reproduce

see this issue for reference: https://github.com/conda-forge/botorch-feedstock/issues/9

** Code snippet to reproduce **
```
conda install botorch gpytorch
```

** Stack trace/error message **
```
// Paste the bad output here!
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/noarch::gpytorch-1.5.1-pyhd8ed1ab_0, conda-forge/noarch::botorch-0.2.2-py_0
  path: 'lib/python3.9/site-packages/test/optim/__pycache__/__init__.cpython-39.pyc'

```

## System information

**Please complete the following information:**
- 
- 
- 
- 

## Additional context

You can add `recursive-exclude test *` or something to your `MANIFEST.in`. As a workaround, we have simply force-deleted the tests folder on the conda-forge's botorch side for now, pending a fix from you.

xref: https://github.com/pytorch/botorch/issues/1019

**Comment by jacobrgardner** [comment]
Fixed by #1855
