### ISSUE TITLE
Why is the default likelihood noise initialized to 0.6932?

### ISSUE THREAD

**Issue by Akella17** [cornellius-gp/gpytorch#1875]
Why is the default likelihood noise ln(2) = 0.6932? Is there any reason why this value is preferred?

**Comment by wjmaddox** [comment]
I believe it's actually because of this initialization:

```python
torch.nn.functional.softplus(torch.zeros(1)) #0.693
```

which is a sensible-ish default (probably the noise should be between zero and one).

**Comment by Akella17** [comment]
Makes sense. Thanks for the answer :)
