### ISSUE TITLE
[Question] How reverse engineering RBF-Kernel

### ISSUE THREAD

**Issue by makinzm** [cornellius-gp/gpytorch#1890]
# 📚 Question

I would like to create odd RBF-kernel which of "x-y" is converted into "x+y".
However, I don't have confidence my code works.
Therefore, if you teach me, I would appreciate it.

```python
# ReverseRBF kernel (start)
from gpytorch.functions import RBFCovariance
from gpytorch.kernels import Kernel
from gpytorch.settings import trace_mode


def postprocess_rbf(dist_mat):
    return dist_mat.div_(-2).exp_()

class ReverseRBFKernel(Kernel):
    has_lengthscale = True

    def forward(self, x1, x2, diag=False, **params):
        if (
            x1.requires_grad
            or x2.requires_grad
            or (self.ard_num_dims is not None and self.ard_num_dims > 1)
            or diag
            or trace_mode.on()
        ):
            x1_ = x1.div(self.lengthscale)
            x2_ = x2.div(self.lengthscale)
            return self.covar_dist(
                -1*x1_, x2_, square_dist=True, diag=diag, dist_postprocess_func=postprocess_rbf, postprocess=True, **params
            )
        return RBFCovariance().apply(
            -1*x1,
            x2,
            self.lengthscale,
            lambda x1, x2: self.covar_dist(
                x1, x2, square_dist=True, diag=False, dist_postprocess_func=postprocess_rbf, postprocess=False, **params
            ),
        )
        
# ReverseRBF kernel (end)
```
my-example is here : https://github.com/makinzm/UNDONE_local/blob/main/08_oputuna/gp-02.ipynb

**Comment by gpleiss** [comment]
I don't think that the resulting kernel would be positive definite.

Also, in the future, this type of inquiry makes for a better [discussion topic](https://github.com/cornellius-gp/gpytorch/discussions) rather than an issue :)

**Comment by makinzm** [comment]
Thank you for your answer.

However, I think this function is semi positive definite(if my calculations are not correct, please tell me).

![image](https://user-images.githubusercontent.com/40193664/150245261-f48d9dc9-b3f4-4098-8b05-ed356d4a89b6.jpeg)

And I'm sorry my question is about code is right or not.

Therefore, I would like to know it is work like behavior; odd rbf kernel.

And I will open new discussion.

Anyway, thank you !

**Comment by makinzm** [comment]
discussions here : https://github.com/cornellius-gp/gpytorch/discussions/1894

**Comment by makinzm** [comment]
The above calculation is wrong . That's because $- x_i x_j$ doesn't satisfy $\Sigma -c_i c_j x_i x_j \geq 0$
