### ISSUE TITLE
MultitaskGPModel won't scale with size of input

### ISSUE THREAD

**Issue by rajkumarkarthik** [cornellius-gp/gpytorch#191]
In the basic multi-task model example shown in https://nbviewer.jupyter.org/github/cornellius-gp/gpytorch/blob/master/examples/multitask_gp_regression.ipynb, the code doesn't scale to larger sizes of training data. Specifically, if you changed training data size in cell 2 of the notebook from 11 to 100, the code no longer works. It throws the following error:
RuntimeError: Function InvQuadLogDetLegacyBackward returned an invalid gradient at index 1 - expected shape [200, 9] but got [200, 5]

Can someone figure out what's going on? Or am I doing this wrong?

**Comment by jacobrgardner** [comment]
I'm looking in to this -- it has to do with the recent changes to lazily evaluating kernels. Easy enough to fix in the exact GP case (I'll push something soon), a little trickier in the sparse GP setting. Working on a fix now.
