### ISSUE TITLE
[Question] Is it possible to fit a GP with the constraint that the output is in [0,1]?

### ISSUE THREAD

**Issue by AndreaPi** [cornellius-gp/gpytorch#1912]
Hi,

I have a small dataset (_N_ ~ 2000) where the output _y_ ∈[0,1]. How can I make sure that the GP output stays in this range? Thanks!

**Comment by wjmaddox** [comment]
Assuming that the observations are continuous in this space, you can try a couple of options:
- transform your observations to $\mathbb{R}$ using an invertible transform (an inverse cdf transform like `torch.distributions.Normal(0., 1.).icdf(y)`) and regress on the transformed observations.
- use a Beta likelihood for the observations, e.g. `gpytorch.likelihoods.BetaLikelihood` but you'll need to use an approximate (variational) GP
- you might also be able to get away with just clamping / truncation of `y` but that is probably going to raise issues down the line.

**Comment by AndreaPi** [comment]
@wjmaddox thanks for the suggestions!

1. the transformation suggestion sounds cool. I actually have to regress on two output variables - one is y ∈[0,1] and the other is z ≥ 0. I think using a multioutput GP could be a good idea. How should I transform the observations for z? Is it enough to just do `w=torch.log(z)`?
2. I'm not against variational GPs! I know you guys did a great job with them, in GPyTorch. I don't see a tutorial on multioutput variational GPs, and this is my first time using GPyTorch (I still have to install it, actually 😅). Do you think it would be complicated for a beginner? Maybe better to go with solution 1?
3. 🤔  do you mean, I train a standard GP on my data as they are, and then I apply a clamping to the GP output during inference? That's doable, but I don't get to penalize the GP for constraint-violating predictions during training...seems suboptimal.

Also, this is related to this other issue https://github.com/cornellius-gp/gpytorch/issues/1913 so if you have time to have a look at it, I'd really appreciate it!

**Comment by AndreaPi** [comment]
Thanks! I'll close this issue for now, while I test these suggestions. If I'm not able to put them in practice, I'll open another issue, maybe.
