### ISSUE TITLE
[Docs] DirichletClassificationLikelihood with VariationalELBO

### ISSUE THREAD

**Issue by y0ast** [cornellius-gp/gpytorch#1938]
Hi GPyTorch team, thanks for the excellent library!

I've been scratching my head on combining variational learning with the `DirichletClassificationLikelihood`.

There is a tutorial in the exact case: https://docs.gpytorch.ai/en/stable/examples/01_Exact_GPs/GP_Regression_on_Classification_Labels.html but not in the variational case.

Concretely the problem is:

When creating the likelihood, you can pass all targets like this:
```
likelihood = DirichletClassificationLikelihood(targets=torch.tensor(train_dataset.targets))
```
Which will lead to `likelihood.transformed_targets` and `likelihood.noise` being a `(C, N)` matrix. However when training in minibatches, and passing a subset of `likelihood.transformed_targets` to an instantiation of `VariationalELBO` will lead to the noise shape not matching. 

Additionally, doing something like `train_dataset.targets = likelihood.targets` goes wrong because of the transpose (it wants `(N,C)`). Transposing back and forth is cumbersome (but possible!).

I've come up with something very hacky:
```
likelihood = DirichletClassificationLikelihood(
    targets=torch.tensor(train_dataset.targets),
    # learn_additional_noise=True,
)
train_dataset.targets = torch.cat(
    [likelihood.transformed_targets.t(), likelihood.noise.t()], dim=1
)

elbo_fn = VariationalELBO(likelihood, gp, num_data=len(train_dataset))

def loss_fn(x, y):
    return -elbo_fn(x, y[:, :10].t(), noise=y[:, 10:].t())
```

But this still leads to shape errors in the `expected_log_prob` in `_GaussianLikelihoodBase` that I don't see a way around.

I thought maybe there is something I am missing that would make all this much nicer. I don't see a theoretical reason why the `DirichletClassificationLikelihood` can't combined with variational learning.

I hope you can help!

**Comment by wjmaddox** [comment]
Ugh that is annoying -- can you double check that this also occurs in `FixedNoiseGaussianLikelihood` as well? It seems like it stems from there rather than from the Dirichlet setting.

I would suspect that you'd want to use the full transformed targets and to pass them instead of the `y` to ensure the noise + transformed_targets are getting passed in properly, but am not entirely sure.

**Comment by y0ast** [comment]
Thanks for your reply!

Yeah it's the same problem.

>  I would suspect that you'd want to use the full transformed targets and to pass them instead of the y to ensure the noise + transformed_targets are getting passed in properly, but am not entirely sure.

I can't do this because of memory issues, I need to do mini batches.

---

I found that the actual underlying cause is that I was trying to use `DirichletClassificationLikelihood` in the multi class (so multi task) setting.

`MultitaskGaussianLikelihood` works fine in my code but the `FixedNoise` equivalent doesn't seem implemented! https://github.com/cornellius-gp/gpytorch/issues/901

**Comment by wjmaddox** [comment]
> I can't do this because of memory issues, I need to do mini batches.

Ahh what I was suggesting was something like:
```python
likelihood = DirichletLikelihood(targets = full_y)

for x, y, noise in zip(inputs, likelihood.targets, likelihood.noise):
    # your minibatches here
    loss_fn(x = x, y = y, noise = noise)
```

which should be fine as long as you can store the full_y in memory. 

> I found that the actual underlying cause is that I was trying to use DirichletClassificationLikelihood in the multi class (so multi task) setting.

Yes, I don't think we ever tested modelling the classes with MTGPs which would have been a good idea in hindsight.
