### ISSUE TITLE
Prediction using Loaded Exact GP model

### ISSUE THREAD

**Issue by rdspace** [cornellius-gp/gpytorch#1946]
I have a multi-input-multi-ouput system (4 inputs --> 3 outputs ). 

I trained with ExactGP model with independent model list for the 3 outputs, the evaluation of the trained model is perfectly fine. 
I saved the model using `torch.save(self.model.state_dict(), 'fkmodel__test_state.pth')`.

For loading the saved model,  I created a new model with the same structure of 3 independent ExactGP models with the same training inputs and outputs, as shown below
```
likelihood1	= gpytorch.likelihoods.GaussianLikelihood()
model1 = FK_pred_GP().ExactGPModel(train_x,train_y[0],likelihood1)

likelihood2	= gpytorch.likelihoods.GaussianLikelihood()
model2 = FK_pred_GP().ExactGPModel(train_x,train_y[1],likelihood2)

likelihood3	= gpytorch.likelihoods.GaussianLikelihood()
model3 = FK_pred_GP().ExactGPModel(train_x,train_y[2],likelihood3)

model =	gpytorch.models.IndependentModelList(model1, model2, model3)
likelihood = gpytorch.likelihoods.LikelihoodList(model1.likelihood,	model2.likelihood, model3.likelihood)
```

I loaded the new model with the saved state_dict 
```
state_dict = torch.load('fkmodel_state.pth')
model.load_state_dict(state_dict)
```
All the keys matched successfully.

However when trying to predict with the loaded model, 
```
with torch.no_grad(), gpytorch.settings.fast_pred_var():
 	# This	contains predictions for both outcomes as a	list
 	y_op = model.likelihood(*model(x_in, x_in, x_in))
```

It is saying _**RuntimeError: You must train on the training inputs!**_

I am not sure what exactly is happening. 

Any suggestion or advice is greatly appreciated.

Thank You.

**Comment by rdspace** [comment]
I forgot to turn on the eval mode. 

After that the prediction worked. The only change I had to do is to reshape the tensor if predicting for a single point. 

So the issue is resolved.

**Comment by pengzhi1998** [comment]
Hi, I'm wondering does your loaded model have the same testing performance as it was during training?
