### ISSUE TITLE
Batch data for training a model using ExactGP

### ISSUE THREAD

**Issue by KasperNiklas** [cornellius-gp/gpytorch#1950]
Hi! 
We are new to GPyTorch and have followed the example from this notebook: https://docs.gpytorch.ai/en/latest/examples/01_Exact_GPs/Simple_GP_Regression.html

Now we wish to use batching since out data size is quite large, however we are running into some issues. 

In this code we have tried to simplify the problem such that only the relevant code, or at least the code we believe is relevant, is shown. This is just a toy example we use to try to make it work: 

``` 
# X_train and y_train looks like this after it has been through some processing 
X_train = tensor([[-1.5667], [-1.2185], [-0.8704], [-0.5222], [-0.1741], [ 0.1741], [ 0.5222], [ 0.8704], [ 1.2185], [ 1.5667]]) 
y_train = tensor([-1.1274, -1.1083, -0.8105, -0.5683, -0.5387, -0.1310,  0.2650,  0.7161, 1.3560,  1.9472]) 

# The model and likelihood is initialized with this data 
likelihood = gpytorch.likelihoods.GaussianLikelihood() 
model = ExactGPModel(train_x, train_y, likelihood) 

# Then it is being put into traing mode 
model.train() 
likelihood.train() 

# Using the Adam optimizer 
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)  

# "Loss" for GPs - the marginal log likelihood 
mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model) 

# Using batch
batch_size = 4
dataset = torch.utils.data.TensorDataset(X_train, y_train) 
dataloader = torch.utils.data.DataLoader(dataset, batch_size=batch_size) 
dataset_size = len(dataloader.dataset) 

# Training
for i in range(60): 
      # Loop over batches in an epoch using DataLoader 
      for id_batch, (x_batch, y_batch) in enumerate(dataloader): 
             # Zero gradients from previous iteration 
             optimizer.zero_grad() 
             # Output from model 
             y_batch_pred = model(x_batch) 
```

Where the model is defined as follows:

``` 
class ExactGPModel(gpytorch.models.ExactGP):

    def __init__(self, X_train, y_train, likelihood):
        super(ExactGPModel, self).__init__(X_train, y_train, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.MaternKernel(nu=1.5))

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
``` 

The trouble comes when running the line `y_batch_pred = model(x_batch)`, which gives the following error:

``` 
RuntimeError: You must train on the training inputs!
``` 

It seems to be due to that `X_train` and `x_batch` does not have the same length. 

We are wondering why this is a problem, since it seems that the model has to be initialised with:
`model = ExactGPModel(train_x, train_y, likelihood)`. 

How do we batch our data, such that we are able to train our model iteratively on the batches? 

After several hours of trying to solve this problem we are still at a loss of ideas, and we would be very grateful if someone would help us solve this problem!

Kind Regards 
Kasper

**Comment by patel-zeel** [comment]
If we follow [this paper](https://proceedings.neurips.cc/paper/2020/file/1cb524b5a3f3f82be4a7d954063c07e2-Paper.pdf), batch training in GPs is straight-forward. `gpytorch` enforces that during the train time only train data should be passed in the forward pass which makes sense. However, in your case, you can explicitly set the training data just before `y_batch_pred = model(x_batch)`:
```py
model.set_train_data(x_batch, y_batch, strict=False)
y_batch_pred = model(x_batch)
```

Remember to set the entire data as train data before predicting on test data.
```py
model.set_train_data(X_train, y_train, strict=False)
model.eval()
likelihood.eval()
predictive_distribution = likelihood(model(X_test))
```
