### ISSUE TITLE
[Question] Cuda Memory overflow during predictions

### ISSUE THREAD

**Issue by wanghuzhen** [cornellius-gp/gpytorch#1978]
# Question - Cuda Memory overflow during predictions
I have the same question with [#647 ](https://github.com/cornellius-gp/gpytorch/issues/647 ), When making predictions, the model will occupy a lot of memory and even have OOM problems. Can someone help me to solve the problem? Many thanks!!!

I run a simple multitask GP on an NVIDIA 3090ti GPU (with mem = 24gb). The shape of input data is (3500,42) and the shape of output data is (3500,3). Use the above data to train the model, then make the prediction by the trained model and the memory will be consumed quickly until OOM.
![856fd7d16da6d66837b3aa6225abaca](https://user-images.githubusercontent.com/37537124/163337016-3cacfff4-1a80-4375-9971-bf7f1d0871d1.png)
The memory during training.

![bb457bbe343d8715231ad70993bfcf4](https://user-images.githubusercontent.com/37537124/163337961-7e917e3c-54d2-4e17-9738-0dea190c5407.png)
The memory during making prediction.
Then the memory will maintain the state of 13.2GB. I tried to use `torch.cuda_empty()` to release the memory, but it didn't work.
`torch.cuda_empty()` can only release half of the memory which makes the memory overflow during cross validation.

Following my code:
GP model:
```
class MultitaskGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood,):
        super(MultitaskGPModel, self).__init__(train_x, train_y, likelihood)
        self.num_tasks = train_y.shape[-1]
        self.input_features = train_x.shape[-1]
        self.mean_module = gpytorch.means.MultitaskMean(
            gpytorch.means.ConstantMean(), num_tasks=self.num_tasks
        )
        self.covar_module = gpytorch.kernels.MultitaskKernel(
            gpytorch.kernels.RBFKernel(), num_tasks=self.num_tasks, rank=1
        )
        self.linear1 = torch.nn.Linear(self.input_features, self.input_features)

    def forward(self, x):
        x = self.linear1(x)
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultitaskMultivariateNormal(mean_x, covar_x)
```
Training:
```
likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(
    num_tasks=3).to(device)
model = MultitaskGPModel(train_x, train_y, likelihood).to(device)
model.double()
likelihood.train()
model.train()
# Use the adam optimizer
# Includes GaussianLikelihood parameters
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# "Loss" for GPs - the marginal log likelihood
mll = gpytorch.mlls.ExactMarginalLogLikelihood(
    likelihood, model)
for i in range(training_iterations):
    optimizer.zero_grad()
    output = model(train_x)
    loss = -mll(output, train_y)
    loss.backward()
    print('Iter %d/%d - Loss: %.3f' %
            (i + 1, training_iterations, loss.item()))
    optimizer.step()
```
Prediction:
```
model.eval()
likelihood.eval()
# Make predictions
with torch.no_grad(), gpytorch.settings.fast_pred_var():
    predictions = likelihood(model(test_x))
    mean = predictions.mean
    lower, upper = predictions.confidence_region()
```

The version is:
`gpytorch:1.6.0;` `python:3.9.7;` `pytorch:1.10.0`

**Comment by wjmaddox** [comment]
Hi,

How many data points you have? That is, what are the sizes of `train_x`, `train_y`, and `test_x`?

**Comment by wanghuzhen** [comment]
Thanks, the size of `train_x` is `(3423,42)`, `train_y` is`(3423,3)` and `test_x` is `(593,42)`.
The following is the `dtype` and `shape` of data:

![a2f45dfdd6aadadfe4e307a1f0b19a9](https://user-images.githubusercontent.com/37537124/163420754-0f4a213c-941b-4275-a531-7a4306990a19.png)

**Comment by wjmaddox** [comment]
Try running in float32 as that will reduce the memory requirements right off the bat. One other thing that _may_ actually reduce the memory requirements here is to not use the `gpytorch.settings.fast_pred_var()` flag.

**Comment by wanghuzhen** [comment]
Emmm, but running in float32 will raise the error that `RuntimeError: expected scalar type Float but found Double`.
I will try to remove the `gpytorch.settings.fast_pred_var()`, but the `torch.cuda_empty()` can't release all GPU memory, the memory will will always increase with iterations. Is there any advice to solve this problem??
I have delete the no use variance as following:

![794c01c3605e5f8bdef265a46bb1958](https://user-images.githubusercontent.com/37537124/163427366-643430c2-61c3-4512-89fe-ace4068c8456.png)

**Comment by wjmaddox** [comment]
Hmm.. so I can't reproduce the out of memory error on a 24GB rtx gpu, but I do get 13GB worth of memory usage when using `fast_pred_var` and ~3GB worth of memory usage if I do not use that flag (for MTGPs not using `fast_pred_var` is going to be more memory efficient and probably faster). 

In general, the memory usage will probably not increase much with iterations (and I also don't really see that) unless you mean predictions with new testing sets. I've found that setting the model to train before deleting it tends to free up more memory due to weirdness with the catching.

The double error is because you have explicitly cast everything to double in your code: `model.double()`

**Comment by wanghuzhen** [comment]
Thank you very much wjmaddox, thank you for your advice. And I do make predictions with new testing sets, it doesn't make sense to make predictions on the training set, does it?

**Comment by wjmaddox** [comment]
In general, probably not.
