### ISSUE TITLE
Use pytorch-native Multivariate Gamma function for Wishart priors

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#198]
With https://github.com/pytorch/pytorch/issues/9378 closed, we can use the pytorch native implementation of the Multivariate Gamma function.

**Comment by Balandat** [comment]
Note that this will require for pytorch/pytorch#9378 to make it into a pytorch release.

**Comment by Balandat** [comment]
Handled in #290

**Comment by ecolss** [comment]
Hey @Balandat, we now have `th.mvlgamma`, but still don't have native Wishart, do we?
And according to the Wishart pdf formula, I tried to implement a naive pdf function using native mvlgamma, but the pdf value is different from `scipy.stats.wishart.pdf`, which uses Cholesky decomposition of scale. However I failed to figure out what's wrong with

**Comment by Balandat** [comment]
@ecolss no there is no native Wishart distribution in pytorch. There is our implementation for a Wishart prior: https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/priors/wishart_prior.py

Did you check that the pdf values of that implementation agree with that of the scipy one? Also, take a close look at the parameterizations and make sure that they agree.

**Comment by ecolss** [comment]
@Balandat Thanks so much!
