### ISSUE TITLE
[Docs] Cannot access to the dataset from 'https://drive.google.com/

### ISSUE THREAD

**Issue by ZPLai** [cornellius-gp/gpytorch#1982]
# 📚 Documentation/Examples
Dear community,
When I try to run the demo code, I found the dataset should be online downloaded from 'https://drive.google.com'.
However, my computer cannot access this website.
Can any one share the dataset? So I can run the demo code without depedence on the connection to google.
Thanks very much.

**Comment by vr308** [comment]
are you referring to the elevator dataset? yes that has been moved. 

see this issue - #1636

**Comment by A2P2** [comment]
I also had the problem with the dataset. I could download it, but it wasn't possible to open it. The file from #1636 wasn't working either.
If somebody needs a workaround for now, I've converted the .mat file to a .csv file. It's now ~ 3MB.

```
#Instead of
#data = torch.Tensor(loadmat('../elevators.mat')['data'])

import numpy as np
data = torch.tensor(np.genfromtxt('elevators.csv', delimiter = ','))
```

[elevators.csv](https://github.com/cornellius-gp/gpytorch/files/8824814/elevators.csv)

**Comment by gpleiss** [comment]
Closing this issue, as it is a duplicate of #1636.
