### ISSUE TITLE
Implementing Jaccard/Tanimoto Kernel 

### ISSUE THREAD

**Issue by leelasd** [cornellius-gp/gpytorch#1986]
# 🚀 Feature Request

Hi,  I am trying to use gpytorch for molecular property regression. In cheminformatics, molecules are often represented in sparse bit vectors, and using RBF/Matern Kernels is not ideal. Recently, a publication came out demonstrating that for dealing with sparse bit vectors, Tanimoto/Jaccard kernel is best. I want to implement this kernel but have been struggling to get started. Any help with implementing this is highly appreciated.  

Here is the blog that shows how to implement this kernel is GPflow
https://towardsdatascience.com/gaussian-process-regression-on-molecules-in-gpflow-ee6fedab2130

## Motivation

**Is your feature request related to a problem? Please describe.**
My motivation here is to leverage Gpytorch for molecular property predictions 

## Pitch

**Describe the solution you'd like**
https://towardsdatascience.com/gaussian-process-regression-on-molecules-in-gpflow-ee6fedab2130

**Describe alternatives you've considered**
I have tried using GPflow, but I am facing mysterious issues getting it to run of mac. Overall I prefer the Pytorch framework to TF, so having this functionality in GPytorch would be a great help.

**Comment by wjmaddox** [comment]
Something like this should work for you:

```python
import torch
import gpytorch
import math
import matplotlib.pyplot as plt
from gpytorch.kernels import Kernel

class TanimotoKernel(Kernel):
    has_lengthscale = True

    def forward(self, x1, x2, diag=False, **params):
        cross_product = (x1.unsqueeze(-2) * x2.unsqueeze(-3)).sum(-1)
        x1_self = x1.pow(2.0).sum(-1)
        x2_self = x2.pow(2.0).sum(-1)
        
        numerator = self.lengthscale * cross_product
        denominator = x1_self.unsqueeze(-1) + x2_self.unsqueeze(-2) - cross_product 
        # probably want to do something smarter than just adding 1e-6 here to prevent roundoff errors
        return numerator / (denominator + 1e-6)

# We will use the simplest form of GP model, exact inference
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = TanimotoKernel()

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

# Training data is 100 points in [0,1] inclusive regularly spaced
train_x = torch.linspace(0, 1, 100)
# True function is sin(2*pi*x) with Gaussian noise
train_y = torch.sin(train_x * (2 * math.pi)) + torch.randn(train_x.size()) * math.sqrt(0.04)

# initialize likelihood and model
likelihood = gpytorch.likelihoods.GaussianLikelihood()
model = ExactGPModel(train_x.view(-1,1), train_y, likelihood)
```

**Comment by leelasd** [comment]
Thank you so much @wjmaddox! I cannot thank you enough for this. I have been playing around with the tutorial from the link you showed with luck for a week. I will give it another try as you suggested. 

Thanks again!
