### ISSUE TITLE
Additional data to train approximate gp model

### ISSUE THREAD

**Issue by GirishMKulkarni** [cornellius-gp/gpytorch#1993]
Hi,

I would like to add new data to the already trained approximate GP model. Is there a way in gpytorch to update the hyperparameters without recalculating again incorporating the additional data? For Exact GP models, there are get_fantasy_data()  and set_train_data() methods.
But how can I achieve this for Approximate GP?
(A similar issue for Exact GP was answered here https://github.com/cornellius-gp/gpytorch/issues/645)

Thanks in advance!

**Comment by wjmaddox** [comment]
Currently, this is somewhat impossible without re-training but this exact question is what #1874 will do for you once we merge it in. That PR is basically complete at this stage.

**Comment by GirishMKulkarni** [comment]
Dear Wesley,
Thank you so much for the update. Looking forward to the adittion.

Best regards,
Girish
