### ISSUE TITLE
[Examples] Does "Variational GPs w/ Multiple Outputs" examples support multiple input?

### ISSUE THREAD

**Issue by rginjapan** [cornellius-gp/gpytorch#2012]
As the tilte, thanks!

**Comment by rginjapan** [comment]
I mean higher dimensional, btw, could you tell me how to define the diemension of inducing points? why in the case is 3 [num_latents, 16,1 ], what is the "latent" meaning? Sorry for the stupid questions.

**Comment by rginjapan** [comment]
Does the batch_shape could be a 2D diemension instead of a scalar?

**Comment by gpleiss** [comment]
Yes, it supports inputs of any dimension. Set the inducing points to have the shape `[num_latents x num_inducing x num_input_dimensions]`

`num_latents` is the number of latent Gaussian process models. The multitask variational GP follows the linear model of coregionalization (see https://arxiv.org/pdf/1106.6251.pdf), where each task is the linear combination of `num_latent` latent Gaussian processes.
