### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by faridf** [cornellius-gp/gpytorch#2014]
# 📚 Documentation/Examples

I am trying to reproduce exactly what is described in this part of the GPyTorch documentation: [https://docs.gpytorch.ai/en/stable/examples/08_Advanced_Usage/Simple_GP_Regression_Derivative_Information_2d.html]

However, I see this error after 2 Iterations: Please help me out reproduce the same results.

/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /Users/distiller/project/conda/conda-bld/pytorch_1646756028548/work/aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/lazy/triangular_lazy_tensor.py:130: UserWarning: torch.triangular_solve is deprecated in favor of torch.linalg.solve_triangularand will be removed in a future PyTorch release.
torch.linalg.solve_triangular has its arguments reversed and does not return a copy of one of the inputs.
X = torch.triangular_solve(B, A).solution
should be replaced with
X = torch.linalg.solve_triangular(A, B). (Triggered internally at  /Users/distiller/project/conda/conda-bld/pytorch_1646756028548/work/aten/src/ATen/native/BatchLinearAlgebra.cpp:1672.)
  res = torch.triangular_solve(right_tensor, self.evaluate(), upper=self.upper).solution
Iter 1/50 - Loss: 1.280   lengthscales: 0.693, 0.693   noise: 0.693
/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/models/exact_gp.py:273: GPInputWarning: The input matches the stored training data. Did you forget to call model.train()?
  warnings.warn(
Iter 2/50 - Loss: 1.202   lengthscales: 0.668, 0.668   noise: 0.669
/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/utils/cholesky.py:38: NumericalWarning: A not p.d., added jitter of 1.0e-06 to the diagonal
  warnings.warn(
/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/utils/cholesky.py:38: NumericalWarning: A not p.d., added jitter of 1.0e-05 to the diagonal
  warnings.warn(
/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/utils/cholesky.py:38: NumericalWarning: A not p.d., added jitter of 1.0e-04 to the diagonal
  warnings.warn(
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/farid/Desktop/Saddle_Point_Searcher_v3(2)/Saddle_Point_Searcher_v3/top_secret.py", line 68, in <module>
    loss = -mll(output, train_y)
  File "/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/module.py", line 30, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 62, in forward
    res = output.log_prob(target)
  File "/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/distributions/multitask_multivariate_normal.py", line 211, in log_prob
    return super().log_prob(value.view(*value.shape[:-2], -1))
  File "/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/distributions/multivariate_normal.py", line 169, in log_prob
    inv_quad, logdet = covar.inv_quad_logdet(inv_quad_rhs=diff.unsqueeze(-1), logdet=True)
  File "/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/lazy/lazy_tensor.py", line 1291, in inv_quad_logdet
    cholesky = CholLazyTensor(TriangularLazyTensor(self.cholesky()))
  File "/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/lazy/lazy_tensor.py", line 1004, in cholesky
    chol = self._cholesky(upper=False)
  File "/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/utils/memoize.py", line 59, in g
    return _add_to_cache(self, cache_name, method(self, *args, **kwargs), *args, kwargs_pkl=kwargs_pkl)
  File "/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/lazy/lazy_tensor.py", line 435, in _cholesky
    cholesky = psd_safe_cholesky(evaluated_mat, upper=upper).contiguous()
  File "/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/utils/cholesky.py", line 63, in psd_safe_cholesky
    L = _psd_safe_cholesky(A, out=out, jitter=jitter, max_tries=max_tries)
  File "/Users/farid/opt/anaconda3/envs/tf/lib/python3.10/site-packages/gpytorch/utils/cholesky.py", line 45, in _psd_safe_cholesky
    raise NotPSDError(f"Matrix not positive definite after repeatedly adding jitter up to {jitter_new:.1e}.")
gpytorch.utils.errors.NotPSDError: Matrix not positive definite after repeatedly adding jitter up to 1.0e-04.

**Comment by gpleiss** [comment]
Are you exactly rerunning the notebook?

These numerical instabilities are not uncommon with GP. One thing you can try is setting a noise constraint on the Gaussian likelihood. This tends to make things more numerically stable:

```python
likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(
    noise_constraint=gpytorch.constraints.GreaterThan(1e-3)
)
```

**Comment by faridf** [comment]
Thanks for recommending to run from Notebook. It actually worked. I apologize for reporting this as an issue.

I have one more question:
Does this class (GPModelWithDerivatives) support higher dimensionality? Should this class work where the input data is 3d instead of 2d? If not, what do you recommend?

**Comment by gpleiss** [comment]
It should work for higher dimensionality data as well.

**Comment by faridf** [comment]
I am trying to use GPModelWithDerivatives class for higher dimensions. My example has 159 dimensions and I set ard_num_dims=159. So the class looks like this now:

________________________________________________
        class GPModelWithDerivatives(gpytorch.models.ExactGP):
            def __init__(self, train_x, train_y, likelihood):
                super(GPModelWithDerivatives, self).__init__(train_x, train_y, likelihood)
                self.mean_module = gpytorch.means.ConstantMeanGrad()
                self.base_kernel = gpytorch.kernels.RBFKernelGrad(ard_num_dims=159)
                self.covar_module = gpytorch.kernels.ScaleKernel(self.base_kernel)


            def forward(self, x):
                mean_x = self.mean_module(x)
                covar_x = self.covar_module(x)
                return gpytorch.distributions.MultitaskMultivariateNormal(mean_x, covar_x)
________________________________________________

and my likelihood has 160 number of tasks now and looks like this:
likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(
                    num_tasks=160)

But I end-up with this error:

{RuntimeError}!(has_different_input_dtypes && !config.promote_inputs_to_common_dtype_ && (has_undefined_outputs || config.enforce_safe_casting_to_output_ || config.cast_common_dtype_to_outputs_))INTERNAL ASSERT FAILED at "/Users/distiller/project/conda/conda-bld/pytorch_1646756028548/work/aten/src/ATen/TensorIterator.cpp":399, please report a bug to PyTorch.

**Comment by faridf** [comment]
Update: this link helped:
https://github.com/cornellius-gp/gpytorch/issues/1807

I set the dtype for the entire script with this line:
torch.set_default_dtype(torch.float64)
