### ISSUE TITLE
[Docs] Do we have tutorials about saving and loading likelihood model

### ISSUE THREAD

**Issue by rginjapan** [cornellius-gp/gpytorch#2016]
# 📚 Documentation/Examples
As the title

**Comment by rginjapan** [comment]
Can I use this to save the likelihood only?
`torch.save(likelihood.state_dict(), 'likelihood_state.pth')
`

**Comment by gpleiss** [comment]
That works, but can you explain exactly what you are trying to do? [This tutorial](https://docs.gpytorch.ai/en/stable/examples/00_Basic_Usage/Saving_and_Loading_Models.html) shows you how to save and load models.

**Comment by rginjapan** [comment]
I use the above method to save likelihood model only, but the size is only 1~2 kb, I am not sure it has been saved correctly or not.

**Comment by gpleiss** [comment]
This is correct. A likelihood only has a few parameters that need to be saved.
