### ISSUE TITLE
[Question] Constructing a - Independent Multivariate Normal Prior 

### ISSUE THREAD

**Issue by vr308** [cornellius-gp/gpytorch#2017]
Hi, 

I am trying to declare a prior over a variable X (n x q) which is independent across q but correlated across n, so it is a product of q multivariate normals with a covariance matrix of size (n x n)

This is how I would do it if I wanted everything to be independent (across n and q):

```
import torch, gpytorch
from gpytorch.priors import NormalPrior, MultivariateNormalPrior

n = 100
q = 2
    
X_prior_mean = torch.zeros(n, q)  # shape: N x Q
X_init = torch.nn.Parameter(torch.zeros(n, 2))
prior_x = NormalPrior(X_prior_mean, torch.ones_like(X_prior_mean))
```
Samples from the prior above have shape (n,q) - all good.

But now I want to correlate across n:
```
#using a kernel for covariance matrix 

t = torch.linspace(0,10,100)
rbf = gpytorch.kernels.RBFKernel(ard_num_dims=1)
rbf.lengthscale = 1.0
covar = rbf(t,t).evaluate() + torch.eye(100)*1e-5

prior_x = MultivariateNormal(mean=X_prior_mean, covariance_matrix=covar)
```
but the samples from this prior have shape (n,) -> how do I give it a shape :/

**Comment by gpleiss** [comment]
Sorry for the slow reply @vr308 ! You could switch the dimensions:

```python
X_prior_mean = torch.zeros(q, n)
# covar = ...
prior_x = MultivariateNormalPrior(X_prior_mean, covar)
print(prior_x.sample().shape)  # q x n
```

This essentially makes a batch of q (independent) n-dimensional multivariate normals.

**Comment by vr308** [comment]
thanks @gpleiss managed to figure out :) but appreciate your writing back!
