### ISSUE TITLE
Why is there no  ARD lengthscale option for the periodic kernel?

### ISSUE THREAD

**Issue by pok99** [cornellius-gp/gpytorch#2018]
Hi
Why is there no  ARD lengthscale option for the periodic kernel?
Is there a  theoretical reason for this?

I'm dealing with a pretty high dimensional dataset (81 features) and I'm in the process of model selection and wanted to fit a periodic with multiple lengthscales.

Is there a manual way to do this?

**Comment by gpleiss** [comment]
It does. See #1919.
This feature is currently only available on the the master branch, but it will be included in the next release.

**Comment by pok99** [comment]
Thank you!
