### ISSUE TITLE
Implement LKJ prior over correlation matrices

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#202]
The Wishart and inverse Wishart can be used as priors over the IndexKernel, but they are hard to intuit, and not easy to specify (many parameters, quite opaque).

Instead, we can write a positive definite matrix `Sigma \in R^{n x n}` as `Sigma = diag(s) C diag(s)`, where `C \in R^{n x n}` is a correlation matrix and `s = sqrt(diag(Sigma))`. We can now put a prior over the elements of `s`, and a separate prior over `C`, which can be parametrized more intuitively using the LKJ prior over correlation matrices. 

See sections 63.1 and 63.2 in the Stan manual for details:
https://github.com/stan-dev/stan/releases/download/v2.17.0/stan-reference-2.17.0.pdf

**Comment by eytan** [comment]
Can we close this out?  This shipped a while ago in eb2aff4.

**Comment by Balandat** [comment]
done by @rajkumarkarthik
