### ISSUE TITLE
What happened to gpytorch.metrics?

### ISSUE THREAD

**Issue by pok99** [cornellius-gp/gpytorch#2024]
Hi,
Trying to evaluate predictions using the tutorial 
https://docs.gpytorch.ai/en/latest/examples/00_Basic_Usage/Metrics.html 
However, I get the error: 
`AttributeError: module 'gpytorch' has no attribute 'metrics' `
Why does this happen?  

```
model.eval()
with torch.no_grad():
  preds_dist= likelihood(model(test_x))
  mean_preds = preds_dist.mean
  lower, upper = preds_dist.confidence_region()

msll = gpytorch.metrics.mean_standardized_log_loss(preds_dist, test_y)
```

**Comment by gpleiss** [comment]
The gpytorch.metrics module is not available in any of our releases yet. Install GPyTorch from source if you want to use this feature now.

**Comment by pok99** [comment]
Thank you!
