### ISSUE TITLE
named_parameter_priors won't get priors for children of torch Modules

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#204]
I think the PR #196  I did fixed things like DKL to at least run, but was a bad fix because we'll fail to get priors for parameters in gpytorch.Modules that are children of torch.nn.Modules. For example, consider AdditiveKernel, which places a bunch of Kernels in a ModuleList. Since named_parameter_priors is a recursive call that won't actually run on the ModuleList because it doesn't exist, we won't actually get priors for the component Kernels even if they are defined.

Ordinarily I'd just implement a fix, but I'm actually not sure how to deal with this one. Even if we implement an in house ModuleList extension, it seems dangerous and insidious to leave this failure case in, since the intention is that GPyTorch Modules are interoperable with torch ones. Therefore, a recursive version of named_parameter_priors seems not possible -- maybe we have to expand each child of a normal torch Module in the method directly?

@Balandat

**Comment by Balandat** [comment]
How about instead of calling this recursively on the object method we move to a functional approach where we in the top-level call of `named_parameter_priors` recursively call a function `_extract_named_parameter_priors` like the following:

```
def _extract_named_parameter_priors(module, memo=None, prefix=""):
    if memo is None:
        memo = set()
    if hasattr(module, "_priors"):
        for name, parameter in module._parameters.items():
            if name in module._priors and module._priors[name] not in memo:
                prior = module._priors[name]
                memo.add(prior)
                yield prefix + ("." if prefix else "") + name, parameter, prior
    for mname, module_ in module.named_children():
        submodule_prefix = prefix + ("." if prefix else "") + mname
        _extract_named_priors(module=mname, memo=memo, prefix=submodule_prefix)
```

Testing this now.
