### ISSUE TITLE
Is that possible to calculate a weighted likelihood directly?

### ISSUE THREAD

**Issue by KarasCvs** [cornellius-gp/gpytorch#2044]
# 🚀 Feature Request

## Motivation
Hi.
I want to calculate a weighted log likelihood of Gaussian process such as [log p(y|WX, \theta)] where W is a weight matrix.
Because the weight needs to be multiplied by the kernel function such as [W^T*K(X,X)*W], I'm not sure how can I deal with the gpytorch.kernels.RBFKernel() output and the likelihood function.

## Pitch

Is that possible to use make this happen easily? I find gpytorch.kernels.ScaleKernel() can zoom the kernel output but I'm not sure how to use a diagonal matrix as scale, and also I'm not sure is this the method that I need.

**Comment by gpleiss** [comment]
You would need to write your own custom kernel for this. This is probably not something that we'd merge upstream into GPyTorch, unless you think that this would be a common use case.
