### ISSUE TITLE
High dimension lengthscales for custom Kernel [Feature Request]

### ISSUE THREAD

**Issue by faridf** [cornellius-gp/gpytorch#2046]
# 🚀 Feature Request

I am trying to write a custom Kernel that is very similar to RBF but with the difference of subtracting the pair distances between pair of points instead of subtracting the points themselves.
To be precise, the RBF kernel(https://docs.gpytorch.ai/en/v1.6.0/kernels.html#rbfkernel) computes a covariance matrix based on the squared exponential kernel between inputs x1 and x2.
However, I would like to change the inputs from x1 and x2 to 1/r(x1) and 1/r(x2). Where r(x) is the matrix of distances between all pair points of x1 and r(x2) is the matrix of distances between all pair points of x2. I call it Inverse Euclidian Distance Kernel.
Please see this link for a clear picture of the Kernel: [https://drive.google.com/file/d/11tXnyQN-mujCm1LEq9gf2L-wmbAk9w-0/view?usp=sharing](url)

I have defined these two classes below for this purpose:

class InverseEuclidianDistanceKernel(gpytorch.kernels.Kernel):
    def __init__(self, num_dimensions, lengthscale_prior=None, active_dims=None):
        super(InverseEuclidianDistanceKernel, self).__init__(active_dims=active_dims)
        self.register_parameter(name="raw_lengthscale", parameter=torch.nn.Parameter(torch.zeros(num_dimensions)))

    @property
    def lengthscale(self):
        return torch.exp(self.raw_lengthscale)

    def forward(self, x1, x2, diag=False, last_dim_is_batch=False):
        if diag:
            return torch.ones(x1.size(-2))

        x1_ = x1.div(self.lengthscale)
        x2_ = x2.div(self.lengthscale)
        x1_ = x1_.unsqueeze(-2)
        x2_ = x2_.unsqueeze(-3)
        # dist = (x1_ - x2_).pow(2).sum(-1) # this would be RBF kernel but I comment it here
        dist_x1, dist_x2 = torch.zeros(x1.size(0), x1.size(0)), torch.zeros(x2.size(0), x2.size(0))
        dist = torch.ones(x1.size(0), x2.size(0))
        dist = (1 / dist1.sum(-1) - 1 / dist2.sum(-1).reshape(-1,1)).pow(2)
        dist = dist.transpose(-1, -2)
        return torch.exp(- dist / 2)

class ExactGPModelwithInverseEuclidianDistanceKernel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModelwithInverseEuclidianDistanceKernel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(InverseEuclidianDistanceKernel(num_dimensions=2))

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

I seem to have completed every part of it however, I am struggling with one aspect of it. The kernel requires a high dimension lengthscale variable that has the size of the distance matrices. For example, if there are 100 input data that are 2d, then lengthscale dimension would 100x100. 

I have looked through the documentation of gpytorch and I have not found the part that addresses this issue. As far as I understand, the lengthscale dimension goes as 2 in my case.

Let me know if I am missing anything from gpytorch that covers this.

## Motivation
The motivation behind this new kernel is from a reference that is newly published, and it has the promise of outperforming the regular RBF kernel when the system is closer to singularities. This type of kernel could be very important to those studying potential energy surfaces.
I leave a link to the study here: [https://pubs.acs.org/doi/10.1021/acs.jctc.9b01038](url)

**Comment by gpleiss** [comment]
How is this Lengthscale parameter generated? Let's say you train your data on 100 data points. During training, you'd want a Lengthscale of 100x100. However, at test time, when you're evaluating your GP on (e.g.) 50 new data points, you'd need a Lengthscale of 150x150. What values would the length scale take for those new test values?

Regardless, you can use a different parameter (e.g. `self.register_parameter("custom_lengthscale", torch.nn.Parameter(torch.randn(100, 100))`). See [the PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.nn.parameter.Parameter.html) for more details.

In the future, this would be better opened up as a discussion (because it concerns a question about custom code) rather than an feature request (something that would be added upstream to GPyTorch).
