### ISSUE TITLE
[Question] Constraining means of variational distribution in low-level pyro integration

### ISSUE THREAD

**Issue by pscicluna** [cornellius-gp/gpytorch#2058]
Hi!

I'm using pyro for latent-function inference with a `CholeskyVariationalDistribution`. I would like to be able to place constraints (or even priors) on the means of the variational distribution, but it isn't immediately obvious how to achieve this. I assume I need to do something similar to https://github.com/cornellius-gp/gpytorch/issues/1598? If I understand it correctly, that applies to the inducing point _locations_, so I would need to do the equivalent of creating a `ConstrainedCholeskyVarationalDistribution` with a `raw_variational_mean` registered as a parameter and then define a transform for those parameters? Can I use e.g. an IntervalConstraint, or do I need to explicitly define the transformation I need?

**Comment by gpleiss** [comment]
Sorry for the slow reply @pscicluna!

> I would like to be able to place constraints (or even priors) on the means of the variational distribution, but it isn't immediately obvious how to achieve this.

Why are you trying to do this? The variational parameters are not parameters of the generative model, and so they shouldn't have priors/constraints placed on them.

If you do want to add some sort of regularization to the variational parameters (not sure this is advisable, as you will then be optimizing an objective that differs from the standard ELBO), then you could always do something like:

```python
loss = svi.step(train_x, train_y) + lamda * model.variational_strategy.variational_distribution.variartional_mean.norm().pow(2.)
```

This essentially adds L2 regularization to the variational mean parameters.

I'm going to close this issue for now - please open a [discussion topic](https://github.com/cornellius-gp/gpytorch/discussions) if you have more questions about this.
