### ISSUE TITLE
[Docs] [Question] A question about evaluating the likelihood and spiky predictions in `ExactGP`.

### ISSUE THREAD

**Issue by miguelgondu** [cornellius-gp/gpytorch#2092]
Hi, `gpytorch`'s community of developers.

I have a very simple question about the difference between `f_pred` and `y_pred` in the [exact regression example](https://docs.gpytorch.ai/en/stable/examples/01_Exact_GPs/Simple_GP_Regression.html).

In the training loop we call the model to obtain a `MultivariateNormal`, which we then use to compute the marginal log likelihood of our training data, namely

```python
mll = gpytorch.mlls.ExactMarginalLogLikelihood(model.likelihood, model)

for _ in range(100):
    optimizer.zero_grad()
    output = model(train_x)
    loss = -mll(output, train_y)
    loss.backward()
```

Internally, the `ExactMarginalLogLikelihood` evaluates `likelihood(distribution).log_prob(data)` and so the hyperparameters of the likelihood are optimized.

At prediction time, the `ExactGP` calls an exact prediction strategy in which the usual update rules for exact GPs are applied, taking the inverse of `self.likelihood(dist, self.train_inputs).lazy_covariance_matrix` ([see line 319 of the exact prediction strategies](https://github.com/cornellius-gp/gpytorch/blob/3c5a5bd08097763a2189ff16496b6216976191a4/gpytorch/models/exact_prediction_strategies.py#L319)). **Why do we have to evaluate on `model.likelihood` again to get noise estimates?** Shouldn't the posterior distribution already account for the noise since we're inverting $(K_{xx} + \sigma I)$?

Moreover, the posterior samples of `model.likelihood(model(new_inputs))` look spiky, even with high lengthscales and smooth kernels. How come? I was expecting the posterior samples of `model.likelihood(model(new_inputs))` to smoothly account for the noise.

![example](https://user-images.githubusercontent.com/8268159/183471758-bf06dc2d-029c-40ce-bc38-e62a4c6a82de.jpg)

Here's the example that generated the image above. It is a copy-paste of the tutorial, plus a prior on the kernel to have high lengthscales.

```python
"""
Just a slightly modified copy of
https://docs.gpytorch.ai/en/latest/examples/01_Exact_GPs/Simple_GP_Regression.html
"""
import numpy as np
import torch
from matplotlib import pyplot as plt

import gpytorch

noise_level = 1e-1
train_x = torch.linspace(0, 2 * np.pi, 100)
train_y = torch.sin(train_x) + noise_level * torch.randn(train_x.size())

# Everything's the same as in the tutorial, except
# we add a prior to have high lengthscales.
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y):
        likelihood = gpytorch.likelihoods.GaussianLikelihood()
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(
            gpytorch.kernels.RBFKernel(
                lengthscale_prior=gpytorch.priors.GammaPrior(10.0, 1.0)
            )
        )

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)


model = ExactGPModel(train_x, train_y)
model.train()
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)
mll = gpytorch.mlls.ExactMarginalLogLikelihood(model.likelihood, model)

for i in range(100):
    optimizer.zero_grad()
    output = model(train_x)
    loss = -mll(output, train_y)
    loss.backward()
    optimizer.step()

model.eval()

new_inputs = torch.linspace(0, 2 * np.pi, 50)
pred1 = model(new_inputs)
pred2 = model.likelihood(model(new_inputs))

fig, (ax1, ax2) = plt.subplots(1, 2, sharey=True, figsize=(2 * 7, 7))

ax1.plot(new_inputs.detach().numpy(), pred1.mean.detach().numpy())
ax2.plot(new_inputs.detach().numpy(), pred2.mean.detach().numpy())

ax1.plot(train_x.detach().numpy(), train_y.detach().numpy(), "*k", alpha=0.2)
ax2.plot(train_x.detach().numpy(), train_y.detach().numpy(), "*k", alpha=0.2)

for _ in range(5):
    sample1 = pred1.sample().detach().numpy()
    ax1.plot(new_inputs.detach().numpy(), sample1, "--")

    sample2 = pred2.sample().detach().numpy()
    ax2.plot(new_inputs.detach().numpy(), sample2, "--")

ax1.set_title("Samples from model(new_data)")
ax2.set_title("Samples from likelihood(model(new_data))")

plt.tight_layout()
plt.show()
plt.close()
```

**Comment by gpleiss** [comment]
> Why do we have to evaluate on model.likelihood again to get noise estimates? Shouldn't the posterior distribution already account for the noise since we're inverting `K_XX + \sigma^2 I`.

This line of code is adding `\sigma^2 I` to `train_train_covar = K_XX`. So it's doing the correct thing.

> Moreover, the posterior samples of model.likelihood(model(new_inputs)) look spiky, even with high lengthscales and smooth kernels. How come? I was expecting the posterior samples of model.likelihood(model(new_inputs)) to smoothly account for the noise.

`model(x).rsample()` samples from the posterior (performs smoothing). `model.likelihood(model(x)).rsample()` samples from the posterior predictive. The posterior predictive distribution assumes there is independent observational noise for each data point, which makes the sample look jumpy.

In general, there aren't really any applications where you'd want to sample from your posterior predictive as far as I can tell. You almost always want to sample from your posterior (i.e. `model(x).rsample()`).

For future reference, this would be a better [discussion topic](https://github.com/cornellius-gp/gpytorch/discussions) rather than an issue.

**Comment by miguelgondu** [comment]
Hi Geoff, thanks for the quick answer.

Thanks for pointing me to the discussions. I will move my future questions there.
