### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by jmunozmendi** [cornellius-gp/gpytorch#2139]
# 🐛 Bug

I get the following error:

'VariationalStrategy' object has no attribute 'get_fantasy_model'

when running the SVGP_Model_Updating.ipynb example notebook.

## System information

- GPyTorch Version 1.6.0
- PyTorch Version 1.10.2
- Windows10

## Additional context
I got the error when trying to update a PolyGamma ApproximateGP. I thought the error was on my part so I ran the example to find out it isn't working either.

**Comment by gpleiss** [comment]
You're using an old version of GPyTorch (current version is 1.9). SVGP model updating was added in [version 1.7](https://github.com/cornellius-gp/gpytorch/releases/tag/v1.7.0).
