### ISSUE TITLE
Setting up lengthscale hyperparameter as a matrix

### ISSUE THREAD

**Issue by cae0027** [cornellius-gp/gpytorch#2144]
I read [here](https://github.com/cornellius-gp/gpytorch/issues/689) on how to alter the lengthscale of a gpytorch model but I was wondering if there is a way to initialize the lengthscale as a matrix since the documentation states that $\Theta$ is initialized as a diagonal matrix?
Thanks

**Comment by gpleiss** [comment]
There isn't, but we'd be open to a PR!

**Comment by cae0027** [comment]
Okay, thank you for responding!
