### ISSUE TITLE
Generalize `to_pyro_random_module` for other PPLs

### ISSUE THREAD

**Issue by feynmanliang** [cornellius-gp/gpytorch#2154]
Please let me know if there is a better way to go about this :)

A clear and concise description of what you wish to refactor. Please include the following:

We would like to generalize `to_pyro_random_module` in order for other PPLs (eg [beanmachine](https://github.com/facebookresearch/beanmachine/blob/main/tests/ppl/experimental/gp/inference_test.py#L61-L70)) to integrate with gpytorch.

Modules that will be modified

 * `to_pyro_random_module` -> `to_random_module` 
 * rename `pyro_random_module_cls` prefix from `_Pyro` to `_Random`
 * We could potentially upstream and refactor to reduce duplication (eg https://github.com/facebookresearch/beanmachine/blob/main/src/beanmachine/ppl/experimental/gp/__init__.py#L15) at the cost of gpytorch taking a dependency on beanmachine (similar to Pyro)

Impact on code structure

 * largely (all except upstreaming the integration in the last bullet) cosmetic, no change in structure

Impact on speed

 * n/a

Will this be a breaking change?
 * Yes, both library BW compatibility due to renaming functions as well as binary compatibility due to renaming class names

**Comment by feynmanliang** [comment]
What about binary compatibility? eg someone pickles a `_PyroRandomModule` and then tries to unpickle after we've updated to using `_RandomModule`?

**Comment by Balandat** [comment]
My hot take is that people shouldn't pickle but instead save state dicts.

**Comment by eytan** [comment]
Is GPYTorch due for a major point release soon? Agree with wrapper
solution. Might make sense to hold off on adding deprecation warnings until
majors point release.

**Comment by gpleiss** [comment]
We should definitely do a new release (1.10) soon, but probably not a major release (2.0)

**Comment by gpleiss** [comment]
Closed by #2164
