### ISSUE TITLE
Small bugs in half_cauchy prior test.

### ISSUE THREAD

**Issue by ZitongZhou** [cornellius-gp/gpytorch#2155]
https://github.com/cornellius-gp/gpytorch/blob/bd4fccc391db38ea2a536b7a8774cf54b82ffa9d/test/priors/test_half_cauchy_prior.py#L22 repeated lines.

https://github.com/cornellius-gp/gpytorch/blob/bd4fccc391db38ea2a536b7a8774cf54b82ffa9d/test/priors/test_half_cauchy_prior.py#L40 testing with the gamma test.

**Comment by gpleiss** [comment]
Thanks for the catch! Would you be able to open a PR to fix these issues?

**Comment by ZitongZhou** [comment]
Okay I'll fix it.

**Comment by gpleiss** [comment]
Fixed by #2156
