### ISSUE TITLE
[Bug] The '+=' operator doesn't work on a lazy tensor when executed out of scope 

### ISSUE THREAD

**Issue by trbedwards** [cornellius-gp/gpytorch#2170]
# 🐛 Bug

Applying the `+=` operator to a `LazyTensor` doesn't work when applied in a function call. This is unexpected behaviour as one would expect it to work the same as it does with regular pytorch tensors or numpy arrays. It only works if the `LazyTensor` is evaluated in the same scope that the `+=` operation is applied. 

Perhaps one needs to implement the `__iadd__` method for `LazyTensor`s?

## To reproduce
```
import torch
from gpytorch.lazy import lazify

t2 = torch.eye(2)
l2 = lazify(t2)

def add1(lazy_tensor):
    lazy_tensor += torch.eye(2)

add1(l2)
assert (l2.evaluate() == torch.tensor([[2., 0],[0., 2.]]).all() 
```
## System information

**Please complete the following information:**
- GPyTorch Version 1.6.0
- PyTorch Version 1.10.2
- Ubuntu 18.04.3

**Comment by gpleiss** [comment]
In general, we don't want to implement __i*__ operators (in-place operations to LinearOperators cause all sorts of bugs).

I think the best thing to do would be to throw an error if someone tries to use an in-place operator.

In any case, this issue no longer belongs in the GPyTorch repo, as the LazyTensor functionality was moved to the LinearOperator repo (see #2027)
