### ISSUE TITLE
Condience intervel in Multitask GP Regression example [Docs]

### ISSUE THREAD

**Issue by ztspirit** [cornellius-gp/gpytorch#2181]
# 📚 Documentation/Examples

Thank you for this powerful library. I am learning the multi-task gaussian regression and trying to reproduce the results in the example provided in the tutorial. 
https://docs.gpytorch.ai/en/v1.6.0/examples/03_Multitask_Exact_GPs/Multitask_GP_Regression.html?highlight=gpytorch.kernels.MultitaskKernel#Define-a-multitask-model 
To rule out the possible mistakes, I exactly copied the example code. Despite the random sampling, the confidence region I got is consistently larger than that in the example. Did I miss something? 

Results in the example document:
![examples_03_Multitask_Exact_GPs_Multitask_GP_Regression_9_0](https://user-images.githubusercontent.com/60516124/199076751-63d373c4-fee8-4b18-94c9-331f9d22ed65.png)
Results reproduced by me:
![download](https://user-images.githubusercontent.com/60516124/199076984-700a364e-40ea-4ba8-8d4e-14b4e912654e.png)

**Comment by gpleiss** [comment]
I am not sure why the confidence intervals look so small in the documentation. Your plots look correct. I'm updating the notebook in a PR.

**Comment by ztspirit** [comment]
Got it. Thanks for the confirmation.
