### ISSUE TITLE
[Bug] Bug Name won't fit in description (Runtime Error)

### ISSUE THREAD

**Issue by ajohnson114** [cornellius-gp/gpytorch#2197]
I was following the gpr tutorial but I didn't do the sin function for my train_y as opposed to a custom function.
Tutorial found here: https://docs.gpytorch.ai/en/latest/examples/01_Exact_GPs/Simple_GP_Regression.html

**Potentially Important note: I'm on a Mac M1 2020 so I'm not using a cuda gpu but I'm not sure if that's part of the issue.**

**Code to reproduce:**

import math
import torch
import gpytorch
from matplotlib import pyplot as plt

%matplotlib inline
%load_ext autoreload
%autoreload 2

# Training data is 100 points in [0,1] inclusive regularly spaced
train_x = torch.linspace(-10, 10, 1000,dtype=float)
# True function is sin(2*pi*x) with Gaussian noise
train_y = train_x**3 - 2*train_x + 7 + torch.normal(0,100,(1000,))
train_y = torch.tensor(train_y,dtype=float) # I added this in to try to fix the issue but the bug occurs with or without this 

# We will use the simplest form of GP model, exact inference
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

# initialize likelihood and model
likelihood = gpytorch.likelihoods.GaussianLikelihood()
model = ExactGPModel(train_x, train_y, likelihood)

training_iter = 100

# Find optimal model hyperparameters
model.train()
likelihood.train()

# Use the adam optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)  # Includes GaussianLikelihood parameters

# "Loss" for GPs - the marginal log likelihood
mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

for i in range(training_iter):
    # Zero gradients from previous iteration
    optimizer.zero_grad()
    # Output from model
    output = model(train_x)
    # Calc loss and backprop gradients
    loss = -mll(output, train_y)
    loss.backward()
    print('Iter %d/%d - Loss: %.3f   lengthscale: %.3f   noise: %.3f' % (
        i + 1, training_iter, loss.item(),
        model.covar_module.base_kernel.lengthscale.item(),
        model.likelihood.noise.item()
    ))
    optimizer.step()

**The bug that I was told to report:**

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [129], in <cell line: 13>()
     17 output = model(train_x)
     18 # Calc loss and backprop gradients
---> 19 loss = -mll(output, train_y)
     20 loss.backward()
     21 print('Iter %d/%d - Loss: %.3f   lengthscale: %.3f   noise: %.3f' % (
     22     i + 1, training_iter, loss.item(),
     23     model.covar_module.base_kernel.lengthscale.item(),
     24     model.likelihood.noise.item()
     25 ))

File ~/miniforge3/envs/tf_m1/lib/python3.9/site-packages/gpytorch/module.py:30, in Module.__call__(self, *inputs, **kwargs)
     29 def __call__(self, *inputs, **kwargs):
---> 30     outputs = self.forward(*inputs, **kwargs)
     31     if isinstance(outputs, list):
     32         return [_validate_module_outputs(output) for output in outputs]

File ~/miniforge3/envs/tf_m1/lib/python3.9/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py:64, in ExactMarginalLogLikelihood.forward(self, function_dist, target, *params)
     62 # Get the log prob of the marginal distribution
     63 output = self.likelihood(function_dist, *params)
---> 64 res = output.log_prob(target)
     65 res = self._add_other_terms(res, params)
     67 # Scale by the amount of data we have

File ~/miniforge3/envs/tf_m1/lib/python3.9/site-packages/gpytorch/distributions/multivariate_normal.py:169, in MultivariateNormal.log_prob(self, value)
    167 # Get log determininant and first part of quadratic form
    168 covar = covar.evaluate_kernel()
--> 169 inv_quad, logdet = covar.inv_quad_logdet(inv_quad_rhs=diff.unsqueeze(-1), logdet=True)
    171 res = -0.5 * sum([inv_quad, logdet, diff.size(-1) * math.log(2 * math.pi)])
    172 return res

File ~/miniforge3/envs/tf_m1/lib/python3.9/site-packages/linear_operator/operators/_linear_operator.py:1657, in LinearOperator.inv_quad_logdet(self, inv_quad_rhs, logdet, reduce_inv_quad)
   1654 probe_vectors, probe_vector_norms = self._probe_vectors_and_norms()
   1656 func = InvQuadLogdet.apply
-> 1657 inv_quad_term, pinvk_logdet = func(
   1658     self.representation_tree(),
   1659     precond_lt.representation_tree(),
   1660     preconditioner,
   1661     len(precond_args),
   1662     (inv_quad_rhs is not None),
   1663     probe_vectors,
   1664     probe_vector_norms,
   1665     *(list(args) + list(precond_args)),
   1666 )
   1667 logdet_term = pinvk_logdet
   1668 logdet_term = logdet_term + logdet_p

File ~/miniforge3/envs/tf_m1/lib/python3.9/site-packages/linear_operator/functions/_inv_quad_logdet.py:132, in InvQuadLogdet.forward(ctx, representation_tree, precond_representation_tree, preconditioner, num_precond_args, inv_quad, probe_vectors, probe_vector_norms, *args)
    130 # Perform solves (for inv_quad) and tridiagonalization (for estimating logdet)
    131 rhs = torch.cat(rhs_list, -1)
--> 132 solves, t_mat = linear_op._solve(rhs, preconditioner, num_tridiag=num_random_probes)
    134 # Final values to return
    135 logdet_term = torch.zeros(linear_op.batch_shape, dtype=ctx.dtype, device=ctx.device)

File ~/miniforge3/envs/tf_m1/lib/python3.9/site-packages/linear_operator/operators/_linear_operator.py:735, in LinearOperator._solve(self, rhs, preconditioner, num_tridiag)
    731 def _solve(self, rhs: torch.Tensor, preconditioner: Callable, num_tridiag: int = 0) -> torch.Tensor:
    732     r"""
    733     TODO
    734     """
--> 735     return utils.linear_cg(
    736         self._matmul,
    737         rhs,
    738         n_tridiag=num_tridiag,
    739         max_iter=settings.max_cg_iterations.value(),
    740         max_tridiag_iter=settings.max_lanczos_quadrature_iterations.value(),
    741         preconditioner=preconditioner,
    742     )

File ~/miniforge3/envs/tf_m1/lib/python3.9/site-packages/linear_operator/utils/linear_cg.py:176, in linear_cg(matmul_closure, rhs, n_tridiag, tolerance, eps, stop_updating_after, max_iter, max_tridiag_iter, initial_guess, preconditioner)
    173 rhs = rhs.div(rhs_norm)
    175 # residual: residual_{0} = b_vec - lhs x_{0}
--> 176 residual = rhs - matmul_closure(initial_guess)
    177 batch_shape = residual.shape[:-2]
    179 # result <- x_{0}

File ~/miniforge3/envs/tf_m1/lib/python3.9/site-packages/linear_operator/operators/added_diag_linear_operator.py:71, in AddedDiagLinearOperator._matmul(self, rhs)
     70 def _matmul(self, rhs: Tensor) -> Tensor:
---> 71     return torch.addcmul(self._linear_op._matmul(rhs), self._diag_tensor._diag.unsqueeze(-1), rhs)

RuntimeError: !(has_different_input_dtypes && !config.promote_inputs_to_common_dtype_ && (has_undefined_outputs || config.enforce_safe_casting_to_output_ || config.cast_common_dtype_to_outputs_)) INTERNAL ASSERT FAILED at "/Users/runner/miniforge3/conda-bld/pytorch-recipe_1660136169395/work/aten/src/ATen/TensorIterator.cpp":407, please report a bug to PyTorch.

**Software Versions**
python = 3.9
torch.version = 1.12.1
gpytorch.version = 1.9.0

**Comment by gpleiss** [comment]
I cannot reproduce the error. My guess is it an issue with PyTorch (possibly due to the MacBook architecture)
