### ISSUE TITLE
Pass arguments to GP model from DeepGPLayer 

### ISSUE THREAD

**Issue by IdanAchituve** [cornellius-gp/gpytorch#2223]
Hi,
In the forward method of the DeepGPLayer class the argument **kwargs is not passed when calling to ApproximateGP ([link](https://github.com/cornellius-gp/gpytorch/blob/cda4bc54b773cb6a98979a95e9ec80310d198663/gpytorch/models/deep_gps/deep_gp.py#L100)). Is it intentionally? I believe that it is not the desired behavior. 

Thanks,
Idan

**Comment by gpleiss** [comment]
It's not - it should be passed through. Mind putting up a PR fixing this?

**Comment by IdanAchituve** [comment]
Done. Thanks.
