### ISSUE TITLE
Improve unit test coverage outside of examples

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#224]
The examples take quite a while to run, let's try to get 100% unit test coverage with lightweight tests outside of the examples.

**Comment by gpleiss** [comment]
LazyTensors are now in a good state. We should make similar base test cases for our other objects:

- [ ] Kernels
- [ ] Models (we have a base case in place - we now just need to use it)
- [ ] Likelihoods (maybe?)
- [ ] Priors (maybe?)
- [ ] Mean functions (maybe?)

**Comment by jacobrgardner** [comment]
This is now done to enough of an extent that any specific uncovered code should be raised in more specific issues.
