### ISSUE TITLE
[Docs] Bernoulli likelihoods 

### ISSUE THREAD

**Issue by LuhuanWu** [cornellius-gp/gpytorch#2245]
# 📚 Documentation/Examples

In the document for [Bernoulli likelihoods](https://docs.gpytorch.ai/en/stable/likelihoods.html), since the labels take value in {0, 1}, the likelihood should be 

$$p(Y=y | f) = \Phi ((2y-1)f)$$

instead of the currently displayed

$$p(Y=y|f) = \Phi(yf).$$

**Comment by gpleiss** [comment]
Makes sense! Mind putting up a PR?

**Comment by brick-transporter** [comment]
In the implementation, the {0,1} input is actually transformed to {-1,1}, so the displayed function is actually what they do actually.

Maybe it's better to clarify that, the input label should be {0,1}, but it is transformed into {-1,1} to fit the compact calculation \Phi(y * f) during implementation.
