### ISSUE TITLE
Subtracting two kernels or multiplying a kernel by a constant

### ISSUE THREAD

**Issue by GurjotDhaliwal** [cornellius-gp/gpytorch#2250]
Hi 

  I am new to gpytorch and trying t implement the additive kernel as described by the equation 6 in Additive Gaussian Processes by David Duvenaud etal. Below is I tried to implement a hand coded version of that equation for n= 1 (first_order_kernel) and n=2 (second_order_kernel)
 On running the following model, I get a type error

TypeError: unsupported operand type(s) for -: 'ProductKernel' and 'AdditiveKernel'

Is there a work-around to include minus sign or a constant for a kernel? 
`

class GPModel(gpytorch.models.ExactGP): 

    def __init__(self,train_x,train_y,likelihood):
        super().__init__(train_x,train_y,likelihood)
        self.mean_module = gpytorch.means.ZeroMean()

        kernel_list = []
        num_dims = train_x.shape[-1]
        #
        for i in range(num_dims):
            kernel = gpytorch.kernels.RBFKernel(active_dims=torch.tensor([i]))
            kernel_list.append(kernel)

        first_order_kernel = kernel_list[0]
        for i in range(1,num_dims):
            first_order_kernel += kernel_list[i]

        sum_sq_kernel = kernel_list[0]*kernel_list[0]
        for i in range(1,num_dims):
            sum_sq_kernel += kernel_list[i]*kernel_list[i]

        second_order_kernel = (first_order_kernel*first_order_kernel) - sum_sq_kernel
        #second_order_kernel = (first_order_kernel*first_order_kernel) + ((-1)**(1))*(sum_sq_kernel(train_x))

        self.covar_module = gpytorch.kernels.ScaleKernel(
            first_order_kernel + second_order_kernel
        )

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
`

**Comment by gpleiss** [comment]
In general, we don't allow subtraction of kernels, because the result might not be positive definite.
However, there's a better option for this additive kernel! See the Newton Girard Additive Kernel (https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/kernels/newton_girard_additive_kernel.py) which is (I believe) exactly what you are trying to implement.
