### ISSUE TITLE
Modeling Time-Varying Noise

### ISSUE THREAD

**Issue by UgurKap** [cornellius-gp/gpytorch#2277]
Hello,

I want to model time-varying and/or periodically-varying noise. Normally, it could be done with "RBF + LinearKernel×WhiteNoiseKernel" or "RBF + PeriodicKernel×WhiteNoiseKernel"[1]. I am not sure how to implement this kernel structure in GPytorch, as white noise kernel is deprecated.

Should I implement a custom kernel? Is there a better, proven way? Any guidance or suggestions would be greatly appreciated!

Best,
Uğur

[1]Page 34: https://www.cs.toronto.edu/~duvenaud/thesis.pdf

**Comment by gpleiss** [comment]
Perhaps we should un-deprecated the WhiteNoiseKernel @Balandat ? I agree that FixedNoiseGaussianLikelihood should be encouraged, but there are use cases like this one where it seems that a WhiteNoiseKernel would actually be useful.

@UgurKap in the meantime you can copy-paste our old implementation of WhiteNoiseKernel: https://github.com/cornellius-gp/gpytorch/blob/v0.2.1/gpytorch/kernels/white_noise_kernel.py
