### ISSUE TITLE
Spectral mixture kernel bug

### ISSUE THREAD

**Issue by sumitsk** [cornellius-gp/gpytorch#233]
It seems that if the training input size is more than one dimension, then spectral mixture kernel initialize_from_data method throws runtime error. Here is a small script that produces the error:

```
import math
import torch

from gpytorch.kernels import SpectralMixtureKernel

train_x = torch.linspace(0, 1, 15)
train_y = torch.sin(train_x.data * (2 * math.pi))
train_x = torch.cat([train_x.unsqueeze(-1), torch.ones_like(train_x.unsqueeze(-1))], dim=-1)

cov = SpectralMixtureKernel(n_mixtures=4)
cov.initialize_from_data(train_x, train_y)
```

**Comment by jacobrgardner** [comment]
I believe `SpectralMixtureKernel` as implemented is a one dimensional kernel. To extend it to multiple dimensions, you should be able to build the multi dimensional version using `ProductKernel` and `active_dims`.
