### ISSUE TITLE
[Bug] strange scalability using keops on a simple Exact GP regression

### ISSUE THREAD

**Issue by jcadena001** [cornellius-gp/gpytorch#2334]
# 🐛 Bug

When using keops (similar to example in https://docs.gpytorch.ai/en/stable/examples/02_Scalable_Exact_GPs/KeOps_GP_Regression.html), I am observing some strange scalability on the dimension of the training data. I am training an Exact GP for regression on a dataset of size NxD where N=12638 and D (the number of features) varies between 10 and 200. There is a huge jump in running time when D changes from 110 (0.54 seconds per iteration) to 112 (29 seconds per iteration). 

## To reproduce

** Code snippet to reproduce **
```python
import torch
import gpytorch
import numpy as np
import time

class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ZeroMean()

        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.keops.MaternKernel(nu=2.5))

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)


def train(train_x, train_y, model, likelihood):
    model.train()
    likelihood.train()
    
    # Use the adam optimizer
    optimizer = torch.optim.Adam(model.parameters(), lr=0.1) 
    
    # "Loss" for GPs - the marginal log likelihood
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)
    
    # training loop
    training_iter = 50
    for i in range(training_iter):
        start_time = time.time()
        # Zero gradients from previous iteration
        optimizer.zero_grad()
        # Output from model
        output = model(train_x)
        # Calc loss and backprop gradients
        loss = -mll(output, train_y)
        loss.backward()
        time_taken = time.time() - start_time
        print('Iter %d/%d - Loss: %.3f   lengthscale: %.3f   noise: %.3f   time taken: %.2fs' % (
            i + 1, training_iter, loss.item(),
            model.covar_module.base_kernel.lengthscale.item(),
            model.likelihood.noise.item(),
             time_taken
        ))
        optimizer.step()
    

if __name__ == "__main__":
    train_size = 12638
    #dim = 100 # 0.44 s per iter
    #dim = 102 # 0.44 s per iter
    #dim = 110 # 0.54 s per iter
    dim = 112 # 29 s   per iter
    output_device = torch.device('cuda:0')
    train_x = torch.randn((train_size, dim))
    train_y = torch.randn(train_size)

    # standardize to Normal(0, 1)
    mean_x, std_x = train_x.mean(axis=0), train_x.std(axis=0)
    mean_y, std_y = train_y.mean(), train_y.std()
    train_x = (train_x - mean_x) / std_x
    train_y = (train_y - mean_y) / std_y
    train_x, train_y = train_x.type(torch.float32), train_y.type(torch.float32)
    
    # all data moved to GPU devices
    train_x, train_y = train_x.to(output_device), train_y.to(output_device)

    # initialize likelihood and model
    likelihood = gpytorch.likelihoods.GaussianLikelihood().cuda()
    model = ExactGPModel(train_x, train_y, likelihood).cuda()

    train(train_x, train_y, model, likelihood)
    
    print('Done')
```

** Stack trace/error message **
No error message

## Expected Behavior

I would expect running time not to increase so disproportionately with feature size. See a table below of the times I am observing:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/cadenapico1/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/cadenapico1/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

number of features | time per iteration (s)
-- | --
40 | 0.2
80 | 0.42
100 | 0.44
102 | 0.44
110 | 0.54
112 | 29.27
120 | 46.02

</body>

</html>

## System information

**Please complete the following information:**
- GPyTorch Version 1.9.1
- PyTorch Version 1.12.1 
- Computer OS Linux Red Hat 7.9 (Maipo)

**Comment by m-julian** [comment]
Hi @jcadena001, for me the time per iteration does not scale as poorly.

This is what I am getting for 110 dimensions on a 1080Ti GPU:
```
Iter 1/50 - Loss: 1.443   lengthscale: 0.693   noise: 0.693   time taken: 1.36s
Iter 2/50 - Loss: 1.434   lengthscale: 0.693   noise: 0.644   time taken: 1.00s
Iter 3/50 - Loss: 1.427   lengthscale: 0.693   noise: 0.599   time taken: 0.99s
Iter 4/50 - Loss: 1.422   lengthscale: 0.693   noise: 0.556   time taken: 0.99s
Iter 5/50 - Loss: 1.419   lengthscale: 0.693   noise: 0.518   time taken: 0.99s
```
and for GPU 112 dimensions:

```
Iter 1/50 - Loss: 1.443   lengthscale: 0.693   noise: 0.693   time taken: 1.37s
Iter 2/50 - Loss: 1.434   lengthscale: 0.693   noise: 0.644   time taken: 1.03s
Iter 3/50 - Loss: 1.426   lengthscale: 0.693   noise: 0.599   time taken: 1.07s
Iter 4/50 - Loss: 1.422   lengthscale: 0.693   noise: 0.556   time taken: 1.06s
Iter 5/50 - Loss: 1.419   lengthscale: 0.693   noise: 0.518   time taken: 1.04s
```

I also tested it out on CPU and it is also not that slow (just changed `likelihood = gpytorch.likelihoods.GaussianLikelihood().to(output_device)` and `model = ExactGPModel(train_x, train_y, likelihood).to(output_device)` as in your code the model and likelihood are initialized to be on the GPU.

5600 CPU 110 dimensions:

```
Iter 1/50 - Loss: 1.443   lengthscale: 0.693   noise: 0.693   time taken: 1.46s
Iter 2/50 - Loss: 1.434   lengthscale: 0.693   noise: 0.644   time taken: 1.30s
Iter 3/50 - Loss: 1.427   lengthscale: 0.693   noise: 0.599   time taken: 1.30s
Iter 4/50 - Loss: 1.422   lengthscale: 0.693   noise: 0.557   time taken: 1.29s
Iter 5/50 - Loss: 1.419   lengthscale: 0.693   noise: 0.519   time taken: 1.34s
```

5600 CPU 112 dimensions:

```
Iter 1/50 - Loss: 1.443   lengthscale: 0.693   noise: 0.693   time taken: 1.39s
Iter 2/50 - Loss: 1.434   lengthscale: 0.693   noise: 0.644   time taken: 1.32s
Iter 3/50 - Loss: 1.427   lengthscale: 0.693   noise: 0.599   time taken: 1.30s
Iter 4/50 - Loss: 1.422   lengthscale: 0.693   noise: 0.557   time taken: 1.30s
Iter 5/50 - Loss: 1.419   lengthscale: 0.693   noise: 0.518   time taken: 1.27s
```

Here are the package versions I am using:

```
gpytorch version: 1.10
linear_operator version: 0.4.0
torch version: 2.0.0+cu117
pykeops version: 2.1.2
```

**Comment by jcadena001** [comment]
@m-julian, thank you for running my sample script. I updated my packages to match yours (except for torch; I have 1.12.1), but that didn't change things for me. I am using a V100 GPU; that might make a difference. At any rate, I will close this issue for now, as it seems to be only affecting me.
