### ISSUE TITLE
[Feature Request] Multiple batch independent input multitask variational GP

### ISSUE THREAD

**Issue by WWXkenmo** [cornellius-gp/gpytorch#2341]
# 🚀 Feature Request

Hey! In current vector-valued variation GP (https://docs.gpytorch.ai/en/stable/examples/04_Variational_and_Approximate_GPs/SVGP_Multitask_GP_Regression.html) seems only could handle one input to multiple outputs. My question is that suppose I have a high dimensional inputs. For example I have hundreds of different time axis (X_1, ..., X_100), for each axis I need to perform vector valued GP prediction (suppose we need to predict 50 variable Y (Y_1, .., Y_50)). Therefore, give a time stamp X* (a 100 dimension vector), the new GP model need to return a 100*50 matrix, indicate the 50 variable Y interpolated values on 100 different time axis, is that possible?

**Comment by gpleiss** [comment]
@WWXkenmo the example you link to also would handle high dimensional inputs. Just pass in your inputs as N x D tensors (see any of our other tutorials for an example of this; e.g. https://docs.gpytorch.ai/en/stable/examples/04_Variational_and_Approximate_GPs/SVGP_Regression_CUDA.html)
