### ISSUE TITLE
Can I use `nn.DataParallel` to use multiple GPUs ?

### ISSUE THREAD

**Issue by Fangwq** [cornellius-gp/gpytorch#2350]
I try to use `nn.DataParallel` to use multiple GPUs. But, it does not work. Anyway,  can `gpytorch` module use multiple GPUs? How to do that? thank you very much!
```
model = nn.DataParallel(GPModel(induce_point, likelihood, train_x, test_x, net, device), device_ids=list(range(torch.cuda.device_count())))
model = model.module
```

**Comment by gpleiss** [comment]
See our [multi-GPU tutorial](https://docs.gpytorch.ai/en/stable/examples/02_Scalable_Exact_GPs/Simple_MultiGPU_GP_Regression.html)

If your goal is large-scale GPs, I would recommend using only a single GPU but using our [KeOps integration](https://docs.gpytorch.ai/en/stable/examples/02_Scalable_Exact_GPs/KeOps_GP_Regression.html)
