### ISSUE TITLE
Allow batch-predictions from non-batch GP

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#236]
In some cases we'd like to get independent posteriors for separate batches of test points. E.g. say we train a single GP on `n x d` train_x and `n` (single-dim) train_y data. Then we'd like to be able to pass in test data of shape `b x k x d` to produce `b` independent posteriors, where the `i`-th one is the posterior of the `k` test points in the `i`-th batch.

Currently, this raises the following error: 
```
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0
```

We should be able to do some reasonable broadcasting / inferring of batch size 1 here.

Pertinent comment by @jacobrgardner:
> I think it would be good if everything in GPyTorch was in batch mode by default. That should automatically solve this issue: the original model would be a model on `x` in `1 x n x d`, `y` in `1 x n x 1`.  Then, for batch predictions, you'd get broadcasting.

**Comment by Balandat** [comment]
Any progress on this? I think standardizing this throughout the codebase will be necessary to make the torch distributions (and other stuff like the HeteroschedasticLikelihood) work as expected.

**Comment by gpleiss** [comment]
We have a feature test that sort of covers this, but right now it expects that you update the training data to include batch data. I'll try to tackle this today or tomorrow

**Comment by Balandat** [comment]
ok cool - let's consider this in the context of #262 and #286, with which we're hopefully converging to a standardized way of handling batches everywhere
