### ISSUE TITLE
[Bug] KeOps LazyTensors are no longer compatible with linear-operator

### ISSUE THREAD

**Issue by Felice27** [cornellius-gp/gpytorch#2363]
# 🐛 Bug

Using the default KeOps example notebook no longer works as of the latest release of GPyTorch and linear-operator (perhaps this issue is better suited for the linear-operator github page, but it was encountered specifically with the GPyTorch KeOps integration)

## To reproduce

Run the KeOps_GP_Regression.ipynb notebook at /examples/02_Scalable_Exact_GPs/ (or with a smaller toy dataset)

** Stack trace/error message **
```
-> 2977     raise TypeError("object of class {} cannot be made into a Tensor".format(obj.__class__.__name__))

TypeError: object of class LazyTensor cannot be made into a Tensor
```

## Expected Behavior

The linear-operator package should be able to perform operations with LazyTensor objects

## System information

- GPyTorch Version 1.11
- linear-operator version 0.5.0
- PyTorch Version 2.0.1
- Computer OS Linux

## Additional context
I know @gpleiss discussed integrating linear_operator with KeOps in my previous issue-- perhaps I missed some critical step for integrating the linear_operator with LazyTensor objects properly?

**Comment by gpleiss** [comment]
Sorry for the slow reply. I will take a look at this soon.

**Comment by adeeb10abbas** [comment]
@gpleiss did you have a chance to look at it? My colleague and I are a bit stuck due to this. Thanks for all the help!

**Comment by adeeb10abbas** [comment]
@Felice27 thanks that helps a ton!

**Comment by pengzhi1998** [comment]
@adeeb10abbas @Felice27 @gpleiss 
Thank you everyone for your discussion and suggestions (when I have GPyTorch 1.11 on my side, it's said that CUDA is out of memory when testing the [default KeOps example](https://docs.gpytorch.ai/en/stable/examples/02_Scalable_Exact_GPs/KeOps_GP_Regression.html)) 

However, when I downgraded GPyTorch to 1.10 and linear-operator to 0.4.0 then run the example, I found another error reported: `RuntimeError: You must have KeOps installed to use a KeOpsKernel`. But I tried many versions of `pykeops` but all couldn't work. May I have your suggestions which `pykeops` and `torch` should I use to run this default exam and to make use of KeOps for exact GP with big dataset?

**Comment by Felice27** [comment]
@pengzhi1998 What GPU are you attempting to use to run the default notebook?  It may be the case that you encountered an issue that I have before, where even with the kernel partitioning of KeOps, there is a CUDA-level memory error with the GPU used when backpropagating the losses that cannot be worked around.  For my 32 GB NVidia Volta V100, this hard limit was around half a million data points.  If it would help, my version of PyKeOps is 2.1.2, which should be able to be downloaded through pip.

**Comment by pengzhi1998** [comment]
Thank you so much for your reply @Felice27 and sorry for my slow update. Actually, I have solved the issue by adding a line in the code: `os.environ['CUDA_PATH'] = '/usr/local/cuda/'`. I guess the problem was the scripts didn't find the path to `CUDA`.

Thank you again!

**Comment by kayween** [comment]
> @pengzhi1998 What GPU are you attempting to use to run the default notebook? It may be the case that you encountered an issue that I have before, where even with the kernel partitioning of KeOps, there is a CUDA-level memory error with the GPU used when backpropagating the losses that cannot be worked around. For my 32 GB NVidia Volta V100, this hard limit was around half a million data points. If it would help, my version of PyKeOps is 2.1.2, which should be able to be downloaded through pip.

I recently had a memory error similar to what you mentioned. I am wondering if you have resolved this issue. Specifically, when training exact GP on a dataset with ~400k data points on a 24 GB GPU, I had the following error at the end of the first epoch

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.55 GiB (GPU 0; 23.68 GiB total capacity; 14.39 GiB already allocated; 8.30 GiB free; 14.54 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`

Versions
- gpytorch 1.10
- linear-operator 0.4.0
- pykeops 2.1.2

Looks like there is no memory issue if I remove the preconditioner by `settings.max_preconditioner_size(0)`. However, this is not ideal.

**Comment by cookbook-ms** [comment]
> Sorry for the slow reply. I will take a look at this soon.

I do experience the same bug.
