### ISSUE TITLE
[Bug] AdditiveKernel with LinearKernel cannot work fine on GPU

### ISSUE THREAD

**Issue by Display-ST** [cornellius-gp/gpytorch#2371]
# 🐛 Bug

When using `AdditiveKernel` that sums over the **`LinearKernel`** and another kernel, the behavior is different on CPU and GPU: it works fine on CPU, but model training does not terminate on GPU.

## To reproduce

In [Simple_GP_Regression_CUDA.ipynb](https://github.com/cornellius-gp/gpytorch/blob/master/examples/02_Scalable_Exact_GPs/Simple_GP_Regression_CUDA.ipynb), please replace `ExactGPModel` as follows (only `self.covar_module` is modified): 

```python
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        # self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel() + gpytorch.kernels.LinearKernel())

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
```

## Expected Behavior

As with the CPU, model training is completed successfully on GPU.

## System information

- GPyTorch: 1.9.1
- PyTorch: 2.0.1
- Python: 3.9.13
- OS: Windows 10
- GPU: NVIDIA GeForce RTX 3060 Ti

```
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:24:09_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
```

```
$ nvidia-smi
Tue Jun 27 12:51:22 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.94       Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| 55%   64C    P2    71W / 200W |   1485MiB /  8192MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

## Additional context

While trying `AdditiveKernel` with `LinearKernel` on another dataset, the following exception occurred in the [linear_operator](https://github.com/cornellius-gp/linear_operator/blob/7c5aabd8291146790e6f178ed6735f86163aca55/linear_operator/operators/_linear_operator.py#L1089).

![image](https://github.com/cornellius-gp/gpytorch/assets/106041509/34daaf4b-616d-40a2-a8b8-0d621300dd50)

**Comment by gpleiss** [comment]
I don't think this is a bug on our end. If it works on CPU and not on GPU, it is likely that your data is very ill-conditioned, and you are catching a corner case where MAGMA-CPU works but MAGMA-GPU does not work.

In any case, it is likely that your data is ill-conditioned, or it's a limitation with the BLAS used by PyTorch.

**Comment by Display-ST** [comment]
I don't think the data in [Simple_GP_Regression_CUDA.ipynb](https://github.com/cornellius-gp/gpytorch/blob/master/examples/02_Scalable_Exact_GPs/Simple_GP_Regression_CUDA.ipynb) is not ill-conditioned, so I understood that it's most likely a limitation with the BLAS used by PyTorch. Thank you so much.
