### ISSUE TITLE
kissgp_kronecker_product_regression

### ISSUE THREAD

**Issue by MaxCamPi** [cornellius-gp/gpytorch#238]
After running the code in kissgp_kronecker_product_regression.ipynb, I obtain the following (after train()):

File "/Users/maxs/anaconda3/lib/python3.6/site-packages/gpytorch/utils/fft.py", line 11, in fft1
    return complex_input.fft(1)

RuntimeError: fft: ATen not compiled with MKL support

**Comment by jacobrgardner** [comment]
This is actually an issue with your PyTorch installation. See #194. In general we recommend that you install on top of Anaconda python for ease, although in that issue apparently compiling PyTorch from scratch was an alternative.

**Comment by MaxCamPi** [comment]
Thank you so much for such a prompt response!
