### ISSUE TITLE
Difference between "Batch GP Regression" and "Batch Independent Multioutput GP"

### ISSUE THREAD

**Issue by Rashfu** [cornellius-gp/gpytorch#2402]
What is the difference between[ Batch GP Regression](https://docs.gpytorch.ai/en/stable/examples/08_Advanced_Usage/Simple_Batch_Mode_GP_Regression.html) and [Batch Independent Multioutput GP](https://docs.gpytorch.ai/en/stable/examples/03_Multitask_Exact_GPs/Batch_Independent_Multioutput_GP.html)?

Assuming the shape of the input x is `[400, 2]`, and the shape of the output y is `[400, 3]`, I can either directly use [Batch Independent Multioutput GP](https://docs.gpytorch.ai/en/stable/examples/03_Multitask_Exact_GPs/Batch_Independent_Multioutput_GP.html) or I can duplicate the input x to have a shape of `[3, 400, 2]`, and adjust the output y to have a shape of `[3, 400]`, then utilize [ Batch GP Regression](https://docs.gpytorch.ai/en/stable/examples/08_Advanced_Usage/Simple_Batch_Mode_GP_Regression.html) . The data for both approaches can be exactly the same, with only minor differences in the code. 

 In [Batch Independent Multioutput GP](https://docs.gpytorch.ai/en/stable/examples/03_Multitask_Exact_GPs/Batch_Independent_Multioutput_GP.html), it says that _Unlike in the [Multitask GP Example](https://docs.gpytorch.ai/en/stable/examples/03_Multitask_Exact_GPs/Multitask_GP_Regression.html), this do not model correlations between outcomes, but treats outcomes independently_. But the code still uses the  `MultitaskMVN` and `MultitaskGaussianLikelihood`. While in [ Batch GP Regression](https://docs.gpytorch.ai/en/stable/examples/08_Advanced_Usage/Simple_Batch_Mode_GP_Regression.html) , it says that _we do NOT account for any correlations between the different functions being modeled._   I am confused about the `correlations` mentioned in the two tutorials. Are these two `correlations`  the same? I'm not clear about the difference between multioutput and multitask.

Thanks in advance !

**Comment by Balandat** [comment]
These two are essentially the same model - In the Batch GP Regression case the model structure is just a single-output model with an additional batch dim that corresponds to the different functions you model. In the batch independent multioutput GP the model has explicit (trailing) output dimensions - these are realized by the `MultitaskMultivariateNormal` that is being used in the model (hence you need the `MultitaskGaussianLikelihood`). The main thing to note here is that the resulting covariance across the outputs is block-diagonal, i.e. the correlations between outputs are not being modeled here. For that you need to use an actual Multitask GP.

**Comment by Balandat** [comment]
> But I visualized the covariance of output, and it doesn't appear to be a block diagonal matrix. There are still non-zero values in other positions.

The `MultitaskMultivariateNormal` has an `interleaved` setting: 
https://github.com/cornellius-gp/gpytorch/blob/981edd83a671e8dca9d67c91b188702354884a34/gpytorch/distributions/multitask_multivariate_normal.py#L27-L29

So you'll have to reshape the covariance matrix to see the block-diagonal structure w.r.t. the outputs.
