### ISSUE TITLE
Ability to perform exact extrapolation with KISS-GP

### ISSUE THREAD

**Issue by tzoiker** [cornellius-gp/gpytorch#243]
Correct me if I am wrong: KISS-GP requires O(1) computations in order to calculate the predictive mean value for each test point. However, the drawback is that for the points that lie outside of the grid, interpolation procedure uses the closest boundary grid points, which gives a very sharp transition of predictions outside of the boundary (first pic - exact, second - KISS-GP).

<img width="450" alt="screen shot 2018-08-23 at 15 08 43" src="https://user-images.githubusercontent.com/6230141/44524551-b12ceb00-a6e6-11e8-8da5-3d33a60e6aac.png">
<img width="448" alt="screen shot 2018-08-23 at 15 09 11" src="https://user-images.githubusercontent.com/6230141/44524552-b4c07200-a6e6-11e8-8843-5705e19c3681.png">

Is it possible to enforce O(m) honest mean prediction for extrapolation somehow? Similar question for the predictive variance, I guess.

**Comment by jacobrgardner** [comment]
In the one dimensional setting with SKI (and in high dimensional adaptations like SKIP), a good approach to getting this behavior is to simply increase the bounds of the grids to not simply bound only the training data, but also the full bounds on which you plan to evaluate the model.

Doing so will of course incur some small additional cost corresponding to increasing the number of inducing points (in your example, you might consider doubling both the grid range and the number of inducing points). 

However, scalability as a function of the number of inducing points is really not a huge issue for these methods. In particular, when the number of training examples is large, I've often found that even doubling the number of inducing points rarely makes a substantial difference on the final time complexity of the model.

**Comment by tzoiker** [comment]
Seems reasonable, thanks!

**Comment by gpleiss** [comment]
Closing this for now, but please re-open if you feel we haven't addressed the issue :)
