### ISSUE TITLE
Links broken to example notebooks

### ISSUE THREAD

**Issue by lionfish0** [cornellius-gp/gpytorch#245]
Links from https://github.com/cornellius-gp/gpytorch/blob/master/README.md to example notebooks broken.

**Comment by jacobrgardner** [comment]
Thanks for pointing this out!

This has to do with some example notebook and tutorial reorganization now that we have so many of them, and now that we've greatly expanded the actual text surrounding the examples. The README now points to the right thing (which is the text in the example folder itself)
