### ISSUE TITLE
[Docs] Links to "Documentation" and to "Example" on the front page are the same link

### ISSUE THREAD

**Issue by partev** [cornellius-gp/gpytorch#2467]
On the front page [gpytorch.ai](https://gpytorch.ai) there are two links to "Examples" and "Documentation".

![image](https://github.com/cornellius-gp/gpytorch/assets/23830955/28597fd1-70f1-4137-9ea3-a3884f2a1d0a)

Both links link to the same location: https://gpytorch.readthedocs.io

They should either link to different locations, or there should only be one link on the front page called "Examples and Documentation"

**Comment by SiddheshBangar** [comment]
I guess that, there should be just one icon and button on the page which directs towards the documentation, however we have examples on the same page as well (I haven't found any other examples page). So just keeping one icon of documentation would be good. If okay I can work on this.

**Comment by partev** [comment]
opened a new issue in the repository for the website here:

https://github.com/cornellius-gp/cornellius-gp.github.io/issues/3

closing this issue
