### ISSUE TITLE
Add example notebooks for SGPR and SKIP

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#256]

**Comment by sumitsk** [comment]
Hey guys! I believe this is not completed in the beta release. Can you kindly provide an example script for SKIP algorithm?

**Comment by jacobrgardner** [comment]
Yes, I will make a SKIP tutorial notebook first thing in the morning.

**Comment by jacobrgardner** [comment]
@sumitsk Just pushed a SKIP example notebook! We'll write an SGPR / SVGP one soon and then close out this issue.

**Comment by sumitsk** [comment]
Thanks a lot @jacobrgardner . Appreciate your quick help :) !!

**Comment by gpleiss** [comment]
This is done.
