### ISSUE TITLE
Remove deprecated parameter bounds for beta release

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#263]
I am of the opinion that the deprecated parameter bounds should not make it in to the beta release, since they are just an alias for a prior at this point and not really even hard constraint bounds anymore.

Thoughts?

**Comment by Balandat** [comment]
yeah, let's kill them for the beta

**Comment by Balandat** [comment]
sounds good. I can take a stab at the LazyTensor codemod, we can get that in right away b/c it's not user-facing

**Comment by Balandat** [comment]
This is addressed by #286
