### ISSUE TITLE
Lapack Error in TestSimpleGPRegression

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#271]
I'm getting a reproducible `RuntimeError: Lapack Error syev : 9 off-diagonal elements didn't converge to zero at caffe2/aten/src/TH/generic/THTensorLapack.cpp:395` in `test_simple_gp_regression.py` with this.

Not sure whether related to #266 or #270. @gpleiss, could you take a look?

**Comment by gpleiss** [comment]
I'm not noticing this issue - @jacobrgardner and I are compiling PyTorch master to set if that's the issue

**Comment by gpleiss** [comment]
@Balandat - this might have been fixed by 2a77a6b - could you check?

**Comment by jacobrgardner** [comment]
I am pretty confident this is now resolved on pytorch master.
