### ISSUE TITLE
Derive priors from torch.distributions

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#284]
We can re-use a bunch of functionality, and we'll also conform to how torch.distributions handle batch mode. This should solve #267.

For the basic versions (e.g. Normal or Gamma priors) there are a couple of things to do
1. overwrite `log_prob` in the base class so that the handling of log-transform is done as is currently [this is straightforward]
2. make sure `Prior` is derived from torch.nn.Module, so it can inherit all the goodies there. This also  means that the distribution parameters will need to be registered as buffers. This is doable, albeit a little bit hacky if we want to avoid duplication by calling the constructor of the respective torch distribution (b/c you can't overwrite attributes when registering buffers - so you'll have to do sth like store the broadcasted parameters [e.g. loc, scale] in a temporary variable, explicitly remove the attribute, and then add it back in as a buffer - not pretty, but seems to work).

For distributions not implemented in torch.distributions (LKJ, Wishart), we just need to conform to the basic torch.distributions api. We should probably just push these upstream once we feel good about those.

I have a local commit that looks pretty promising, shouldn't be too long until I diff this out.

**Comment by gpleiss** [comment]
CLosed by #286
