### ISSUE TITLE
multitask learning where each task has multiple kernels

### ISSUE THREAD

**Issue by Sabina321** [cornellius-gp/gpytorch#285]
Hello, 

I have got a working example of using a multitask GP using gpytorch, and also got an example working where the covariance has multiple kernels, but when I try to combine them the training fails. The forward method works but I'm not sure where it is failing in the training. Has anyone seen this before/have suggestions?

**Comment by jacobrgardner** [comment]
Do you maybe have an example model or some example code that fails? It might be hard to hazard a guess about what's going wrong without seeing exactly what you're trying.

**Comment by Sabina321** [comment]
This is what I was trying to do:

class  MultitaskGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(MultitaskGPModel, self).__init__(train_x, train_y, likelihood)
        # Default bounds on mean are (-1e10, 1e10)
        self.mean_module = ConstantMean()
        # We use the very common RBF kernel

        
        self.covar_one_module = RBFKernel()
        self.covar_two_module = RBFKernel()
        self.covar_module = self.covar_one_module+self.covar_two_module
  
        
        # We learn an IndexKernel for 2 tasks
        # (so we'll actually learn 2x2=4 tasks with correlations)
        self.task_covar_module = IndexKernel(n_tasks=2, rank=1)

    def forward(self,x,i):
        
        # Get predictive mean

        mean_x = self.mean_module(x)
        # Get all covariances, we'll look up the task-speicific ones
       
    
        covarx = self.covar_module(x)
        covar_i = self.task_covar_module(i)

        covar_xi = covarx.mul(covar_i)
     
        
        return GaussianRandomVariable(mean_x, covar_xi)

**Comment by jacobrgardner** [comment]
025f4cf should fix this for the Hadamard multitask case. 

The Kronecker multitask case seems to already support this (even our example notebook for it uses the sum of two multitask kernels for example: https://github.com/cornellius-gp/gpytorch/blob/master/examples/03_Multitask_GP_Regression/Multitask_GP_Regression.ipynb) 

Feel free to reopen the issue if there are still problems!

**Comment by Sabina321** [comment]
Great looks like it fixed it. Thanks!
