### ISSUE TITLE
multitask with many tasks, Function AddDiagLegacyBackward 

### ISSUE THREAD

**Issue by Sabina321** [cornellius-gp/gpytorch#294]
Hello, 

I am trying to do a multitask gp with 36 tasks. However, I'm getting an error in training: 

Function AddDiagLegacyBackward returned an invalid gradient at index 1 - expected shape [1] but got []

I wanted to check a few things about setting up this model. 

Following the multitask example:https://github.com/cornellius-gp/gpytorch/blob/master/examples/03_Multitask_GP_Regression/Hadamard_Multitask_GP_Regression.ipynb

it seems that all of the data is flattened into training x and y tensors with an index tensor. So I have: 

x = [x1,....,x696], y=[y1,...,y696] and then y_indices = [0,0,0,1,1,1,1,1,1,...,35,35,35]. 

Is that the correct way to set up the indices? This seems to be the same as in the example. 

The tasks are not of the same dimension. Is that a problem? 

The model is straight from the example:

class  MultitaskGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(MultitaskGPModel, self).__init__(train_x, train_y, likelihood)
        # Default bounds on mean are (-1e10, 1e10)
        self.mean_module = ConstantMean()
        # We use the very common RBF kernel
        self.covar_module = RBFKernel()
        # We learn an IndexKernel for 2 tasks
        # (so we'll actually learn 2x2=4 tasks with correlations)
        **self.task_covar_module = IndexKernel(n_tasks=36, rank=1)**

    def forward(self,x,i):
        # Get predictive mean
        mean_x = self.mean_module(x)
        # Get all covariances, we'll look up the task-speicific ones
        covar_x = self.covar_module(x)
        # # Get the covariance for task i
        covar_i = self.task_covar_module(i)
        covar_xi = covar_x.mul(covar_i)
        return GaussianRandomVariable(mean_x, covar_xi)

Thanks for your help!

**Comment by Sabina321** [comment]
Hi again, 

This might be related to the fix suggested for the last thing I posted. It actually seems like I'm getting the error now with the example code as well.

**Comment by jacobrgardner** [comment]
I am not able to reproduce this easily on the latest version of master. In the example notebook, I changed the `IndexKernel` creation to `self.task_covar_module = IndexKernel(n_tasks=36, rank=1)`.

Have you pulled recently?

**Comment by Balandat** [comment]
Orthogonal to the question at hand, but using 36 tasks is probably pushing it. Either you need tons of data to estimate these correlations (then it becomes computationally challenging). Or you use less data and it will be hard to estimate the correlations between that many parameters. Note also that you're using a rank 1 approximation of a 32x32 correlation matrix, which seems problematic. If you do have enough data and can run this, you should think about putting an LKJCovariancePrior over the correlation matrix.

**Comment by Sabina321** [comment]
@jacobrgardner I just reinstalled. And I had changed that line. But do you not get that error when you run the example: 

https://github.com/cornellius-gp/gpytorch/blob/master/examples/03_Multitask_GP_Regression/Hadamard_Multitask_GP_Regression.ipynb


I think this is just happening after I made the changes in #285, is there any way they are related?

**Comment by gpleiss** [comment]
@Sabina321 @jacobrgardner @Balandat I have seen similar issues (related to batch MTGPs). I am working on a PR to address them

**Comment by Sabina321** [comment]
I just took out the changes from #285 and now the example is working again.

**Comment by Sabina321** [comment]
And the 36x36 case works as well. 

The code from #285 did fix that issue, however, so I don't want to throw out the baby with the bath water.

**Comment by gpleiss** [comment]
Sorry, do you mean you reverted 025f4cf ?

**Comment by Sabina321** [comment]
Yes. I reverted it and that fixed this problem.

**Comment by gpleiss** [comment]
@Sabina321 try now on master - it should work
