### ISSUE TITLE
Move LKJ priors into pytorch core (as distributions)

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#300]
These are generally useful, we should PR this into pytorch core. See https://pytorch.slack.com/archives/C879Y9Q8K/p1538155154000100

Will require implementing sampling functionality. This is Algorithm 3.2. from 
*D. Lewandowski, D. Kurowicka, and H. Joe. Generating random correlation matrices based on vines and extended onion method. Journal of Multivariate Analysis, 100(9):1989 – 2001, 2009. ISSN 0047-259X. doi: https://doi.org/10.1016/j.jmva.2009.04.008.*

**Comment by wjmaddox** [comment]
Closed by https://pytorch.org/docs/stable/_modules/torch/distributions/lkj_cholesky.html#LKJCholesky.
