### ISSUE TITLE
GridInterpolationKernel bug

### ISSUE THREAD

**Issue by sumitsk** [cornellius-gp/gpytorch#312]
Running the [KISSGP_Kronecker_Regression.ipynb](https://github.com/cornellius-gp/gpytorch/blob/alpha/examples/05_Scalable_GP_Regression_Multidimensional/KISSGP_Kronecker_Regression.ipynb) script throws this error: 
`AttributeError: 'Tensor' object has no attribute 'flip'`

The bug is associated with GridInterpolationKernel as other scripts with the same kernel throws the same error and when I replace it with simple RBF kernel, the script works just fine.

**Comment by jacobrgardner** [comment]
Is this on the very recent beta release a couple hours ago or on an older release on alpha?

**Comment by sumitsk** [comment]
This was on the alpha version. On the latest beta release, there is this bug while importing gpytorch:
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-8b7747befa0d> in <module>()
----> 1 import gpytorch

~/research/gpytorch/gpytorch/__init__.py in <module>()
      1 from __future__ import absolute_import, division, print_function, unicode_literals
      2 
----> 3 from . import (
      4     beta_features,
      5     distributions,

~/research/gpytorch/gpytorch/distributions/__init__.py in <module>()
      2 
      3 from .distribution import Distribution
----> 4 from .multivariate_normal import MultivariateNormal
      5 from .multitask_multivariate_normal import MultitaskMultivariateNormal
      6 

~/research/gpytorch/gpytorch/distributions/multivariate_normal.py in <module>()
      3 import torch
      4 from torch.distributions import MultivariateNormal as TMultivariateNormal
----> 5 from torch.distributions.utils import _standard_normal, lazy_property
      6 
      7 from ..lazy import LazyTensor, NonLazyTensor

ImportError: cannot import name '_standard_normal'
```

**Comment by Balandat** [comment]
@sumitsk this is likely b/c you're not using the most recent version of pytorch (gpytorch beta is developed against the pytorch 1.0 pre-release). You can find a recent tagged release here: https://github.com/pytorch/pytorch/releases/tag/v1.0rc1

**Comment by sumitsk** [comment]
@Balandat Yes you are right. I updated to pytorch 1.0 and everything seems fine so far!! Closing this issue now.
