### ISSUE TITLE
Preconditioning for SV-DKL is slow

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#320]
I'm just opening an issue so that we can track the fact that we are aware of this, but it seems that until PyTorch implements batch potrf (https://github.com/pytorch/pytorch/pull/11796/) using preconditioning for SV-DKL training is definitely not worth it. 

I've been running some speed tests, and it makes training about 5x slower in the example notebook (going from ~100ms per minibatch to ~600ms per minibatch).

I'm not sure there's a lot we can do on our end about this for now other than to recommend people not use preconditioning at training time.

**Comment by jacobrgardner** [comment]
Related: I've also verified that with preconditioning off, the bottleneck seems to remain to be the lack of batched small matrix eigenvalue solvers / access to a batched `syevj` call (see https://github.com/pytorch/pytorch/issues/10172).

**Comment by gpleiss** [comment]
I'll ping the issues, and maybe try taking a stab at them myself.

**Comment by gpleiss** [comment]
Let's see if this is now fixed by #388
