### ISSUE TITLE
SpectralMixtureKernel example typo

### ISSUE THREAD

**Issue by sumitsk** [cornellius-gp/gpytorch#321]
It seems that the example part in `spectral_mixture_kernel.py` file has been copied but not modified from the `rbf_kernel.py` file. See [here](https://github.com/cornellius-gp/gpytorch/blob/f17e2bfbf8311575b08b051bc8052613518fc647/gpytorch/kernels/spectral_mixture_kernel.py#L53-L53)

**Comment by gpleiss** [comment]
Oops thanks for the catch! I'll fix this example.
