### ISSUE TITLE
multitask predictive distribution

### ISSUE THREAD

**Issue by Sabina321** [cornellius-gp/gpytorch#326]
Hello, 

I was wondering if you could write out the predictive distribution for a new data point from task i, using the Kronecker product notebook? 

Do you follow the exact form of the[ paper you point to](https://papers.nips.cc/paper/3189-multi-task-gaussian-process-prediction.pdf)? Or is there another paper which fully specifies the mean and covariance when you predict for new data? 

Thanks!

**Comment by gpleiss** [comment]
Hi @Sabina321 - are you asking for the derivation? We follow exactly what is in equation (2) for the mean computations. The mean that we return is a matrix $[f_1, ..., f_t]$, where each row represents a data point and each column 1...t represents a task.

**Comment by Sabina321** [comment]
Hi Geoff, 

Thanks for responding. If you follow eqn 2 in the paper, that clarifies. I just wasn't sure if you followed that paper, or something else. So to confirm, if you predict for a single test point from one task it calculates inter-task similarities across the training data?

**Comment by gpleiss** [comment]
That is correct! All predictions take inter-task similarities into account.

With the Kronecker notebook, when you make predictions for a test point you will get predictions for every task (though if you only care about one task, you can index into the returned distribution).

If each data point is only associated with a single task, you should check out the Hadamard notebook. The derivation is very similar to what's in (2) - also taking inter-task similarities into account.

Hope this helps!

**Comment by gpleiss** [comment]
I'm going to close this issue for now, but feel free to reopen if you still have lingering questions!
