### ISSUE TITLE
GPR fails with LBFGS optimizer 

### ISSUE THREAD

**Issue by sumitsk** [cornellius-gp/gpytorch#348]
Running a simple 1D GP regression (RBF kernel) sporadically throws runtime error when using `LBFGS` optimizer. This happens when MLL loss suddenly increases by a big value.

**Comment by Balandat** [comment]
#371 added the ability to use less extreme parameter transforms such as `softplus`, which should help a lot in that regard. Can you test if that works for you?

**Comment by jacobrgardner** [comment]
Closing this because it should be fixed by recent stability improvements. That being said, we strongly recommend the use of @hjmshi's Implementation of LBFGS (linked to above) over the built in PyTorch one.
