### ISSUE TITLE
Use torch.cholesky instead of torch.potrf

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#349]
This was renamed in: https://github.com/pytorch/pytorch/pull/12699
We should update the call sites accordingly once this has made its way into a release.

**Comment by jacobrgardner** [comment]
While we're on the subject, we should rename `LazyTensor.log_det` to `LazyTensor.logdet` to maintain our mirror of the `torch.Tensor` interface.

**Comment by gpleiss** [comment]
This happened with #368, so closing.
