### ISSUE TITLE
SM kernel shared mixture weights

### ISSUE THREAD

**Issue by sumitsk** [cornellius-gp/gpytorch#350]
The mixture weights of spectral mixture kernels has size `batch_size x num_mixtures` unlike means and scales hyperparameters. Any particular reason behind sharing the weights across all the dimensions? The paper keeps separate weights, means and scales.

**Comment by jacobrgardner** [comment]
In the multidimensional SM kernel, multiple `d` dimensional Gaussians are mixed together (e.g. equation 12 of https://arxiv.org/pdf/1302.4245.pdf). Therefore, while the Gaussians themselves can have `d` variances, each Gaussian obviously only has one weight.
