### ISSUE TITLE
Transition from test/examples to testing Jupyter notebooks directly

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#358]
See comments in #356 . Having unit tests that make sure all of the basic models we think should function actually do is really nice, but it's getting too cumbersome to have happen every time we want to run unit tests locally.

The proposed solution is to use one of the frameworks that directly lets us test Jupyter notebooks. This also has the advantage of making sure our examples all still work.

**Comment by gpleiss** [comment]
This has been done for a while
