### ISSUE TITLE
Hadamard Multitask GP with KISS

### ISSUE THREAD

**Issue by akbari59** [cornellius-gp/gpytorch#360]
Hi
I want to implement a scalable Multitask GP where we learn one task per input. I used an approach like the Hadamard multi-task approach. However, I confused how to use GridInterpolationKernel and IndexKernel together? Any way to implement it?
Thanks,
Mohammad

**Comment by jacobrgardner** [comment]
If you follow the model here: https://github.com/cornellius-gp/gpytorch/blob/master/examples/03_Multitask_GP_Regression/Hadamard_Multitask_GP_Regression.ipynb

But instead of using
```python
self.covar_module = gpytorch.kernels.RBFKernel()
```
you do
```python
self.covar_module = gpytorch.kernels.GridInterpolationKernel(gpytorch.kernels.RBFKernel(), grid_size=100, num_dims=1)
```

Then everything should work the way you want

**Comment by akbari59** [comment]
Thanks :)
