### ISSUE TITLE
Make DiagLazyTensor work with any batch size

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#361]
Currently, `DiagLazyTensor` assumes either a vector or matrix as input. This has the following weird behavior:

```
> d1 = DiagLazyTensor(torch.ones(4))
> d1.ndimension(), d1.shape
2, (4, 4)

> d2 = DiagLazyTensor(torch.ones(3, 4))
> d2.ndimension(), d2.shape
3, (3, 4, 4)

> d3 = DiagLazyTensor(torch.ones(2, 3, 4))
> d3.ndimension(), d3.shape
2, (4, 4)
```
Given @gpleiss's previous work on supporting general batch shapes, I suggest we modify `DiagLazyTensor` to support input tensors of general shapes. The last dimension will be interpreted as the diagonal, and the previous dimensions as batches. That is, a `DiagLazyTensor(torch.ones(2, 3, 4))` would have 4 dimensions and a batch shape of `[2, 3]`. 

I need this for implementing Heteroskedastic Likelihoods for batched Multitask GPs.

**Comment by Balandat** [comment]
more generally, I suspect we could get rid of a lot of special casing also in other LazyTensor implementations by consistently using general batch shapes. E.g. here we'd have `batch_shape = base_lazy_tensor.shape[:-1]`

**Comment by jacobrgardner** [comment]
I'm in agreement with this change for sure, a DiagLazyTensor created with a 2 x 3 x 4 tensor should represent a 2 x 3 x 4 x 4 matrix.

Do our other LazyTensors already support multiple batch dimensions already? I remember @gpleiss working on this, but wasn't 100% sure whether it was fully done.

**Comment by jacobrgardner** [comment]
While we're on the subject of revamping `DiagLazyTensor`, we should also remove the checks in the custom `inv_matmul` and `inv_quad_log_det` that incorrectly prevent broadcasting:
https://github.com/cornellius-gp/gpytorch/blob/9829ed9bf3f7f039c5b2d8b1f994d774996666f5/gpytorch/lazy/diag_lazy_tensor.py#L97-L108

**Comment by Balandat** [comment]
Yeah it needs a good spring cleaning all around.

**Comment by gpleiss** [comment]
@jacobrgardner @Balandat - haha still haven't gotten around to getting other LazyTensors to work with multitbatch stuff. (Post CVPR...)

**Comment by Balandat** [comment]
Here's a draft PR: #362, input welcome.

**Comment by Balandat** [comment]
this was done in #362
