### ISSUE TITLE
DKL model fixed train size for test

### ISSUE THREAD

**Issue by h-jia** [cornellius-gp/gpytorch#366]
`invalid argument 0: Sizes of tensors must match except in dimension 1. Got 149 and 841 in dimension 0.` Here the 149 is the test data while the 841 is the training data.

What I am doing is to use a network to downsize the dimension of the input. Say, input 841\*60\*2 into 841*60 output. Where 841 and 149 are batches. It seems that the DKL model fixed the dimension into 841 when I do test. 

If I set the` batch_size` into 841 for training then the GP Kernal will be fixed into 841 and still cannot be tested under 149 batches.

Any suggestions in this case? Thanks~

**Comment by jacobrgardner** [comment]
Do you think you could give us a small example of your model that fails that you think should work, maybe just passing random data generated with `torch.randn` through it?
