### ISSUE TITLE
Make all LazyTensors work with any batch size

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#369]
#362 extended `DiagLazyTensor` to work with general batch sizes. We need to do the same for the KroneckerProductLazyTensor. This is required to make the new Heteroskedastic Likelihoods work correctly in the multi-batch multi-task case. 

Currently, the behavior is
```
T = NonLazyTensor(torch.rand(2, 3, 4))
KLT = KroneckerProductLazyTensor(T, T)
KLT.shape, KLT.evaluate().shape
# torch.Size([2, 9, 16]), torch.Size([2, 9, 16]) <- great
```

```
T = NonLazyTensor(torch.rand(1, 2, 3, 4))
KLT = KroneckerProductLazyTensor(T, T)
KLT.shape, KLT.evaluate().shape
# <- (torch.Size([9, 16]), torch.Size([9, 64])) <- not great
```

**Comment by Balandat** [comment]
@jacobrgardner, @gpleiss, how do you feel about broadcasting the batch sizes here? That is, you could do `KroneckerProductLazyTensor(T1, T2)` for Tensors `T1` and `T2` as long as `T1.shape[:-2]` and `T2.shape[:-2]` are broadcastable. This seems like reasonable behavior.

**Comment by gpleiss** [comment]
That seems super reasonable!

**Comment by gpleiss** [comment]
I'm going to make this a more general issue, about all LazyTensors supporting arbitrary batch dimensions. Expect a flurry of small PRs about this :)
