### ISSUE TITLE
Add unit tests for batch shapes and broadcasting

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#378]
(Related to #291, #361, etc, builds on work in #356 )

Our unit test coverage of basic batch mode functionality could be substantially improved. We should add basic shape unit tests for the following:

- [x] All kernels should accept `n x d` inputs and return `n x n` covariance matrices (or another appropriate shape that is kernel specific).
- [x] All kernels should accept `b x n x d` inputs and return `b x n x n` covariance matrices (or another appropriate shape).
- [ ] All models extending `gpytorch.models.GP` should be callable on  `n x d` inputs and return appropriately sized MultivariateNormal distributions (`(mu, Sigma) = (n, n x n)`).
- [ ] All models extending `gpytorch.models.GP` should be callable on  `b x n x d` inputs and return appropriately sized MultivariateNormal distributions (`(mu, Sigma) = (b x n, b x n x n)`).
- [ ] All models extending `gpytorch.models.GP` initialized with `n x d` training data (or inducing points) should be (repeatedly) callable on both `m x d` inputs and `b x m x d` inputs, returning MVN distributions with the appropriate sizes.
- [x] All `LazyTensors` should broadcast `matmul` calls in all situations that normal `torch.Tensors` do. This may require more work on the general goal of "`LazyTensors` support arbitrary batch shapes that @Balandat has been working on.

**Comment by gpleiss** [comment]
I can tackle this!

**Comment by Balandat** [comment]
Note also the related issue #384 (though they're sufficiently separate that I can take care of that)
