### ISSUE TITLE
Drop py2 support

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#385]
It looks like we haven't really been supporting py2 for a little while now, see https://github.com/cornellius-gp/gpytorch/pull/383#pullrequestreview-176066680

Let's formally drop support for it, put that into the readme, and update the code accordingly (get rid of `from future ...` imports, add `#!/usr/bin/env python3` to all files).

More controversial: If we feel ambitious and want to require >3.6, we could also start typing things....

**Comment by jacobrgardner** [comment]
I think if we are going to drop py2, then I am certainly also in favor of requiring py36 or higher since I'm not sure you can even install py34 anymore.

**Comment by Balandat** [comment]
Yeah I guess the ambitious referred to starting to type things :). We can do that organically step-by-step in new PRs though, no need to rush this.

**Comment by Balandat** [comment]
I guess the readme already stated py>=3.6 as a requirement...

**Comment by gpleiss** [comment]
CLosed by #387
