### ISSUE TITLE
More issues with batch mode in MTGPs

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#420]
I'm running into some more issues with (alleged) size incompatibilities when using batch mode for multitask GPs. In particular, 
- fitting a MTGP in batch mode fails outright
- fitting a MTPG in non-batch mode works, but evaluating that model in batch mode fails.

See [MTGP_batch_errors.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/2658985/MTGP_batch_errors.ipynb.txt)

@gpleiss, fixing these kind of issues properly without a ton of special casing relies on #369 -  can we prioritize this?

**Comment by gpleiss** [comment]
@Balandat - sure, I can try to get it done by the end of the week

**Comment by Balandat** [comment]
Closing this out in favor of #531
