### ISSUE TITLE
marginal likelihood discrepancy with gpflow for exact gp regression

### ISSUE THREAD

**Issue by hughsalimbeni** [cornellius-gp/gpytorch#421]
I'm looking at the basic exact regression example and getting discrepancy between gpflow and gpytorch in the marginal likelihood. The predictive distributions match, however, so I don't think it's an issue of hyperparameters. 

For example
```python
np.random.seed(0)
N = 20
Ns = 10
X = np.linspace(0, N, N).reshape(-1, 1)
Xs = np.linspace(0, N, Ns).reshape(-1, 1)
Y = np.random.randn(N, 1)

model_gpflow = gpflow.models.GPR(X, 
                                 Y,
                                 gpflow.kernels.RBF(1))


print('gpflow ML: {}'.format(model_gpflow.compute_log_likelihood()))
preds_gpflow = model_gpflow.predict_y(Xs)

print('gpflow pred mean: {}'.format(preds_gpflow[0].flatten()))

with torch.no_grad(), gpytorch.settings.max_cg_iterations(10000):

    class ExactGPModel(gpytorch.models.ExactGP):
        def __init__(self, train_x, train_y, likelihood):
            super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
            self.mean_module = gpytorch.means.ZeroMean()
            self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

        def forward(self, x):
            mean_x = self.mean_module(x)
            covar_x = self.covar_module(x)
            return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)


    model_gpytorch = ExactGPModel(torch.Tensor(X.flatten()),
                                 torch.Tensor(Y.flatten()),
                                 gpytorch.likelihoods.GaussianLikelihood())

    mll = gpytorch.mlls.ExactMarginalLogLikelihood(model_gpytorch.likelihood, model_gpytorch)
    output = model_gpytorch(torch.Tensor(X.flatten()))
    marginal_likelihood = mll(output, torch.Tensor(Y.flatten()))
    print('gpytorch ML {}'.format(torch.sum(marginal_likelihood)))
    
    model_gpytorch.eval()
    model_gpytorch.likelihood.eval()
    
    f_preds = model_gpytorch.likelihood(model_gpytorch(torch.Tensor(Xs.flatten())))
    
    print('gpytorch pred mean {}'.format(f_preds.mean))
```
returns
```
gpflow ML: -29.71134295080608
gpflow pred mean: [ 0.84703465  0.85736492  0.6959016   0.20702686  0.05754075  0.59123416
  0.29651992  0.38384497  0.27194487 -0.33804375]
gpytorch ML -1.5208690166473389
gpytorch pred mean tensor([ 0.8470,  0.8574,  0.6959,  0.2070,  0.0575,  0.5912,  0.2965,  0.3838,
         0.2719, -0.3380])
```
Also, the ML seems to be non-deterministic. On three runs I get -1.5357774496078491, -1.51754629611969 and -1.4996962547302246 (predictions are always the same, however). Is this the correct behaviour?

**Comment by hughsalimbeni** [comment]
Thanks for this. I included the factor of `N` and now I get agreement for 

```python
w1 = torch.no_grad()
w2 = gpytorch.settings.max_cg_iterations(100000)
w3 = gpytorch.settings.max_lanczos_quadrature_iterations(100000)
w4 = gpytorch.settings.num_trace_samples(100000)
w5 = gpytorch.settings.max_preconditioner_size(20)

with w1, w2, w3, w4, w5:
    ...
```

Just one more thing, though. I note though that if `w5 = gpytorch.settings.max_preconditioner_size(19)` then I observe a bias, which as . On four runs with `w1`-`w4` as above I get:

gpytorch ML -29.739524841308594
gpytorch ML -29.73921775817871
gpytorch ML -29.73922348022461
gpytorch ML -29.73902130126953

Is this to be expected?

**Comment by jacobrgardner** [comment]
The reason you get exact matching when `max_preconditioner_size` is 20 is because at that point you are using a rank 20 pivoted Cholesky decomposition of a 20x20 kernel matrix, which is an exact Cholesky decomposition up to permutation of the rows and columns. 

Thus, when Woodbury + matrix determinant lemma happens internally to get the “preconditioner” solve and log det, those values will in fact be what you’d get from running Cholesky directly, and CG should terminate instantly.

In general, I definitely wouldn’t recommend running with such large values in actual use case scenarios (although a rank 20 preconditioner is fine). As the size of the matrix increases, this will not only be slower but actually be detrimental to numerical performance.

**Comment by gpleiss** [comment]
It might also be possible that the GPFlow model and GPyTorch models are initialized with different hyperparameters. In GPyTorch, the lengthscale, outputscale, and Gaussian noise are all initialized as ln(2) (softplus(0)).
