### ISSUE TITLE
Using gpytorch for Bayesian inference

### ISSUE THREAD

**Issue by vallis** [cornellius-gp/gpytorch#435]
Hello developers, thanks so much for your work!

I'd like to experiment with gpytorch in a statistical inference setting, where I want to compute the GP marginal likelihood for the same data and many different covariance matrices (as chosen by a sampling algorithm that explores the hyperparameter posteriors).

I already have optimized code to prepare my (rather custom) covariance matrices, so for the moment I would concentrate in accelerating the log likelihood computation, which currently relies on Cholesky.

Can I do this with gpytorch?

Thanks!

**Comment by gpleiss** [comment]
Closing this for now, since it seems like your question was answered :)
