### ISSUE TITLE
torch.pdist for kernel computations only useable for small matrices

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#446]
See pytorch/pytorch#15511.

I committed 1ce7216 to temporarily cap the data size for which we will use pdist. Once the issue is resolved we can just revert that.

@gpleiss Let's maybe hold off on releasing `0.1.1` until that's sorted out?

**Comment by gpleiss** [comment]
Removing `pdist` for now. We can reopen this issue once the `pdist` bug is fixed.
