### ISSUE TITLE
Implement cholesky-based root_decomposition for lazy tensors

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#465]
The new `fast_computations(covar_root_decomposition=False)` setting allows to use `torch.cholesky` for computing root decompositions. Right now this lives in `LazyTensor`, so when calling this the full matrix has to be instantiated, except for a small number of lazies that overwrite `root_decomposition` (e.g. `DiagLazyTensor`).

For things like `BlockDiagLazyTensor` this is of course very inefficient. We should overwrite root_decomposition there, and if use batch Cholesky decomposition to compute the Cholesky decomposition of each sub-block, and stitch the results together in another `BlockDiagLazyTensor`.

**Comment by gpleiss** [comment]
Something that I've been thinking about recently: most of our public LazyTensor methods do lots of checking (i.e. `root_decomposition` determines whether or not to do a Cholesky-based root decomposition, `tranpsose` does argument checking, `__getitem__` adds extra indices when necessary, etc.)

I think moving forward we should make it a pattern where all of our public LazyTensor methods that do any sort of checking/casing should call an underscore'd version of the method. We've started this pattern a bit: (e.g. `__getitem__` calls `_getitem` after processing all the batch dimensions).

It might be good to have `_root_decomposition`, `_inv_quad_logdet`, etc.

**Comment by gpleiss** [comment]
@jacobrgardner ^^

**Comment by gpleiss** [comment]
@Balandat - I have a WIP on this that I want to merge in after the multi-batch LT stuff.

**Comment by gpleiss** [comment]
I think this has been in GpyTorch for a while now :) Closing
