### ISSUE TITLE
Implement BatchLazyTensor

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#468]
There is a `BatchRepeatLazyTensor`, but no `BatchLazyTensor` that would allow batching of a number of arbitrary `LazyTensor`s of the same size. 

I'd like to use this to set up a `BlockDiagLazyTensor` with a base_lazy_tensor that is a batch of `LazyTensor`s.

**Comment by KeAWang** [comment]
`CatLazyTensor` should allow arbitrary `LazyTensors` of the same size

**Comment by Balandat** [comment]
`CatLazyTensor` would work, but this will require being able to unsqueeze the individual LazyTensors...

**Comment by KeAWang** [comment]
Maybe we want to be able to stack the tensors along any new dimension besides the batch dimension. Then we could call it `StackedLazyTensor` which would be consistent with `torch.stack`

**Comment by Balandat** [comment]
That's a good idea, though I wonder how much that would complicate the implementation.

**Comment by gpleiss** [comment]
I'm working on a unsqueezing option right now as part of the batch mode PR. I'll try to get that component up soon. @Balandat

**Comment by Balandat** [comment]
Seems like we don't need after all this as we can use `CatLazyTensor` on unsqueezed Lazies.
