### ISSUE TITLE
Encountered nan in confidence bounds (variational inference)

### ISSUE THREAD

**Issue by Akella17** [cornellius-gp/gpytorch#475]
Simple 3D GP Regression using AbstractVariationalGP module and AdditiveGridInterpolationVariationalStrategy:
Please find the ipython notebook in this link: https://drive.google.com/file/d/1o8IkdLq_nrUF51IFdKyI64ZBLICk5is3/view?usp=sharing
I wanted to know the reason why this might be occurring, and would also like to know if it would have any implications on the overall performance of GP regression (i.e. the kernel means and covariances have been finite and prolonged training seems to fit them better to the training data despite nans in confidence bounds).

**Comment by gpleiss** [comment]
Thanks for the example notebook. I'm investigating this now. Two things to note:

1) The reason you're seeing NaNs is because the returned variances are negative (which shouldn't be happening).
2) We are refactoring variational inference, so this issue might go away soon.

**Comment by gpleiss** [comment]
I think I've encountered the bug. There should be a fix soon.

**Comment by Akella17** [comment]
First, even I thought that the reason for NaNs is the negatives in the covariance matrix. But I have encountered negative values in covariance even when the confidence predictions were finite. Secondly, even the  ```param_transform = softplus``` has no impact on the negatives in the covariance matrix.

Would I run into the same issue using Spectral Mixture Kernel as it can model negative covariances?

**Comment by gpleiss** [comment]
Negative *covariances* are reasonable. Negative *variances* (the diagonal of the covariance) shouldn't occur.

This appears to be a bug in some of our internals, so switching to the spectral mixture kernel probably won't make a difference. It should be fixed once I patch the code.

**Comment by gpleiss** [comment]
This is fixed in 061fa4f . Let me know if the problem persists.
