### ISSUE TITLE
Recursively initialize Module parameters

### ISSUE THREAD

**Issue by KeAWang** [cornellius-gp/gpytorch#476]
Say I have an `ExactGP` called `gp`. It would be great if I could just do `gp.initialize(kwargs)` and all the parameters will be initialized recursively. This would allow us to put all the initialization values in one place. 

Note that it would have to raise an error if there were a parameter name collision.

**Comment by Balandat** [comment]
should be relatively straightforward to do if you pass in the full name (`module.submodule.submodule.parameter_name`)

**Comment by gpleiss** [comment]
I think the module.submodule.parameter_name pattern seems good
