### ISSUE TITLE
Option to not compute the variances

### ISSUE THREAD

**Issue by KeAWang** [cornellius-gp/gpytorch#477]
In some use cases, we only ever care about the predictive mean of the GP. It would save a lot of computation time if there were an option to not compute the variances. Currently we have a hack to turn off variance computation at https://github.com/cornellius-gp/gpytorch/commit/34912d666664c34b0e420dafbd7b424445a52bc0

Maybe we can un-hackify this and make it an option for all GPs.

**Comment by gpleiss** [comment]
We could make a LazyTensor for the variance computations, but it might be a little complicated.

**Comment by gpleiss** [comment]
Alternatively, we could have a feature flag (or option passed into ExactGP models) that returns a ZeroLazyTensor for the multivariate normal and skips covariance computation.
