### ISSUE TITLE
RuntimeError: Trying to backward through the graph a second time

### ISSUE THREAD

**Issue by Akella17** [cornellius-gp/gpytorch#485]
This error occurred on master when running a single optimizer step which is strange because when I ran the same code using (v0.1.1) release, there wasn't any error message.

```RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time```

Details: I am using SV-DKL (AbstractVariationalGP module, AdditiveGridInterpolationVariationalStrategy)

**Comment by Balandat** [comment]
What exactly did you run? Do you have code to reproduce?

**Comment by Akella17** [comment]
You can find the ipython notebook (and two supporting files) in this link: https://drive.google.com/drive/folders/1Kg5bdL_kE6rv6It0mr8pxAIvsL6fa7cS?usp=sharing

**Comment by gpleiss** [comment]
You can solve this by setting `retain_graph=True` on the first backwards call you make (see the PyTorch docs: https://pytorch.org/docs/stable/autograd.html#torch.autograd.backward)

For the future, it is easier for us if you can provide a more slimmed-down example that isolates the problem :)

**Comment by fonnesbeck** [comment]
I'm getting this error as well, but adding the argument to `backward` does not eliminate the issue (see line 7 in the traceback):

```
<ipython-input-34-a4d25b282d98> in train()
      5         output = model(X)
      6         loss = -mll(output, y)
----> 7         loss.backward(retain_graph=True)
      8         if not i % 100:
      9             print('Iter %d/%d - Loss: %.3f' % (i + 1, training_iterations, loss.item()))

/opt/anaconda3/lib/python3.7/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    105                 products. Defaults to ``False``.
    106         """
--> 107         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    108 
    109     def register_hook(self, hook):

/opt/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     91     Variable._execution_engine.run_backward(
     92         tensors, grad_tensors, retain_graph, create_graph,
---> 93         allow_unreachable=True)  # allow_unreachable flag
     94 
     95 

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
```
