### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by Lazloo** [cornellius-gp/gpytorch#512]
I get the following error when I try to install version 0.2.0:

> pip install gpytorch
> Collecting gpytorch
>   Using cached https://files.pythonhosted.org/packages/04/d4/da5ab9bd53cd72b34c9dc260a0e8ed4ee551cbddabee9ea9ac1ffcdfcebe/gpytorch-0.2.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\Lazloo\AppData\Local\Temp\pip-install-4w4dnw48\gpytorch\setup.py", line 40, in <module>
>         with open("requirements.txt", "r") as f:
>     FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\Lazloo\AppData\Local\Temp\pip-install-4w4dnw48\gpytorch\

**Comment by gpleiss** [comment]
Uh oh. Let me take a look at this.

**Comment by gpleiss** [comment]
v0.2.1 is up. This should install.
