### ISSUE TITLE
Where is `fast_pred_var` moving?

### ISSUE THREAD

**Issue by neighthan** [cornellius-gp/gpytorch#524]
I received the following warning when using `fast_pred_var`:

```
/cluster/nhunt/anaconda/envs/bayes_opt/lib/python3.7/site-packages/gpytorch/beta_features.py:17:
DeprecationWarning: `gpytorch.settings.fast_pred_var` has moved to `gpytorch.settings.fast_pred_var`.
```

It seems that I'm being warned that `fast_pred_var` has moved to its current location. Was there a typo in the warning about how we should be using this setting now?

```bash
$ pip list | grep gpytorch
gpytorch           0.2.1
```

**Comment by jacobrgardner** [comment]
@gpleiss This seems like a problem with the autogenerated warning.

@neighthan `fast_pred_var` now lives in `settings` -- the location you are seeing it at is the correct location.

**Comment by gpleiss** [comment]
Hmmm yeah I'll see if I can figure out what the issue is. The correct context manager is `with gpytorch.settings.fast_pred_var`

(It used to be either `gpytorch.beta_features.fast_pred_var` an also as `gpytorch.fast_pred_var`, but these are both deprecated)

**Comment by neighthan** [comment]
Ah, I see - I was actually using `gpytorch.fast_pred_var`, so it was correct that I received the deprecation warning. It was just confusing that in the warning it said `gpytorch.settings.fast_pred_var` both times (instead of `gpytorch.fast_pred_var` has moved to `gpytorch.settings.fast_pred_var` or `gpytorch.beta_features.fast_pred_var` has moved to `gpytorch.settings.fast_pred_var`, depending on how it was accessed). Thanks for clearing that up! I'll leave the issue open for fixing the warning message.
