### ISSUE TITLE
An issue with active dims for linearkernel

### ISSUE THREAD

**Issue by Duane321** [cornellius-gp/gpytorch#526]
Hi,

So I think we may have an issue similar to #523 . Basically, the linear kernel seems to be ignoring the active_dims argument. This time it is without being wrapped in the ScaleKernel.

I'll show you what I mean. I'll do this by sampling functions from the prior for each of two cases.

```
import numpy as np
import pandas as pd
import gpytorch
import torch
torch.set_default_tensor_type('torch.DoubleTensor')

import matplotlib.pyplot as plt
%matplotlib inline
```

We'll start by making some fake data.

```
X = torch.from_numpy(np.array([range(100)]).reshape(-1,1)).to(torch.float64)

linear_kernel = gpytorch.kernels.LinearKernel(num_dimensions=1)
```

This function below is useful for visualizing samples from the prior.

```
def plot_samples_from_kernel(kernel, X, num_samples=1, figsize=(15, 8)):
    """
    Given

        kernel: a kernel component from a GP model (e.g. model.covar_module.kernel[0])
        X: a torch tensor with our X features for our GP.

    This function will sample and plot functions implied by this kernel and those features.
    """

    cov = kernel.forward(X, X).evaluate().detach().numpy()[0, :, :]

    samples = np.random.multivariate_normal([0] * X.shape[0], cov, num_samples)
    fig, ax = plt.subplots(figsize=figsize)

    for i in range(samples.shape[0]):
        ax.plot(samples[i, :], color='blue', alpha=.6)

    ax.grid(True)
    for which in ['top', 'right']:
        ax.spines[which].set_visible(False)

    return fig, ax
```

Now let's check out those samples:

```
plot_samples_from_kernel(linear_kernel, X, num_samples=4, figsize=(8, 5))
```

![image](https://user-images.githubusercontent.com/19956442/53198629-ac7fbb80-35d1-11e9-9b3e-5fd21e4a432a.png)

Looks good! Ok, now let's add 1 feature to X and tell the linear kernel to ignore it.

```
x = np.array([range(100)]).reshape(-1,1)
X = np.concatenate([x,np.mod(x,7)],axis=1)
X = torch.from_numpy(X).to(torch.float64)

linear_kernel = gpytorch.kernels.LinearKernel(num_dimensions=1, active_dims=[0])
plot_samples_from_kernel(linear_kernel, X, num_samples=4, figsize=(8, 5))
```

![image](https://user-images.githubusercontent.com/19956442/53198684-d89b3c80-35d1-11e9-9d1b-e73693de13d4.png)

We can tell by those kinks that the LinearKernel is not ignoring the modular feature.

Side bar, how do you in house avoid using active_dims? Is there another way to get the same effect?

Thanks again for this awesome package :)

**Comment by jacobrgardner** [comment]
Can you replace
```python
cov = kernel.forward(X, X).evaluate().detach().numpy()[0, :, :]
```
with

```python
cov = kernel(X, X).evaluate().detach().numpy()[0, :, :]
```

**Comment by Duane321** [comment]
Oh I see! Ok very good. Thanks! 

Closing.
