### ISSUE TITLE
Posterior evaluation with floating point precision can cause severe degradation

### ISSUE THREAD

**Issue by sdaulton** [cornellius-gp/gpytorch#534]
I have encountered an issue where posterior evaluation using float point precision results in drastically different results than using double precision. I fit a simple 1-d GP using double precision and evaluated the posterior using double precision, which shows a good model fit. Converting the model to floating point precision and evaluating the posterior again, shows a poor model fit. Converting the model back to double precision and evaluating again (now with rounded hyperparameters) shows good model fit.

Repro:
[gpytorch_floating_point_posterior_evaluation_issue.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/2896226/gpytorch_floating_point_posterior_evaluation_issue.ipynb.txt)

**Comment by sdaulton** [comment]
cc @Balandat

**Comment by sdaulton** [comment]
This happens with both cuda and cpu

**Comment by Balandat** [comment]
Note that using naive squared distances of the form 
```
@torch.jit.script_method
def _jit_sq_dist(self, x1, x2, diag, x1_eq_x2):
    res = (x1.unsqueeze(-2) - x2.unsqueeze(-3)).pow_(2).sum(-1)
    return self._postprocess(res)
```
here https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/kernels/kernel.py#L23-L42 mitigates this issue slightly (though not fully). So it appears that this is a numerical issue with evaluating the kernel matrix.

**Comment by jacobrgardner** [comment]
Closed via #536

**Comment by sdaulton** [comment]
I am still encountering numerical issues using floats on this example. Double precision is fine. 
Repro:
[gpytorch_float_issue_posterior_evaluation.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/2937781/gpytorch_float_issue_posterior_evaluation.ipynb.txt)

**Comment by jacobrgardner** [comment]
Should be fixed again!
