### ISSUE TITLE
Need example notebook using fast_pred_samples

### ISSUE THREAD

**Issue by KeAWang** [cornellius-gp/gpytorch#542]
It seems like the `fast_pred_samples` setting is unimplemented: https://github.com/cornellius-gp/gpytorch/blob/04adb4a14ffffed1c1ff18010ffd64dac69bf264/gpytorch/settings.py#L204

When will this be implemented? Also we should probably have an example notebook or test case where we use `fast_pred_samples`.

**Comment by gpleiss** [comment]
It is implemented. It's just using the default settings (by default, not on). But you're right - it probably should be demoed in an example notebook.
