### ISSUE TITLE
Converting sklearn GP code to GPyTorch

### ISSUE THREAD

**Issue by neighthan** [cornellius-gp/gpytorch#549]
This is a request for documentation. I'm trying to convert some GP code using sklearn to equivalent code in GPyTorch. Here is a simple example of some sklearn code:

```python
import numpy as np
import matplotlib.pyplot as plt
from sklearn.gaussian_process.kernels import Matern
from sklearn.gaussian_process import GaussianProcessRegressor

gp = GaussianProcessRegressor(
    kernel=Matern(nu=2.5, length_scale=1),
    alpha=0,
    optimizer=None
)

train_x = np.linspace(-2, 2, 20).reshape(-1 ,1)
train_y = np.sin(train_x).ravel()

gp.fit(train_x, train_y)
test_x = np.linspace(-4, 4, 200).reshape(-1, 1)
test_y = np.sin(test_x).ravel()
pred_y = gp.predict(test_x)

plt.plot(test_x, test_y, label="True")
plt.plot(test_x, pred_y, label="Pred")
plt.scatter(train_x, train_y, label="Obs")
plt.legend()
```

This generates the following figure:

![image](https://user-images.githubusercontent.com/12573501/53822070-f6a35e00-3f3c-11e9-8436-0b9c22910152.png)

And here is my attempt to replicate this in GPyTorch:

```python
import numpy as np
import matplotlib.pyplot as plt
import torch
import gpytorch

# this is the model from the GP regression tutorial but with
# the mean/kernel changed to try to match those above

class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ZeroMean()
        matern = gpytorch.kernels.MaternKernel(
            nu=2.5,
            lengthscale_prior=gpytorch.priors.NormalPrior(1, .001)
        )
        self.covar_module = matern

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

train_x = np.linspace(-2, 2, 20).reshape(-1 ,1)
train_y = np.sin(train_x).ravel()

likelihood = gpytorch.likelihoods.GaussianLikelihood(
    noise_prior=gpytorch.priors.GammaPrior(.001, 100)
)
model = ExactGPModel(
    torch.tensor(train_x).float(),
    torch.tensor(train_y).float(),
    likelihood
)
model.eval()

test_x = np.linspace(-4, 4, 200).reshape(-1, 1)
test_y = np.sin(test_x).ravel()
pred_y = model(torch.tensor(test_x).float()).loc.detach().numpy()

plt.plot(test_x, test_y, label="True")
plt.plot(test_x, pred_y, label="Pred")
plt.scatter(x, y, label="Obs")
plt.legend()
```

which gives this figure:

![image](https://user-images.githubusercontent.com/12573501/53822139-2a7e8380-3f3d-11e9-8b14-f49960474e70.png)

In both cases, I'm trying to explicitly set the hyperparameters of the GP; I don't do any training. In sklearn, I set the lengthscale of the Matern kernel explicitly; in GPyTorch, there's a prior for this, but I set it so that it is very concentrated around the same value (1). I set the additive noise (alpha) in sklearn to zero, and I try to set the Gaussian noise in GPyTorch to ~0 by using a Gamma prior which is very concentrated near 0. However, it still seems like the GPyTorch GP thinks there is more noise in the data. Is there something else that I need to do to tell GPyTorch that this data is noise-free? Or am I doing something else wrong to try to replicate the sklearn example? I think it might be nice somewhere in the docs to have an example like this - a GP in sklearn and one in GPyTorch to show how to get equivalent behavior.

**Comment by jacobrgardner** [comment]
@neighthan I think the issue you are running in to is that sklearn includes an outputscale (see https://scikit-learn.org/stable/modules/gaussian_process.html#basic-kernels), where as GPyTorch does not by default.

If you do:
```python
matern = gpytorch.kernels.ScaleKernel(gpytorch.kernels.MaternKernel(...))
```
That will probably fix the issue. The reason we don't use outputscales by default is because when you use product kernels (e.g., `k(x,x') = k_1(x, x') * k_2(x, x')`, multiplying the outputscales together produces a single outputscale, leading to unnecessary parameters.

**Comment by jacobrgardner** [comment]
Sorry one more thing: the prior is also a completely optional argument. If you don't want the lengthscale prior, just don't pass it to the kernel. In some sense, the minimal kernel definition for Matern you could use here would be:
```python
matern = ScaleKernel(MaternKernel(nu=2.5))
```

**Comment by neighthan** [comment]
If I don't use a prior for the lengthscale, what is done by default? Is there a default prior or just a default value? The documentation also seems a bit conflicting; the function signature has the argument `lengthscale_prior` but the docstring has ```:attr:`log_lengthscale_prior` ``` in it.

I didn't know about the `initialize` function - thanks for that! It looks like it works for the kernel's hyperparameters as well. I'll try using that instead of priors and matching the output variance (I was aware that GPyTorch didn't use this, but I didn't realize that sklearn does) and then see if I can get things to match.

**Comment by neighthan** [comment]
By using `matern.initialize(lengthscale=1)` and `likelihood.initialize(noise=1e-4)` I am able to get the same results as in sklearn (at least, up to errors in how well I can compare the figures visually) even without using a scale kernel, which I'll still look into. This works, but now I wonder - what was wrong with my priors before? Were those not essentially equivalent to setting the values that I just set at initialize?

For reference, here's code that can easily switch between using priors and using `initialize`. I even made the priors more strongly concentrated around the values to which I initialize, but it doesn't seem to make a difference.

```python
import numpy as np
import matplotlib.pyplot as plt
import torch
import gpytorch

use_priors = True

class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ZeroMean()
        if use_priors:
            matern = gpytorch.kernels.MaternKernel(
                nu=2.5,
                lengthscale_prior=gpytorch.priors.NormalPrior(1, .00001)
            )
        else:
            matern = gpytorch.kernels.MaternKernel(nu=2.5)
            matern.initialize(lengthscale=1)
        self.covar_module = matern

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

train_x = np.linspace(-2, 2, 20).reshape(-1 ,1)
train_y = np.sin(train_x).ravel()

if use_priors:
    likelihood = gpytorch.likelihoods.GaussianLikelihood(
        noise_prior=gpytorch.priors.GammaPrior(.0001, 1000)
    )
else:
    likelihood = gpytorch.likelihoods.GaussianLikelihood()
    likelihood.initialize(noise=1e-4)

model = ExactGPModel(
    torch.tensor(train_x).float(),
    torch.tensor(train_y).float(),
    likelihood
)
model.eval()

test_x = np.linspace(-4, 4, 200).reshape(-1, 1)
test_y = np.sin(test_x).ravel()
pred_y = model(torch.tensor(test_x).float()).loc.detach().numpy()

plt.plot(test_x, test_y, label="True")
plt.plot(test_x, pred_y, label="Pred")
plt.scatter(x, y, label="Obs")
plt.legend()
```

If I have `use_priors = False` then I get

![image](https://user-images.githubusercontent.com/12573501/53829567-679f4180-3f4e-11e9-98ef-b0ba2611d5a3.png)

With `use_priors = True` I get (about the same as before)

![image](https://user-images.githubusercontent.com/12573501/53829592-7685f400-3f4e-11e9-8307-0bb291ba824b.png)

**Comment by neighthan** [comment]
From going through sklearn's [source code] for the Matern kernel, it appears that they set $\sigma^2 = \gamma = 1$, which is why I didn't need to add the scale kernel in order to get the same results.

[source code]: https://github.com/scikit-learn/scikit-learn/blob/7b136e9/sklearn/gaussian_process/kernels.py#L1348

**Comment by neighthan** [comment]
I also get errors / crazy results if I make the noise value too small. E.g. with `likelihood.initialize(noise=1e-7)` I get

![image](https://user-images.githubusercontent.com/12573501/53830506-99b1a300-3f50-11e9-9581-739c6e1ae279.png)

and with `likelihood.initialize(noise=1e-8)` I get an error:

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-180-621bceae47d1> in <module>
     45 test_x = np.linspace(-4, 4, 200).reshape(-1, 1)
     46 test_y = np.sin(test_x).ravel()
---> 47 pred_y = model(torch.tensor(test_x).float()).loc.detach().numpy()
     48 
     49 plt.plot(test_x, test_y, label="True")

~/.cache/pypoetry/virtualenvs/bayes-optim-py3.7/lib/python3.7/site-packages/gpytorch/models/exact_gp.py in __call__(self, *args, **kwargs)
    261             test_train_covar = full_covar[..., num_train:, :num_train]
    262 
--> 263             predictive_mean = self.prediction_strategy.exact_predictive_mean(test_mean, test_train_covar)
    264             predictive_covar = self.prediction_strategy.exact_predictive_covar(test_test_covar, test_train_covar)
    265 

~/.cache/pypoetry/virtualenvs/bayes-optim-py3.7/lib/python3.7/site-packages/gpytorch/models/exact_prediction_strategies.py in exact_predictive_mean(self, test_mean, test_train_covar)
    280             :obj:`torch.tensor`: The predictive posterior mean of the test points
    281         """
--> 282         precomputed_cache = self.mean_cache
    283 
    284         if self.train_train_covar.dim() == 3:

~/.cache/pypoetry/virtualenvs/bayes-optim-py3.7/lib/python3.7/site-packages/gpytorch/utils/memoize.py in g(self, *args, **kwargs)
     15         cache_name = name if name is not None else method
     16         if cache_name not in self._memoize_cache:
---> 17             self._memoize_cache[cache_name] = method(self, *args, **kwargs)
     18         return self._memoize_cache[cache_name]
     19 

~/.cache/pypoetry/virtualenvs/bayes-optim-py3.7/lib/python3.7/site-packages/gpytorch/models/exact_prediction_strategies.py in mean_cache(self)
    250         else:
    251             # Standard mode
--> 252             mean_cache = train_train_covar.inv_matmul(train_labels_offset)
    253 
    254         if settings.detach_test_caches.on():

~/.cache/pypoetry/virtualenvs/bayes-optim-py3.7/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py in inv_matmul(self, right_tensor, left_tensor)
    685         )
    686         if left_tensor is None:
--> 687             return func(right_tensor, *self.representation())
    688         else:
    689             return func(left_tensor, right_tensor, *self.representation())

~/.cache/pypoetry/virtualenvs/bayes-optim-py3.7/lib/python3.7/site-packages/gpytorch/functions/_inv_matmul.py in forward(self, *args)
     23 
     24         with torch.no_grad():
---> 25             self.preconditioner = lazy_tsr.detach()._inv_matmul_preconditioner()
     26 
     27         self.is_vector = False

~/.cache/pypoetry/virtualenvs/bayes-optim-py3.7/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py in _inv_matmul_preconditioner(self)
    331             function: a function on x which performs P^{-1}(x)
    332         """
--> 333         base_precond, _ = self._preconditioner()
    334 
    335         if base_precond is not None:

~/.cache/pypoetry/virtualenvs/bayes-optim-py3.7/lib/python3.7/site-packages/gpytorch/lazy/added_diag_lazy_tensor.py in _preconditioner(self)
     59                 )
     60                 return None, None
---> 61             self._woodbury_cache = pivoted_cholesky.woodbury_factor(self._piv_chol_self, self._diag_tensor.diag())
     62 
     63         # preconditioner

~/.cache/pypoetry/virtualenvs/bayes-optim-py3.7/lib/python3.7/site-packages/gpytorch/utils/pivoted_cholesky.py in woodbury_factor(low_rank_mat, shift)
    100     shifted_mat = shifted_mat + torch.eye(k, dtype=shifted_mat.dtype, device=shifted_mat.device)
    101 
--> 102     R = cholesky_solve(low_rank_mat, torch.cholesky(shifted_mat))
    103     return R
    104 

RuntimeError: Lapack Error in potrf : the leading minor of order 2 is not positive definite at /pytorch/aten/src/TH/generic/THTensorLapack.cpp:658
```

I assume this is related to #399 though the except error is different.

**Comment by jacobrgardner** [comment]
@neighthan Had a chance to actually run the code, and it was indeed just the noise initialization. Adding:
```python
# Ensure hyperparameters match sklearn hyperparameters
likelihood.initialize(noise=1e-4)
model.covar_module.initialize(lengthscale=1.)
```
After the likelihood and model are created yields:
![image](https://user-images.githubusercontent.com/4016393/53852482-08a1f280-3f77-11e9-8412-b446ead0411a.png)

The extremely low noise issue is expected behavior, as the kernel matrix becomes extremely ill conditioned with a noise value that small. sklearn gets around this by adding jitter to the covariance matrix, effectively enforcing a lower bound on the noise value. This is something we are likely to transition to doing, and is indeed related to #399, although during optimization a simple prior typically suffices.

Regarding the priors you set, they don't have any effect before you've optimized, because they effectively enter optimization as penalties.

Hope this helps!

**Comment by neighthan** [comment]
Ah, I see - I thought that if I set a prior, the default value used would be based on that. The initial values are independent of the priors then, and the only way to set them is through `.initialize`. Thanks for your help!

**Comment by Balandat** [comment]
@neighthan I have a todo for revamping parameter transforms that also touches on the priors. One idea there would be to initialize the parameters based on the priors - e.g. using the mean/mode, or by sampling from the priors.

**Comment by neighthan** [comment]
@Balandat I had thought the prior would make a difference, but I'm not sure what would be the best way to do this; perhaps that's why there is no effect right now. Maybe to preserve backwards-compatibility, there could be a flag that determines how the prior affects the parameter value? So that there is no effect by default (as now), and then this allows the user to explicitly specify whether they want the mean / mode / a sample. Otherwise, I think it's a bit hard to decide what to use from the prior. The mean would have been good for me, but if the mean has low probability density, that wouldn't make much sense.

**Comment by neighthan** [comment]
Okay, I thought this was resolved, but I'm still having ~the same issue when I use data from a different function: the `GPyTorch` GP won't fit exactly to the training data, even if I specify through `.initialize` that the noise is ~0. If I want the predictive means at the training points to be ~exactly the observed training labels, is there something else that I can do? Here's an example with a few points drawn from a different test function; I plot the correspondence between the predictive mean at the training points and the true values there.

```python
import torch
import gpytorch
from matplotlib import pyplot as plt

%matplotlib inline

train_x = torch.tensor([
    [0.9973],
    [2.5000],
    [0.5000],
    [0.7779],
    [0.7432],
    [1.4585],
    [0.6578],
    [0.8037],
    [1.2159],
    [0.7523],
    [0.7519]
])

train_y = torch.tensor([
    0.0428, -5.0625, -0.0625,
    0.4091, 0.6530, -0.3749,
    -0.7512, -0.0734, -0.1997,
    0.6590,  0.6600
])

# We will use the simplest form of GP model, exact inference
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ZeroMean()
        self.covar_module = gpytorch.kernels.MaternKernel(nu=2.5)
        self.covar_module.initialize(lengthscale=1)

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

# initialize likelihood and model
likelihood = gpytorch.likelihoods.GaussianLikelihood()
likelihood.initialize(noise=1e-4)
model = ExactGPModel(train_x, train_y, likelihood)
model.eval()

pred_y = likelihood(model(train_x)).loc.detach().numpy()
plt.scatter(pred_y, train_y.numpy(), label="GPyTorch")

from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern
gp = GaussianProcessRegressor(
    kernel=Matern(nu=2.5),
    optimizer=None
)
gp.fit(train_x.numpy(), train_y.numpy())
pred_y = gp.predict(train_x.numpy())
plt.scatter(pred_y, train_y.numpy(), label="sklearn")
plt.plot(train_y.numpy(), train_y.numpy(), label="Expected", zorder=0)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.legend()
```

![image](https://user-images.githubusercontent.com/12573501/53990004-47f64d80-40f5-11e9-9703-86ec04028516.png)

**Comment by jacobrgardner** [comment]
Consider that the predictive mean on the data points is `K_{XX}(K_{XX}+sI)^{-1}y`, which equals `y` only when either `s ->0` or `K_{XX} -> I` (and `s` is still mostly small). With this in mind, there are two ways to achieve perfect overfitting to a training set: (1) reduce the lengthscale, or (2) reduce the noise even further. 

When I run with a lengthscale of `1.` and a noise of `1e-6` in your most recent code, I get:
![image](https://user-images.githubusercontent.com/4016393/54001128-fc48a180-40fe-11e9-93d8-34edb0a16ce9.png)

Alternatively, when I run with a lengthscale of `1e-4` and a noise of `1e-4`, I also get:
![image](https://user-images.githubusercontent.com/4016393/54001142-0c608100-40ff-11e9-8deb-09187e6f531e.png)

However, if I run with a lengthscale of `1` and a noise of `1e-4`, I indeed get the same plot as you. This in some sense does a good pedagogical job of highlighting the relationship between the lengthscale and the noise :-)

**Comment by neighthan** [comment]
Ah, I see - I had been considering the amount of noise to be essentially 0, so that all training points should be fit to exactly, but because the lengthscale I was using was too large to allow the model to easily fit the given data, even that small amount of noise mattered. There also seem to be some recent commits that improve fitting in the very low noise regime. When I leave the lengthscale at 1 and set the noise to 1e-6 using gpytorch 0.2.1, I get

![image](https://user-images.githubusercontent.com/12573501/54003478-5dcd3800-4120-11e9-9efd-a6a062699173.png)

where the fit still isn't as good; changing the noise to 1e-7 makes things even worse, and 1e-8 gives errors. So it isn't really possible to fit the training data exactly in this example without adjusting the lengthscale in the current version. However, when I install from GitHub instead, I get 

![image](https://user-images.githubusercontent.com/12573501/54003407-23639b00-4120-11e9-8a59-1eab217e1427.png)

Thanks again for your help, explanation, and whatever recent commits made this easier!

**Comment by jacobrgardner** [comment]
Ah, yes that makes sense. Some recent commits to master will help the model automatically better adapt to the illconditioned setting, essentially by using more time to get better solves.

**Comment by cherepanovic** [comment]
> Consider that the predictive mean on the data points is `K_{XX}(K_{XX}+sI)^{-1}y`,

where is to find this formula in code?
