### ISSUE TITLE
Minor change in docs for settings.max_cg_iterations

### ISSUE THREAD

**Issue by harvineet** [cornellius-gp/gpytorch#555]
As per docs, default value of settings.max_cg_iterations is 20. However, in code it is set to 100.
https://github.com/cornellius-gp/gpytorch/blob/4e671371b1305bc4609475de9579a7535c11f481/gpytorch/settings.py#L284-L291

Apologies for nitpicking :-)

**Comment by gpleiss** [comment]
No worries! Thanks for the catch :)
Could you open up a PR?

**Comment by harvineet** [comment]
Sure.
