### ISSUE TITLE
Improved handling of parameter transforms and constraints

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#563]
The way parameter transformations are currently handled is somewhat ad-hoc. The `torch.distributions` module provides `Transforms` that can be used to do this in a more elegant way. 

In addition, there is currently no support for registering parameter constraints on the module level. This means that imposing possible constraints on the parameters during fitting (e.g. when using constrained optimization algorithms like L-BFGS-B for fitting) is cumbersome since everything has to be tracked manually. We can use the `torch.distributions.constraints` to register parameter constraints when instantiating the model, so that these constraints don't have to be manually tracked outside the models.

**Comment by jacobrgardner** [comment]
Just one thing to track for this issue: some of our `Transforms` will need to be different from PyTorch. Primarily, PyTorch uses `exp` to ensure positiveness, accomplish lower bounds etc, and we've found that `softplus` is significantly more stable. 

This is true to such an extent that we should override most of the transforms PyTorch defines by default, or else suggest that PyTorch adopt softplus for those transforms upstream.
