### ISSUE TITLE
Rename checkpoint_kernel

### ISSUE THREAD

**Issue by KeAWang** [cornellius-gp/gpytorch#570]
We should rename `gpytorch.beta_settings.checkpoint_kernel` to a name that contains "size" such as `kernel_partition_size` or `kernel_checkpoint_size`.

I would recommend calling it `kernel_parition_size` to be more intuitive and match the terminology in our recent paper

**Comment by gpleiss** [comment]
Closing because checkpointing is now deprecated (as of v1.11)
