### ISSUE TITLE
from_independent_mvns does the wrong thing in batch mode

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#573]
The issue is that currently calling `BlockDiagLazyTensor` on `covar_blocks_lazy` results in a batched covariance matrix with wrong block ordering.

That is, if `mvn_a` and `mvn_b` are `k`-batched with covariance matrices `C_a1, ..., C_ak` and `C_b1, ..., C_bk`, respectively, then the 1st batch of the joint covariance matrix is 
```
   | C_a1 |   0  |
   | 0    | C_a2 |
```

instead of
```
   | C_a1 |   0  |
   | 0    | C_b1 |
```
etc. 

Not sure if there is an elegant way to fix this in the current setting. @gpleiss, #492 should make that straightforward, right?

**Comment by gpleiss** [comment]
Yes - this should be very easy with #492 . I'll make sure that it's fixed in that branch.

**Comment by gpleiss** [comment]
Just confirmed that on #492 that `from_independent_mvn` is doing the correct thing -- i.e. that you get 

```
   | C_a1 |   0  |
   | 0    | C_b1 |
```

for the first batch.

**Comment by Balandat** [comment]
Yep, I tested this as well with multiple batch dimensions. Thanks for the fix.
