### ISSUE TITLE
RuntimeError: expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by Akella17** [cornellius-gp/gpytorch#583]
I am not sure as to why this error might be occurring. My speculation for the cause of this problem is that creating the Multivariate Normal object (```actual_value```) somehow blocks the gradients to flow to ```value_pred_mean_clipped``` and ```value_preds_covar_batch```.

> value_pred_mean_clipped = value_preds_mean_batch + (values.mean - value_preds_mean_batch).clamp(-self.clip_param, self.clip_param)
value_losses = -self.mll(values, return_batch)
actual_value = gpytorch.distributions.MultivariateNormal(value_pred_mean_clipped, value_preds_covar_batch)
value_losses_clipped = -self.mll(actual_value,return_batch, -1)
value_loss = 0.5 * torch.max(value_losses, value_losses_clipped).mean()

Error message:

>  File "/home/ravitej/Desktop/a2c-ppo-acktr/a2c_ppo_acktr/algo/gp_ppo.py", line 121, in update
    (value_loss * self.value_loss_coef + action_loss - dist_entropy * self.entropy_coef).backward()
  File "/home/ravitej/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ravitej/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/ravitej/anaconda3/lib/python3.6/site-packages/gpytorch/functions/_inv_quad_log_det.py", line 192, in backward
    left_factors = torch.cat(left_factors_list, -1)
RuntimeError: expected a non-empty list of Tensors

In case you need any more information to solve this issue, please let me know

**Comment by jacobrgardner** [comment]
Could you provide example tensors of the correct size that are failing to work? E.g., a self contained small code snippet that produces the problem but likely shouldn't?

**Comment by Akella17** [comment]
I needed to clip the mean of the Multivariate Normal object before passing it through ```gpytorch.mlls.VariationalELBO```. For this, I created a new Multivariate Normal object (```actual_value```) with clipped mean and previous covariance matrix.

> value_pred_mean_clipped = value_preds_mean_batch + (values.mean - value_preds_mean_batch).clamp(-self.clip_param, self.clip_param)
value_losses = -self.mll(values, return_batch)
actual_value = gpytorch.distributions.MultivariateNormal(value_pred_mean_clipped, value_preds_covar_batch)
value_losses_clipped = -self.mll(actual_value,return_batch, -1)
value_loss = 0.5 * torch.max(value_losses, value_losses_clipped).mean()

**Comment by jacobrgardner** [comment]
No, I think this should be fine -- I am fairly certain PyTorch supports backpropagating through the `clamp` function.

**Comment by jacobrgardner** [comment]
When I was asking for self contained code I more meant code that doesn't depend on tensors that are defined elsewhere. It's somewhat difficult to debug otherwise because the problem is unlikely to be in the exact code snippet you put here. For example, the following code clamps the mean of a (presumably much simpler) variational model's output and works fine:
```python
class GPClassificationModel(AbstractVariationalGP):
    def __init__(self, train_x):
        variational_distribution = CholeskyVariationalDistribution(train_x.size(0))
        variational_strategy = VariationalStrategy(self, train_x, variational_distribution)
        super(GPClassificationModel, self).__init__(variational_strategy)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        latent_pred = gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
        return latent_pred


train_x = torch.randn(100, 1)
train_y = torch.randn(100)
    
# Initialize model and likelihood
model = GPClassificationModel(train_x)
likelihood = gpytorch.likelihoods.BernoulliLikelihood()

# Run with a clamped mean
mll = VariationalELBO(likelihood, model, num_data=100)
my_mvn = model(train_x)
my_mvn.loc = my_mvn.loc.clamp(-2, -1)
print(my_mvn.mean)
loss = -mll(my_mvn, train_y)
print(loss)
loss.backward()
```

**Comment by Akella17** [comment]
The error occurs in the following line,

> value_loss = 0.5 * torch.max(value_losses, value_losses_clipped).mean()

The ```backward()``` call works for both ```value_losses``` and ```value_losses_clipped```. However, when used with ```torch.max()``` it raises this error.

> File "/home/ravitej/Desktop/a2c-ppo-acktr/a2c_ppo_acktr/algo/gp_ppo.py", line 117, in update
    (value_loss * self.value_loss_coef + action_loss - dist_entropy * self.entropy_coef).backward()
  File "/home/ravitej/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ravitej/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/ravitej/anaconda3/lib/python3.6/site-packages/gpytorch/functions/_inv_quad_log_det.py", line 192, in backward
    left_factors = torch.cat(left_factors_list, -1)
RuntimeError: expected a non-empty list of Tensors

**Comment by Akella17** [comment]
As per your request for a self-contained code, I am trying to isolate the issue further and provide you with a compact code snippet. Meanwhile, any intuition that you might have for the cause of this issue might be helpful.

**Comment by Akella17** [comment]
I am unable to isolate the issue and hence unable to provide a self-contained piece of code. Hence, I am sharing the project folder (https://drive.google.com/drive/folders/1MbtBNpPInOMjl8Nlakhd9YUvtBujwsa6?usp=sharing). When you try to run the ```gp_main.py``` file, you will encounter the following error which originates at ```gp_ppo.py``` (line: 120). This error does not occur when you run the commented code in lines 121 or 122. This brings my focus to the ```torch.max()``` operation in line 113 (as both the arguments of torch.max() do not raise errors upon ```backward()``` call).

A little information about the project:
The project tries to make continuous RL more sample-efficient using Bayesian approaches. Every file with a prefix ```gp_``` in the filename is a Bayesian version of its counterpart in standard RL. In other words, while ```gp_main.py``` is a Bayesian PPO algorithm, ```main.py``` corresponds to the original PPO algorithm.

**Comment by Kravrolens** [comment]
I got this problem when I use custom dataset to train this model. And I found out that the number of images and labels are not equal, finally it works.
