### ISSUE TITLE
KISS-GP 

### ISSUE THREAD

**Issue by herwineric** [cornellius-gp/gpytorch#587]
Hello,

Thank you for a great implementation of GPs and it's methods!

I have a question about the local linear/cubic interpolation in the KISS-GP `GridInterpolationKernel` implementation. In the paper "_Kernel Interpolation for Scalable Structured Gaussian Processes (KISS-GP)_" it is mentioned that linear or cubic interpolation can be used. Which of these is implemented in the `GridInterpolationKernel`? I would like to know, since I am using your package for my MSc thesis.

Thank you!

**Comment by gpleiss** [comment]
It's using cubic interpolation.
