### ISSUE TITLE
Error in `psd_safe_cholesky` (when data has low noise?)

### ISSUE THREAD

**Issue by neighthan** [cornellius-gp/gpytorch#598]
It's possible to hit the [`return L`][return] line in `psd_safe_cholesky` without `L` being defined. This happens if `torch.cholesky` throws a `RuntimeError` for both `A` and `Aprime` and `"singular"` is not in the error message. Then the user just gets `UnboundLocalError: local variable 'L' referenced before assignment`, which isn't very helpful. I'm not actually sure what error I got that led to this, but perhaps it would be good to change

```python
if "singular" in e.args[0]:
    raise RuntimeError("Adding jitter of {} to the diagonal did not make A p.d.".format(jitter))
```

to

```python
if "singular" in e.args[0]:
    raise RuntimeError("Adding jitter of {} to the diagonal did not make A p.d.".format(jitter))
else:  # or skip the else, depending on your coding style
    raise
```

This should give the user a more useful error message at least. Or is there anything that would be better to do in this case?

[return]: https://github.com/cornellius-gp/gpytorch/blob/9a2fb2ef870bf66efc29775245b8ce6c624e45a5/gpytorch/utils/cholesky.py#L43

**Comment by Balandat** [comment]
Thanks for flagging. Passing to @gpleiss who has worked on Cholesky related stuff recently.

**Comment by gpleiss** [comment]
I've seen this error before. I think that this typically fails when there are NaNs, which isn't caught by our exception handling.

@neighthan - your solution would be good so that we can get better error messages, and try to pin-point the problem more closely.

**Comment by gpleiss** [comment]
Added that change in.
