### ISSUE TITLE
implementing custom kernel

### ISSUE THREAD

**Issue by Sabina321** [cornellius-gp/gpytorch#600]
Hi, 

I am trying to implement a certain simple kernel. I think the grid interpolation structure can help. However, there is one operation that doesn't seem to be working. I am trying to have a scale kernel where the scale parameter is a function of the variances of two other kernels. For example, I would like kernel_one = LinearKernel(), kernel_two = LinearKernel(), kernel_three = ScaleKernel() where the scale term is equal to kernel_one.variance*kernel_two.variance. Is it possible to have a parameter be a function of other parameters? Is there or will there be support to define custom kernels in a straightforward way? Also is giving a parameter value a SmoothedBoxPrior a guarantee that that value will stay in that box? 

Thanks for your help!

**Comment by jacobrgardner** [comment]
Hi @Sabina321 --

This should be no problem -- I would just learn the underlying variances and use their product in the kernel. Something like

```python
class MyScaleKernel(Kernel):
    def __init__(base_covar1, base_covar2, **kwargs):
        self.base_covar1 = base_covar1
        self.base_covar2 = base_covar2

    def forward(self, x1, x2, **kwargs):
        outputscale = self.base_covar1.variance * self.base_covar2.variance
        # Do stuff
```
You may not even want to bother defining a kernel for this. You could also accomplish this in the `forward` of your model directly by doing something like:
```python
def forward(self, x):
    ...
    covar_x = f(self.covar_module1, self.covar_module2, x)  # Do something to get the covariance matrix
    covar_x = covar_x * (self.covar_module1.variance * self.covar_module2.variance) # Now scale
    return MultivariateNormal(mean_x, covar_x)
```

With regards to your question about bounds: a SmoothedBoxPrior won't precisely guarantee the bounds, but it will come close. For hard bound constraints, I have a PR open right now (#596) that we hope to have in by the end of next week that will allow for explicit hard constraints.

**Comment by Sabina321** [comment]
Thank you for the reply! When I try the following in forward(): 

scale = self.base_covar1.variance * self.base_covar2.variance

covar_final = self.base_covar1(x)+self.base_covar2(x)+scale*self.base_covar3(x)

I get the error:  'mul(): argument 'other' (position 1) must be Tensor, not LazyEvaluatedKernelTensor'

**Comment by jacobrgardner** [comment]
Ah, sorry that's actually just an unfortunate consequence of not being able to extend Tensor directly :-(.

If you do `self.base_covar3(x) * scale` or `self.base_covar3(x).mul(scale)` instead of `scale*...` it will work.

**Comment by Sabina321** [comment]
Thanks, 

Thank you! I was still getting some errors but they are gone now, I think they had more to do with how I set up the grid. Would it be ok if I posted that later and asked if it is set up the most efficiently? I am trying to use your library to see some computational time saving but I'm not sure if it is best set up...

**Comment by jacobrgardner** [comment]
@Sabina321 Sure -- maybe open a new issue when you have your efficiency question ready!

**Comment by Sabina321** [comment]
Hi again, it actually looks like I'm getting this error:

expand(torch.FloatTensor{[1]}, size=[]): the number of sizes provided (0) must be greater or equal to the number of dimensions in the tensor (1).

**Comment by gpleiss** [comment]
@Sabina321 - what version of gpytorch are you currently using?

**Comment by Sabina321** [comment]
Hi @gpleiss I'm using version 0.2.1.

**Comment by gpleiss** [comment]
Sorry for the slow reply. This might be fixed on gpytorch master. Could you install gpytorch master and see if it's fixed? (See the instructions on the readme).

**Comment by Sabina321** [comment]
No problem, thank you for all of your help! 

It didn't seem to fix it. Now I'm using version 0.2.1. 

However, I'm now just writing the kernel from scratch and it seems to be ok to just have the operations there instead of as a composition of three kernels. But here is the code anyway. 

Everything works until I add that scale term where covarx is set. 



    class ExactGPModel(gpytorch.models.ExactGP):
        def __init__(self, train_x, train_y, likelihood):
            super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
       
            self.mean_module = gpytorch.means.ConstantMean()
   
            self.covar_module_one = GridInterpolationKernel(LinearKernel(4,variance_prior=gpytorch.priors.SmoothedBoxPrior(a=0,b=10000000,sigma=1)),\
                                                        grid_size=10, active_dims=[0], num_dims=1)
            self.covar_module_two = GridInterpolationKernel(LinearKernel(4,variance_prior=gpytorch.priors.SmoothedBoxPrior(a=0,b=10000000,sigma=1)), \
                                                        grid_size=10, active_dims=[1], num_dims=1)
        

        
            self.covar_module_three = GridInterpolationKernel(LinearKernel(4,variance_prior=gpytorch.priors.SmoothedBoxPrior(a=-1,b=1,sigma=1)), grid_size=10, active_dims=[2,3], \
                                                          num_dims=2)
        
    def forward(self, x):
    
        mean_x = self.mean_module(x)
        
        scale = self.covar_module_one.base_kernel.variance**.5*self.covar_module_two.base_kernel.variance**.5
       
        covarx = self.covar_module_one.base_kernel(x) + self.covar_module_two.base_kernel(x) + self.covar_module_three.base_kernel(x)*self.scale
      
        return gpytorch.distributions.MultivariateNormal(mean_x, covarx)`

**Comment by gpleiss** [comment]
So I'm not sure if this is the issue that you're running into or not, but unfortunately `GridInterpolationKernel` does not work with `LinearKernel`. (Sorry for not catching this sooner!)

Grid interpolation is designed to work with kernels that are "stationary" (where the covariance function only depends on the distance between two points.) The Linear kernel is not a stationary kernel. See http://proceedings.mlr.press/v37/wilson15.pdf for more info.

I would try implementing your model without wrapping everything with GridInterpolationKernel. LinearKernel is extremely efficient on its own (it's O(nd) rather than O(n^2)).
