### ISSUE TITLE
Piecewise polynomial kernel

### ISSUE THREAD

**Issue by datashinobi** [cornellius-gp/gpytorch#607]
I am under the impression that gpytorch does not provide a PP kernel, can you please confirm?

Thanks in advance

**Comment by gpleiss** [comment]
We don't have one currently, but it should be fairly easy to implement. See the kernel documentation: https://gpytorch.readthedocs.io/en/latest/kernels.html#kernel

**Comment by RSid8** [comment]
@gpleiss are you still interested in having this implemented? I can do this by the end of the week. You can assign the task to me

**Comment by gpleiss** [comment]
Hi @RSid8 that would be great! See the [docs on implementing a custom kernel](https://docs.gpytorch.ai/en/stable/examples/00_Basic_Usage/Implementing_a_custom_Kernel.html) for a good starting point.

**Comment by gpleiss** [comment]
Closed by #1738
