### ISSUE TITLE
RuntimeError: expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by Akella17** [cornellius-gp/gpytorch#608]
I am attaching a self-contained code of an issue I have been facing when I pass two **mll loss** through a ```torch.max()``` function.

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import gpytorch
from gpytorch.models import AbstractVariationalGP
from gpytorch.variational import CholeskyVariationalDistribution, VariationalStrategy

class GPClassificationModel(AbstractVariationalGP):
    def __init__(self, train_x):
        variational_distribution = CholeskyVariationalDistribution(train_x.size(0))
        variational_strategy = VariationalStrategy(self, train_x, variational_distribution)
        super(GPClassificationModel, self).__init__(variational_strategy)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        latent_pred = gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
        return latent_pred


train_x = torch.randn(100, 1)
train_y = torch.randn(100)
train_x_1 = torch.randn(100, 1)
    
# Initialize model and likelihood
model = GPClassificationModel(train_x)
likelihood = gpytorch.likelihoods.BernoulliLikelihood()

# Run with a clamped mean
mll = gpytorch.mlls.VariationalELBO(likelihood, model, num_data=100)
my_mvn = model(train_x)
my_mvn_mean = my_mvn.mean.clamp(-2, -1)
my_mvn_1 = model(train_x_1)
my_mvn_cov_1 = my_mvn_1.covariance_matrix
my_mvn_comb = gpytorch.distributions.MultivariateNormal(my_mvn_mean, my_mvn_cov_1)
print(my_mvn_comb.mean)
loss_1 = -mll(my_mvn_comb, train_y)
loss_2 = -mll(my_mvn_comb, train_y)
loss =  torch.max(loss_1, loss_2)
print(loss)
loss.backward()
```
Error message:

> Traceback (most recent call last):
  File "gp.py", line 44, in <module>
    loss.backward()
  File "/home/ravitej/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ravitej/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/ravitej/anaconda3/lib/python3.6/site-packages/gpytorch/functions/_inv_quad_log_det.py", line 192, in backward
    left_factors = torch.cat(left_factors_list, -1)
RuntimeError: expected a non-empty list of Tensors

**Comment by gpleiss** [comment]
Thanks for the self-contained issue. I think the problem is that - by using `torch.max` - one of the mll's is not getting any gradients.

mlls aren't typically used in this way. Can you explain what you're trying to accomplish?

**Comment by Akella17** [comment]
I don't think that is the problem though, because I am able to run the backward call through either of the mll inputs of the ```torch.max``` function. Could you be more specific as to why one of the mlls in not receiving any gradients (in the self-contained code above)?

I am supposed to choose the maximum of original loss and clipped loss as my final loss (clipping the value loss is a way to stabilize training in RL settings).

**Comment by jacobrgardner** [comment]
@gpleiss I also ran in to this issue when trying to backprop through only a KL divergence, because it seems like somehow we are calling `InvQuadLogDetBackward` if we call forward on it *regardless* of whether it is used to compute the final output.

Converting to the new pytorch function style (#603) seems to have fixed this problem entirely for me, so hopefully merging that in will just fix this.

**Comment by Akella17** [comment]
Yeah, this fixes the error :p.

Also, when using ```gpytorch.mlls.VariationalELBO```, can I get the output as a ```batch_size``` sized vector instead of a scalar overall loss over the input batch of data.

Also, does ```GPyTorch``` have any predefined **mll** for finding the loss between the output and target ```gpytorch.distributions.MultivariateNormal``` objects instead of an output ```gpytorch.distributions.MultivariateNormal``` object and a tensor of target values.

**Comment by jacobrgardner** [comment]
I suppose if you wanted a loss between two multivariate normals you could e.g. do something like `torch.distributions.kl.kl_divergence` between them?

**Comment by Akella17** [comment]
That seems like a possibility but would ```backward()``` through a KL_divergence without any mll loss optimize the GP layer (not just the hyperparameters of the GP but the Bayesian optimization of its mean and covariance matrix)?

**Comment by jacobrgardner** [comment]
I think the behavior of training through a KL divergence would depend on whether you are computing the KL divergence between two `q(u)` distributions or two `q(f)` distributions. Either way, it's kind of a strange thing to do -- you probably want to think about exactly what it is you want to minimize rather than making guesses about what the loss should be.

**Comment by Akella17** [comment]
I am trying to use SVI+DKL model as my **critic** (deep Q network). To train this network, the traditional approach is to reduce the L1 distance between the predicted and target Q values as follows:

> a2 = self.target_actor.forward(s2).detach()
next_val = torch.squeeze(self.target_critic.forward(s2, a2).detach())
y_expected = r1 + GAMMA*next_val
y_predicted = torch.squeeze(self.critic.forward(s1, a1))
loss_critic = F.smooth_l1_loss(y_predicted, y_expected)

As the modified critic now outputs a ```gpytorch.distributions.MultivariateNormal``` for Q value predictions, I modified the code as follows,

> a2 = self.target_actor.forward(s2).detach()    
next_val = torch.squeeze(self.target_critic.forward(s2, a2).mean.detach())
y_expected = r1 + GAMMA*next_val
y_predicted = self.critic.forward(s1, a1)
#loss_critic = F.smooth_l1_loss(y_predicted, y_expected)
loss_critic = -self.mll(y_predicted, y_expected)

**Comment by gpleiss** [comment]
The correct approach here would be to sample a value from `next_val`.
`next_val = self.target_critic.forward(s2, a2).rsample()`.

This gives you an unbiased estimate of the marginal probability. As far as I know, there is no exact way to otherwise compute the expected log probability in closed form.
