### ISSUE TITLE
GP learning not happening in RL settings

### ISSUE THREAD

**Issue by Akella17** [cornellius-gp/gpytorch#611]
While the critic network seems to learn the function when trained in a supervised learning fashion on synthetic data, the overall actor-critic network struggles to learn a meaningful policy even for simple gym environments such as Pendulum-v0.

I am sharing a simple example of the DDPG algorithm implemented in two versions, ```Actor_Critic.ipynb``` (actor and critic are neural networks) and ```GP-AC.ipynb``` (critic consists of SVI+DKL model with additive structure). While ```Actor_Critic.ipynb``` learns a good policy within 100 updates, the ```GP-AC.ipynb``` does not perform considerably better than the initial random policy even after 600+ updates. ```Actor_Critic.ipynb``` and ```GP-AC.ipynb``` are near similar pieces of code, with the only difference being the last linear layer of the former is replaced by a GP regression layer in the later.

https://drive.google.com/drive/folders/1ioE_T6MS-YVgLKNG8aLeKbgOERwUx2NT?usp=sharing

**Comment by gpleiss** [comment]
It may very well be the case that DKL is not suited to your problem.
One thing to try: can you try training GP-AC, but initializing the feature extractor weights to be those learned by the Actor_Critic network?
