### ISSUE TITLE
marginalization of hyperparameters via MCMC sampling?

### ISSUE THREAD

**Issue by shalijiang** [cornellius-gp/gpytorch#622]
Thanks for the awesome package! I was wondering if it supports marginalization of GP hyperparameters yet?

**Comment by gpleiss** [comment]
This is something that we're definitely thinking about! At the moment, we don't have any wrappers that handle the MCMC for you. That being said, it should be possible to write your own sampling code, or perhaps to integrate with Pyro and use there sampling code.

What we currently do support: we have batch GPs, and each GP can use a different set of hyperparameters. So once you have a set of hypers that are selected via sampling, you can then perform inference on all GP samples simultaneously.

As far as having direct-package support for MCMC sampling - this is priority for us, so expect to see something in the future!

**Comment by shalijiang** [comment]
Hey Geoff, thank you for your reply! It sounds doable to write my own sampling and then use batch GP! 
I was just playing with your package to do some BO experiments. BTW, are you currently developing BO on top of gpytorch?

**Comment by eytan** [comment]
Yes.

**Comment by shalijiang** [comment]
cool! any timeline for the BO package to be released? can't wait to try it out!

**Comment by gpleiss** [comment]
@shalijiang - it was just released yesterday :)
https://ai.facebook.com/blog/open-sourcing-ax-and-botorch-new-ai-tools-for-adaptive-experimentation/

**Comment by gpleiss** [comment]
This is now ready to go with #918 !
