### ISSUE TITLE
SGPR outputs constant value

### ISSUE THREAD

**Issue by adamhaber** [cornellius-gp/gpytorch#623]
Hi,

I'm trying to use GPyTorch to solve a large-scale regression problem. I'm getting reasonable results with simpler methods and want to see if I can improve them with GPs. 

I have two datasets, one in which the input tesnor's shape is (500000,12) and the output is (500000,); the other dataset's input size is ~ (500000,90). I've followed the SGPR notebook example and got sensible results for the first, simpler problem; however, in the second problem I keep getting a constant prediction on the test set (despite a decrease in loss during training). Is this a known problem? I'm very new to GPs and would appreciate any references/tutorials that might be relevant.

**Comment by jacobrgardner** [comment]
Hi,

It's going to be a little tricky to diagnose without access to the data ourselves. It's possible you are using too few inducing points for a dataset of that dimensionality, or too smooth a kernel (like RBF).

I'd try more inducing points, a less smooth kernel like Matern or a deep kernel, or possibly using variational methods like a deep GP.

**Comment by jacobrgardner** [comment]
In general, a constant predictor usually occurs in GP regression when the underlying data looks too nonsmooth for your choice of model, so the training procedure learns to treat all of the variation in the data as noise -- your final model probably has a fairly long lengthscale for the kernel and possibly a fairly high noise value for the likelihood.

**Comment by adamhaber** [comment]
Thanks @jacobrgardner  for the detailed response! I've tried switching the kernel to Matern, and to follow the SVDKL example, but still got the same constant prediction. Increasing the number of inducing points raised the following exception (when I reached ~1500 points):

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-60-2b00b3bb0c2f> in <module>
      1 # See dkl_mnist.ipynb for explanation of this flag
      2 with gpytorch.settings.use_toeplitz(True):
----> 3     train(10)

<ipython-input-59-774c5e9e0f6e> in train(training_iterations)
      7         # Calc loss and backprop derivatives
      8         loss = -mll(output, train_y)
----> 9         loss.backward()
     10         print('Iter %d/%d - Loss: %.3f' % (i + 1, training_iterations, loss.item()))
     11         optimizer.step()

~\AppData\Local\conda\conda\envs\cvxpy\lib\site-packages\torch\tensor.py in backward(self, gradient, retain_graph, create_graph)
    100                 products. Defaults to ``False``.
    101         """
--> 102         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    103 
    104     def register_hook(self, hook):

~\AppData\Local\conda\conda\envs\cvxpy\lib\site-packages\torch\autograd\__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     88     Variable._execution_engine.run_backward(
     89         tensors, grad_tensors, retain_graph, create_graph,
---> 90         allow_unreachable=True)  # allow_unreachable flag
     91 
     92 

RuntimeError: CUDA error: invalid configuration argument
```

About the data itself - I'm happy to share it, if it helps (it's a subset of ~10000 rows due to GitHub size limits; I can send a DB link if the full dataset is needed):
[sample from larger dataset.zip](https://github.com/cornellius-gp/gpytorch/files/3057485/sample.from.larger.dataset.zip)
[sample from smaller dataset.zip](https://github.com/cornellius-gp/gpytorch/files/3057490/sample.from.smaller.dataset.zip)

**Comment by gpleiss** [comment]
It may very well be the case that SGPR is not the right method for the dataset that you have. You have two sources of modeling decisions: the kernel choice, and the type of approximation.

When debugging GP performance, it can be useful to run your model on a subset of the data, and use an exact GP. This way, you won't have to worry about the model approximation affecting your results. You can choose the correct kernel this way (or get a better sense as to whether or not a GP is the right model for your problem).

After you have a reasonable idea as to what kernels work, then you can choose the best approximate model (SGPR, SVGP, KISSGP + DKL, etc.)

Hope this helps!

**Comment by tmpethick** [comment]
This does seem to be an actual issue. If we learn the hyperparameters with a GP on a subset `N=1000` of the natural sound dataset (taken from https://github.com/kd383/GPML_SLD/tree/master/demo/sound) we get

<img width="294" alt="Screenshot 2019-07-02 at 10 18 37" src="https://user-images.githubusercontent.com/544312/60496497-398afd80-9cb3-11e9-92d0-cb90b7ed19aa.png">

where top is training examples and bottom is predictions with the following hyperparameters:

```
outputscale: 0.0003
lengthscale: 10.46
noise: 0.0015
```

Fitting a SGPR on the same `N=1000` points even when using "too" many inducing points `M=5000` we get the following prediction:

<img width="277" alt="Screenshot 2019-07-02 at 10 18 45" src="https://user-images.githubusercontent.com/544312/60496804-d8175e80-9cb3-11e9-966a-4a03a8c49eb7.png">

**Comment by ginward** [comment]
i am experiencing similar issues - SGPR gives same prediction values.

**Comment by ginward** [comment]
> In general, a constant predictor usually occurs in GP regression when the underlying data looks too nonsmooth for your choice of model, so the training procedure learns to treat all of the variation in the data as noise -- your final model probably has a fairly long lengthscale for the kernel and possibly a fairly high noise value for the likelihood.

It seems that tuning down the lengthscale or reducing likelihood noise and increasing signal noise doesn't resolve the constant prediction issues for SPGR either. On the contrary, exact GP does not predict same values on the same dataset.
