### ISSUE TITLE
[Question] KISS-GP w/ LOVE time performance

### ISSUE THREAD

**Issue by Raikao** [cornellius-gp/gpytorch#628]
Hi,

First, the library is really amazing!

Let me know if I have assumed something wrong. I am following the paper "Constant-TimePredictiveDistributionsforGaussianProcesses".

I'm trying the test the performance time of the GP with KISS-GP w/ LOVE, in inference (pre-computation) and prediction. In order to compare with the classical GP (cholesky decomposition), I want to calculate and store the linear system (K+ \sigma^2 I) , which in the classic is O(n^3) with cholesky decomposition, and in KISS-GP w/ LOVE is supposed to be O(kn+knlogn) with grid points=m=n. 

After calculating the linear system, the prediction mean should be O(n) in the classical and O(1) in KISS-GP, and the variance O(n^2) for classical and O(k) for KISS-GP w/ LOVE.

However, in GPyTorch the covariance matrix is stored as a lazy tensor which apparently is much more efficient, but then I don't know how to get this O(1), O(k) for prediction that I should get with KISS-GP w/ LOVE.

Is there a way that I could do that linear system pre-computation?
Thanks!

**Comment by Raikao** [comment]
Thanks for the reply!

What I'm trying to do is to replicate this table in the paper "Constant-Time Predictive Distributions for Gaussian Processes". 

![image](https://user-images.githubusercontent.com/19425393/55864568-0b4ac580-5b7d-11e9-94b8-6476267c244b.png)

I don't need to replicate the part of drawing samples, I'm more interested in calculating the computational time of the mean, but it should be O(1), after pre-computation as in KISS-GP.

But if the code for LOVE is only existing in the prediction strategies, then I won't be able to do the pre-computation stage, am I right?

Thanks!

**Comment by jacobrgardner** [comment]
You can easily get an approximation of the pre computation time by looking at the time taken for the first prediction call. This will include the time required to compute the mean cache as well, but is off by at most 2x.

The second time you do `model(test_x)` in the `fast_pred_var` context will be the time excluding the cache computation.

**Comment by Raikao** [comment]
That works like a charm! 

Thank you so much!
