### ISSUE TITLE
[Bug] Negative variances when using fast_pred_var()

### ISSUE THREAD

**Issue by danielrjiang** [cornellius-gp/gpytorch#635]
# 🐛 Bug

Seeing negative variances when using fast_pred_var(). Seems to be related to cache-ing: goes away when caches are cleared by using .train().eval(). In addition, when evaluating the variance at some set of points test_x and the evaluating again at a single point in test_x, they may not match.

## To reproduce

See attached notebook and the comments there.

** Stack trace/error message **
```
tensor([ 1.0139e+00,  8.5046e-02,  8.5050e-02,  5.4592e-01,  8.5045e-02,
         1.1338e+00,  2.0938e+00,  2.3304e+00,  2.3283e+00,  9.9273e-01,
         9.6964e-01, -2.7103e+00, -1.7627e+02, -4.9231e+01, -9.5254e-01,
         6.7344e-01,  1.1548e+00,  8.4972e-02,  1.1811e+00,  2.1131e+00])
```

## Expected Behavior

Variances that are positive and match when evaluated in different ways.

## System information

**Please complete the following information:**
- gpytorch 0.2.1
- PyTorch 1.0.0a0
- Linux release 7.5.1804

cc: @Balandat 
[negative_variance.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/3065928/negative_variance.ipynb.txt)

**Comment by jacobrgardner** [comment]
Was this actually on 0.2.1, as you say? If so, I'd like to see this reproduced on master, because we've fixed a lot of these issues in even the past few weeks, nevermind since December.

**Comment by Balandat** [comment]
Pretty sure @danielrjiang was testing this on gpytorch master. Either way, I was able to repro this on gpytorch master.

**Comment by danielrjiang** [comment]
Yes, it was on gpytorch master.

**Comment by danielrjiang** [comment]
Tested this again on the multi-batch PR and the issue has disappeared!

**Comment by Balandat** [comment]
Great. Must have been some weird caching thing that got solved inadvertently...
