### ISSUE TITLE
[Docs] Dimensional Reduction/Regression with different dimensions

### ISSUE THREAD

**Issue by SaoYan** [cornellius-gp/gpytorch#637]
I wonder how to do regression the input and target are of different dimensions?

Another relative question is: how to do dimension reduction using gpytorch?

From existing examples, I only find demos where the dimension of the target (output data, or the mean) is the same as the input.

**Comment by gpleiss** [comment]
The input and target are often different dimensions: typically the target is only single-dimensional (e.g. you only have one output per input). If you have multi-output data, use one of the multitask models. See the response here: https://github.com/cornellius-gp/gpytorch/issues/641

Are you talking about dimensionality reduction with latent variable GPs? This is not a feature we've implemented yet.
