### ISSUE TITLE
[Bug] ScaleKernel shape issue when evaluating independent batch GP on multi-batch test points

### ISSUE THREAD

**Issue by sdaulton** [cornellius-gp/gpytorch#639]
# 🐛 Bug

Outputscales in ScaleKernel are not expanded properly for when evaluating a batch mode (`b`) GP with independent hyperparameters for each batch on a multi-batch set of test points (`b' x b x n x d`) .

## To reproduce

[Simple_GP_Regression_outputscale_batch_issue.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/3070978/Simple_GP_Regression_outputscale_batch_issue.ipynb.txt)

**Comment by jacobrgardner** [comment]
Is this on #627?

**Comment by sdaulton** [comment]
Yes. Sorry, I did not realize that PR was still open. I'll close this and move this to a comment on that PR
