### ISSUE TITLE
Issue regarding the Dimensionality of train_y

### ISSUE THREAD

**Issue by the-darklord** [cornellius-gp/gpytorch#641]
With the naive implementation of GPs, one can do multiple output regression. 
My question is: are there any GP classes in gpytorch which can handle multiple regression with dim(train_y) >1?

**Comment by jacobrgardner** [comment]
There are many many example notebooks of doing this, both with and without ways of encoding correlations between the outputs:

- [Batch mode GPs](https://github.com/cornellius-gp/gpytorch/blob/master/examples/01_Simple_GP_Regression/Simple_Batch_Mode_GP_Regression.ipynb) support training multiple independent GPs for each function. This could be extended to encode correlations by mixing the functions at the end with a weight matrix. We are currently working on an implementation of GPRNs for the package that make the weight matrix location dependent.
- [Multitask GPs](https://github.com/cornellius-gp/gpytorch/tree/master/examples/03_Multitask_GP_Regression) are something we have a folder of 3 examples for that use various kernels to incorporate function correlations.
- [Deep GPs](https://github.com/cornellius-gp/gpytorch/blob/deep_gp_wip/examples/12_Deep_Gaussian_Processes/Deep_Gaussian_Processes.ipynb) are currently a work in progress (#564) that support multiple output dimensions.

**Comment by the-darklord** [comment]
Thanks 👍
