### ISSUE TITLE
Flaky unit test in BaseLikelihoodTestCase

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#646]
The random matrix constructed [here](https://github.com/cornellius-gp/gpytorch/blob/3bb10d37d51d79d23f535b9e6b1ddbabbf5c85d8/test/likelihoods/_base_likelihood_test_case.py#L21-L22) will occasionally cause a failure in instantiating the MVN with an error of the sort
```
RuntimeError: cholesky_cpu: For batch 3: U(5,5) is zero, singular U
```
which results in a flaky test. We should just add some small value to the diagonal.

**Comment by gpleiss** [comment]
Looks like @jacobrgardner took care of this :)
