### ISSUE TITLE
Implementing a new kernel which has different kernel computation for inputs and inducing points

### ISSUE THREAD

**Issue by jyhnnhyj** [cornellius-gp/gpytorch#649]
I'm adding a new kernel which has a different computation for X (input) and Z (inducing points).
Assume `K_uu` is the kernel function for the inducing inputs (e.g. `z1` and `z2`) and `K_ff` in the kernel function for the inputs (e.g. `x1` and `x2`). In my implementation, I'm extending the `Kernel` class and implementing my own `forward` function. Inputs to this function are `x1` and `x2` - now I need to distinguish inside this function whether the inputs belong to `X` or `Z` so that I compute and return the correct `K` there, essentially one of `K_uu`, `K_ff`, `K_uf` or `K_uf`
In RBF for example, all of these quantities are the same - so there is no distinction between normal data points and inducing data points, everything is much simpler there - in my case, I'm not sure how to proceed...
Is there an easy way of identifying if `x1` and `x2` belong to normal data points or inducing data points in the `forward` function of a kernel?
Ideally I need something like this pseudo code:
```
    def forward(self, x1, x2, diag=False, **params):
        if x1 & x2 both belong to input points:
            return kff(x1, x2)
        elif x1 & x2 both belong to inducing points:
            return kuu(x1, x2)
        elif x1 belongs to input points and x2 belongs to inducing points:
            return kfu(x1, x2)
        else:
            return kuf(x1, x2)
```

(I can implement a hacky version of this to store and index all `X` values and then do some sort of lookup here - but that does't seem very elegant and seems really hacky)

Any suggestions is really appreciated!

**Comment by jacobrgardner** [comment]
My recommendation would be to follow along the patterns we use in other inducing point methods, e.g. `InducingPointKernel` (our implementation of SGPR) directly registers inducing points: https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/kernels/inducing_point_kernel.py

This kernel is potentially a little more complicated because `forward` is broken out in to a few helper methods, but the main idea is that inducing points are registered to the kernel when you initialize it. This is the pattern that I would strongly recommend you follow if it is at all usable by you.

If it isn't, I will note that `forward` of Kernel takes arbitrary `**params`. Therefore, if you define:
```python
def forward(self, x1, x2, diag=False, inducing_points=None, **params)
```
Then you can do something like:
```python
covar = ScaleKernel(YourKernel(RBFKernel()))
covar(x1, x2, inducing_points=x_uu)
```
and the inducing points will make their way to the right place.

**Comment by jyhnnhyj** [comment]
thanks for the quick reply - so my scenario is to use stochastic variational inference for GP classification with my new kernel
I checked `KISSGP_Classification_1D.ipynb` notebook where the `InducingPointKernel` is not used and RBF is directly used there. I also checked `SGPR_Example_CUDA.ipynb` where `ExactGP` model is used and the kernel is wrapped inside the `InducingPointKernel`
I am a bit puzzled on how should I proceed here - to wrap my kernel inside an `InducingPointKernel` and subclass `ExactGP` or implement this class `AbstractVariationalGP` and use my kernel directly there - or both? In my case, GP should be approximated, since it's a classification task and I want to use SVI so that it can be scaled to large datasets

**Comment by jacobrgardner** [comment]
@jyhnnhyj Ah, thanks for the clarification.

Handling inducing points in the SVI case is quite different than the exact case, because the fundamental object you need to learn when doing VI is the distribution over the inducing points' function values. To do this, you will want to be extending `AbstractVariationalGP`, and if you have a custom inducing point method there are two basic classes you may need to extend:

- `VariationalDistribution` and its subclasses define the *parametric form* of the distribution `q(u)`. For example, `CholeskyVariationalDistribution` says we parameterize `q(u) ~ N(m, LL')` by `m` and `L`.
- `VariationalStrategy` and its subclasses define how we compute the integral `q(f) = \int p(f|u)q(u)du`. 

An `AbstractVariationalGP` is a GP that instantiates one of each of these, and defines `forward` to produce the prior `p(f|x)`.

In these objects the way we handle getting covariances like you mention is to concatenate the data:
```python
covar_mat = my_covar(torch.cat([inducing_points, data_points]))  # Lazily evaluates
```
The reason this is efficient is because **in GPyTorch, kernels are lazily evaluated** (e.g., that call will return a `LazyEvaluatedKernelTensor`. Thus, no kernel computations are done until you actually use the result in some computation or explicitly ask for it. E.g., the following are all efficient:
```python
covar_mat = my_covar(torch.cat([inducing_points, data_points]))  # So far, no work has actually been done
k_ff = covar_mat[num_inducing:, num_inducing:].evaluate_kernel()
k_ff_vec = covar_mat[num_inducing:, num_inducing:].matmul(...)  # Calling things like matmul will automatically evaluate the kernel.
K_uf = covar_mat[:num_inducing, num_inducing:].evaluate_kernel()
```

See here for an example of us doing this in the package:
https://github.com/cornellius-gp/gpytorch/blob/6b3f0548a38c85d200775a0f4c98f18028817d9e/gpytorch/variational/variational_strategy.py#L120-L122

**Comment by jacobrgardner** [comment]
If your goal is just to special case what the kernel does for each of the `k_ff, k_uf, k_uu` cases then I would do something like:
```python
class MyKernel(Kernel):
    """
    Pass in variational_strategy.inducing_points as inducing_points. This way, as the inducing
    point locations change as you do SVI, the inducing points in this kernel module automatically get
    updated.
    """
    def __init__(self, data_data_kernel, data_induc_kernel, induc_induc_kernel, inducing_points):
        # Register each of these to the class
        ... 

    def forward(self, x1, x2, diag=False, **params):
        if torch.equal(x1, self.inducing_points) and torch.equal(x2, self.inducing_points):
            # Do k_uu thing
        elif torch.equal(x1, self.inducing_points):
            # Do k_uf thing
        elif torch.equal(x2, self.inducing_points):
            # Do k_fu thing
        else:
            # Do k_ff thing
```
And then use our default variational strategy / variational distribution (see any of our SVI tutorials).

**Comment by jyhnnhyj** [comment]
Thanks so much for the detailed responses. I'll try these suggestions and update this thread.
Appreciate your help :)
Your detailed explanations clarified many ambiguities that I had in using GPyTorch

**Comment by jyhnnhyj** [comment]
another question, more inline with best practices type question
my kernel is some sort of integral kernel and I have upper and lower bound values. 
for example 1 dimensional X would be represented with two-dimensions (for upper and lower bound) - my current implementation sort of works and this is how I represent X:
```
x = np.array([[1., 2.], [3., 4.], [5, 6]])
```
so the above has shape of `(3, 2)` but indeed it is 1D
then when I moved to 2D data, it requires 4D for bounds and then I decided to reshape my data to be like (for the same 1D data above):
```
x = np.array([[[1., 2.]], [[3., 4.]], [[5, 6]]])
```
which has shape of `(3, 1, 2)` - so far all is good and I don't have those extra dimensions. Then when I plug my kernel it fails in different places, such as `distributions/multivariate_normal.py` when using the covariance matrix
```
RuntimeError: LazyTensor (size=torch.Size([16, 1, 1])) cannot be multiplied with right-hand-side Tensor (size=torch.Size([16, 16, 1])).
```
(16 is the data points count, in case)

so my question is what's the pragmatic way of dealing with this type of input? should be I use my hacky version of having 2x dimensions or how can I work my case work in the reshaped form?

**Comment by jacobrgardner** [comment]
@jyhnnhyj One example pattern you could use to handle inputs that have different semantic meanings is to follow the pattern in https://github.com/cornellius-gp/gpytorch/blob/master/examples/03_Multitask_GP_Regression/Hadamard_Multitask_GP_Regression.ipynb

where we define a GP model that takes two arguments to forward instead of one. In that specific case the args are `x` and `i`, but you could easily for example have `lb` and `ub` or something.

Is this roughly what you are looking for?

**Comment by jyhnnhyj** [comment]
Thanks @jacobrgardner , yes, need to think how inducing points can be added and what happens there...
regarding my very first question of how to distinguish between the actual data points and inducing points, I don't have a good solution yet. So based on the suggestions, I changed my model to something like this:
```
class VarGPModel(AbstractVariationalGP):
    def __init__(self, train_x, inducing_points):
        variational_distribution = CholeskyVariationalDistribution(inducing_points.size(0))
        variational_strategy = VariationalStrategy(model=self, inducing_points=inducing_points, variational_distribution=variational_distribution, learn_inducing_locations=True)
        super(VarGPModel, self).__init__(variational_strategy)
        self.mean_module = ConstantMean()
        self.covar_module = ScaleKernel(MyKernel(train_x=train_x, inducing_points=variational_strategy.inducing_points))
```
Where I explicitly pass the inducing points to the model and from there to the kernel. In my kernel now I have access to the inducing points and they get updated and etc. So in `forward` method of my kernel, I tried comparing `x1` and `x2` to the inducing points to decide which function to call (`kff`, `kuu`, `kfu`, `kuf`) - it kind of works, but the issue is that in some of the calls to the `forward` method during training, `x1` and `x2` are not the entire set of data points of the inducing inputs, but part of it. This is a toy example: I pass 16 data points and 5 inducing points to the model and here you can see what are the shapes of `x1` and `x2` during optimisation:
```
Counter:  1
x1.shape torch.Size([1, 5, 2]) x2.shape torch.Size([1, 5, 2])

Counter:  2
x1.shape torch.Size([1, 1, 2]) x2.shape torch.Size([1, 5, 2])

Counter:  3
x1.shape torch.Size([1, 1, 2]) x2.shape torch.Size([1, 5, 2])

Counter:  4
x1.shape torch.Size([1, 1, 2]) x2.shape torch.Size([1, 5, 2])

Counter:  5
x1.shape torch.Size([1, 1, 2]) x2.shape torch.Size([1, 5, 2])

Counter:  6
x1.shape torch.Size([1, 1, 2]) x2.shape torch.Size([1, 5, 2])

Counter:  7
x1.shape torch.Size([1, 16, 2]) x2.shape torch.Size([1, 5, 2])

Counter:  8
x1.shape torch.Size([1, 5, 2]) x2.shape torch.Size([1, 16, 2])

Counter:  9
x1.shape torch.Size([1, 16, 2]) x2.shape torch.Size([1, 16, 2])

Counter:  10
x1.shape torch.Size([1, 5, 2]) x2.shape torch.Size([1, 5, 2])

.
.
.
```
So for the first call, both `x1` and `x2` are inducing points (judging based on shape and inspecting values as well, which I omitted here for brevity)
Second call: `x2` is the whole inducing points, but `x1` is only one inducing point (based on it's value - when I pass the training and inducing points, I made sure they do not have any thing in common) - so here just comparing `x1` and `self.inducing_points` won't work
The same is true for the third call, `x2` is the whole set of inducing points, but `x1` is only one inducing point
If you follow the shapes for the rest of the calls, some are very clear based on the shapes that they are either data points or inducing points and I can decide based on that to call which function, but for those cases that the input has only one data point, I have to search `train_x` and `inducing_point` member variables to find out if they belong to data points or inducing points. It kind of works, but won't be scalable if I move away from my current toy dataset.
So I'm not still sure what's the most pragmatic way here to implement my kernel. Any feedback is really appreciated!

**Comment by gpleiss** [comment]
@jyhnnhyj - can you post your kernel implementation, and your code that you're using for training?

**Comment by jyhnnhyj** [comment]
Sure, here is the kernel:
```python
class BoundKernel(Kernel):
    def __init__(self, train_x, inducing_points, kff, kfu, kuf, kuu, **kwargs):
        super(BoundKernel, self).__init__(has_lengthscale=True, **kwargs)
        self.train_x = train_x
        self.inducing_points = inducing_points
        self.kff = kff
        self.kfu = kfu
        self.kuf = kuf
        self.kuu = kuu
        self.counter = 0

    def forward(self, x1, x2, diag=False, **params):
        self.counter += 1
        print("Counter: ", self.counter)
        print("x1.shape", x1.shape, "x2.shape", x2.shape)
                       
        if x1.shape[1:] == self.train_x.shape and x2.shape[1:] == self.train_x.shape:
            result = self.kff(x1, x2)
        elif x1.shape[1:] == self.inducing_points.shape and x2.shape[1:] == self.inducing_points.shape:
            result = self.kuu(x1, x2)
        elif x1.shape[1:] == self.train_x.shape and x2.shape[1:] == self.inducing_points.shape:
            result = self.kfu(x1, x2)
        elif x1.shape[1:] == self.inducing_points.shape and x2.shape[1:] == self.train_x.shape:
            result = self.kuf(x1, x2)
        else:
            if self.vector_is_contained(x1, x2):
                if x1.shape[1] == 1 and x2.shape[1] != 1:  # check which one was the larger one (the other one is contained in the )
                    if torch.equal(x2.squeeze(0), self.train_x):
                        result = self.kff(x1, x2)
                    elif torch.equal(x2.squeeze(0), self.inducing_points):
                        result = self.kuu(x1, x2)
                    else:
                        raise Exception("This should not have happened.")
                elif x1.shape[1] != 1 and x2.shape[1] == 1:
                    if torch.equal(x1.squeeze(0), self.train_x):
                        result = self.kff(x1, x2)
                    elif torch.equal(x1.squeeze(0), self.inducing_points):
                        result = self.kuu(x1, x2)
                    else:
                        raise Exception("This should not have happened.")
                else:
                    raise Exception("This should not have happened.")

        if diag:
            result = result.squeeze(0).diag().unsqueeze(0)
            
        return result

    def vector_is_contained(self, x1, x2):
        if x1.shape[1] == 1 and x2.shape[1] != 1:
            pass
        elif x1.shape[1] != 1 and x2.shape[1] == 1:
            x1, x2 = x2, x1
        else:
            return False

        for i in x2[0]:
            if torch.equal(i, x1[0][0]):
                return True
                
        return False
```

Here is the model:
```python
class VarGPModel(AbstractVariationalGP):
    def __init__(self, train_x, inducing_points):
        variational_distribution = CholeskyVariationalDistribution(inducing_points.size(0))
        variational_strategy = VariationalStrategy(model=self, 
                                                   inducing_points=inducing_points, 
                                                   variational_distribution=variational_distribution, 
                                                   learn_inducing_locations=True)
        
        super(VarGPModel, self).__init__(variational_strategy)
        
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(BoundKernel(train_x=train_x, 
                                                                     inducing_points=variational_strategy.inducing_points,
                                                                     kff=kff, kfu=kfu, kuf=kuf, kuu=kuu))
    
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x) 
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
```

and here is the training code:

```python    
likelihood = gpytorch.likelihoods.BernoulliLikelihood()
model = VarGPModel(train_x=train_x, inducing_points=train_x[:5]+0.001, kff=kff, kfu=kfu, kuf=kuf, kuu=kuu)

model.train()
likelihood.train()

optimizer = torch.optim.Adam([{'params': model.parameters()},], lr=0.1)

mll = gpytorch.mlls.VariationalELBO(likelihood, model, train_y.numel())

training_iter = 100
for i in range(training_iter):
    optimizer.zero_grad()
    output = model(train_x)
    loss = -mll(output, train_y)
    loss.backward()  
    print('Iter %d/%d - Loss: %.3f   lengthscale: %.3f  scale: %.3f' % (
        i + 1, training_iter, loss.item(),
        model.covar_module.base_kernel.lengthscale.item(),
        model.covar_module.outputscale.item()
        ))
    optimizer.step()
```

the `forward` method in the kernel is very hacky as you can see :)
(I'm just checking the shape here instead of equality, because I assumed that there will always be less inducing points than training points)

also another hacky part is here:
```python
model = VarGPModel(train_x=train_x, inducing_points=train_x[:5]+0.0001, ...)
```
I need to make sure that the inducing points and the training points do not have anything in common (by adding a small value) so that when I search if `x` is contained in the training or inducing points, the result is correct.

**Comment by jyhnnhyj** [comment]
@gpleiss @jacobrgardner any feedback is really appreciated!

**Comment by jacobrgardner** [comment]
@jyhnnhyj you're sure that the call to get a single row is not a training point against the inducing point? It's not clear to me that we would ever ask for a single inducing point against all inducing points unless there was grid structure or something. @gpleiss can you think of where we'd do this? Ask for k(z_1, Z) for non grid?

**Comment by jacobrgardner** [comment]
Oh! The preconditioner. @jyhnnhyj can you try running all of your training code in a `with gpytorch.settings.max_preconditioner_size(0):` context and see if you still see this behavior?

**Comment by jyhnnhyj** [comment]
Thanks @jacobrgardner  
using `with gpytorch.settings.max_preconditioner_size(0)`, I no longer get those single points.
