### ISSUE TITLE
Multi-task classification example?

### ISSUE THREAD

**Issue by jyhnnhyj** [cornellius-gp/gpytorch#657]
Are there any examples for multi-task classification (rather than regression) similar to https://github.com/cornellius-gp/gpytorch/blob/master/examples/03_Multitask_GP_Regression/Hadamard_Multitask_GP_Regression.ipynb ?

**Comment by gpleiss** [comment]
By multi-task classification, do you mean multi-class (non-binary) classification? If so, check out the CIFAR10 example.

**Comment by jyhnnhyj** [comment]
No, I didn't mean multi class classification. What I meant was multi-output GP where e.g. you can use linear model coregionalisation (lmc) to calculate the relation between outputs as well (cross co-var between e.g. first and second output) for a classification task

**Comment by jyhnnhyj** [comment]
@gpleiss  any suggestions?
I tried adapting `03_Multitask_GP_Regression/Hadamard_Multitask_GP_Regression.ipynb` to a classification task (instead of regression), but was not successful. The issue is that I'm not sure how to pass x's and i's to the variational strategy (as in classification models, those need to be set)
really appreciate any feedback here :)

**Comment by jyhnnhyj** [comment]
also appreciate any comment from @jacobrgardner

**Comment by gpleiss** [comment]
Right now variational models are not set up to do multitask. You can train a variational model to output several independent GPs, but that is probably not what you're looking for.

@jacobrgardner has been working on some variational multitask GP models (GPRNs, etc. - see #564) which will allow you to do multitask classification. We'll get an example notebook once those models are ready.

**Comment by gpleiss** [comment]
This should now be possible with #903 in

**Comment by jyhnnhyj** [comment]
Thanks a lot @gpleiss - are there any samples? Had a quick look into examples folder and couldn't find anything there

**Comment by gpleiss** [comment]
Whoops I realized I added a duplicate issue for this (#948). I'll close this one in favor of the more recent one. Should come out soon.
