### ISSUE TITLE
[Bug] pip install installs torch stable if torch nightlies are present

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#662]
Installing nightlies first and then installing gpytorch reverts torch to latest stable:
```
pip install -q torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
pip install -q git+https://github.com/cornellius-gp/gpytorch.git
torch.__version__  # 1.0.1.post2
```

Installing gpytorch first and then installing nightlies works properly:
```
pip install -q git+https://github.com/cornellius-gp/gpytorch.git
pip install -q torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
torch.__version__  # 1.1.0.dev20190423
```

Taking a step back, we do all this version parsing magic in setup.py [here](https://github.com/cornellius-gp/gpytorch/blob/master/setup.py#L30-L46).
Not really sure why this is necessary, can't we just require this to be `"torch>=1.0.1"`? Or is there some issue with the package naming?

**Comment by jacobrgardner** [comment]
Before #663 was merged the reason we did version parsing was to solve exactly this issue, where we want to allow people to update gpytorch without overwriting their torch install if they have torch-nightly installed.

Do you have a solution in mind or should we revert #663? I'd rather do the version parsing than have `pip install gpytorch` do silly things for people who are on pytorch-nightly.

**Comment by Balandat** [comment]
Yeah so is scrapped this because the parsing actually didn't work for me. Turns out this is an obscure bug with pip 19.0.1 in conjunction with having a `pyproject.toml` file: https://github.com/pypa/pip/issues/6163

Not quite sure what the proper solution is for this. Sledgehammer would be removing `pyproject.toml`. We could also try to check pip version at runtime. Maybe there is also a way to check whether either torch or torch-nightly is installed without actually importing them?

**Comment by Balandat** [comment]
@jacobrgardner I put up #666 if you want to merge that in and go back to the way things were.
