### ISSUE TITLE
[Docs] Docs for constraints are missing

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#664]
https://gpytorch.readthedocs.io doesn't contain documentation on the recently added constraints.

**Comment by AbhilashMathews** [comment]
Not sure if this is the same type of constraints, but on the topic of handling [regression with derivative information](https://github.com/cornellius-gp/gpytorch/blob/master/examples/10_GP_Regression_Derivative_Information/Simple_GP_Regression_Derivative_Information_2d.ipynb), are there any ways to ensure certain conditions in the derivative are satisfied (e.g. zero slope at x = 0)?

**Comment by gpleiss** [comment]
This is a duplicate of #640 - so closing it for now.

@AbhilashMathews - I believe it is a different topic. The constraints in this case refers to model parameters and hyperparameters.
