### ISSUE TITLE
[Feature Request] Accounting for heteroscedastic errors on the training data

### ISSUE THREAD

**Issue by AbhilashMathews** [cornellius-gp/gpytorch#670]
Following the simple 1D regression example in the docs, I wanted to account for heteroscedastic error on the training data itself. In the case below, I simply set it to be 10% of the training data itself, but ideally it would be arbitrary:

```
import math
import torch
import gpytorch
from matplotlib import pyplot as plt
import numpy as np

# Training data is 11 points in [0,1] inclusive regularly spaced
len_train = 1000 
len_predict = 1000
training_iter = 20
train_x = torch.linspace(0, 1, len_train)
# True function is sin(2*pi*x) with Gaussian noise
train_y = torch.sin(train_x * (2 * math.pi)) + torch.randn(train_x.size()) * 0.2
train_yerr = torch.from_numpy(np.abs([0.1*train_y.numpy()])) #or = torch.from_numpy(np.abs(0.1*train_y.numpy())) gives same result
# We will use the simplest form of GP model, exact inference
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())
    
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

# initialize likelihood and model
likelihood = gpytorch.likelihoods.GaussianLikelihood()
likelihood.initialize(noise=train_yerr)
model = ExactGPModel(train_x, train_y, likelihood)

# Find optimal model hyperparameters
model.train()
likelihood.train()

# Use the adam optimizer
optimizer = torch.optim.Adam([
    {'params': model.parameters()},  # Includes GaussianLikelihood parameters
], lr=0.1)

# "Loss" for GPs - the marginal log likelihood
mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

for i in range(training_iter):
    # Zero gradients from previous iteration
    optimizer.zero_grad()
    # Output from model
    output = model(train_x)
    # Calc loss and backprop gradients
    loss = -mll(output, train_y)
    loss.backward()
    print('Iter %d/%d - Loss: %.3f   lengthscale: %.3f   noise: %.3f' % (
        i + 1, training_iter, loss.item(),
        model.covar_module.base_kernel.lengthscale.item(),
        model.likelihood.noise.item()
    ))
    optimizer.step()
    
# Get into evaluation (predictive posterior) mode
model.eval()
likelihood.eval()

# Test points are regularly spaced along [0,1]
# Make predictions by feeding model through likelihood
with torch.no_grad(), gpytorch.settings.fast_pred_var():
    test_x = torch.linspace(0, 1, len_predict)
    observed_pred = likelihood(model(test_x)) 
    
with torch.no_grad():
    # Initialize plot
    f, ax = plt.subplots(1, 1, figsize=(4, 3))

    # Get upper and lower confidence bounds
    lower, upper = observed_pred.confidence_region()
    # Plot training data as black stars
    ax.plot(train_x.numpy(), train_y.numpy(), 'k*')
    # Plot predictive means as blue line
    ax.plot(test_x.numpy(), observed_pred.mean.numpy(), 'b')
    # Shade between the lower and upper confidence bounds
    ax.fill_between(test_x.numpy(), lower.numpy(), upper.numpy(), alpha=0.5)
    ax.set_ylim([-3, 3])
    ax.legend(['Observed Data', 'Mean', 'Confidence']) 
```

But I receive the following error when I run the code:

```
  File "/home/mathewsa/anaconda3/lib/python3.6/site-packages/gpytorch/likelihoods/noise_models.py", line 56, in _set_noise
    self.initialize(raw_noise=self.raw_noise_constraint.inverse_transform(value))

  File "/home/mathewsa/anaconda3/lib/python3.6/site-packages/gpytorch/module.py", line 83, in initialize
    "Attempting to manually set a parameter value that is out of bounds of "

RuntimeError: Attempting to manually set a parameter value that is out of bounds of its current constraints, GreaterThan(1.000E-04). Most likely, you want to do the following:
 likelihood = GaussianLikelihood(noise_constraint=gpytorch.constraints.GreaterThan(better_lower_bound))
```
or on a different run:

```
  File "/home/mathewsa/anaconda3/lib/python3.6/site-packages/gpytorch/likelihoods/noise_models.py", line 56, in _set_noise
    self.initialize(raw_noise=self.raw_noise_constraint.inverse_transform(value))

  File "/home/mathewsa/anaconda3/lib/python3.6/site-packages/gpytorch/module.py", line 91, in initialize
    self.__getattr__(name).data.copy_(val.view_as(self.__getattr__(name)))

RuntimeError: shape '[1]' is invalid for input of size 1000
```

Any ideas on why this error is arising and why I cannot specify non-constant errors on the training data? General code to solve this problem would be appreciated.

**Comment by jacobrgardner** [comment]
You're going to want to use a `FixedNoiseGaussianLikelihood` for this: https://github.com/cornellius-gp/gpytorch/blob/e95724262e21befc4a2402170f898fde95c8a5b3/gpytorch/likelihoods/gaussian_likelihood.py#L88

**Comment by AbhilashMathews** [comment]
Thank you! To clarify one part of the code: is using `test_noises` in `pred_y = likelihood(gp_model(test_x), noise=test_noises)` simply equivalent to adding these test noise terms across the diagonal of the terms K(x*,x*), where x* corresponds to a test point where a prediction is taking place? If so, is there a particular reason or physical justification for why this is included in line 110 of the linked code, yet is not included in [(2.21)](http://www.gaussianprocess.org/gpml/chapters/RW2.pdf) in 'Gaussian Processes for Machine Learning'?

**Comment by jacobrgardner** [comment]
Well in equation 2.24 they are computing `Var[f*]`, which is the variance of the **latent function**, e.g. `gp_model(test_x)`. When you pass data through the likelihood (e.g. `likelihood(gp_model(test_x))`, you are computing `Var[y*]` which is the variance of the **observation**, which does include an added `\sigma^2` (in the homoskedastic case) or the added test noises.

**Comment by AbhilashMathews** [comment]
Interesting and thank you! So the difference arises because (2.22)-(2.24) correspond to the underlying predictive distribution, `f*`, while `y*` corresponds to a noisy target based upon `f*`, which has its negative log likelihood given by (2.34). With the below quote from page 18 for context, my question is: the means are equivalent since `E[f*] = E[y*]`, but when predicting the variance for a new target point, should we be using `Var[f*]` or `Var[y*]`? 

I believe the answer would be: use `Var[y*]` if you want to reproduce the variance of the noisy observations, or use `Var[f*]` if you want to output the variance from the underlying distribution of the noisy observations. But happy to get your thoughts on the above and in what context to use which variance. 

-------------------------------------------------------------------------------------------------------------------

"Note also that the variance in eq. (2.24) does not depend on the observed targets, but only on the inputs; this is a property of the Gaussian distribution. The variance is the difference between two terms: the first term K(X∗, X∗) is simply the prior covariance; from that is subtracted a (positive) term, representing the information the observations gives us about the function. We can very simply compute the predictive distribution of test targets y∗ by adding σ2n*I to the variance in the expression for cov(f∗)."

**Comment by jacobrgardner** [comment]
@AbhilashMathews Yes, the means are equivalent (and everything else you mention is a correct interpretation). This is because the Gaussian likelihood for regression GP models is given by `p(y|f) = N(f, \sigma_{n}^{2}I)`.
