### ISSUE TITLE
[Bug] In grid creation?

### ISSUE THREAD

**Issue by KeAWang** [cornellius-gp/gpytorch#675]
# 🐛 Bug

Grid creation in the repo exceeds the grid bounds. Example: https://github.com/cornellius-gp/gpytorch/blob/db889f1eaa1be3206e57f5a1494ef3fb7f2e3524/test/examples/test_grid_gp_regression.py#L65 and https://github.com/cornellius-gp/gpytorch/blob/5411c905b778280122e2524fc4aafd13cdc7270d/gpytorch/variational/grid_interpolation_variational_strategy.py#L15

## To reproduce

Copying the code from the test case, we have 
```
import torch
num_dim=1
grid_bounds = [(0, 1)] if num_dim == 1 else [(0, 1), (0, 2)]
grid_size = 25
grid = torch.zeros(grid_size, len(grid_bounds))
for i in range(len(grid_bounds)):
    grid_diff = float(grid_bounds[i][1] - grid_bounds[i][0]) / (grid_size - 2)
    grid[:, i] = torch.linspace(
        grid_bounds[i][0] - grid_diff, grid_bounds[i][1] + grid_diff, grid_size
    )
```
which returns the grid 
```
tensor([[-0.0435],
        [ 0.0018],
        [ 0.0471],
        [ 0.0924],
        [ 0.1377],
        [ 0.1830],
        [ 0.2283],
        [ 0.2736],
        [ 0.3188],
        [ 0.3641],
        [ 0.4094],
        [ 0.4547],
        [ 0.5000],
        [ 0.5453],
        [ 0.5906],
        [ 0.6359],
        [ 0.6812],
        [ 0.7264],
        [ 0.7717],
        [ 0.8170],
        [ 0.8623],
        [ 0.9076],
        [ 0.9529],
        [ 0.9982],
        [ 1.0435]])
```
which clearly exceeds the `grid_bounds`.

## Expected Behavior

I believe this should return a grid with all the points within the `grid_bounds`. This can be done by doing 
```
torch.linspace(
        grid_bounds[i][0] - grid_diff, grid_bounds[i][1] + grid_diff, grid_size
    )
```
or
```
torch.linspace(
        grid_bounds[i][0], grid_bounds[i][1], grid_size
    )
```
instead.

**Comment by jacobrgardner** [comment]
This is actually intentional: we extend grids two points past the specified boundary. The reason for this is that when doing e.g. cubic interpolation over a grid you get pretty bad behavior around the "actual" boundary. Doing things this way ensures that users can never supply data near the "actual" boundary.
