### ISSUE TITLE
[Feature Request] model.sample_from_prior()

### ISSUE THREAD

**Issue by shalijiang** [cornellius-gp/gpytorch#681]
# 🚀 Feature Request

if we want to sample from hyperprior, seems we can only do this for each module separately, e.g. `model.covar_module.base_kernel.sample_from_prior('lengthscale_prior')`
`model.covar_module.sample_from_prior('outputscale_prior')`
and these are also specific to a special type of kernel. 
It would be great if we have a higher level interface such as 
`model.sample_from_prior()',
which automatically samples from all hyperpriors, regardless the type of the kernel etc.

**Comment by jacobrgardner** [comment]
I think this would be a reasonable thing to implement yeah. Basically we could sample a whole `state_dict`. Then you could initialize hypers by loading the resulting state dict.

**Comment by gpleiss** [comment]
I think this should be implemented with #918 (using Pyro - call `model.pyro_sample_from_prior`)
