### ISSUE TITLE
Setting some hyperparameters to fixed values

### ISSUE THREAD

**Issue by bwengals** [cornellius-gp/gpytorch#689]
Quick question that I couldn't seem to find in the issues/docs:  Is it possible to fix some hyperparameters, like covariance lengthscales, to specific values?  If so, how does one do this?

**Comment by gpleiss** [comment]
The PyTorch optimizers optimize whatever parameters you pass to them. So for example, if you only wanted to optimize the mean parameters and the likelihood parameters, you could construct an optimizer as follows:

```python
optimizer = torch.optim.SGD([
    {"params": model.mean_module.parameters()},
    {"params": model.likelihood.parameters()},
], lr=0.1)
```

This will optimize everything except the kernel hyperparameters. Alternatively (but a bit messier)

```python
optimizer = torch.optim.SGD(
    params=list(set(model.parameters()) - {model.covar_module.base_kernel.lengthscale, }),
    lr=0.1
)
```

See [the torch.optim docs](https://pytorch.org/docs/stable/optim.html) for more info.

**Comment by bwengals** [comment]
thank you!

**Comment by jacobrgardner** [comment]
Just to add on really quickly: another option is to set requires_grad to False on any parameters you don't want optimized. Then you can still just pass model.parameters() to the optimizer.

**Comment by georgedeath** [comment]
If anyone reads this and wonders why they can't get it to work, make sure you're setting requires_grad on the raw parameters, it doesn't work on the transformed ones. E.g. 
`covar_module.base_kernel.raw_lengthscale.requires_grad` not `covar_module.base_kernel.lengthscale.requires_grad`.

**Comment by aegonwolf** [comment]
> ```python
> ([
>     {"params": model.mean_module.parameters()},
>     {"params": model.likelihood.parameters()},
> ], lr=0.1)
> ```

Hi,  would I do this with a composite Kernel? I.e. if I had Matern() + LinearKernel()*OtherKernel() (or something of the sort) and would want to fix the lengthscale of Matern?

**Comment by gpleiss** [comment]
@aegonwolf any of the solutions described in this thread would work
