### ISSUE TITLE
[Question] How to properly use `SpectralMistureKernel`?

### ISSUE THREAD

**Issue by scigeek72** [cornellius-gp/gpytorch#691]
#  Question
I am trying to see if I can use the `SpectralMixtureKernel`.  Since I am still in the learning phase, I am trying out different kernels to get an idea of how all these works. To this end, I am again using the code block for Simple Regression Tutorial, but instead of RBFKernel, I am using SpectralMixtureKernel with appropriate parameter values. According to the documentation, I must have `ard_dum_dim` set to `d` if my input matrix has dimension `n x d`. However, when I do that, even with the code snippet provided (with input dim=5), I am getting the following error:

```
covar_module(x)
Traceback (most recent call last):

  File "<ipython-input-178-e698b2d55a0e>", line 1, in <module>
    covar_module(x)

  File "/anaconda3/envs/py36/lib/python3.6/site-packages/gpytorch/kernels/kernel.py", line 430, in __call__
    "(based on the ard_num_dims argument). Got {}.".format(self.ard_num_dims, x1_.size(-1))

RuntimeError: Expected the input to have 1 dimensionality (based on the ard_num_dims argument). Got 5.
```
Where the code snippet is:

```
x = torch.randn(10,5)
covar_module = gpytorch.kernels.SpectralMixtureKernel(num_mixture=4, ard_dum_dim = 5)

```

Any suggestions?
Thanks.

**Comment by KeAWang** [comment]
Seems like just a typo in your code to me. Try
```
x = torch.randn(10,5)
covar_module = gpytorch.kernels.SpectralMixtureKernel(num_mixtures=4, ard_num_dims=5)
```
