### ISSUE TITLE
[Question] Where does one set the number of GPs learned in when using AdditiveGridInterpolationStrategy ?

### ISSUE THREAD

**Issue by kunalghosh** [cornellius-gp/gpytorch#698]
Hi, 

I am trying to re-implement the model in [SV-DKL paper](https://papers.nips.cc/paper/6426-stochastic-variational-deep-kernel-learning.pdf) and I suppose the [DKL example](https://gpytorch.readthedocs.io/en/latest/examples/08_Deep_Kernel_Learning/Deep_Kernel_Learning_DenseNet_CIFAR_Tutorial.html) is the one I should follow.

However, in the DKL example notebook there is one GP learnt per input feature (output by the neural network) as is mentioned [here](https://gpytorch.readthedocs.io/en/latest/examples/08_Deep_Kernel_Learning/Deep_Kernel_Learning_DenseNet_CIFAR_Tutorial.html#Creating-the-GP-Layer). So, there are as many GPs as there are dimensions in the neural network output. Is it possible for me to specify the number of GPs learnt as in the paper ? i.e. I would like to keep the neural network output dimension fixed and vary the number of GPs (the **J** in Figure 1 of SV-DKL paper, where each GP is trained on the **Q** dimensional output of the NN).

**Comment by gpleiss** [comment]
At the moment, AdditiveGridInterpolationStrategy assumes that each feature gets assigned to one GP - which follows the experiments in the paper.

If you want to try a different configuration, you could create several RBFKernels, each with a different active_dims argument, and add them together using a SumKernel.
