### ISSUE TITLE
DKL Batch vs. single examples results

### ISSUE THREAD

**Issue by jgbos** [cornellius-gp/gpytorch#702]
Not sure if this is a feature of DKL or a bug.  When I train a DKL model, say on MNIST, with a large batch size and also evaluate accuracy with large batch sizes I see really good results.  Yet when I try to evaluate the model in a single image (batch size of 1), and evaluate over the test set, I see a significant drop in accuracy (say, 98% (large batches) to 1% (batch size of 1)).  Is this a function of GPs and fitting over the dataset or should the DKL model learn to provide good results even when given one example?

**Comment by jacobrgardner** [comment]
I think if you are *training* with a single point this might be expected behavior -- for VI, there's some noise in the loss and gradients as it is, so single point SGD might be too stochastic to make progress. Do you see problems if you just test the model in batch?

**Comment by cherepanovic** [comment]
@jacobrgardner 
what is meant by "VI"?

Is it theoretically possible to train and NN layer by GP not batchwise? I thought to do it batchwise is a requirement, isn't?
