### ISSUE TITLE
Making base test cases importable?

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#730]
We'd like to use some of the gpytorch test infrastructure outside of gpytorch. Specifically, we'd like to re-use some of `BaseKernelTestCase` for some new kernels that we're playing around with (we're planning on upstreaming these once they work). The issue is that we can't import this class b/c the `test` module isn't part of the gpytorch package (and we don't want to require the source and do some questionable path manipulations). 

Since this is just a barebones class and not an actual unittest test case, we could move this into a `pytorch.test` module and leave the actual tests in the `test` folder (the same applies to other test infra such as `BaseTestCase`, `BaseLikelihoodTestCase` etc). 

This shouldn't have any effects other than making the base test infra importable. 

@jacobrgardner, @gpleiss thoughts on this?

**Comment by jacobrgardner** [comment]
Yeah if it is useful to you I'm not opposed to moving the base test cases under gpytorch.test

**Comment by Balandat** [comment]
cool I'll put up a diff for this soon then

**Comment by Balandat** [comment]
Done in #733
