### ISSUE TITLE
How to implement Fisher kernel in GPyTorch?

### ISSUE THREAD

**Issue by Akella17** [cornellius-gp/gpytorch#734]
Is it possible to implement the Fisher kernel in GPyTorch that further uses inducing points (KISS-GP) techniques to scale to a large number of datapoints?

Fisher kernel: F(x<sub>1</sub>,x<sub>2</sub>) = u(x<sub>1</sub>)<sup>T</sup> G<sup>-1</sup> u(x<sub>2</sub>)
u(x) = &nabla;<sub>&theta;</sub>[log(P(x|&theta;))]
G is the fisher information matrix
P(x|&theta;) is estimated using a neural network @jacobrgardner @gpleiss

**Comment by buchholzmd** [comment]
Did you ever make any progress on this? I am also interested in using the Fisher Kernel in such a way

**Comment by Akella17** [comment]
Yes actually. Fisher kernel can equivalently be written as a linear kernel. Refer to my paper (https://arxiv.org/abs/2006.15637) and the code (https://github.com/Akella17/Deep-Bayesian-Quadrature-Policy-Optimization) for implementation details.

**Comment by buchholzmd** [comment]
Thank you for the quick response! This information has been extremely helpful.

I see in another post that you claim the fisher information matrix is learned by the neural network: x = u(z) = ∇θ[log(P(z|θ))]. Could you provide an explanation (or any relevant references) of how you can guarantee that the neural network is learning this mapping?

My thought would be that you would explicitly want to take the grad of the log probability using torch.autograd.functional.jacobian. Maybe my intuition is misguided? Any clarification is highly appreciated!

**Comment by Akella17** [comment]
Fisher kernel is not learned by the neural network, it is derived from the neural network.
So the fisher kernel matrix K_f = U^T G^{-1} U and we already know that the fisher information matrix G \approx (1/n)* U U^T (here U = [u(z_1), ..., u(z_n)]).

So if you can find the SVD of U matrix = u s v^T, K_f can be simplified as n*v v^T (look at Eq. 33 in Appendix from the paper I shared earlier).

So essentially, K_f = n v v^T, which is like a linear kernel with input as rows of v.

**Comment by buchholzmd** [comment]
My apologies, I should have been more clear. What I meant was how can we guarantee that the neural network does indeed provide the mapping: u(z) = ∇θ[log(P(z|θ))]? I assume here that u(z) would be the output of the neural network, given input z.

In addition, my primary question is how we can be certain the Fisher information matrix G \approx (1/n)*UU^T. I could not find the literature showing this claim. I am still becoming more familiar with this material, so I do appreciate the help.

**Comment by Akella17** [comment]
u(z) is not the output of NN. P(z|\theta) is probably the output of NN, atleast in my case. So u(z) is simply the gradient if log of NN's output.

Fisher information matrix is the expectation of u(z)u(z)^T, where z is drawn from policy environment interaction, so basically z are the state action samples that you collect.

In practice, you can't compute the expectation exactly since it is both statistically and computationally impossible to average infinitely many z values. So what you do is you average over the finite number of z values that you have (this is called the Monte Carlo estimate). So \sum_{i=1}^{n} u(z_i) u(z_i)^T = U U^T.

I am not sure about other literature, but my paper that I shared should be sufficient if you want to efficiently compute Fisher information in RL settings. The paper should be easy to follow and most of your questions are already sufficiently addressed in the paper. I encourage you to read it :)
