### ISSUE TITLE
Build a Bilinear kernel?

### ISSUE THREAD

**Issue by Akella17** [cornellius-gp/gpytorch#735]
I want a kernel of the format:
K(x<sub>1</sub>,x<sub>2</sub>) = x<sub>1</sub><sup>T</sup> A<sup>-1</sup> x<sub>2</sub>
where A is a symmetric positive definite matrix.

Would modifying this [line](https://github.com/cornellius-gp/gpytorch/blob/4c71e54f519fe1c51db8d0609c5a88532039f17b/gpytorch/kernels/linear_kernel.py#L112) of the **linear kernel** (line: 112) as follows be sufficient?
```Python
# prod = MatmulLazyTensor(x1_, x2_.transpose(-2, -1))
prod = A.inv_matmul(right_tensor= x2_, left_tensor=x1_)
```

The matrix A in the above equation is not a **LazyTensor** as it is of the format E<sub>x~p(x)</sub>[x.x<sup>T</sup>]. Would it be possible to compute the *expectation*, as well as store the matrix A more efficiently (like a lazy tensor)?

Also, if LazyTensors are stored as low-rank factorizations *K = XX<sup>T</sup>*, wouldn't all lazy tensors be singular. Then how is the ```inv_matmul()``` being computed? @jacobrgardner @gpleiss

**Comment by jacobrgardner** [comment]
In general, yes that modification can be done, and will give you the result you want.

Assuming you are approximating `A` as a covariance matrix given samples `X_iX'_i`, then you could make a `RootLazyTensor` out of it. Alternatively, if you have `A` directly you can make a `NonLazyTensor` out of it.

Not all lazy tensors are low rank factorizations, only e.g. `MatmulLazyTensor` or `RootLazyTensor` and `CholLazyTensor` as special cases could potentially work that way. If the matrix is singular, you'll get something like the solution to a least squares problem. However, note that e.g. in the Linear kernel case, the added diagonal component corresponding to the noise (`K + sI`) makes the matrix positive definite again with minimum eigenvalue `s>0`.

In your case, this means you may want to ensure you use more than `d` samples `x_i` to ensure the positive definiteness of `A`, unless you also have a compelling reason to add a diagonal component.

**Comment by Akella17** [comment]
```A``` is the Fisher information matrix corresponding to a neural network.

Fisher kernel: F(z<sub>1</sub>,z<sub>2</sub>) = u(z<sub>1</sub>)<sup>T</sup> A<sup>-1</sup> u(z<sub>2</sub>)
u(z) = &nabla;<sub>&theta;</sub>[log(P(z|&theta;))]
Assuming x = u(z), Fisher kernel can be replaced with a Bilinear kernel
F(x,x') = x<sup>T</sup> A<sup>-1</sup> x'
A is the Fisher information matrix
x = u(z) = &nabla;<sub>&theta;</sub>[log(P(z|&theta;))] is estimated using the neural network

With ```A``` as a ```NonLazyTensor```, both the compute time and memory requirements are inordinate as we increase the size of the neural network. However, I am not aware of any approach to efficiently estimate A = E<sub>x~p(x)</sub>[x.x<sup>T</sup>] and compute x<sub>1</sub><sup>T</sup> A<sup>-1</sup> x<sub>2</sub>.

Alternatively, I think I can get an estimate of A<sup>-1</sup> with just the efficiency of computing A = E<sub>x~p(x)</sub>[x.x<sup>T</sup>] (using Sherman-Morrison matrix inversion lemma). While this does not solve the memory issue, I think it would be faster to compute x<sub>1</sub><sup>T</sup> A<sup>-1</sup> x<sub>2</sub> directly as two consecutive matrix vector products (assuming A<sup>-1</sup> is known) rather than using conjugate gradient followed by a vector product. Which do you think is a better way to proceed with? @jacobrgardner
