### ISSUE TITLE
How to combine two different types of kernels?

### ISSUE THREAD

**Issue by mejliu** [cornellius-gp/gpytorch#739]
Hi,

I'm wondering is there a way to combine two different kernels as a product structure kernel? 

For example, test_x is n by 3. For the first two dimensions, I want to use a 2D RBF. For the last dimension, I want to use a spectral mixture kernel. I searched all the examples in the tutorial. It seems like there is no example of how to combine two different types.  

```
n=20
train_x = torch.zeros(pow(n, 2), 3)
for i in range(n):
    for j in range(n):
        train_x[i * n + j][0] = float(i) / (n-1)
        train_x[i * n + j][1] = float(j) / (n-1)
        train_x[i * n + j][2] = float(j) / (n-1)
 
train_y = torch.sin(train_x[:, 0] + train_x[:, 1]) *torch.cos(train_x[:,2]) * (2 * math.pi) + 
               torch.randn_like(train_x[:, 0]).mul(0.01)

self.covar_module = gpytorch.kernels.ProductStructureKernel(
           gpytorch.kernels.GridInterpolationKernel(
                gpytorch.kernels.ScaleKernel(
                    gpytorch.kernels.RBFKernel(),
                ), grid_size=128, num_dims=2
            ), 
           gpytorch.kernels.GridInterpolationKernel(
                gpytorch.kernels.SpectralMixtureKernel(num_mixtures=4), 
               grid_size=128, num_dims=1
            ), num_dims=3
        )
```
This way seems doesn't work. Any help is appreciated. thanks.

**Comment by gpleiss** [comment]
`ProductStructureKernel` shouldn't be used here. What you want instead is to use `gpytorch.kernels.ProductKernel`

**Comment by mejliu** [comment]
thanks for your reply. May I know the difference between `ProductStructureKernel` and `ProductKernel`?

**Comment by gpleiss** [comment]
ProductStructureKernel assumes that the kernel you are learning takes the form `k1 x k2 x ... x kd` where each of the `d` kernels acts on one dimension of the input data. However, ProductStructureKernel uses batch matrix math to perform this computation in parallel very efficiently.

ProductKernel is used for any type of kernel product. It is more general than ProductStructureKernel, but does not use parallel math to compute the kernel. Therefore, if you can use ProductStructureKernel it is preferable. See the docs for more information :)
