### ISSUE TITLE
[Bug] Multitask learning with additive kernel structure

### ISSUE THREAD

**Issue by WRJacobs** [cornellius-gp/gpytorch#740]
# 🐛 Bug

When I train a GP with an additive kernel structure the multitask learning (Hadamard) does not work correctly. It looks like it is only training on the first input (the one with an index of 0). The output (mean) is identical for any other index/task. 

It is working for the product of kernels. 

## To reproduce
To reproduce you could replace the kernel in the example given in the documentation: Hadamard_Multitask_GP_Regression.ipynb

Original: 
```python
class MultitaskGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(MultitaskGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.RBFKernel()
        
        # We learn an IndexKernel for 2 tasks
        # (so we'll actually learn 2x2=4 tasks with correlations)
        self.task_covar_module = gpytorch.kernels.IndexKernel(num_tasks=2, rank=1)
```
Replace with: 
```python
class MultitaskGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(MultitaskGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.RBFKernel() + gpytorch.kernels.PeriodicKernel()
        
        # We learn an IndexKernel for 2 tasks
        # (so we'll actually learn 2x2=4 tasks with correlations)
        self.task_covar_module = gpytorch.kernels.IndexKernel(num_tasks=2, rank=1)
```

I have included a plot of the output with the undesirable behaviour. 

Many thanks, 
Will. 

![image](https://user-images.githubusercontent.com/23551270/59771776-57636600-92a2-11e9-8d5b-35f24db8d16c.png)

**Comment by gpleiss** [comment]
@WRJacobs I am not able to reproduce this behavior on GpyTorch master. What version of Pytorch/GPyTorch are you using.

**Comment by WRJacobs** [comment]
@gpleiss I am using versions:

gpytorch==0.2.1
pytorch==1.1.0

checked with a few kernels and got similar results.

**Comment by gpleiss** [comment]
Could you try upgrading GPyTorch and let me know if you still see this issue?

**Comment by WRJacobs** [comment]
Ahh, OK. I only recently installed it so I just assumed I was up to date. Apologies, I should of checked that first.
