### ISSUE TITLE
How to generate a spatio temporal gp data using gp model?

### ISSUE THREAD

**Issue by vtttta** [cornellius-gp/gpytorch#754]
Hi all, 

I'm pretty new to gpytorch. Now, I want to use gpytorch to generate a dataset for simulation. Specifically, I want to generate a  `N by 3` train_x and `N by 1` train_y.  `N` is the number of training inputs. For each input, the first two dimensions represent a location in a  2d field (probably a spatial kernel). The last dimension is a time index (probably a temporal kernel). Basically, this dataset can be seen as a dataset generated from a 2D dynamic terrain at different time. Because the training outputs of a specific location at different time have correlation, I want to use a temporal kernel to represent this relation. 

My problem is how to generate this dataset directly from gp model using some prior hyperparameters? thanks.

**Comment by eytan** [comment]
To start off, you can simply treat the time component as another plain GP
input (e.g., a 3D RBF kernel).  If you want to impose additional
assumptions about how things progress through time, you may want to
consider using a different kernel for the third dimension.

**Comment by vtttta** [comment]
@eytan  thanks for your suggestion. Just to clarify, do you mean use a 1D kernel (like periodical kernel) for the time dimension, and then use a Kronecker product (or multiplication) to combine this with the first two dimensions? 

I am not sure how to generate this data. Because when we initialize a GP, we need to use `model = GPRegressionModel(train_x, train_y, likelihood)`. The problem is that we don't have train data to feed into this model. Therefore, my problem is sort of generate data using GP, not using data to train GP. Could you give me some hints? thanks.

**Comment by KeAWang** [comment]
So are you trying to sample from a GP without any training data? i.e. trying to sample from a GP prior?

**Comment by vtttta** [comment]
> So are you trying to sample from a GP without any training data? i.e. trying to sample from a GP prior with some set of preset hyperparameters?

@KeAWang  Yes. I'm trying to generate some simulated data from a spatiotemporal gaussian process with given priors. Now, I'm stuck on it.

**Comment by KeAWang** [comment]
But you need to specify the points at which you want to query the GP. What are those points? Put another way, we have f(x_1, x_2, ..., x_N) ~ N(mu, Sigma) where all x_i are d dimensional and f is one dimensional. What are you using for your x_i?

**Comment by KeAWang** [comment]
But you need to specify the points at which you want to query the GP. What are those points? Put another way, we have f(x_1), f(x_2), ..., f(x_N) that are jointly multivariate Normal N(mu, Sigma) where all x_i are d dimensional and f(x_i) is one dimensional. What are you using for your x_i?

**Comment by KeAWang** [comment]
Are you trying to query the GP at a set of N points that are 3 dimensional? Here's an example with a RBFKernel for each dimension. 

```
import math
import torch
import gpytorch

train_x = None
train_y = None

class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ZeroMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel(ard_num_dims=3))
    
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

likelihood = gpytorch.likelihoods.GaussianLikelihood()
model = ExactGPModel(train_x, train_y, likelihood)

# We want to initialize the actual parameter, not the raw parameters
# see https://github.com/cornellius-gp/gpytorch/blob/master/examples/00_Basic_Usage/Hyperparameters.ipynb

hypers = {
    # We won't be using the likelihood so we don't need to initialize the noise
    'covar_module.base_kernel.lengthscale': torch.tensor([1.0, 1.0, 1.0]),
    'covar_module.outputscale': torch.tensor(2.0),
}

model.initialize(**hypers)

N = 1000
test_x = torch.randn(N, 3)

model.eval()
with gpytorch.settings.prior_mode(True):
    test_y = model(test_x).sample()
```

**Comment by mejliu** [comment]
@KeAWang thanks for your reply. For my input, each point is 3 dimensional. The first two are `x` and `y`, which is a location in a 2D field. The third dimension is a time `t`. Let's say `t=1, 2, ...`. What I want is to generate a simulated spatiotemporal data using GP with some given priors. e.g., a dynamic sea level data in a 2D region.

**Comment by KeAWang** [comment]
Then my example should do what you want.

**Comment by vtttta** [comment]
Thank you very much for your help. It works.
