### ISSUE TITLE
[Bug] Batch-indexing lazy covariance matrix fails for batch-mode ExactGP

### ISSUE THREAD

**Issue by sdaulton** [cornellius-gp/gpytorch#758]
# 🐛 Bug

Evaluating a batch-mode ExactGP with training inputs of shape `b x n x d` and targets of shape `b x n` on a set of test points with shape `m x d` yields a lazy_covariance_matrix with shape `b x m x m`. Indexing along the batch dimension fails.

## To reproduce

[batch_indexing_bug_lazy_covar.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/3331406/batch_indexing_bug_lazy_covar.ipynb.txt)

## Expected Behavior

Selecting a single index of the batch dimension:

```
mvn.lazy_covariance_matrix[0, :, :]
```
should yield the lazy covariance matrix for the 0th batch (with shape `m x m`)

## System information
-  0.3.2
-  1.0.0a0

**Comment by sdaulton** [comment]
This issue comes from having a batch-mode kernel, which is not "indexed" along the batch dimension when the LazyEvaluatedKernelTensor is indexed along the batch dimension--for this use case, the kernel would also need to be "indexed" along the batch dim when creating the new LazyEvaluatedKernelTensor: https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/lazy/lazy_evaluated_kernel_tensor.py#L121

**Comment by Balandat** [comment]
@jacobrgardner, @gpleiss is this something you think you can fix in the near future? This is kind of important in order to get multi-output models working efficiently.
