### ISSUE TITLE
How to generate samples from model before training and after training?

### ISSUE THREAD

**Issue by vtttta** [cornellius-gp/gpytorch#759]
I want to use gpytorch model with given prior hyperparameters to generate some samples before training. Besides, I also want to use gpytorch model to generate another group of samples after training. 
Any suggestion would be appreciated. thanks.

**Comment by Balandat** [comment]
Does prior mode help? `with gpytorch.settings.prior_mode(True):` will sample from the GP prior. 

You can always load different parameter values by using the model's state_dict.

**Comment by jacobrgardner** [comment]
Sampling in general is done via the answer in #757 -- the GP model returns a `MultivariateNormal` distribution which exposes the same interface as `torch.distributions.MultivariateNormal` and therefore has an `rsample` method which can be used for sampling.

As @Balandat points out, you can sample from the prior at any time by enabling prior mode, including on a trained model.
