### ISSUE TITLE
[Bug] Incorrect gradients for kernels using torch.cdist

### ISSUE THREAD

**Issue by sdaulton** [cornellius-gp/gpytorch#766]
# 🐛 Bug
Auto-differientiating torch.cdist on the GPU is broken (https://github.com/pytorch/pytorch/issues/22353). This means kernels using torch.cdist have incorrect gradients on the GPU

## To reproduce
[cdist_issue_gpytorch.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/3340948/cdist_issue_gpytorch.ipynb.txt)

## Expected Behavior

Numerical and analytic gradients match

## System information

**Please complete the following information:**
GPyTorch Version: master
PyTorch Version (e.g., 1.0): master
OS (e.g., Linux): CentOS Linux 7 (Core)
CUDA/cuDNN version:CUDA Version 9.2.88
Tesla M40

**Comment by sdaulton** [comment]
cc @Balandat @danielrjiang

**Comment by Balandat** [comment]
It seems that the straightforward solution to this is to add a check that the tensors not be cuda tensors here: https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/kernels/kernel.py#L25

**Comment by Balandat** [comment]
And to make sure this gets fixed upstream before pytorch 1.2.

**Comment by jacobrgardner** [comment]
The newest non cdist version of the distance computation is pretty darn fast even in low data settings. Let's either just disable cdist for GPU tensors as max suggests or disable cdist entirely for now.

@Balandat do we need to release 0.3.4 as a result of this?

**Comment by Balandat** [comment]
> @Balandat do we need to release 0.3.4 as a result of this?

That would be great. Let's make sure we understand the implications of using either the custom or cdist implementation first though, in particular regarding batch mode (see my comment on the PR).

**Comment by Balandat** [comment]
@jacobrgardner I didn't get to look into this much further (not sure I will anytime soon). Do you mind putting out a 0.3.4 at this point while we're waiting for cdist to get implemented properly on the pytorch end?

**Comment by jacobrgardner** [comment]
@Balandat Sure thing, I'll put out 0.3.4 first thing tomorrow.

**Comment by Balandat** [comment]
Great, thanks. I checked about prioritizing fixing up cdist (both gradients and perf) with the pytorch folks, let's see what they say.
