### ISSUE TITLE
How to use productstructurekernel when different dimension has different kernel?

### ISSUE THREAD

**Issue by mejliu** [cornellius-gp/gpytorch#770]
My `train_x` is a `N` by 3 matrix. For the first dimension, I want to use a general `RBF` kernel. For the second, I want to use a matern kernel. For the third dimension, I want to use a spectral mixture kernel. My kernel structure follows `k(x_1, x_2) = k(x_1^1, x_2^1) k(x_1^2, x_2^2) k(x_1^3, x_2^3)`. The example given in the tutorial is like following:
```
self.base_covar_module = ScaleKernel(RBFKernel())
        self.covar_module = ProductStructureKernel(
            GridInterpolationKernel(self.base_covar_module, grid_size=100, num_dims=1), num_dims=3
        )
```
I was trying to use `ProductStructureKernel` when different dimensions have different kernels, but somehow I failed. Can any one give an example. I will be very appreciated.

**Comment by gpleiss** [comment]
In this case, you should use a `ProductKernel` rather than a product structure kernel.

```python
self.covar_module = ScaleKernel(ProductKernel(
    RBFKernel(active_dims=[0,]),
    MaternKernel(nu=0.5, active_dims=[1,]),
    SpectralMixtureKernel(active_dims=[2,], ...),
)
```

See https://gpytorch.readthedocs.io/en/latest/kernels.html#productkernel for more information. Hope this helps!
