### ISSUE TITLE
GPU acceleration with IndependentModelList 

### ISSUE THREAD

**Issue by fonnesbeck** [cornellius-gp/gpytorch#771]
Looking at the docs, I can see how individual models can be accelerated with a GPU using the `cuda()` method on data tensors, and how `IndependentModelList` can be used to simultaneously fit sets of independent GPs. However, its not clear how best to accelerate  an `IndependentModelList` with a GPU. Is it helpful to use `cuda()` on the individual inputs for each model instance, or is there a way of applying this to the model list as a whole?

**Comment by Balandat** [comment]
Using `.cuda()` on the model list will put all the parameters and buffers for each model onto the gpu, but not their training data. You'll have to either construct the training data directly as cuda tensors, or move them over for each model.

**Comment by fonnesbeck** [comment]
Thanks. Got it working.
