### ISSUE TITLE
How to change the parameters in state_dict?

### ISSUE THREAD

**Issue by mejliu** [cornellius-gp/gpytorch#787]
I want to initialize a GP model using a stored `state_dict`. However, I want to keep the hyperparameters and change the `train_x` and `train_y`. Is there a way to do this? thanks.

**Comment by jacobrgardner** [comment]
`train_x` and `train_y` aren't stored in the state dict, so you should just be able to either initialize your GP object with the training data you actually want and then load the state dict or use the `set_train_data` method on an already created GP object: https://github.com/cornellius-gp/gpytorch/blob/caf712d2fa30f434cd707ec07224e2eea1f1d272/gpytorch/models/exact_gp.py#L48

**Comment by mejliu** [comment]
thanks for your quick reply. This is really helpful.
