### ISSUE TITLE
[Bug] SGPR Regularization different from Titias 2009?

### ISSUE THREAD

**Issue by KeAWang** [cornellius-gp/gpytorch#791]
# 🐛 Bug

The paper by [Titsias 2009](http://proceedings.mlr.press/v5/titsias09a.html) derives a trace regularization term for the loss function of variational SGPR which has a coefficient of Tr(T)/(2 * sigma^2). But the code here implements it as just Tr(T) / sigma https://github.com/cornellius-gp/gpytorch/blob/b4aee6f81a3428172d4914e7e0fef0e71cd1f519/gpytorch/mlls/inducing_point_kernel_added_loss_term.py#L15

Is there a reason for this difference?

**Comment by KeAWang** [comment]
Never mind I think it's because of the log

**Comment by KeAWang** [comment]
There's a factor of 1/2 from https://github.com/cornellius-gp/gpytorch/blob/b4aee6f81a3428172d4914e7e0fef0e71cd1f519/gpytorch/mlls/exact_marginal_log_likelihood.py#L35, but I think the noise should still be squared.

Also it seems weird to put the factor of 1/2 there instead of in `InducingPointKernelAddedLossTerm`

**Comment by jacobrgardner** [comment]
The squared issue is just a parameterization difference. For our likelihoods, `noise` directly returns the amount of diagonal noise we add.
