### ISSUE TITLE
[Bug] Error when I import gpytorch constraint

### ISSUE THREAD

**Issue by kellywzhang** [cornellius-gp/gpytorch#794]
# 🐛 Bug

I just installed gpytorch using conda. I get an error when I try to import constraints. 

## To reproduce

Python 3.7.2 (default, Dec 29 2018, 00:00:04)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gpytorch
>>> from gpytorch import constraints
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/py37/lib/python3.7/site-packages/gpytorch/constraints/__init__.py", line 1, in <module>
    from .constraints import GreaterThan, Interval, LessThan, Positive
  File "/miniconda3/envs/py37/lib/python3.7/site-packages/gpytorch/constraints/constraints.py", line 6, in <module>
    from ..utils.transforms import _get_inv_param_transform, inv_sigmoid, inv_softplus
ImportError: cannot import name 'inv_sigmoid' from 'gpytorch.utils.transforms' (/miniconda3/envs/py37/lib/python3.7/site-packages/gpytorch/utils/transforms.py)

## System information

**Please complete the following information:**
-  0.2.1
-  1.1.0
-  Mac

## Additional context
It looks like gpytorch.utils.transforms was recently updated based on the github repo: https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/utils/transforms.py

Let me know if there is an error on my side.

**Comment by jacobrgardner** [comment]
0.2.1 is quite an old version at this point -- does the problem still exist in 0.3.4 or on master? Everything seems to be working on my end.

**Comment by kellywzhang** [comment]
Ah, I didn't realize my version of gpytorch was old. It's fixed now. Thanks!
