### ISSUE TITLE
AttributeError: 'LazyEvaluatedKernelTensor' object has no attribute 'lazy_tensors'

### ISSUE THREAD

**Issue by Akella17** [cornellius-gp/gpytorch#803]
The ```gpytorch.settings.fast_pred_var()``` setting fails when I am using an additive kernel, i.e. a composition of an RBF kernel and Linear kernel. This however does not occur when the additive kernel is over two RBF kernels.

To reproduce this issue,
```Python
import torch
import gpytorch
import torch.nn as nn
from torch.autograd import Variable
import math

class GP_layer(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(GP_layer, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        
        self.covar_module_1 = gpytorch.kernels.RBFKernel(ard_num_dims=2, active_dims=torch.tensor([0,1]))
        self.covar_module_2 = gpytorch.kernels.LinearKernel(active_dims=torch.tensor([2,3]))
        self.covar_module = self.covar_module_1 + self.covar_module_2

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

train_x = torch.stack((torch.linspace(0, 10, 1500), torch.linspace(0.5, 10.5, 1500), torch.linspace(3, 14, 1500), torch.linspace(7.5, 19.5, 1500)),1).cuda()
train_y = (train_x[:,3]**2 - train_x[:,2])/10 + torch.cos(train_x[:,0] * (2 * math.pi)) + torch.sin(train_x[:,1] * (2 * math.pi)) + 0.1 * torch.randn(1500).cuda()

likelihood = gpytorch.likelihoods.GaussianLikelihood().cuda()
model = GP_layer(train_x, train_y, likelihood).cuda()
mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

model.train()
likelihood.train()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-3)

for _ in range(10):
    optimizer.zero_grad()
    outputs = model(train_x)
    loss = -mll(outputs, train_y).mean()
    loss.backward()
    optimizer.step()

model.eval()
likelihood.eval()

test_x = torch.stack((torch.linspace(0, 10, 17), torch.linspace(0.5, 10.5, 17), torch.linspace(3, 14, 17), torch.linspace(7.5, 19.5, 17)),1).cuda()
test_y = (test_x[:,3]**2 - test_x[:,2])/10 + torch.cos(test_x[:,0] * (2 * math.pi)) + torch.sin(test_x[:,1] * (2 * math.pi)) + 0.1 * torch.randn(17).cuda()

with gpytorch.settings.fast_pred_var():
    outputs_y = model(test_x).mean
print(outputs_y.size())
```

```
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    outputs_y = model(test_x).mean
  File "/home1/deepak/anaconda/envs/rl_proj/lib/python3.6/site-packages/gpytorch/models/exact_gp.py", line 265, in __call__
    predictive_mean, predictive_covar = self.prediction_strategy.exact_prediction(full_mean, full_covar)
  File "/home1/deepak/anaconda/envs/rl_proj/lib/python3.6/site-packages/gpytorch/models/exact_prediction_strategies.py", line 265, in exact_prediction
    self.exact_predictive_covar(test_test_covar, test_train_covar),
  File "/home1/deepak/anaconda/envs/rl_proj/lib/python3.6/site-packages/gpytorch/models/exact_prediction_strategies.py", line 332, in exact_predictive_covar
    test_train_covar)
  File "/home1/deepak/anaconda/envs/rl_proj/lib/python3.6/site-packages/gpytorch/models/exact_prediction_strategies.py", line 549, in _exact_predictive_covar_inv_quad_form_root
    self._sub_strategies, precomputed_cache, test_train_covar.evaluate_kernel().lazy_tensors
  File "/home1/deepak/anaconda/envs/rl_proj/lib/python3.6/site-packages/gpytorch/models/exact_prediction_strategies.py", line 515, in _sub_strategies
    for lazy_tensor in self.train_prior_dist.lazy_covariance_matrix.lazy_tensors:
AttributeError: 'LazyEvaluatedKernelTensor' object has no attribute 'lazy_tensors'

```

**Comment by gpleiss** [comment]
I just pushed a hot fix to master that fixes this issue.

**Comment by mohammadshams7201** [comment]
Hi there, when I ran this part of the dkl_mnist I faced the below error:

class DKLModel(gpytorch.GPModel):
    def __init__(self, feature_extractor, n_features=64, n_classes=10, grid_bounds=(-10., 10.)):
        likelihood = gpytorch.likelihoods.SoftmaxLikelihood(n_features=n_features, n_classes=n_classes)
        super(DKLModel, self).__init__(likelihood)
        
        self.feature_extractor = feature_extractor
        self.latent_functions = LatentFunctions(n_features=n_features, grid_bounds=grid_bounds)
        self.grid_bounds = grid_bounds
    
    def forward(self, x):
        features = self.feature_extractor(x)
        # Scale to fit insid egrid bounds
        features = gpytorch.utils.scale_to_bounds(features, self.grid_bounds[0], self.grid_bounds[1])
        res = self.latent_functions(features.unsqueeze(-1))
        return res
    
    
class LatentFunctions(gpytorch.AdditiveGridInducingPointModule):
    def __init__(self, n_features, grid_bounds, grid_size=128):
        super(LatentFunctions, self).__init__(grid_size=grid_size, grid_bounds=[grid_bounds],
                                             n_components=n_features, mixing_params=False, sum_output=False)
        cov_module = gpytorch.kernels.RBFKernel()
        cov_module.initialize(log_lengthscale=0)
        self.cov_module = cov_module
        
    def forward(self, x):
        mean = Variable(x.data.new(len(x)).zero_())
        covar = self.cov_module(x)
        return gpytorch.random_variables.GaussianRandomVariable(mean, covar)
    
    
model = DKLModel(feature_extractor)



---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\Users\MOHAMM~1\AppData\Local\Temp/ipykernel_10676/179094755.py in <module>
----> 1 class DKLModel(gpytorch.GPModel):
      2     def __init__(self, feature_extractor, n_features=64, n_classes=10, grid_bounds=(-10., 10.)):
      3         likelihood = gpytorch.likelihoods.SoftmaxLikelihood(n_features=n_features, n_classes=n_classes)
      4         super(DKLModel, self).__init__(likelihood)
      5 

AttributeError: module 'gpytorch' has no attribute 'GPModel'
