### ISSUE TITLE
[Question] Best way of implementing multiple kernels

### ISSUE THREAD

**Issue by arkottke** [cornellius-gp/gpytorch#806]
I am looking at implementing a model that is defined using the following kernels:
![image](https://user-images.githubusercontent.com/1033651/61829287-71eaab00-ae1d-11e9-9b6d-f4eb8cab2b39.png)
Five of the kernels are modified with exponential kernels with a constant offset (π) and the other five kernels are just scalars (θ).

Any suggestions on how to implement this kernel? I was thinking about either creating my own kernel class for the entire form, or just OffsetKernel that would be used in a similar way as the ScaleKernel (e.g., OffsetKerne(ScaleKernel(RBFKernel())).

When combining multiple kernels, is there anything that should be considered to improve performance?

Thanks.

**Comment by jacobrgardner** [comment]
Your base kernel is basically just `MaternKernel(nu=0.5)` (assuming the distances in your equation are correctly not squared -- if they are squared then obviously `RBFKernel`). Something like `OffsetKernel` would be reasonable.

In terms of combining multiple kernels, there aren't any particular performance issues you should have to worry about unless you start combining it with more complicated kernels like inducing point methods.
