### ISSUE TITLE
[Bug] Request to re-open: SpectralMixtureKernel initialize_from_data CUDA bug

### ISSUE THREAD

**Issue by adam-rysanek** [cornellius-gp/gpytorch#816]
I've written a comment on #737 . I am able to replicate that issue, and the advice suggested doesn't seem to work for me. I'm creating this new issue just to draw attention it to the response.

**Comment by jacobrgardner** [comment]
I've reopened #737

**Comment by adam-rysanek** [comment]
Thanks @jacobrgardner !
