### ISSUE TITLE
[Bug] Upstream changes to tensor comparisons breaks things

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#822]
# 🐛 Bug

After https://github.com/pytorch/pytorch/pull/21113 a bunch of tests are failing b/c of the change in tensor comparison behavior (return type from uint8 to bool). Creating this issue to track the fix.

**Comment by Balandat** [comment]
It appears most of this happens in `batch_symeig` where we do `1 - mask` - will put up a fix shortly.

**Comment by izdeby** [comment]
@Balandat, we have introduced '~' operator for masks to fix this issue. You should be able to just replace '1-mask' with '~mask'

**Comment by Balandat** [comment]
Sure that works. There are a few other places in the code where this causes failures, but they should be easy enough to fix.

**Comment by Balandat** [comment]
Fixed by #823

**Comment by Balandat** [comment]
Ok of course there are now a bunch more warnings emitted now when using uint8 on master, so all the tests that count the warnings fail there ...

**Comment by Balandat** [comment]
It's worse than that, the change actually breaks the jit script code for `_jit_linear_cg_updates`. So the correct thing is to use bool everywhere, and fix the tests that count the warnings...

**Comment by Balandat** [comment]
Won't be able to fix all this properly right now, deferring to the above issue.

**Comment by jacobrgardner** [comment]
@Balandat I'll take a look once the nightly build comes out and I can repro the errors without having to build pytorch from source.

**Comment by Balandat** [comment]
@jacobrgardner sounds good, if you base this on #825 at least you won't have to deal with the warnings.

**Comment by Balandat** [comment]
Fwiw, here's a notebook that shows the failure (commented out the jit decorators locally). 

It only happens when broadcasting. @izdeby, maybe broadcasting semantics for bool tensors are different?

[test_broadcasting_issues.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/3459249/test_broadcasting_issues.ipynb.txt)

**Comment by izdeby** [comment]
@Balandat, what exactly failed in broadcasting for you? there shouldn't be any difference in broadcasting semantics for bool tensors

**Comment by Balandat** [comment]
@izdeby looks like this is a different issue related to changing sizes in `addcmul`, see #827

**Comment by jacobrgardner** [comment]
For now do we think we could define like a `gpytorch.bool` type to be torch.bool if that will work (i.e. we are on master), and torch.uint8 otherwise?

**Comment by jacobrgardner** [comment]
We could similarly define `gpytorch.not` to do `~` and `1 - ...` respectively

**Comment by Balandat** [comment]
So `~` will work even with `uint8`, so there is no need for that. But we can do the `gpytorch.bool` thing to avoid the mass of warnings

**Comment by Balandat** [comment]
made this change in the latest update to #827

**Comment by jacobrgardner** [comment]
Reasonably fixed for now via #827
