### ISSUE TITLE
Make test more robust to emitted warnings

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#824]
Sometimes upstream changes will change the kind/amount of warnings emitted. Some tests count the number of emitted warnings, which is really brittle. Instead, if we're looking for a particular warning being emitted or not, we should explicitly check for that instead. 

See #822 for more context.

**Comment by gpleiss** [comment]
Oooof I guess we should check the types of errors that we're getting.... good catch.

**Comment by Balandat** [comment]
Fixed by #825
