### ISSUE TITLE
[Docs] About Bayesian optimization tutorial

### ISSUE THREAD

**Issue by yjhong89** [cornellius-gp/gpytorch#826]
# 📚 Documentation/Examples

Thanks for great work.

I am new to gpytorch and bayesian optimization.

There are several libraries supporting GP and bayesian optimization, but I decide to work with gpytorch and potentially BoTorch.

I looked into examples but I coudn`t find bayesian optimization examples (saied to be released soon.)

Can you let me know any simple bayesian optimizatino examples? (simple acquisition function such as Expected Improvement would be fine).

Thanks in advance.

**Comment by gpleiss** [comment]
Hi @yjhong89 - you should take a look at the [BoTorch tutorials](https://botorch.org/tutorials/). Also, if you're looking for a very simple Bayesian optimization interface, I would check out the [Ax tutorials](https://ax.dev/tutorials/), which is a package that wraps BoTorch. This gives you a high-level interface.
