### ISSUE TITLE
error in example - new data 

### ISSUE THREAD

**Issue by andrewczgithub** [cornellius-gp/gpytorch#828]
Hi @dougalsutherland @jmhessel 

Hi I am trying the below example with new data
https://github.com/cornellius-gp/gpytorch/blob/master/examples/03_Multitask_GP_Regression/Multitask_GP_Regression.ipynb

model.train()
likelihood.train()

Use the adam optimizer
optimizer = torch.optim.Adam([
{‘params’: model.parameters()}, # Includes GaussianLikelihood parameters
], lr=0.1)

“Loss” for GPs - the marginal log likelihood
mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

n_iter = 50
for i in range(n_iter):
optimizer.zero_grad()
output = model(train_x)
loss = -mll(output, train_y)
loss.backward()
print(‘Iter %d/%d - Loss: %.3f’ % (i + 1, n_iter, loss.item()))
optimizer.step()

RuntimeError Traceback (most recent call last)
in ()
16 optimizer.zero_grad()
17 output = model(train_x)
—> 18 loss = -mll(output, train_y)
19 loss.backward()
20 print(‘Iter %d/%d - Loss: %.3f’ % (i + 1, n_iter, loss.item()))

3 frames
/usr/local/lib/python3.6/dist-packages/gpytorch/distributions/multivariate_normal.py in log_prob(self, value)
112
113 mean, covar = self.loc, self.lazy_covariance_matrix
–> 114 diff = value - mean
115
116 # Repeat the covar to match the batch shape of diff

RuntimeError: expected backend CPU and dtype Double but got backend CPU and dtype Float

I am getting a runtime error i have two tensors one x and two y values and I am trying the multitask example.

**Comment by jacobrgardner** [comment]
This means you are passing in data or other tensors that are float but have made one of your modules the other data type. Are you converting your data from numpy? The default data type in numpy is double, while in torch it is float.

**Comment by andrewczgithub** [comment]
Hi @jacobrgardner 
I was using a pandas data array.
How do I convert a pandas data array to the suitable data structure.
Best,
Andrew

**Comment by jacobrgardner** [comment]
`torch.tensor(df.values, dtype=torch.float32)`

**Comment by andrewczgithub** [comment]
mate champion!
This issue can now be considered closed.
Thank you so much for your help.
Best,
Andrew
