### ISSUE TITLE
[Docs] Multiple-Dimension-Feature GP Regression Example

### ISSUE THREAD

**Issue by Micha-93** [cornellius-gp/gpytorch#829]
# 📚 Documentation/Examples

** Is there documentation missing? **

** Is documentation wrong? **

** Is there a feature that needs some example code? **

** Think you know how to fix the docs? ** (If so, we'd love a pull request from you!)

- Link to [GPyTorch documentation](https://gpytorch.readthedocs.io)
- Link to [GPyTorch examples](https://github.com/cornellius-gp/gpytorch/tree/master/examples)

**Comment by Micha-93** [comment]
Hello everybody,
im new to Gpytorch and have done the simple and Multitask GP Regression examples and tried to add a second dimension to the feature x and failed. Is there any example that shows Multidimensional Feature and Target Regression?
Thank you all very much,
Micha

**Comment by gpleiss-asapp** [comment]
Hi @Micha-93 - can you send us a code example/error message for why it isn't working? It should be as simple as replacing your single dimensional input (size `n`) with a multi-dimensional input (size `n x d`).

Here's an example notebook which uses an input with multiple examples: https://gpytorch.readthedocs.io/en/latest/examples/01_Simple_GP_Regression/Simple_GP_Regression_With_LOVE_Fast_Variances_CUDA.html. Getting multiple outputs should be as simple as replacing the model with the MultitaskKernel.

**Comment by gpleiss** [comment]
Hi @Micha-93 - can you send us a code example/error message for why it isn't working? It should be as simple as replacing your single dimensional input (size n) with a multi-dimensional input (size n x d).

Here's an example notebook which uses an input with multiple examples: https://gpytorch.readthedocs.io/en/latest/examples/01_Simple_GP_Regression/Simple_GP_Regression_With_LOVE_Fast_Variances_CUDA.html. Getting multiple outputs should be as simple as replacing the model with the MultitaskKernel.

**Comment by Micha-93** [comment]
Thank you for the fast respont. I found my fault in the dimension of the imputs. Now it works! thanks for the example, too.
