### ISSUE TITLE
Periodic kernel for multivariate input

### ISSUE THREAD

**Issue by yeahrmek** [cornellius-gp/gpytorch#835]
# 🐛 Bug

Implementation of PeriodicKernel is not positive definite in case of multivariate input
Here is how I checked it:

** Code snippet to reproduce **
```python
import torch
from gpytorch import kernels

X = torch.randn(1000, 2, dtype=torch.float64)
kernel = kernels.PeriodicKernel().double()
with torch.no_grad():
    K = kernel(X, X).evaluate()
    eig = torch.symeig(K)[0]

    negative_eig = eig[eig < 0]
    assert torch.allclose(negative_eig, torch.zeros_like(negative_eig))
```

** Stack trace/error message **
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-1d738d7c73d9> in <module>
      9 
     10     negative_eig = eig[eig < 0]
---> 11     assert torch.allclose(negative_eig, torch.zeros_like(negative_eig))

AssertionError: 
```

## Expected Behavior

Positive definite kernel must have non-negative eigenvalues.

##
The implementation is correct for one-dimensional input. For multidimensional input it should be product of one-dimensional kernels, however, it calculates the norm first and applies sine and exponent to the norm which is not correct: see eq. (47) on page 15 of
> MacKay, D. J. (1998). Introduction to Gaussian processes. NATO ASI Series F Computer and Systems Sciences, 168, 133-166.

## System information

**Please complete the following information:**
- gpytorch=0.3.4
- torch=1.1.0
- Ubuntu 19.04

**Comment by yeahrmek** [comment]
The same for the Cosine kernel

**Comment by jacobrgardner** [comment]
The periodic kernel is by definition a kernel defined in 1D. To extend to multiple dimensions use e.g. ProductKernel

**Comment by yeahrmek** [comment]
But the implementation and docs (see example [in documentation](https://gpytorch.readthedocs.io/en/latest/kernels.html#periodickernel)) allows multi-dimensional input. In other GP packages (e.g. GPy) periodic kernel is implemented as I mentioned in my previous comment.
So, I think it should be implemented as a product of one-dimensional periodic kernels or the exception should be raised for multi-dimensional inputs.

**Comment by jacobrgardner** [comment]
Sure, that's reasonable! I'll put up a PR that automatically has it product over the dimensions.

**Comment by gpleiss** [comment]
@tawe141 I don't think we ever got around to this. If you're interested and willing, we'd love a PR from you!
