### ISSUE TITLE
How to modify IndexKernel?

### ISSUE THREAD

**Issue by Jonas-Metzger** [cornellius-gp/gpytorch#848]
I'd like to perform multitask regression with a custom IndexKernel, which only learns two parameters: one covariance factor for observations coming from the same task and another factor for observations coming from different tasks. I'd like to use this structure in order to generalize to tasks not seen during training, which wouldn't be possible using the regular IndexKernel.

What would be the easiest way to achieve this with the existing tools? Thank you!

**Comment by jacobrgardner** [comment]
@Jonas-Metzger Will it be the case that each point is observed for all tasks? The answer to your question depends on this a bit.

**Comment by Jonas-Metzger** [comment]
@jacobrgardner Thank you for your answer! Yes, that can be assumed.

**Comment by Jonas-Metzger** [comment]
Would something like this work? Assuming `i` is a `n * 1` tensor containing the task indices of the observations. I'm having trouble finding out whether this behaves and trains as I want it to. The idea is to multiply the covariance between any two observations with 1 if they're from the same task according to `i`, and with `1-self.task_factor` if they're not.

```
class CustomMultitaskGP(gp.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super().__init__(train_x, train_y, likelihood)
        self.mean_module = gp.means.ConstantMean(),
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel)
        self.task_factor = torch.nn.Parameter(torch.tensor(1))

    def forward(self, x, i):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        notsame = (i.transpose(0,1).expand([len(i)]*2) != i.expand([len(i)]*2)).to(torch.float)
        covar_i = 1 - self.task_factor * notsame
        covar = covar_x.mul(covar_i)
        return gp.distributions.MultitaskMultivariateNormal(mean_x, covar)
```
