### ISSUE TITLE
How to scale a covariance matrix by a constant factor?

### ISSUE THREAD

**Issue by Akella17** [cornellius-gp/gpytorch#850]
My objective is to scale the covariance matrix of a Linear kernel, i.e. multiply each element in it with a constant factor. I tried using the ```.mul()``` operation inside the kernel definition but the output did not change. More precisely, the value of

```Python
>>> (random_vector * likelihood(model(input)).lazy_covariance_matrix.inv_matmul(random_vector)).sum(0)
```
remained the same (while I expected it to decrease by the same constant factor). Am I missing something here? @jacobrgardner @gpleiss

Please find the [example iPython notebook](https://drive.google.com/file/d/1Dg1bEb3_5g9Rf-BIBT71kyj4Q2aMy9p0/view?usp=sharing) that demonstrate this issue.

**Comment by jacobrgardner** [comment]
@Akella17 in your example notebook you aren't actually using your defined linear kernel as the kernel, you are using just an RBF kernel:
```python
class GP_model(gpytorch.models.ExactGP):
    def __init__(self, likelihood, train_x = None, train_y = None):
        super(GP_model, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.RBFKernel().cuda()
```

**Comment by Akella17** [comment]
@jacobrgardner That was my bad. I fixed this in the [iPython notebook](https://drive.google.com/file/d/1Dg1bEb3_5g9Rf-BIBT71kyj4Q2aMy9p0/view?usp=sharing). Also, I think I found the bug. When I wrap a covariance matrix with **likelihood**, the ratio becomes 1. However, when I directly try to use the covariance matrix, I am getting the expected ratio.

Please correct me if I am wrong, but isn't 
likelihood(model(inputs)).lazy_covariance_matrix = model(inputs).lazy_covariance_matrix + &sigma;<sup>2</sup>I
Because if that is the case, how do I find ```likelihood(model(inputs)).lazy_covariance_matrix.inv_matmul(vec)```, where the covariance is scaled by a constant factor.

**Comment by Shandilya21** [comment]
Hey! I am also facing the same issue. Have you found any solution for this? @Akella17 @jacobrgardner
