### ISSUE TITLE
Non equal-sized grids for GridInterpolationKernel

### ISSUE THREAD

**Issue by eytan** [cornellius-gp/gpytorch#853]
# 🚀 Feature Request

Currently GridInterpolationKernel assumes that the grid size is equal along all dimensions.  I would like to specify the grid size along the x,y or x,y,z axes.

## Motivation

**Is your feature request related to a problem? Please describe.**
In many spatiotemporal applications where GridInterpolationKernel would be very handy, one may have cases where the x and y widths that differ (e.g., for data that is longer than shorter), and may have much longer or shorter z widths (e.g., if time is measured by year or day or hour).
 
## Pitch

**Describe the solution you'd like**
I'd like to specify a tuple for `grid_size`, much like how I can specify the `grid_bounds`.

It looks like it could be easy for me to hack this by modifying `GridInterpolationKernel._create_grid()` but I am not sure if this would mess other things up and how you feel about allowing `grid_size` to optionally be a tuple.

**Describe alternatives you've considered**
I would consider using SGPR if I can't use GridInterpolationKernel.

**Comment by eytan** [comment]
Awesome, thanks @jacobrgardner !

**Comment by jacobrgardner** [comment]
Closed by #888.
