### ISSUE TITLE
[Docs] no GPU section

### ISSUE THREAD

**Issue by deltaskelta** [cornellius-gp/gpytorch#862]
# 📚 Documentation/Examples

** Is there documentation missing? **

The GPU docs that are linked to in the docs [here](https://gpytorch.readthedocs.io/en/latest/examples/README.html?highlight=gpu#id1) are missing

the missing doc page is...

https://gpytorch.readthedocs.io/en/latest/examples/01_Simple_GP_Regression/Simple_GP_Regression_CUDA.ipynb

I have tried to call `.cuda()` on a torch tensor but it appears to still be a cpu tensor, is cuda currently supported by gpytorch?

**Comment by KeAWang** [comment]
Yes gpytorch supports cuda (in fact we recommend using GPU or GPUs to speed up computations or scale to larger datasets.

If you're calling `.cuda` on a `torch.Tensor` and getting a CPU tensor, then there must be something wrong with your setup preventing pytorch from detecting your GPU device.

**Comment by KeAWang** [comment]
See https://github.com/cornellius-gp/gpytorch/blob/master/examples/01_Simple_GP_Regression/Simple_GP_Regression_With_LOVE_Fast_Variances_CUDA.ipynb or https://github.com/cornellius-gp/gpytorch/blob/master/examples/01_Simple_GP_Regression/Simple_MultiGPU_GP_Regression.ipynb for example

**Comment by deltaskelta** [comment]
Thanks, I missed some simple details
