### ISSUE TITLE
Windows installation problem

### ISSUE THREAD

**Issue by Quenjy** [cornellius-gp/gpytorch#87]
Hello,

I'm currently trying to install gpytorch for Windows 10 and keep running into errors. I have installed both pytorch v0.3.1 and gotten the fftw-3.3.5-dll64 files, which I have added to my path.

The first error happened when I ran the "conda install fftw cffi pytorch torchvision cuda80 -c conda-forge -c pytorch" command. I kept running into this error

![image](https://user-images.githubusercontent.com/11042499/37590678-570cd052-2b69-11e8-9ea3-64471a44ef70.png)

yet torchvision shows up in conda list
![image](https://user-images.githubusercontent.com/11042499/37590619-27cf8f5a-2b69-11e8-8ee2-141e63364ab9.png)

I tried installing without torchvision as a requirement (I know it's not the greatest idea, I was mostly curious). The installation worked, but when I tried to run the second command, i.e "pip install git+https://github.com/cornellius-gp/gpytorch.git" I ran into this

![image](https://user-images.githubusercontent.com/11042499/37590799-addfceca-2b69-11e8-96d0-acc94aee7791.png)

I have spent the last hour or so going from stackoverflow thread to stackoverflow thread, I have uninstalled and reinstalled pretty much everything I could (pip, setuptools...) but nothing has worked so far.

Would you be able to tell me what causes this? Thanks

**Comment by jrg365** [comment]
I think the issue might be as simple as we haven't tested GPyTorch (or PyTorch for that matter) on Windows directly -- only on the windows subsystem for linux. You shouldn't need torchvision for anything other than the Mnist example where I think we use it to download mnist. As for the error you are getting, it might be that the file has linux path specifications in it?

I think I remember reading torchvision is explicitly not compatible with Windows.

I will take a look at trying to install it directly on Windows this week, but my recommendation if you are amenable to it would just be to use the linux version of anaconda via the windows subsystem for linux. That's my setup on my laptop, so I know it works.

**Comment by Quenjy** [comment]
Alright, thank you for the quick answer!
I haven't worked with the windows subsystem for linux yet, but I will try that out soon

Feel free to close this thread when you see fit, which might be now or after you have tested your own installation to give a conclusion, I'll probably reopen it if it still doesn't work.

**Comment by gpleiss** [comment]
Now that we've switched to PyTorch 0.4, which supports Windows (officially), I'm imagining that everything should work! @Quenjy give it a shot?
