### ISSUE TITLE
Deprecate last_dim_is_batch?

### ISSUE THREAD

**Issue by KeAWang** [cornellius-gp/gpytorch#881]
Now that we support arbitrary batch shapes in gpytorch, it seems to me that `last_dim_is_batch` should be deprecated from the arguments of `Kernel`s. The reason for this is that this would simplify the interface of Kernels and further make it easier to implement a custom kernel, and more understandable. This would also allow us to reduce the case considerations in our code. Instead of having to first check if `last_dim_is_batch` AND testing that the `Kernel` handles batch mode correctly, we will only need to do the latter.

# Modules that will be modified
Todo

# Impact on speed
Negligible but it makes the code a cleaner, especially to people who want to build their own custom `Kernel`s.

# Will this be a breaking change?
Yes

**Comment by jacobrgardner** [comment]
`last_dim_is_batch` exists because we want to allow for the option to reinterpret the data dimension as a batch dimension. For example, if you want to implement product and additive structure efficiently, it's nice for people to still be able to pass in `n x d` data and have the transformation to `n x d x 1` data happen internally.

If we removed this, users would have to start creating their data directly as `n x d x 1` data to achieve this I think.

**Comment by KeAWang** [comment]
I think they can still still keep their data `n x d`. The only difference is that when we forward pass through an additive/product kernel, the implementer of the additive/product kernel would be the one responsible for reshaping the data before passing it to the base kernel, which seems like the right thing to do. That way, an implementer of a base kernel would only need to make sure that the base kernel does the right thing on batch data

**Comment by gpleiss** [comment]
I'd be very reluctant to change this, as it would be a massive breaking change for any of the additive structure/SKIP models.

The current implementation of SKIP is the following:
```python
...
# In init
self.covar_module = gpytorch.kernels.ProductStructureKernel(gpytorch.kernels.RBFKernel())
...
```

The new implementation would be
```
...
# In init
self.covar_module = gpytorch.kernels.RBFKernel()
...

# In forward
covar = self.covar_module(input.transpose(-1, -2).unsqueeze(-1)).prod(-3)
```

The latter is definitely more confusing for the average user (who is unlikely to be implementing custom kernels).

**Comment by gpleiss** [comment]
@jacobrgardner and I also discussed getting rid of the `last_dim_is_batch` argument when we were implementing the arbitrary batch dimensions (the last time we made big breaking changes). We decided to keep it for these reasons.

**Comment by KeAWang** [comment]
What I was thinking of was 
```
# For the implementer of a new kernel
# In init
self.covar_module = gpytorch.kernels.ProductStructureKernel(MyNewKernel())

# in forward
covar = self.covar_module(input)
```
but modify it so that in `ProductStructureKernel` we have
```
def forward(self, x1, x2, diag=False, last_dim_is_batch=False, **params):
        x1 = x1.transpose(-1, -2).unsqueeze(-1)
        x2 = x2.transpose(-1, -2).unsqueeze(-1)
        res = self.base_kernel(x1, x2, diag=diag, **params)
        res = res.prod(-2 if diag else -3)
        return res
```

This way, `MyNewKernel` would only have to worry about correctly implementing batch mode as opposed to implementing BOTH batch mode and handling `last_dim_is_batch`. The onus is then on `ProductStructureKernel` (or some other new kernel) to use batch mode correctly.

**Comment by gpleiss** [comment]
That was the implementation we had about a year ago. We had to change it because that implementation breaks with ARD kernels or batch-specific parameters.

Without having the user do the specific work in the forward pass, there’s really not a way to get around last_dim_is_batch
