### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by Sabina321** [cornellius-gp/gpytorch#885]
# 📚 Documentation/Examples

It seems like this link is broken. 
[https://gpytorch.readthedocs.io/en/latest/examples/01_Simple_GP_Regression/Simple_GP_Regression_CUDA.ipynb]

Is there another place to get information on how to run gpytorch with a gpu?

**Comment by jacobrgardner** [comment]
@Sabina321 I'll put together the missing notebook as soon as I can.

In the mean time, we have a few other example notebooks that do use cuda. The process is essentially the same as for any pytorch model. You pretty much want to run:
```python
train_x = train_x.cuda()
train_y = train_y.cuda()
model = ExactGP(train_x, train_y, likelihood).cuda()
```
And then train / test as normal.

**Comment by Sabina321** [comment]
Hi Jake, 

Thanks, I got that together from some other notebooks, but now I'm running out of memory so I"ll have to try the multi-gpu example.

**Comment by jacobrgardner** [comment]
@Sabina321 actually, my recommendation would be to try the KeOps example first and see if it's fast enough before worrying about multiple GPUs. `pip install pykeops[full]` should be enough to get up and running with that notebook.

**Comment by gpleiss** [comment]
Just pushed the CUDA notebook. The link should be fixed.
