### ISSUE TITLE
Iterator for Actual Parameters

### ISSUE THREAD

**Issue by sberglin** [cornellius-gp/gpytorch#908]
# 🚀 Feature Request

I would like to iterate over the actual parameters, rather than the raw parameters through `model.named_parameters()`.

## Motivation

I am making plots of how the actual parameters change over training. As of now, I transform the raw parameters to do this.

However, I understand that we can elegantly access the actual parameters through removing `_raw` from the parameter name. For example, we can access the actual outputscale for `model.covar_module.raw_outputscale` with `model.covar_module.outputscale` rather than transforming it. But I have not found a way to iterate over all these parameters for the model, rather than accessing specific ones.

If there is an elegant way to do this that I am missing, please let me know!

## Pitch

`model.actual_named_parameters()` which iterates over the actual parameters instead.

**Comment by jacobrgardner** [comment]
GPyTorch Modules have a `named_parameters_and_constraints` method that returns (name, param, constraint) tuples. If you iterate over this and use the constraint (if not None) to transform the parameter, this should get you what you want, right?

**Comment by sberglin** [comment]
You are totally right! Thanks for the help.
