### ISSUE TITLE
GPyTorch Does Not Find FFTW Installation From Conda Forge

### ISSUE THREAD

**Issue by jrg365** [cornellius-gp/gpytorch#91]
Similar to #89, I and Eric (who I just met with and showed me this) can verify that it seems like the standard installation instructions don't find fftw as installed from conda-forge.

Things do work when installing fftw from source or from `apt-get`, so we should either figure out how to add the correct paths to where conda installs fftw, or change the installation instructions to recommend installing from `apt-get` or from source.

**Comment by gpleiss** [comment]
Closed by #92
