### ISSUE TITLE
Does the prediction always calculate posterior covariance? 

### ISSUE THREAD

**Issue by Alaya-in-Matrix** [cornellius-gp/gpytorch#910]
Is there a way to only calculate the posterior mean and variance of each data point?

**Comment by samuelstanton** [comment]
All you need to do is
```
model.eval()
out = model(test_x)
mean = out.mean
variance = out.variance
```
Since the covariance matrix is lazily computed, the full covariance matrix is only computed if you call
`out.covariance_matrix.evaluate()`
