### ISSUE TITLE
[Example] create example notebook for GPs with uncertain inputs

### ISSUE THREAD

**Issue by gpleiss** [cornellius-gp/gpytorch#914]
Based on #659 and #913, we probably want some examples that show how to train GPs with uncertain inputs.

1) Inputs with known uncertainty - can be trained using SVGP, where we sample from the distribution of inputs

2) Unknown inputs that we want to impute - should be done using Pyro

**Comment by eytan** [comment]
I’d be curious to see a solution for this for exact GPs in the small data regime.

**Comment by gpleiss** [comment]
I believe you need approximate inference when you have input noise: https://papers.nips.cc/paper/2313-gaussian-process-priors-with-uncertain-inputs-application-to-multiple-step-ahead-time-series-forecasting.pdf
