### ISSUE TITLE
How to freeze the task parameters and the mean parameters during optimization

### ISSUE THREAD

**Issue by Galto2000** [cornellius-gp/gpytorch#931]
Howdy folks

I would like to be able to freeze the parameters pertaining to the task covariance and the parameters pertaining to the means. The idea is that I'd like to re-train my kernel on new data, but without messing with the aforementioned parameters.

I like the approach where I provide a list of param dictionaries to the optimizer in order to select the parameters that I want the optimizer to adjust, but how would I go about getting a param dict containing the mean and the one for the task covar parameters?

Thanks in advance

Galto

**Comment by jacobrgardner** [comment]
Torch optimizers also deal with generators so you could probably do something like

`(param for param in model.parameters() if param not in model.covar_module.parameters())`

If it's just a few parameters though I might just set them to `requires_grad = False`

**Comment by Galto2000** [comment]
Thank you @jacobrgardner for the tip on using generators
