### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by SHIMONSHEIBA** [cornellius-gp/gpytorch#933]
# 📚 Documentation/Examples

Hi!

Thanks for this amazing package, I am learning a lot about GPs thanks to it.
I am not sure that this is the right place for my (many) questions, if not please refer me to the more suitable address.

I am currently writing my code based on - "Large-Scale Stochastic Variational GP Regression (CUDA) (w/ KISS-GP)", due to hardware limitation + dataset size of ~ 120k * 90.

I have some questions / attempts that I would like to try and couldn't find the right documentation for an **AbstractVariationalGP** implementation, which makes me think that maybe it doesn't exist yet.
1. Use of LCM kernel 
2. Building a custom kernel class, incorporating my own mathematical formula.
2. Insertion of hetroskedastic noise 
3. Replacing the gaussian likelihood with for example student t
4. In the evaluation phase, I am using data loaders in the same training batch size, because I am facing with CUDA memory issues while predicting on entire test, thanks to a combination of kernels that I am performing on different parts of the data. I was wondering if it is problematic to infer in that manner, while the grid interpolation + scaling grid bounds in the variational strategy might affect the values in different batch size. (you refer to CIFAR example to see how to evaluate batch wise, do you mean Deep Kernel Learning (DenseNet + GP) on CIFAR10/100? if so, couldn't find it there)
5. What is the right way to infer on a single test point, while using CholeskyVariationalDistribution(GridInterpolationVariationalStrategy)?

6. I would appreciate knowing what assumptions this variational strategy mentioned above holds, about the kernel / input, for example in terms of grid size & bounds. Since I am changing the kernel structure, and hopefully if I will have enough memory, will change the output shape of the feature extractor as well. In the meantime I am simply forwarding the feature extractor layer output regularly in the GPRegressionLayer, while another "external" input through a different covariance module, and then combining them.
code:
class GPRegressionLayer(AbstractVariationalGP):
    def __init__(self, kernel, month_kernel, covar_weight=None, constant_mean=0, grid_size=32, deep_mean=False, # grid_bounds=[(-1, 1), (-1, 1)],
                 features_embedding_size=2, additive_strategy=False):
        grid_bounds = [(-1, 1)]*(features_embedding_size) 
        variational_distribution = CholeskyVariationalDistribution(num_inducing_points=grid_size*grid_size)
        if additive_strategy:
            variational_strategy = gpytorch.variational.AdditiveGridInterpolationVariationalStrategy(
                self, grid_size=grid_size, grid_bounds=[grid_bounds], num_dim=features_embedding_size,
                variational_distribution=variational_distribution, mixing_params=False, sum_output=False
            )
        else:
            variational_strategy = GridInterpolationVariationalStrategy(self,
                                                                    grid_size=grid_size,
                                                                    grid_bounds=grid_bounds,
                                                                    variational_distribution=variational_distribution)
        super(GPRegressionLayer, self).__init__(variational_strategy)
        self.mean_module = gpytorch.means.ConstantMean()
        self.mean_module.initialize(constant=constant_mean)
        if not deep_mean:
            self.mean_module.constant.requires_grad = False
        self.covar_module = gpytorch.kernels.ScaleKernel(kernel)
        self.covar_module_test_month = gpytorch.kernels.ScaleKernel(month_kernel)
        self.covar_weight = covar_weight

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

    def forward_2(self, x):
        # calculate mean and covar for test month column
        test_month_mean_x = self.mean_module(x[:, -1])
        test_month_covar_x = self.covar_module_test_month(x[:, -1])
        # forward original layer only with embedded features
        mult_norm_dist = self(x[:, :-1])
        # combine priors
        combined_covar_matrix = test_month_covar_x * mult_norm_dist.covariance_matrix
        combined_mean = test_month_mean_x + mult_norm_dist.mean
        return gpytorch.distributions.MultivariateNormal(combined_mean, combined_covar_matrix)

Cheers,
Shimon

**Comment by gpleiss** [comment]
1. The variational interface changed with #903 but the documentation/examples have not been updated yet. I'll add an example for multi-task variational GPs.

2. See [the kernel documentation](https://gpytorch.readthedocs.io/en/latest/kernels.html). See the source code for PolynomialKernel for a simple example.

3. See the [HeteroskedasticNoise class](https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/likelihoods/noise_models.py#L96). This can be added to a `GaussianLikelihood` using `heteroskedastic_noise_model = HeteroskedasticNoise( ... ); GaussianLikelihood(noise_model=heteroskedastic_noise_model)`.

4. We don't have a student t likelihood. You'd have to implement one yourself. See the likelihood documentation for info.

5. Using the same batch size shouldn't hurt

6. Make sure the single test point is shaped in a `1 x d` tensor.

7. The variational strategy assumes that your inducing points lie on a grid and that your kernel is stationary. See https://arxiv.org/abs/1611.00336 for more info.

**Comment by cherepanovic** [comment]
> The variational interface changed with #903 but the documentation/examples have not been updated yet. I'll add an example for multi-task variational GPs.

@gpleiss , what are exact the changes? Could you provide the papers, thanks!

**Comment by gpleiss** [comment]
@cherepanovic the papers haven't changed. We just refactored the interface.
