### ISSUE TITLE
[Discussion] Contributing

### ISSUE THREAD

**Issue by jahall** [cornellius-gp/gpytorch#935]
I would be keen to contribute more regularly to this project as I think it is awesome. Just wondering what the most useful way to go about this would be? Do you have a backlog of bugs/enhancements/documentation for which you would welcome additional help? Or maybe you have sufficient support, which is also fine...

**Comment by gpleiss** [comment]
Hi @jahall - we would love to have you as a regular contributor :D 

I went through and marked some open issues with "help wanted" and "good first issue" - feel free to tackle any of those! There's a mix of creating missing examples, implementing new kernels/likelihoods, and some bug fixes.

In general, is there a part of the package/type of model that you typically use (e.g. multitask models, variational models, etc.)?

**Comment by jahall** [comment]
Great stuff, this is helpful, thanks! Will take a look.
