### ISSUE TITLE
[Docs] Example setting (local or cubic) interpolation matrix in KISS-GP?

### ISSUE THREAD

**Issue by joacorapela** [cornellius-gp/gpytorch#942]
Is there any example piece of KISS-GP code setting the local or cubic interpolation matrix?
J.

**Comment by gpleiss** [comment]
Sorry, what do you mean by "setting" the cubic interpolation matrix?
To use KISS-GP wrap your base kernel with `GridInterpolationKernel`. See [this example](https://gpytorch.readthedocs.io/en/latest/examples/04_Scalable_GP_Regression_1D/KISSGP_Regression_1D.html).

**Comment by joacorapela** [comment]
Thanks for your reply Geoff. I will look at the code in kernels/grid_interpolation_kernel.py

I don't want to use KISS-GP for GP regression. I want to use it in a GP latent variables model (Duncker and Sahani, 2018). Thus, I was not planning to use GPyTorch kernels in my code. But I will look at the code in class GridInterpolationKernel to learn how to incorporate kernel interpolation in my code, or I may change my mind and use GPyTorch kernels in my code.

Thanks again, Joaquin
