### ISSUE TITLE
[Feature Request] Allow instantiating MVNs using scale_tril

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#962]
# 🚀 Feature Request

We should allow instantiating gpytorch `MultivariateNormal` using `scale_tril`.

## Motivation

I'd like to instantiate a transformed MVN from an MVN where I already have the `scale_tril` root decomposition. If I can perform the transform directly on `scale_tril` then I can save a bunch of time using the transformed `scale_tril`. This is currently not easily possible b/c the gpytorch MVN doesn't allow easy construction using this.

My particular use case is performing transformation of posteriors for `MultitaskMultivariateNormal`s.

**Comment by jacobrgardner** [comment]
Would the behavior be substantially different from `MultivariateNormal(mean, CholLazyTensor(scale_tril))`? I'm all for allowing `scale_tril=` in the constructor, but it might just be a one liner.

**Comment by Balandat** [comment]
Hmm good point, this should cover most of it. Let me see if there's anything I'm missing.

**Comment by Balandat** [comment]
Hmm yeah looks like this works, given how I had initially set up the MVN to overwrite `_unbroadcasted_scale_tril` to handle lazies.
