### ISSUE TITLE
batch GridInterpolationKernel [Feature Request]

### ISSUE THREAD

**Issue by samuelstanton** [cornellius-gp/gpytorch#963]
# 🚀 Feature Request

Add support for batched SKI kernel approximations. I'm not sure how one would go about adding this functionality. Ideally `GridInterpolationKernel` would infer the batch shape from `base_kernel`.

If this can't be done soon, we should add a warning that GridInterpolationKernel doesn't support batch evaluation. Currently it seems to fail silently by producing incorrectly shaped outputs. 

```
>>> import torch
>>> import gpytorch
>>> base_kernel = gpytorch.kernels.RBFKernel(batch_shape=torch.Size([2]))
>>> ski_kernel = gpytorch.kernels.GridInterpolationKernel(base_kernel, num_dims=1, grid_size=128)
>>> a = torch.rand(2)
>>> ski_kernel(a, a).shape
torch.Size([2, 2])
>>> base_kernel(a, a).shape
torch.Size([2, 2, 2])
```

## Motivation

In general for multi-dimensional outputs we have to train and evaluate multiple GPs in parallel. Currently this functionality appears to be completely absent in `GridInterpolationKernel`. I think SKI could have compelling applications in the context of online model learning, where one may be unable or unwilling to solve a slowly converging variational optimization problem.

## Pitch

Ultimately it would be amazing if `batch_shape` could be added as an argument to the `GridInterpolationKernel` constructor, or inferred from the base kernel. I'm not sure how much work this would involve.

One alternative could be relying on a multitask-like approach, but this requires memory usage that scales quadratically with the output dimension, which quickly becomes impractical. 

I'd be willing to open a pull request, but I'd need some pointers for how to get started. How was arbitrary batch_shape supported in the first place?

**Comment by gpleiss** [comment]
I just put up a PR to fix this. There were some issues with broadcasting if the kernel had batch hypers.
