### ISSUE TITLE
ImportError: cannot import name 'ApproximateGP' [Bug]

### ISSUE THREAD

**Issue by PingjunChen** [cornellius-gp/gpytorch#978]
# 🐛 'ApproximateGP' ImportError

## To reproduce

** Code snippet to reproduce **
```python
from gpytorch.models import ApproximateGP
```

** Stack trace/error message **
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-bb3a720fdf62> in <module>
----> 1 from gpytorch.models import ApproximateGP

ImportError: cannot import name 'ApproximateGP'
```

## Expected Behavior
Import without error. I tried this import on multiple machines, including two ubuntu machines and one Mac, all have this import error. 

## System information
- GPyTorch Version: 0.3.6
- PyTorch Version: 1.3.1
- Computer OS: ubuntu 16.04 LTS

**Comment by gpleiss** [comment]
ApproximateGP is only available on the master branch of GPyTorch right now. You can install it using `pip install git+https://github.com/cornellius-gp/gpytorch.git`.

We will be cutting a new release very shortly.

**Comment by PingjunChen** [comment]
Got it. Thanks!
