### ISSUE TITLE
How to get posterior predictive distribution from new data? 

### ISSUE THREAD

**Issue by grishabhg** [cornellius-gp/gpytorch#985]
Hello Guys, 

I am interested in obtaining the posterior predictive distribution for some of the regression examples provided with the package. Lets say I have trained a GP on some data and now I want to use it to predict the values of new data (time series). 

For example here: 

https://gpytorch.readthedocs.io/en/latest/examples/01_Simple_GP_Regression/Simple_GP_Regression.html#Make-predictions-with-the-model

in the final task the model predicts the values for the same data that it used for training. But what if I had a new timeseries altogether?

How would I get the predictive distribution for that new timeseries:
- If it had the same length as training set?
- If it had a different length than training set?

Can you guys suggest a way to do it? 

Thanks

**Comment by KeAWang** [comment]
Notice that in the end of the notebook that you link, the model predicts on `test_x`, not `train_x`. I think this is what you're looking for.

**Comment by KeAWang** [comment]
In more detail, if you have a trained GP model `model` train on `N x D` points, to compute the predictive distribution on some `M x D` points `test_x`, you need to put `model` in `eval` mode and then call `model`, i.e.
```
model.eval()
predictive_distribution = model(test_x)
```

**Comment by grishabhg** [comment]
@KeAWang Thanks for your answer. But I think my case is a little different than the one presented in the notebook. 

Lets say I trained a GP on some time-series (lets say it has 100, x and y values). But now I get a new time-series where I observe the first 40 (x and y) values and now i need to predict the next 60 y values at given x values of that new time series.

How would I go about doing that? 

Thanks again.

**Comment by KeAWang** [comment]
Say you have `train_x` that's `40 x 2` and `train_y` that's `40` and a `model` trained on this dataset. You also have a new time series `train_x_new` that's `40 x 2` and `train_y_new` that's `40`and `test_x_new` that's `60 x `.
If you want to use the same hyperparameters, you can do
```
model.set_train_data(inputs=train_x_new, targets=train_y_new, strict=False)
model.eval()
predictive_distribution = likelihood(model(test_x_new))
```

**Comment by grishabhg** [comment]
Hey thanks @KeAWang does this use equation 2.19 in Rasmussen's book on gaussian processes for machine learning: [http://www.gaussianprocess.org/gpml/chapters/RW2.pdf] or equation 2,4,5 in http://krasserm.github.io/2018/03/19/gaussian-processes/?

**Comment by KeAWang** [comment]
This uses equation 2.23,2.24 in GPML which is the same as equation 4,5 in your second link
